// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint and Aster contributors

import Foundation

enum BatteryCareText: Int, CaseIterable {
    case title, description, lower, upper, heat, resumeTemperature, autoDischarge, save, install, approve
    case test, testInfo, persistentInfo, system, discharge, topUp, calibration, cancel, resume, schedules
    case add, remove, when, repetition, timeZone, missed, target, evidence, charging, holding
    case cooling, fault, paused, sleeping, unavailable, recovery, conflict, calibrationInfo, qualifying, enabled
    case actual, helper, busy, once, daily, weekdays, weekly, biweekly, monthly, chargePhase, dischargePhase, rechargePhase, holdPhase
    case systemStatus, batteryPower
}

struct BatteryCareStrings: CustomReflectable {
    let values: [String]
    var customMirror: Mirror {
        let fields = BatteryCareText.allCases.map { (String(describing: $0), self[$0]) }
        return Mirror(self, children: fields, displayStyle: .struct)
    }
    subscript(_ key: BatteryCareText) -> String { values[key.rawValue] }

    func reason(_ reason: BatteryReason) -> String {
        switch reason {
        case .system: return self[.systemStatus]
        case .unplugged: return self[.batteryPower]
        case .charging: return self[.charging]
        case .holding: return self[.holding]
        case .discharging: return self[.discharge]
        case .heat, .cooling: return self[.cooling]
        case .topUp: return self[.topUp]
        case .calibration: return self[.calibration]
        case .paused: return self[.paused]
        case .sleeping: return self[.sleeping]
        case .qualifying: return self[.qualifying]
        case .recovery: return self[.recovery]
        case .unavailable, .helperUnavailable: return self[.unavailable]
        case .conflict: return self[.conflict]
        case .busy: return self[.busy]
        default: return self[.fault]
        }
    }

    func action(_ action: BatteryScheduleAction) -> String {
        switch action {
        case .limit: return self[.upper]
        case .topUp: return self[.topUp]
        case .discharge: return self[.discharge]
        case .calibrate: return self[.calibration]
        case .system: return self[.system]
        }
    }

    func repetition(_ value: BatteryRepeat) -> String {
        self[[.once, .daily, .weekdays, .weekly, .biweekly, .monthly][BatteryRepeat.allCases.firstIndex(of: value)!]]
    }

    func phase(_ value: BatteryCalibrationPhase) -> String {
        switch value {
        case .charge: return self[.chargePhase]
        case .discharge: return self[.dischargePhase]
        case .recharge: return self[.rechargePhase]
        case .hold: return self[.holdPhase]
        }
    }
}

extension FeatureStrings {
    static func batteryCare(_ language: AppLanguage) -> BatteryCareStrings {
        BatteryCareStrings(values: BatteryCareTranslations.rows[language]!.components(separatedBy: "|"))
    }
}

private enum BatteryCareTranslations {
    static let rows: [AppLanguage: String] = [
        .enUS: "Battery care|Charge limits, heat protection and planned charging.|Start charging at|Stop charging at|Stop above °C|Resume below °C|Discharge automatically to the upper limit|Save policy|Install battery service|Approve in System Settings|Test charge control|Plug in at 20–90%. This test charges, pauses and discharges briefly, then restores macOS. Stop other battery controllers first. Native macOS limits can prevent the test from passing.|The service keeps working when Aster quits. Charging pauses during sleep. Calibration and manual discharge pause after sleep or restart; resume them here.|Return to macOS|Discharge|Top up once to 100%|Calibrate|Cancel|Resume|Schedules|Add|Remove|Date and time|Repeat|Time zone|Run missed tasks within six hours|Target %|Evidence and history|Charging|Charging paused|Waiting for the battery to cool|Control stopped; inspect the evidence|Paused; resume when ready|Sleeping|Control unavailable|Restoration pending; keep the service installed|Another battery controller may be active|Calibration: 100% → 10% → 100% → one-hour hold. Cancellation restores the saved policy. Heat protection stays active.|Testing measured power flow|Enable charge policy|Measured battery state|Battery service|Another action is running|Once|Daily|Weekdays|Weekly|Every two weeks|Monthly|Charge to 100%|Discharge to 10%|Recharge to 100%|Hold at full charge|macOS controls charging|Running on battery",
        .es: "Cuidado de batería|Límites de carga, protección térmica y horarios.|Iniciar carga al|Detener carga al|Detener por encima de °C|Reanudar por debajo de °C|Descargar automáticamente hasta el límite superior|Guardar política|Instalar servicio de batería|Aprobar en Ajustes del Sistema|Probar control de carga|Conecta la corriente con 20–90%. La prueba carga, pausa y descarga brevemente; después restaura macOS. Cierra otros controladores. Los límites de macOS pueden impedir la prueba.|El servicio sigue al cerrar Aster. La carga se pausa durante el reposo. La calibración y la descarga manual se pausan tras reposo o reinicio; reanúdalas aquí.|Volver a macOS|Descargar|Cargar al 100% una vez|Calibrar|Cancelar|Reanudar|Horarios|Añadir|Eliminar|Fecha y hora|Repetición|Zona horaria|Ejecutar tareas pendientes en seis horas|Objetivo %|Pruebas e historial|Cargando|Carga pausada|Esperando a que se enfríe la batería|Control detenido; revisa las pruebas|En pausa; reanuda cuando quieras|En reposo|Control no disponible|Restauración pendiente; conserva el servicio|Puede haber otro controlador activo|Calibración: 100% → 10% → 100% → mantener una hora. Cancelar restaura la política guardada. La protección térmica permanece activa.|Probando el flujo de energía real|Activar política de carga|Estado medido de la batería|Servicio de batería|Hay otra acción en curso|Una vez|Diariamente|Días laborables|Semanalmente|Cada dos semanas|Mensualmente|Cargar al 100%|Descargar al 10%|Recargar al 100%|Mantener carga completa|macOS controla la carga|Usando la batería",
        .ptBR: "Cuidados com a bateria|Limites de carga, proteção térmica e horários.|Iniciar carga em|Parar carga em|Parar acima de °C|Retomar abaixo de °C|Descarregar automaticamente até o limite superior|Salvar política|Instalar serviço de bateria|Aprovar nos Ajustes do Sistema|Testar controle de carga|Conecte à tomada com 20–90%. O teste carrega, pausa e descarrega brevemente; depois restaura o macOS. Feche outros controladores. Limites do macOS podem impedir o teste.|O serviço continua ao fechar o Aster. A carga pausa durante o repouso. Calibração e descarga manual pausam após repouso ou reinício; retome aqui.|Voltar ao macOS|Descarregar|Carregar até 100% uma vez|Calibrar|Cancelar|Retomar|Agendamentos|Adicionar|Remover|Data e hora|Repetição|Fuso horário|Executar tarefas perdidas em seis horas|Meta %|Evidências e histórico|Carregando|Carga pausada|Aguardando a bateria esfriar|Controle parado; veja as evidências|Pausado; retome quando quiser|Em repouso|Controle indisponível|Restauração pendente; mantenha o serviço|Outro controlador pode estar ativo|Calibração: 100% → 10% → 100% → manter por uma hora. Cancelar restaura a política salva. A proteção térmica continua ativa.|Testando o fluxo real de energia|Ativar política de carga|Estado medido da bateria|Serviço de bateria|Outra ação está em andamento|Uma vez|Diariamente|Dias úteis|Semanalmente|A cada duas semanas|Mensalmente|Carregar até 100%|Descarregar até 10%|Recarregar até 100%|Manter carga completa|macOS controla a carga|Usando a bateria",
        .de: "Batteriepflege|Ladegrenzen, Wärmeschutz und Zeitpläne.|Laden starten bei|Laden stoppen bei|Stoppen über °C|Fortsetzen unter °C|Automatisch bis zur Obergrenze entladen|Regeln speichern|Batteriedienst installieren|In Systemeinstellungen erlauben|Ladesteuerung testen|Bei 20–90% ans Netz anschließen. Der Test lädt, pausiert und entlädt kurz und stellt macOS wieder her. Andere Batteriesteuerungen beenden. macOS-Limits können den Test verhindern.|Der Dienst läuft nach dem Beenden von Aster weiter. Laden pausiert im Ruhezustand. Kalibrierung und manuelle Entladung pausieren nach Ruhezustand oder Neustart; hier fortsetzen.|Zurück zu macOS|Entladen|Einmal auf 100% laden|Kalibrieren|Abbrechen|Fortsetzen|Zeitpläne|Hinzufügen|Entfernen|Datum und Uhrzeit|Wiederholen|Zeitzone|Verpasste Aufgaben binnen sechs Stunden ausführen|Ziel %|Nachweise und Verlauf|Wird geladen|Laden pausiert|Batterie muss abkühlen|Steuerung gestoppt; Nachweise prüfen|Pausiert; bei Bedarf fortsetzen|Ruhezustand|Steuerung nicht verfügbar|Wiederherstellung ausstehend; Dienst installiert lassen|Andere Batteriesteuerung möglicherweise aktiv|Kalibrierung: 100% → 10% → 100% → eine Stunde halten. Abbrechen stellt gespeicherte Regeln wieder her. Wärmeschutz bleibt aktiv.|Gemessenen Stromfluss testen|Laderegeln aktivieren|Gemessener Batteriestatus|Batteriedienst|Andere Aktion läuft|Einmal|Täglich|Werktags|Wöchentlich|Alle zwei Wochen|Monatlich|Auf 100% laden|Auf 10% entladen|Auf 100% nachladen|Volle Ladung halten|macOS steuert das Laden|Batteriebetrieb",
        .fr: "Entretien de la batterie|Limites de charge, protection thermique et horaires.|Charger à partir de|Arrêter la charge à|Arrêter au-dessus de °C|Reprendre sous °C|Décharger automatiquement jusqu’à la limite haute|Enregistrer les règles|Installer le service batterie|Autoriser dans Réglages Système|Tester le contrôle de charge|Branchez à 20–90%. Le test charge, suspend et décharge brièvement, puis restaure macOS. Fermez les autres contrôleurs. Les limites de macOS peuvent empêcher le test.|Le service continue après la fermeture d’Aster. La charge s’arrête en veille. Étalonnage et décharge manuelle sont suspendus après veille ou redémarrage ; reprenez ici.|Revenir à macOS|Décharger|Charger à 100% une fois|Étalonner|Annuler|Reprendre|Horaires|Ajouter|Supprimer|Date et heure|Répétition|Fuseau horaire|Exécuter les tâches manquées sous six heures|Cible %|Preuves et historique|En charge|Charge suspendue|En attente du refroidissement|Contrôle arrêté ; consultez les preuves|En pause ; reprendre quand prêt|En veille|Contrôle indisponible|Restauration en attente ; gardez le service installé|Un autre contrôleur peut être actif|Étalonnage : 100% → 10% → 100% → maintien une heure. Annuler restaure les règles enregistrées. La protection thermique reste active.|Test du flux d’énergie mesuré|Activer les règles de charge|État mesuré de la batterie|Service batterie|Une autre action est en cours|Une fois|Chaque jour|Jours ouvrés|Chaque semaine|Toutes les deux semaines|Chaque mois|Charger à 100%|Décharger à 10%|Recharger à 100%|Maintenir la pleine charge|macOS contrôle la charge|Sur batterie",
        .it: "Cura della batteria|Limiti di carica, protezione termica e programmi.|Avvia carica al|Ferma carica al|Ferma sopra °C|Riprendi sotto °C|Scarica automaticamente fino al limite superiore|Salva regole|Installa servizio batteria|Approva in Impostazioni di Sistema|Verifica controllo carica|Collega la corrente al 20–90%. Il test carica, sospende e scarica brevemente, poi ripristina macOS. Chiudi altri controllori. I limiti macOS possono impedire il test.|Il servizio continua quando Aster si chiude. La carica si ferma in stop. Calibrazione e scarica manuale si sospendono dopo stop o riavvio; riprendile qui.|Torna a macOS|Scarica|Carica al 100% una volta|Calibra|Annulla|Riprendi|Programmi|Aggiungi|Rimuovi|Data e ora|Ripetizione|Fuso orario|Esegui attività perse entro sei ore|Obiettivo %|Riscontri e cronologia|In carica|Carica sospesa|Attesa raffreddamento batteria|Controllo fermo; consulta i riscontri|In pausa; riprendi quando vuoi|In stop|Controllo non disponibile|Ripristino in attesa; mantieni il servizio|Potrebbe essere attivo un altro controllore|Calibrazione: 100% → 10% → 100% → mantieni un’ora. Annullare ripristina le regole salvate. La protezione termica resta attiva.|Verifica del flusso di energia misurato|Attiva regole di carica|Stato misurato della batteria|Servizio batteria|Un’altra azione è in corso|Una volta|Ogni giorno|Giorni feriali|Ogni settimana|Ogni due settimane|Ogni mese|Carica al 100%|Scarica al 10%|Ricarica al 100%|Mantieni carica completa|macOS controlla la carica|Alimentazione a batteria",
        .tr: "Pil bakımı|Şarj sınırları, ısı koruması ve programlar.|Şarjı başlatma düzeyi|Şarjı durdurma düzeyi|Bu °C üzerinde durdur|Bu °C altında sürdür|Üst sınıra kadar otomatik deşarj|Kuralları kaydet|Pil hizmetini kur|Sistem Ayarları’nda onayla|Şarj denetimini test et|%20–90 düzeyinde prize takın. Test kısa süre şarj eder, duraklatır ve deşarj eder; sonra macOS’u geri yükler. Diğer pil denetleyicilerini kapatın. macOS sınırları testi engelleyebilir.|Aster kapandığında hizmet çalışır. Uykuda şarj duraklar. Kalibrasyon ve elle deşarj uyku veya yeniden başlatma sonrası duraklar; buradan sürdürün.|macOS’a dön|Deşarj et|Bir kez %100 şarj et|Kalibre et|İptal|Sürdür|Programlar|Ekle|Kaldır|Tarih ve saat|Tekrar|Saat dilimi|Kaçırılan görevleri altı saat içinde çalıştır|Hedef %|Kanıt ve geçmiş|Şarj oluyor|Şarj duraklatıldı|Pilin soğuması bekleniyor|Denetim durdu; kanıtları inceleyin|Duraklatıldı; hazır olunca sürdürün|Uykuda|Denetim kullanılamıyor|Geri yükleme bekliyor; hizmeti kurulu tutun|Başka bir pil denetleyicisi etkin olabilir|Kalibrasyon: %100 → %10 → %100 → bir saat tut. İptal, kayıtlı kuralları geri yükler. Isı koruması etkin kalır.|Ölçülen güç akışı test ediliyor|Şarj kurallarını etkinleştir|Ölçülen pil durumu|Pil hizmeti|Başka bir işlem sürüyor|Bir kez|Her gün|Hafta içi|Her hafta|İki haftada bir|Her ay|%100 şarj et|%10’a deşarj et|Yeniden %100 şarj et|Tam şarjda tut|Şarjı macOS denetliyor|Pille çalışıyor",
        .ru: "Уход за аккумулятором|Пределы заряда, защита от нагрева и расписания.|Начать зарядку при|Остановить зарядку при|Остановить выше °C|Продолжить ниже °C|Автоматически разряжать до верхнего предела|Сохранить правила|Установить службу батареи|Разрешить в Системных настройках|Проверить управление зарядкой|Подключите питание при 20–90%. Тест ненадолго заряжает, приостанавливает и разряжает, затем возвращает управление macOS. Закройте другие контроллеры. Ограничения macOS могут помешать тесту.|Служба работает после закрытия Aster. Во сне зарядка приостановлена. Калибровка и ручная разрядка приостанавливаются после сна или перезапуска; продолжите здесь.|Вернуть управление macOS|Разрядить|Один раз зарядить до 100%|Калибровать|Отмена|Продолжить|Расписания|Добавить|Удалить|Дата и время|Повтор|Часовой пояс|Выполнить пропущенные задачи в течение шести часов|Цель %|Данные и история|Заряжается|Зарядка приостановлена|Ожидание охлаждения батареи|Управление остановлено; проверьте данные|Приостановлено; продолжите когда готовы|Сон|Управление недоступно|Восстановление ожидается; не удаляйте службу|Возможно, активен другой контроллер|Калибровка: 100% → 10% → 100% → удержание один час. Отмена восстанавливает сохранённые правила. Тепловая защита остаётся активной.|Проверка измеренного потока энергии|Включить правила зарядки|Измеренное состояние батареи|Служба батареи|Выполняется другое действие|Один раз|Ежедневно|По будням|Еженедельно|Раз в две недели|Ежемесячно|Зарядить до 100%|Разрядить до 10%|Снова зарядить до 100%|Удерживать полный заряд|Зарядкой управляет macOS|Питание от батареи",
        .uk: "Догляд за акумулятором|Межі заряду, захист від нагрівання та розклади.|Почати заряджання при|Зупинити заряджання при|Зупинити вище °C|Продовжити нижче °C|Автоматично розряджати до верхньої межі|Зберегти правила|Установити службу батареї|Дозволити в Системних параметрах|Перевірити керування заряджанням|Під’єднайте живлення при 20–90%. Тест ненадовго заряджає, призупиняє та розряджає, потім відновлює macOS. Закрийте інші контролери. Межі macOS можуть завадити тесту.|Служба працює після закриття Aster. У сні заряджання призупинено. Калібрування й ручне розряджання призупиняються після сну або перезапуску; продовжте тут.|Повернути керування macOS|Розрядити|Один раз зарядити до 100%|Калібрувати|Скасувати|Продовжити|Розклади|Додати|Видалити|Дата й час|Повтор|Часовий пояс|Виконати пропущені завдання протягом шести годин|Ціль %|Дані та історія|Заряджається|Заряджання призупинено|Очікування охолодження батареї|Керування зупинено; перевірте дані|Призупинено; продовжте коли готові|Сон|Керування недоступне|Відновлення очікується; не видаляйте службу|Можливо, активний інший контролер|Калібрування: 100% → 10% → 100% → утримання одну годину. Скасування відновлює збережені правила. Тепловий захист залишається активним.|Перевірка виміряного потоку енергії|Увімкнути правила заряджання|Виміряний стан батареї|Служба батареї|Виконується інша дія|Один раз|Щодня|У будні|Щотижня|Раз на два тижні|Щомісяця|Зарядити до 100%|Розрядити до 10%|Знову зарядити до 100%|Утримувати повний заряд|Заряджанням керує macOS|Живлення від батареї",
        .sk: "Starostlivosť o batériu|Limity nabíjania, tepelná ochrana a plány.|Začať nabíjať pri|Zastaviť nabíjanie pri|Zastaviť nad °C|Pokračovať pod °C|Automaticky vybíjať po horný limit|Uložiť pravidlá|Nainštalovať službu batérie|Povoliť v Systémových nastaveniach|Otestovať riadenie nabíjania|Pripojte napájanie pri 20–90%. Test krátko nabíja, pozastaví a vybíja, potom obnoví macOS. Zatvorte ostatné ovládače. Limity macOS môžu test zastaviť.|Služba funguje aj po ukončení Aster. Nabíjanie sa v spánku pozastaví. Kalibrácia a ručné vybíjanie sa po spánku alebo reštarte pozastavia; pokračujte tu.|Vrátiť riadenie macOS|Vybíjať|Raz nabiť na 100%|Kalibrovať|Zrušiť|Pokračovať|Plány|Pridať|Odstrániť|Dátum a čas|Opakovanie|Časové pásmo|Spustiť zmeškané úlohy do šiestich hodín|Cieľ %|Dôkazy a história|Nabíjanie|Nabíjanie pozastavené|Čakanie na ochladenie batérie|Riadenie zastavené; skontrolujte dôkazy|Pozastavené; pokračujte keď môžete|Spánok|Riadenie nedostupné|Obnova čaká; ponechajte službu nainštalovanú|Môže byť aktívny iný ovládač batérie|Kalibrácia: 100% → 10% → 100% → udržať hodinu. Zrušenie obnoví uložené pravidlá. Tepelná ochrana ostáva aktívna.|Test meraného toku energie|Zapnúť pravidlá nabíjania|Meraný stav batérie|Služba batérie|Prebieha iná akcia|Raz|Denne|Pracovné dni|Týždenne|Každé dva týždne|Mesačne|Nabiť na 100%|Vybiť na 10%|Znova nabiť na 100%|Udržať plné nabitie|Nabíjanie riadi macOS|Napájanie z batérie",
        .ja: "バッテリー管理|充電上限、温度保護、スケジュール。|充電を開始する残量|充電を停止する残量|この温度以上で停止 °C|この温度以下で再開 °C|上限まで自動放電|設定を保存|バッテリーサービスをインストール|システム設定で許可|充電制御をテスト|残量20〜90%で電源を接続してください。短時間の充電、停止、放電後にmacOSへ戻します。他の制御アプリは終了してください。macOSの上限設定によりテストできない場合があります。|Aster終了後もサービスは動作します。スリープ中は充電を停止します。調整と手動放電はスリープや再起動後に一時停止するため、ここで再開してください。|macOSに戻す|放電|一度だけ100%まで充電|バッテリー調整|キャンセル|再開|スケジュール|追加|削除|日時|繰り返し|タイムゾーン|未実行の操作を6時間以内に実行|目標 %|記録と履歴|充電中|充電停止中|バッテリーの冷却待ち|制御停止。記録を確認してください|一時停止中。準備ができたら再開|スリープ中|制御できません|復元待ち。サービスを削除しないでください|別の制御アプリが動作している可能性があります|調整：100% → 10% → 100% → 1時間保持。キャンセルで保存した設定に戻ります。温度保護は有効なままです。|実測電力をテスト中|充電ルールを有効化|バッテリーの実測状態|バッテリーサービス|別の操作が実行中|一度|毎日|平日|毎週|2週間ごと|毎月|100%まで充電|10%まで放電|100%まで再充電|満充電を保持|macOSが充電を管理|バッテリー駆動",
        .ko: "배터리 관리|충전 제한, 발열 보호 및 일정.|충전 시작 잔량|충전 중지 잔량|이 온도 이상에서 중지 °C|이 온도 이하에서 재개 °C|상한까지 자동 방전|정책 저장|배터리 서비스 설치|시스템 설정에서 승인|충전 제어 테스트|20–90%에서 전원을 연결하세요. 잠시 충전, 정지, 방전한 뒤 macOS로 복원합니다. 다른 배터리 제어 앱을 종료하세요. macOS 제한으로 테스트가 실패할 수 있습니다.|Aster 종료 후에도 서비스가 작동합니다. 잠자기 중에는 충전이 멈춥니다. 보정과 수동 방전은 잠자기 또는 재시작 후 일시 정지되며 여기서 재개합니다.|macOS로 복원|방전|한 번 100% 충전|보정|취소|재개|일정|추가|삭제|날짜 및 시간|반복|시간대|놓친 작업을 6시간 이내 실행|목표 %|증거 및 기록|충전 중|충전 일시 정지|배터리 냉각 대기|제어 중지됨. 기록을 확인하세요|일시 정지됨. 준비되면 재개하세요|잠자기 중|제어 불가|복원 대기 중. 서비스를 유지하세요|다른 배터리 제어 앱이 활성 상태일 수 있습니다|보정: 100% → 10% → 100% → 1시간 유지. 취소하면 저장한 정책으로 복원합니다. 발열 보호는 유지됩니다.|측정된 전력 흐름 테스트 중|충전 정책 활성화|측정된 배터리 상태|배터리 서비스|다른 작업 실행 중|한 번|매일|평일|매주|2주마다|매월|100%까지 충전|10%까지 방전|100%까지 재충전|완전 충전 유지|macOS가 충전 제어 중|배터리 사용 중",
        .zhHans: "电池养护|充电上限、温度保护和计划。|开始充电电量|停止充电电量|高于此温度停止 °C|低于此温度恢复 °C|自动放电至上限|保存策略|安装电池服务|在系统设置中批准|测试充电控制|电量20–90%时接入电源。测试会短暂充电、暂停、放电，然后恢复macOS。请先退出其他电池控制器。macOS充电限制可能导致测试失败。|退出Aster后服务仍会运行。睡眠期间暂停充电。校准和手动放电在睡眠或重启后暂停，请在此恢复。|交还macOS控制|放电|单次充电至100%|校准|取消|恢复|计划|添加|删除|日期和时间|重复|时区|六小时内执行错过的任务|目标 %|证据和历史|正在充电|充电已暂停|等待电池冷却|控制已停止，请查看证据|已暂停，就绪后恢复|正在睡眠|无法控制|等待恢复，请保留服务|可能有其他电池控制器正在运行|校准：100% → 10% → 100% → 保持一小时。取消后恢复已保存策略。温度保护保持启用。|正在测试实测电流|启用充电策略|电池实测状态|电池服务|其他操作正在进行|一次|每天|工作日|每周|每两周|每月|充电至100%|放电至10%|再次充电至100%|保持满电|macOS控制充电|使用电池供电",
        .zhTW: "電池保養|充電上限、溫度保護和排程。|開始充電電量|停止充電電量|高於此溫度停止 °C|低於此溫度恢復 °C|自動放電至上限|儲存規則|安裝電池服務|在系統設定中允許|測試充電控制|電量20–90%時接上電源。測試會短暫充電、暫停、放電，再恢復macOS。請先結束其他電池控制器。macOS充電限制可能使測試失敗。|結束Aster後服務仍會執行。睡眠期間暫停充電。校正和手動放電在睡眠或重新啟動後暫停，請在此恢復。|交還macOS控制|放電|單次充電至100%|校正|取消|恢復|排程|新增|移除|日期和時間|重複|時區|六小時內執行錯過的工作|目標 %|證據和歷史|正在充電|充電已暫停|等待電池冷卻|控制已停止，請查看證據|已暫停，就緒後恢復|睡眠中|無法控制|等待恢復，請保留服務|可能有其他電池控制器正在執行|校正：100% → 10% → 100% → 保持一小時。取消後恢復已儲存規則。溫度保護保持啟用。|正在測試實測電流|啟用充電規則|電池實測狀態|電池服務|其他操作正在進行|一次|每天|工作日|每週|每兩週|每月|充電至100%|放電至10%|再次充電至100%|保持滿電|macOS控制充電|使用電池供電",
        .zhHK: "電池保養|充電上限、溫度保護及排程。|開始充電電量|停止充電電量|高於此溫度停止 °C|低於此溫度恢復 °C|自動放電至上限|儲存規則|安裝電池服務|在系統設定中批准|測試充電控制|電量20–90%時接上電源。測試會短暫充電、暫停、放電，再恢復macOS。請先結束其他電池控制器。macOS充電限制可能令測試失敗。|結束Aster後服務仍會運作。睡眠期間暫停充電。校準及手動放電在睡眠或重新啟動後暫停，請在此恢復。|交還macOS控制|放電|單次充電至100%|校準|取消|恢復|排程|新增|移除|日期及時間|重複|時區|六小時內執行錯過的工作|目標 %|證據及記錄|正在充電|充電已暫停|等待電池冷卻|控制已停止，請查看證據|已暫停，就緒後恢復|睡眠中|無法控制|等待恢復，請保留服務|可能有其他電池控制器正在運作|校準：100% → 10% → 100% → 保持一小時。取消後恢復已儲存規則。溫度保護保持啟用。|正在測試實測電流|啟用充電規則|電池實測狀態|電池服務|其他操作正在進行|一次|每天|工作日|每週|每兩週|每月|充電至100%|放電至10%|再次充電至100%|保持滿電|macOS控制充電|使用電池供電"
    ]
}
