// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct ClipboardLibraryStrings {
    let language: AppLanguage
    static var current: ClipboardLibraryStrings { .init(language: L10n.shared.language) }
    var collections: String { Self.collectionsValues[language]! }
    var newCollection: String { Self.newCollectionValues[language]! }
    var name: String { Self.nameValues[language]! }
    var color: String { Self.colorValues[language]! }
    var rename: String { Self.renameValues[language]! }
    var pause: String { Self.pauseValues[language]! }
    var resume: String { Self.resumeValues[language]! }
    var retention: String { Self.retentionValues[language]! }
    var forever: String { Self.foreverValues[language]! }
    var days: String { Self.daysValues[language]! }
    var apply: String { Self.applyValues[language]! }
    var exportLibrary: String { Self.exportLibraryValues[language]! }
    var restoreLibrary: String { Self.restoreLibraryValues[language]! }
    var merge: String { Self.mergeValues[language]! }
    var replace: String { Self.replaceValues[language]! }
    var unavailable: String { Self.unavailableValues[language]! }
    var unknownApp: String { Self.unknownAppValues[language]! }
    var saved: String { Self.savedValues[language]! }
    var saving: String { Self.savingValues[language]! }
    var saveFailure: String { Self.saveFailureValues[language]! }
    var privateArchive: String { Self.privateArchiveValues[language]! }
    var retentionWarning: String { Self.retentionWarningValues[language]! }
    var plainText: String { Self.plainTextValues[language]! }
    var editCopy: String { Self.editCopyValues[language]! }
    var copyFallback: String { Self.copyFallbackValues[language]! }
    var dragFiles: String { Self.dragFilesValues[language]! }
    private static let dragFilesValues: [AppLanguage: String] = [
        .enUS: "Drag all files",
        .es: "Arrastrar todos los archivos",
        .ptBR: "Arrastar todos os arquivos",
        .tr: "Tüm dosyaları sürükle",
        .ru: "Перетащить все файлы",
        .sk: "Presunúť všetky súbory",
        .de: "Alle Dateien ziehen",
        .fr: "Faire glisser tous les fichiers",
        .it: "Trascina tutti i file",
        .ja: "すべてのファイルをドラッグ",
        .ko: "모든 파일 드래그",
        .zhHans: "拖动所有文件",
        .zhTW: "拖移所有檔案",
        .zhHK: "拖移所有檔案",
        .uk: "Перетягнути всі файли",
    ]
    private static let collectionsValues: [AppLanguage: String] = [
        .enUS: "Collections",
        .es: "Colecciones",
        .ptBR: "Coleções",
        .tr: "Koleksiyonlar",
        .ru: "Коллекции",
        .sk: "Zbierky",
        .de: "Sammlungen",
        .fr: "Collections",
        .it: "Raccolte",
        .ja: "コレクション",
        .ko: "컬렉션",
        .zhHans: "收藏集",
        .zhTW: "收藏集",
        .zhHK: "收藏集",
        .uk: "Колекції",
    ]
    private static let newCollectionValues: [AppLanguage: String] = [
        .enUS: "New collection",
        .es: "Nueva colección",
        .ptBR: "Nova coleção",
        .tr: "Yeni koleksiyon",
        .ru: "Новая коллекция",
        .sk: "Nová zbierka",
        .de: "Neue Sammlung",
        .fr: "Nouvelle collection",
        .it: "Nuova raccolta",
        .ja: "新規コレクション",
        .ko: "새 컬렉션",
        .zhHans: "新建收藏集",
        .zhTW: "新增收藏集",
        .zhHK: "新增收藏集",
        .uk: "Нова колекція",
    ]
    private static let nameValues: [AppLanguage: String] = [
        .enUS: "Name",
        .es: "Nombre",
        .ptBR: "Nome",
        .tr: "Ad",
        .ru: "Название",
        .sk: "Názov",
        .de: "Name",
        .fr: "Nom",
        .it: "Nome",
        .ja: "名前",
        .ko: "이름",
        .zhHans: "名称",
        .zhTW: "名稱",
        .zhHK: "名稱",
        .uk: "Назва",
    ]
    private static let colorValues: [AppLanguage: String] = [
        .enUS: "Color",
        .es: "Color",
        .ptBR: "Cor",
        .tr: "Renk",
        .ru: "Цвет",
        .sk: "Farba",
        .de: "Farbe",
        .fr: "Couleur",
        .it: "Colore",
        .ja: "色",
        .ko: "색상",
        .zhHans: "颜色",
        .zhTW: "顏色",
        .zhHK: "顏色",
        .uk: "Колір",
    ]
    private static let renameValues: [AppLanguage: String] = [
        .enUS: "Rename",
        .es: "Renombrar",
        .ptBR: "Renomear",
        .tr: "Yeniden adlandır",
        .ru: "Переименовать",
        .sk: "Premenovať",
        .de: "Umbenennen",
        .fr: "Renommer",
        .it: "Rinomina",
        .ja: "名前を変更",
        .ko: "이름 변경",
        .zhHans: "重命名",
        .zhTW: "重新命名",
        .zhHK: "重新命名",
        .uk: "Перейменувати",
    ]
    private static let pauseValues: [AppLanguage: String] = [
        .enUS: "Pause capture",
        .es: "Pausar captura",
        .ptBR: "Pausar captura",
        .tr: "Kaydı duraklat",
        .ru: "Приостановить запись",
        .sk: "Pozastaviť záznam",
        .de: "Aufnahme pausieren",
        .fr: "Suspendre la capture",
        .it: "Sospendi acquisizione",
        .ja: "記録を一時停止",
        .ko: "기록 일시 정지",
        .zhHans: "暂停记录",
        .zhTW: "暫停記錄",
        .zhHK: "暫停記錄",
        .uk: "Призупинити запис",
    ]
    private static let resumeValues: [AppLanguage: String] = [
        .enUS: "Resume capture",
        .es: "Reanudar captura",
        .ptBR: "Retomar captura",
        .tr: "Kaydı sürdür",
        .ru: "Возобновить запись",
        .sk: "Pokračovať v zázname",
        .de: "Aufnahme fortsetzen",
        .fr: "Reprendre la capture",
        .it: "Riprendi acquisizione",
        .ja: "記録を再開",
        .ko: "기록 재개",
        .zhHans: "恢复记录",
        .zhTW: "繼續記錄",
        .zhHK: "繼續記錄",
        .uk: "Відновити запис",
    ]
    private static let retentionValues: [AppLanguage: String] = [
        .enUS: "Keep recent history",
        .es: "Conservar historial reciente",
        .ptBR: "Manter histórico recente",
        .tr: "Son geçmişi sakla",
        .ru: "Хранить недавнюю историю",
        .sk: "Uchovať nedávnu históriu",
        .de: "Letzten Verlauf behalten",
        .fr: "Conserver l’historique récent",
        .it: "Conserva cronologia recente",
        .ja: "最近の履歴を保持",
        .ko: "최근 기록 보관",
        .zhHans: "保留最近历史",
        .zhTW: "保留最近歷史",
        .zhHK: "保留最近記錄",
        .uk: "Зберігати недавню історію",
    ]
    private static let foreverValues: [AppLanguage: String] = [
        .enUS: "Forever",
        .es: "Siempre",
        .ptBR: "Sempre",
        .tr: "Süresiz",
        .ru: "Бессрочно",
        .sk: "Navždy",
        .de: "Unbegrenzt",
        .fr: "Toujours",
        .it: "Sempre",
        .ja: "無期限",
        .ko: "영구 보관",
        .zhHans: "永久",
        .zhTW: "永久",
        .zhHK: "永久",
        .uk: "Назавжди",
    ]
    private static let daysValues: [AppLanguage: String] = [
        .enUS: "days",
        .es: "días",
        .ptBR: "dias",
        .tr: "gün",
        .ru: "дней",
        .sk: "dní",
        .de: "Tage",
        .fr: "jours",
        .it: "giorni",
        .ja: "日",
        .ko: "일",
        .zhHans: "天",
        .zhTW: "天",
        .zhHK: "天",
        .uk: "днів",
    ]
    private static let applyValues: [AppLanguage: String] = [
        .enUS: "Apply",
        .es: "Aplicar",
        .ptBR: "Aplicar",
        .tr: "Uygula",
        .ru: "Применить",
        .sk: "Použiť",
        .de: "Anwenden",
        .fr: "Appliquer",
        .it: "Applica",
        .ja: "適用",
        .ko: "적용",
        .zhHans: "应用",
        .zhTW: "套用",
        .zhHK: "套用",
        .uk: "Застосувати",
    ]
    private static let exportLibraryValues: [AppLanguage: String] = [
        .enUS: "Export clipboard library…",
        .es: "Exportar biblioteca…",
        .ptBR: "Exportar biblioteca…",
        .tr: "Panoyu dışa aktar…",
        .ru: "Экспортировать библиотеку…",
        .sk: "Exportovať knižnicu…",
        .de: "Zwischenablage exportieren…",
        .fr: "Exporter la bibliothèque…",
        .it: "Esporta libreria…",
        .ja: "ライブラリを書き出す…",
        .ko: "라이브러리 내보내기…",
        .zhHans: "导出剪贴板库…",
        .zhTW: "匯出剪貼簿庫…",
        .zhHK: "匯出剪貼簿庫…",
        .uk: "Експортувати бібліотеку…",
    ]
    private static let restoreLibraryValues: [AppLanguage: String] = [
        .enUS: "Restore clipboard library…",
        .es: "Restaurar biblioteca…",
        .ptBR: "Restaurar biblioteca…",
        .tr: "Panoyu geri yükle…",
        .ru: "Восстановить библиотеку…",
        .sk: "Obnoviť knižnicu…",
        .de: "Zwischenablage wiederherstellen…",
        .fr: "Restaurer la bibliothèque…",
        .it: "Ripristina libreria…",
        .ja: "ライブラリを復元…",
        .ko: "라이브러리 복원…",
        .zhHans: "恢复剪贴板库…",
        .zhTW: "還原剪貼簿庫…",
        .zhHK: "還原剪貼簿庫…",
        .uk: "Відновити бібліотеку…",
    ]
    private static let mergeValues: [AppLanguage: String] = [
        .enUS: "Merge",
        .es: "Combinar",
        .ptBR: "Mesclar",
        .tr: "Birleştir",
        .ru: "Объединить",
        .sk: "Zlúčiť",
        .de: "Zusammenführen",
        .fr: "Fusionner",
        .it: "Unisci",
        .ja: "統合",
        .ko: "병합",
        .zhHans: "合并",
        .zhTW: "合併",
        .zhHK: "合併",
        .uk: "Об’єднати",
    ]
    private static let replaceValues: [AppLanguage: String] = [
        .enUS: "Replace",
        .es: "Reemplazar",
        .ptBR: "Substituir",
        .tr: "Değiştir",
        .ru: "Заменить",
        .sk: "Nahradiť",
        .de: "Ersetzen",
        .fr: "Remplacer",
        .it: "Sostituisci",
        .ja: "置き換える",
        .ko: "교체",
        .zhHans: "替换",
        .zhTW: "取代",
        .zhHK: "取代",
        .uk: "Замінити",
    ]
    private static let unavailableValues: [AppLanguage: String] = [
        .enUS: "Unavailable",
        .es: "No disponible",
        .ptBR: "Indisponível",
        .tr: "Kullanılamıyor",
        .ru: "Недоступно",
        .sk: "Nedostupné",
        .de: "Nicht verfügbar",
        .fr: "Indisponible",
        .it: "Non disponibile",
        .ja: "利用不可",
        .ko: "사용 불가",
        .zhHans: "不可用",
        .zhTW: "無法使用",
        .zhHK: "無法使用",
        .uk: "Недоступно",
    ]
    private static let unknownAppValues: [AppLanguage: String] = [
        .enUS: "Unknown app",
        .es: "App desconocida",
        .ptBR: "App desconhecido",
        .tr: "Bilinmeyen uygulama",
        .ru: "Неизвестное приложение",
        .sk: "Neznáma aplikácia",
        .de: "Unbekannte App",
        .fr: "App inconnue",
        .it: "App sconosciuta",
        .ja: "不明なApp",
        .ko: "알 수 없는 앱",
        .zhHans: "未知应用",
        .zhTW: "未知 App",
        .zhHK: "未知 App",
        .uk: "Невідома програма",
    ]
    private static let savedValues: [AppLanguage: String] = [
        .enUS: "Saved locally",
        .es: "Guardado en este Mac",
        .ptBR: "Salvo neste Mac",
        .tr: "Yerel olarak kaydedildi",
        .ru: "Сохранено на Mac",
        .sk: "Uložené v Macu",
        .de: "Lokal gespeichert",
        .fr: "Enregistré sur ce Mac",
        .it: "Salvato sul Mac",
        .ja: "このMacに保存済み",
        .ko: "이 Mac에 저장됨",
        .zhHans: "已保存在此 Mac",
        .zhTW: "已儲存於此 Mac",
        .zhHK: "已儲存於此 Mac",
        .uk: "Збережено на Mac",
    ]
    private static let savingValues: [AppLanguage: String] = [
        .enUS: "Saving…",
        .es: "Guardando…",
        .ptBR: "Salvando…",
        .tr: "Kaydediliyor…",
        .ru: "Сохранение…",
        .sk: "Ukladanie…",
        .de: "Speichern…",
        .fr: "Enregistrement…",
        .it: "Salvataggio…",
        .ja: "保存中…",
        .ko: "저장 중…",
        .zhHans: "正在保存…",
        .zhTW: "儲存中…",
        .zhHK: "儲存中…",
        .uk: "Збереження…",
    ]
    private static let saveFailureValues: [AppLanguage: String] = [
        .enUS: "This copy could not be saved. Check storage and payload size.",
        .es: "No se pudo guardar. Revisa el espacio y el tamaño.",
        .ptBR: "Não foi possível salvar. Verifique espaço e tamanho.",
        .tr: "Kaydedilemedi. Depolamayı ve boyutu kontrol edin.",
        .ru: "Не удалось сохранить. Проверьте место и размер.",
        .sk: "Nepodarilo sa uložiť. Skontrolujte miesto a veľkosť.",
        .de: "Speichern fehlgeschlagen. Speicher und Größe prüfen.",
        .fr: "Échec de l’enregistrement. Vérifiez l’espace et la taille.",
        .it: "Salvataggio non riuscito. Controlla spazio e dimensione.",
        .ja: "保存できません。空き容量とサイズを確認してください。",
        .ko: "저장할 수 없습니다. 공간과 크기를 확인하세요.",
        .zhHans: "无法保存。请检查存储空间和大小。",
        .zhTW: "無法儲存。請檢查空間和大小。",
        .zhHK: "無法儲存。請檢查空間和大小。",
        .uk: "Не вдалося зберегти. Перевірте місце й розмір.",
    ]
    private static let privateArchiveValues: [AppLanguage: String] = [
        .enUS: "The backup contains private clipboard content. Keep it in a trusted location.",
        .es: "La copia contiene datos privados. Guárdala en un lugar de confianza.",
        .ptBR: "O backup contém dados privados. Guarde em um local confiável.",
        .tr: "Yedek özel pano verileri içerir. Güvenilir bir konumda saklayın.",
        .ru: "Копия содержит личные данные. Храните её в надёжном месте.",
        .sk: "Záloha obsahuje súkromné údaje. Uložte ju na dôveryhodné miesto.",
        .de: "Das Backup enthält private Inhalte. An einem sicheren Ort speichern.",
        .fr: "La sauvegarde contient des données privées. Choisissez un endroit sûr.",
        .it: "Il backup contiene dati privati. Scegli una posizione sicura.",
        .ja: "バックアップには個人情報が含まれます。安全な場所に保存してください。",
        .ko: "백업에 비공개 내용이 포함됩니다. 안전한 곳에 보관하세요.",
        .zhHans: "备份包含私人内容。请存放在可信位置。",
        .zhTW: "備份包含私人內容。請存放於可信位置。",
        .zhHK: "備份包含私人內容。請存放於可信位置。",
        .uk: "Копія містить приватні дані. Зберігайте її в надійному місці.",
    ]
    private static let retentionWarningValues: [AppLanguage: String] = [
        .enUS: "Items to remove. Collections are kept. Apply to confirm.",
        .es: "Elementos que se borrarán. Las colecciones se conservan. Aplica para confirmar.",
        .ptBR: "Itens a remover. Coleções são mantidas. Aplique para confirmar.",
        .tr: "Silinecek öğeler. Koleksiyonlar korunur. Onaylamak için uygulayın.",
        .ru: "Будут удалены элементы. Коллекции сохранятся. Примените для подтверждения.",
        .sk: "Položky na odstránenie. Zbierky zostanú. Potvrďte použitím.",
        .de: "Zu löschende Einträge. Sammlungen bleiben erhalten. Mit Anwenden bestätigen.",
        .fr: "Éléments à supprimer. Les collections sont conservées. Appliquez pour confirmer.",
        .it: "Elementi da rimuovere. Le raccolte restano. Applica per confermare.",
        .ja: "削除する項目です。コレクションは保持されます。適用して確定します。",
        .ko: "삭제할 항목입니다. 컬렉션은 유지됩니다. 적용하여 확인하세요.",
        .zhHans: "将删除的项目。收藏集会保留。点击应用确认。",
        .zhTW: "將刪除的項目。收藏集會保留。套用以確認。",
        .zhHK: "將刪除的項目。收藏集會保留。套用以確認。",
        .uk: "Елементи для видалення. Колекції залишаться. Застосуйте для підтвердження.",
    ]
    private static let plainTextValues: [AppLanguage: String] = [
        .enUS: "Paste as plain text",
        .es: "Pegar sin formato",
        .ptBR: "Colar sem formatação",
        .tr: "Düz metin olarak yapıştır",
        .ru: "Вставить без форматирования",
        .sk: "Vložiť obyčajný text",
        .de: "Als reinen Text einsetzen",
        .fr: "Coller sans mise en forme",
        .it: "Incolla senza formattazione",
        .ja: "標準テキストでペースト",
        .ko: "일반 텍스트로 붙여넣기",
        .zhHans: "粘贴纯文本",
        .zhTW: "貼上純文字",
        .zhHK: "貼上純文字",
        .uk: "Вставити звичайний текст",
    ]
    private static let editCopyValues: [AppLanguage: String] = [
        .enUS: "Edit a copy",
        .es: "Editar una copia",
        .ptBR: "Editar uma cópia",
        .tr: "Bir kopyayı düzenle",
        .ru: "Редактировать копию",
        .sk: "Upraviť kópiu",
        .de: "Kopie bearbeiten",
        .fr: "Modifier une copie",
        .it: "Modifica una copia",
        .ja: "コピーを編集",
        .ko: "복사본 편집",
        .zhHans: "编辑副本",
        .zhTW: "編輯副本",
        .zhHK: "編輯副本",
        .uk: "Редагувати копію",
    ]
    private static let copyFallbackValues: [AppLanguage: String] = [
        .enUS: "Return copies. Allow Accessibility to paste directly.",
        .es: "Intro copia. Permite Accesibilidad para pegar directamente.",
        .ptBR: "Enter copia. Permita Acessibilidade para colar diretamente.",
        .tr: "Return kopyalar. Doğrudan yapıştırmak için Erişilebilirliğe izin verin.",
        .ru: "Return копирует. Разрешите универсальный доступ для вставки.",
        .sk: "Return kopíruje. Na vloženie povoľte prístupnosť.",
        .de: "Return kopiert. Bedienungshilfen für direktes Einsetzen erlauben.",
        .fr: "Retour copie. Autorisez l’accessibilité pour coller directement.",
        .it: "Invio copia. Consenti Accessibilità per incollare direttamente.",
        .ja: "Returnでコピーします。直接ペーストにはアクセシビリティを許可してください。",
        .ko: "Return은 복사합니다. 바로 붙여넣으려면 손쉬운 사용을 허용하세요.",
        .zhHans: "Return 复制。允许辅助功能后可直接粘贴。",
        .zhTW: "Return 複製。允許輔助使用後可直接貼上。",
        .zhHK: "Return 複製。允許輔助使用後可直接貼上。",
        .uk: "Return копіює. Дозвольте доступність для прямої вставки.",
    ]
}
