// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct MenuBarOrganizerStrings {
    let pageTitle: String
    let hubDescription: String
    let unsupportedSystem: String
    let enable: String
    let enableCaption: String
    let setupTitle: String
    let setupCaption: String
    let finishSetup: String
    let visible: String
    let hidden: String
    let alwaysHidden: String
    let emptySection: String
    let dragHint: String
    let manualHint: String
    let refresh: String
    let retry: String
    let undo: String
    let secondaryBar: String
    let accessibilityCaption: String
    let automaticMoveUnavailable: String
    let unresolvedCountFormat: String
    let unresolvedItem: String
    let protectedItem: String
    let conflictTitle: String
    let conflictFormat: String
    let sectionsTitle: String
    let alwaysHiddenToggle: String
    let showDividers: String
    let behaviorTitle: String
    let presentationTitle: String
    let presentationAutomatic: String
    let presentationMenuBar: String
    let presentationSecondary: String
    let presentationCaption: String
    let attribution: String
    let contextShowHidden: String
    let contextHideHidden: String
    let contextShowAlways: String
    let contextHideAlways: String
    let contextSettings: String
    let contextDisable: String
    let errorPermission: String
    let errorUnavailable: String
    let errorNotMovable: String
    let errorUnresolved: String
    let errorMenuOpen: String
    let errorEvent: String
    let errorVerification: String
    let errorBusy: String
}

extension FeatureStrings {
    static func menuBarOrganizer(_ language: AppLanguage) -> MenuBarOrganizerStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .uk: return .uk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension MenuBarOrganizerStrings {
    static let enUS = MenuBarOrganizerStrings(
        pageTitle: "Menu Bar",
        hubDescription: "Hide, reveal and arrange menu bar items",
        unsupportedSystem: "Not yet compatible with macOS 27. Your saved setup will be kept for a future update.",
        enable: "Manage menu bar items",
        enableCaption: "Adds movable dividers for visible, hidden and always-hidden items.",
        setupTitle: "Set up your sections",
        setupCaption: "Drag items between sections. Nothing is hidden until setup is finished.",
        finishSetup: "Finish setup",
        visible: "Visible",
        hidden: "Hidden",
        alwaysHidden: "Always hidden",
        emptySection: "Drop menu bar items here",
        dragHint: "Drag to reorder. Every successful move is verified against the real menu bar.",
        manualHint: "Unresolved or protected items stay locked so Aster never moves the wrong item.",
        refresh: "Refresh",
        retry: "Try again",
        undo: "Undo last move",
        secondaryBar: "Show secondary bar",
        accessibilityCaption: "Accessibility lets Aster perform the same Command-drag gesture you can do manually.",
        automaticMoveUnavailable: "Automatic arrangement is unavailable until item access is reliable.",
        unresolvedCountFormat: "%d items could not be identified and remain locked.",
        unresolvedItem: "This item could not be identified reliably and will not be moved.",
        protectedItem: "Aster and protected system items cannot be moved here.",
        conflictTitle: "Another menu bar manager is running",
        conflictFormat: "Quit %@ before enabling Aster’s menu bar manager. Running two managers can corrupt the layout.",
        sectionsTitle: "Sections",
        alwaysHiddenToggle: "Enable the always-hidden section",
        showDividers: "Keep section dividers visible",
        behaviorTitle: "Presentation",
        presentationTitle: "Show hidden items",
        presentationAutomatic: "Automatic",
        presentationMenuBar: "Menu bar",
        presentationSecondary: "Secondary bar",
        presentationCaption: "Automatic uses the secondary bar on notched screens or when hidden items do not fit.",
        attribution: "Behavior informed by Ice and Thaw. Implemented for Aster under the GPL.",
        contextShowHidden: "Show hidden items",
        contextHideHidden: "Hide hidden items",
        contextShowAlways: "Show always-hidden items",
        contextHideAlways: "Hide always-hidden items",
        contextSettings: "Menu Bar Settings...",
        contextDisable: "Turn Off Menu Bar Manager",
        errorPermission: "Accessibility permission is required.",
        errorUnavailable: "The menu bar item is no longer available.",
        errorNotMovable: "macOS does not allow this item to be moved.",
        errorUnresolved: "The item identity is not reliable enough to move.",
        errorMenuOpen: "Close the item’s open menu and try again.",
        errorEvent: "Aster could not create the drag operation.",
        errorVerification: "The item did not reach the requested section.",
        errorBusy: "Another menu bar operation is still running."
    )

    static let ptBR = MenuBarOrganizerStrings(
        pageTitle: "Barra de menus",
        hubDescription: "Oculte, revele e organize itens da barra de menus",
        unsupportedSystem: "Ainda não é compatível com o macOS 27. Sua configuração salva será mantida para uma atualização futura.",
        enable: "Gerenciar itens da barra de menus",
        enableCaption: "Adiciona divisores móveis para itens visíveis, ocultos e sempre ocultos.",
        setupTitle: "Configure suas seções",
        setupCaption: "Arraste itens entre as seções. Nada será ocultado até concluir.",
        finishSetup: "Concluir configuração",
        visible: "Visíveis",
        hidden: "Ocultos",
        alwaysHidden: "Sempre ocultos",
        emptySection: "Solte itens da barra aqui",
        dragHint: "Arraste para reordenar. Cada movimento é verificado na barra real.",
        manualHint: "Itens não identificados ou protegidos ficam bloqueados para evitar movimentos incorretos.",
        refresh: "Atualizar",
        retry: "Tentar novamente",
        undo: "Desfazer último movimento",
        secondaryBar: "Mostrar barra secundária",
        accessibilityCaption: "A Acessibilidade permite ao Aster executar o mesmo gesto Comando-arrastar feito manualmente.",
        automaticMoveUnavailable: "A organização automática está indisponível até que o acesso aos itens seja confiável.",
        unresolvedCountFormat: "%d itens não puderam ser identificados e continuam bloqueados.",
        unresolvedItem: "Este item não pôde ser identificado com segurança e não será movido.",
        protectedItem: "Itens do Aster e do sistema protegidos não podem ser movidos aqui.",
        conflictTitle: "Outro gerenciador de barra de menus está em execução",
        conflictFormat: "Encerre %@ antes de ativar o gerenciador do Aster. Dois gerenciadores podem corromper o layout.",
        sectionsTitle: "Seções",
        alwaysHiddenToggle: "Ativar a seção sempre oculta",
        showDividers: "Manter divisores visíveis",
        behaviorTitle: "Apresentação",
        presentationTitle: "Mostrar itens ocultos",
        presentationAutomatic: "Automático",
        presentationMenuBar: "Barra de menus",
        presentationSecondary: "Barra secundária",
        presentationCaption: "O modo automático usa a barra secundária em telas com notch ou sem espaço.",
        attribution: "Comportamento baseado no Ice e no Thaw. Implementado para o Aster sob a GPL.",
        contextShowHidden: "Mostrar itens ocultos",
        contextHideHidden: "Ocultar itens",
        contextShowAlways: "Mostrar itens sempre ocultos",
        contextHideAlways: "Ocultar itens sempre ocultos",
        contextSettings: "Ajustes da barra de menus...",
        contextDisable: "Desativar gerenciador",
        errorPermission: "A permissão de Acessibilidade é necessária.",
        errorUnavailable: "O item da barra não está mais disponível.",
        errorNotMovable: "O macOS não permite mover este item.",
        errorUnresolved: "A identidade do item não é confiável o bastante para movê-lo.",
        errorMenuOpen: "Feche o menu aberto do item e tente novamente.",
        errorEvent: "O Aster não conseguiu criar a operação de arrastar.",
        errorVerification: "O item não chegou à seção solicitada.",
        errorBusy: "Outra operação da barra de menus ainda está em andamento."
    )

    static let tr = MenuBarOrganizerStrings(
        pageTitle: "Menü Çubuğu",
        hubDescription: "Menü çubuğu öğelerini gizleyin, gösterin ve düzenleyin",
        unsupportedSystem: "Henüz macOS 27 ile uyumlu değil. Kayıtlı ayarlarınız gelecekteki bir güncelleme için korunur.",
        enable: "Menü çubuğu öğelerini yönet",
        enableCaption: "Görünür, gizli ve her zaman gizli öğeler için taşınabilir ayırıcılar ekler.",
        setupTitle: "Bölümlerinizi ayarlayın",
        setupCaption: "Öğeleri bölümler arasında sürükleyin. Kurulum bitene kadar hiçbir şey gizlenmez.",
        finishSetup: "Kurulumu tamamla",
        visible: "Görünür",
        hidden: "Gizli",
        alwaysHidden: "Her zaman gizli",
        emptySection: "Menü çubuğu öğelerini buraya bırakın",
        dragHint: "Yeniden sıralamak için sürükleyin. Her hareket gerçek menü çubuğunda doğrulanır.",
        manualHint: "Yanlış öğenin taşınmaması için çözümlenemeyen ve korunan öğeler kilitli kalır.",
        refresh: "Yenile",
        retry: "Yeniden dene",
        undo: "Son taşımayı geri al",
        secondaryBar: "İkincil çubuğu göster",
        accessibilityCaption: "Erişilebilirlik, Aster’in elle yapılan Komut-sürükle hareketini uygulamasını sağlar.",
        automaticMoveUnavailable: "Öğe erişimi güvenilir olana kadar otomatik düzenleme kullanılamaz.",
        unresolvedCountFormat: "%d öğe tanımlanamadı ve kilitli kaldı.",
        unresolvedItem: "Bu öğe güvenilir biçimde tanımlanamadı ve taşınmayacak.",
        protectedItem: "Aster ve korunan sistem öğeleri buradan taşınamaz.",
        conflictTitle: "Başka bir menü çubuğu yöneticisi çalışıyor",
        conflictFormat: "Aster yöneticisini açmadan önce %@ uygulamasından çıkın. İki yönetici düzeni bozabilir.",
        sectionsTitle: "Bölümler",
        alwaysHiddenToggle: "Her zaman gizli bölümünü etkinleştir",
        showDividers: "Bölüm ayırıcılarını görünür tut",
        behaviorTitle: "Sunum",
        presentationTitle: "Gizli öğeleri göster",
        presentationAutomatic: "Otomatik",
        presentationMenuBar: "Menü çubuğu",
        presentationSecondary: "İkincil çubuk",
        presentationCaption: "Otomatik mod, çentikli veya yetersiz alanlı ekranlarda ikincil çubuğu kullanır.",
        attribution: "Davranış Ice ve Thaw’dan yararlanır. Aster için GPL altında uygulanmıştır.",
        contextShowHidden: "Gizli öğeleri göster",
        contextHideHidden: "Gizli öğeleri sakla",
        contextShowAlways: "Her zaman gizli öğeleri göster",
        contextHideAlways: "Her zaman gizli öğeleri sakla",
        contextSettings: "Menü Çubuğu Ayarları...",
        contextDisable: "Menü Çubuğu Yöneticisini Kapat",
        errorPermission: "Erişilebilirlik izni gerekiyor.",
        errorUnavailable: "Menü çubuğu öğesi artık kullanılamıyor.",
        errorNotMovable: "macOS bu öğenin taşınmasına izin vermiyor.",
        errorUnresolved: "Öğe kimliği taşımak için yeterince güvenilir değil.",
        errorMenuOpen: "Öğenin açık menüsünü kapatıp yeniden deneyin.",
        errorEvent: "Aster sürükleme işlemini oluşturamadı.",
        errorVerification: "Öğe istenen bölüme ulaşmadı.",
        errorBusy: "Başka bir menü çubuğu işlemi hâlâ sürüyor."
    )

    static let ru = MenuBarOrganizerStrings(
        pageTitle: "Строка меню",
        hubDescription: "Скрывайте, показывайте и упорядочивайте значки строки меню",
        unsupportedSystem: "Пока не поддерживается в macOS 27. Сохранённая конфигурация останется для будущего обновления.",
        enable: "Управлять значками строки меню",
        enableCaption: "Добавляет перемещаемые разделители для видимых, скрытых и всегда скрытых значков.",
        setupTitle: "Настройте разделы",
        setupCaption: "Перетаскивайте значки между разделами. До завершения настройки ничего не скрывается.",
        finishSetup: "Завершить настройку",
        visible: "Видимые",
        hidden: "Скрытые",
        alwaysHidden: "Всегда скрытые",
        emptySection: "Перетащите сюда значки строки меню",
        dragHint: "Перетаскивайте для сортировки. Каждое перемещение проверяется в реальной строке меню.",
        manualHint: "Неопознанные и защищённые значки остаются заблокированными, чтобы не переместить неверный.",
        refresh: "Обновить",
        retry: "Повторить",
        undo: "Отменить перемещение",
        secondaryBar: "Показать дополнительную панель",
        accessibilityCaption: "Универсальный доступ позволяет Aster выполнить тот же жест Command-перетаскивание вручную.",
        automaticMoveUnavailable: "Автоматическая сортировка недоступна, пока доступ к значкам ненадёжен.",
        unresolvedCountFormat: "Не удалось определить %d значков; они заблокированы.",
        unresolvedItem: "Этот значок нельзя надёжно определить, поэтому он не будет перемещён.",
        protectedItem: "Значки Aster и защищённые системные значки здесь не перемещаются.",
        conflictTitle: "Запущен другой менеджер строки меню",
        conflictFormat: "Завершите %@ перед включением менеджера Aster. Два менеджера могут повредить раскладку.",
        sectionsTitle: "Разделы",
        alwaysHiddenToggle: "Включить раздел «Всегда скрытые»",
        showDividers: "Всегда показывать разделители",
        behaviorTitle: "Отображение",
        presentationTitle: "Показывать скрытые значки",
        presentationAutomatic: "Автоматически",
        presentationMenuBar: "В строке меню",
        presentationSecondary: "На отдельной панели",
        presentationCaption: "Автоматический режим использует отдельную панель при наличии выреза или нехватке места.",
        attribution: "Поведение основано на Ice и Thaw. Реализовано для Aster по лицензии GPL.",
        contextShowHidden: "Показать скрытые значки",
        contextHideHidden: "Скрыть значки",
        contextShowAlways: "Показать всегда скрытые",
        contextHideAlways: "Скрыть всегда скрытые",
        contextSettings: "Настройки строки меню...",
        contextDisable: "Выключить менеджер строки меню",
        errorPermission: "Требуется разрешение «Универсальный доступ».",
        errorUnavailable: "Значок строки меню больше недоступен.",
        errorNotMovable: "macOS не разрешает перемещать этот значок.",
        errorUnresolved: "Идентификатор значка недостаточно надёжен для перемещения.",
        errorMenuOpen: "Закройте открытое меню значка и повторите попытку.",
        errorEvent: "Aster не удалось создать операцию перетаскивания.",
        errorVerification: "Значок не попал в выбранный раздел.",
        errorBusy: "Другая операция со строкой меню ещё выполняется."
    )

    static let es = MenuBarOrganizerStrings(
        pageTitle: "Barra de menús",
        hubDescription: "Oculta, muestra y ordena los elementos de la barra",
        unsupportedSystem: "Aún no es compatible con macOS 27. Tu configuración guardada se conservará para una futura actualización.",
        enable: "Gestionar los elementos de la barra de menús",
        enableCaption: "Añade separadores móviles para elementos visibles, ocultos y siempre ocultos.",
        setupTitle: "Configura tus secciones",
        setupCaption: "Arrastra elementos entre las secciones. Nada se oculta hasta terminar.",
        finishSetup: "Terminar configuración",
        visible: "Visible",
        hidden: "Oculta",
        alwaysHidden: "Siempre oculta",
        emptySection: "Suelta aquí elementos de la barra",
        dragHint: "Arrastra para ordenar. Cada movimiento se comprueba en la barra real.",
        manualHint: "Los elementos sin identificar o protegidos permanecen bloqueados para evitar movimientos incorrectos.",
        refresh: "Actualizar",
        retry: "Volver a intentar",
        undo: "Deshacer último movimiento",
        secondaryBar: "Mostrar barra secundaria",
        accessibilityCaption: "Accesibilidad permite que Aster realice el mismo gesto Comando-arrastrar que harías manualmente.",
        automaticMoveUnavailable: "La organización automática no está disponible hasta que el acceso sea fiable.",
        unresolvedCountFormat: "No se pudieron identificar %d elementos y siguen bloqueados.",
        unresolvedItem: "Este elemento no se pudo identificar de forma fiable y no se moverá.",
        protectedItem: "Los elementos de Aster y del sistema protegidos no se pueden mover aquí.",
        conflictTitle: "Hay otro gestor de barra de menús abierto",
        conflictFormat: "Cierra %@ antes de activar el gestor de Aster. Dos gestores pueden dañar la disposición.",
        sectionsTitle: "Secciones",
        alwaysHiddenToggle: "Activar la sección siempre oculta",
        showDividers: "Mantener visibles los separadores",
        behaviorTitle: "Presentación",
        presentationTitle: "Mostrar elementos ocultos",
        presentationAutomatic: "Automático",
        presentationMenuBar: "Barra de menús",
        presentationSecondary: "Barra secundaria",
        presentationCaption: "El modo automático usa la barra secundaria con notch o cuando no hay espacio.",
        attribution: "Comportamiento basado en Ice y Thaw. Implementado para Aster bajo la GPL.",
        contextShowHidden: "Mostrar elementos ocultos",
        contextHideHidden: "Ocultar elementos",
        contextShowAlways: "Mostrar los siempre ocultos",
        contextHideAlways: "Ocultar los siempre ocultos",
        contextSettings: "Ajustes de la barra de menús...",
        contextDisable: "Desactivar gestor",
        errorPermission: "Se necesita permiso de Accesibilidad.",
        errorUnavailable: "El elemento de la barra ya no está disponible.",
        errorNotMovable: "macOS no permite mover este elemento.",
        errorUnresolved: "La identidad del elemento no es suficientemente fiable.",
        errorMenuOpen: "Cierra el menú abierto del elemento e inténtalo de nuevo.",
        errorEvent: "Aster no pudo crear la operación de arrastre.",
        errorVerification: "El elemento no llegó a la sección solicitada.",
        errorBusy: "Todavía hay otra operación en curso."
    )

    static let de = MenuBarOrganizerStrings(
        pageTitle: "Menüleiste",
        hubDescription: "Menüleistenobjekte ausblenden, einblenden und anordnen",
        unsupportedSystem: "Noch nicht mit macOS 27 kompatibel. Deine gespeicherte Konfiguration bleibt für ein zukünftiges Update erhalten.",
        enable: "Menüleistenobjekte verwalten",
        enableCaption: "Fügt verschiebbare Trenner für sichtbare, ausgeblendete und immer ausgeblendete Objekte hinzu.",
        setupTitle: "Bereiche einrichten",
        setupCaption: "Objekte zwischen Bereichen ziehen. Bis zum Abschluss wird nichts ausgeblendet.",
        finishSetup: "Einrichtung abschließen",
        visible: "Sichtbar",
        hidden: "Ausgeblendet",
        alwaysHidden: "Immer ausgeblendet",
        emptySection: "Menüleistenobjekte hier ablegen",
        dragHint: "Zum Sortieren ziehen. Jede Bewegung wird in der echten Menüleiste geprüft.",
        manualHint: "Nicht erkannte und geschützte Objekte bleiben gesperrt, damit nichts Falsches bewegt wird.",
        refresh: "Aktualisieren",
        retry: "Erneut versuchen",
        undo: "Letzte Bewegung widerrufen",
        secondaryBar: "Sekundärleiste anzeigen",
        accessibilityCaption: "Bedienungshilfen erlauben Aster dieselbe Befehl-Ziehen-Geste wie bei manueller Bedienung.",
        automaticMoveUnavailable: "Automatisches Anordnen ist erst bei zuverlässigem Objektzugriff verfügbar.",
        unresolvedCountFormat: "%d Objekte konnten nicht erkannt werden und bleiben gesperrt.",
        unresolvedItem: "Dieses Objekt konnte nicht zuverlässig erkannt werden und wird nicht bewegt.",
        protectedItem: "Aster- und geschützte Systemobjekte können hier nicht bewegt werden.",
        conflictTitle: "Ein anderer Menüleistenmanager läuft",
        conflictFormat: "%@ beenden, bevor der Aster-Manager aktiviert wird. Zwei Manager können das Layout beschädigen.",
        sectionsTitle: "Bereiche",
        alwaysHiddenToggle: "Bereich „Immer ausgeblendet“ aktivieren",
        showDividers: "Bereichstrenner sichtbar lassen",
        behaviorTitle: "Darstellung",
        presentationTitle: "Ausgeblendete Objekte zeigen",
        presentationAutomatic: "Automatisch",
        presentationMenuBar: "Menüleiste",
        presentationSecondary: "Sekundärleiste",
        presentationCaption: "Automatisch nutzt bei Notch oder Platzmangel die Sekundärleiste.",
        attribution: "Verhalten nach Ice und Thaw. Für Aster unter der GPL umgesetzt.",
        contextShowHidden: "Ausgeblendete Objekte zeigen",
        contextHideHidden: "Objekte ausblenden",
        contextShowAlways: "Immer ausgeblendete zeigen",
        contextHideAlways: "Immer ausgeblendete verbergen",
        contextSettings: "Menüleisteneinstellungen...",
        contextDisable: "Menüleistenmanager ausschalten",
        errorPermission: "Die Bedienungshilfen-Berechtigung ist erforderlich.",
        errorUnavailable: "Das Menüleistenobjekt ist nicht mehr verfügbar.",
        errorNotMovable: "macOS erlaubt das Verschieben dieses Objekts nicht.",
        errorUnresolved: "Die Objektidentität ist zum Verschieben nicht zuverlässig genug.",
        errorMenuOpen: "Das offene Menü schließen und erneut versuchen.",
        errorEvent: "Aster konnte den Ziehvorgang nicht erstellen.",
        errorVerification: "Das Objekt erreichte den gewünschten Bereich nicht.",
        errorBusy: "Ein anderer Menüleistenvorgang läuft noch."
    )

    static let fr = MenuBarOrganizerStrings(
        pageTitle: "Barre des menus",
        hubDescription: "Masquer, afficher et organiser les éléments de la barre",
        unsupportedSystem: "Pas encore compatible avec macOS 27. Votre configuration enregistrée sera conservée pour une future mise à jour.",
        enable: "Gérer les éléments de la barre des menus",
        enableCaption: "Ajoute des séparateurs mobiles pour les éléments visibles, masqués et toujours masqués.",
        setupTitle: "Configurer les sections",
        setupCaption: "Faites glisser les éléments entre les sections. Rien n’est masqué avant la fin.",
        finishSetup: "Terminer la configuration",
        visible: "Visibles",
        hidden: "Masqués",
        alwaysHidden: "Toujours masqués",
        emptySection: "Déposez des éléments ici",
        dragHint: "Faites glisser pour trier. Chaque déplacement est vérifié dans la barre réelle.",
        manualHint: "Les éléments non identifiés ou protégés restent verrouillés pour éviter une mauvaise manipulation.",
        refresh: "Actualiser",
        retry: "Réessayer",
        undo: "Annuler le dernier déplacement",
        secondaryBar: "Afficher la barre secondaire",
        accessibilityCaption: "Accessibilité permet à Aster d’effectuer le même geste Commande-glisser que manuellement.",
        automaticMoveUnavailable: "L’organisation automatique reste indisponible tant que l’accès n’est pas fiable.",
        unresolvedCountFormat: "%d éléments n’ont pas pu être identifiés et restent verrouillés.",
        unresolvedItem: "Cet élément n’a pas pu être identifié de façon fiable et ne sera pas déplacé.",
        protectedItem: "Les éléments de Aster et les éléments système protégés ne peuvent pas être déplacés ici.",
        conflictTitle: "Un autre gestionnaire de barre des menus est actif",
        conflictFormat: "Quittez %@ avant d’activer celui de Aster. Deux gestionnaires peuvent altérer la disposition.",
        sectionsTitle: "Sections",
        alwaysHiddenToggle: "Activer la section toujours masquée",
        showDividers: "Garder les séparateurs visibles",
        behaviorTitle: "Présentation",
        presentationTitle: "Afficher les éléments masqués",
        presentationAutomatic: "Automatique",
        presentationMenuBar: "Barre des menus",
        presentationSecondary: "Barre secondaire",
        presentationCaption: "Le mode automatique utilise la barre secondaire avec une encoche ou en cas de manque de place.",
        attribution: "Comportement inspiré d’Ice et Thaw. Implémenté pour Aster sous GPL.",
        contextShowHidden: "Afficher les éléments masqués",
        contextHideHidden: "Masquer les éléments",
        contextShowAlways: "Afficher les éléments toujours masqués",
        contextHideAlways: "Masquer les éléments toujours masqués",
        contextSettings: "Réglages de la barre des menus...",
        contextDisable: "Désactiver le gestionnaire",
        errorPermission: "L’autorisation Accessibilité est requise.",
        errorUnavailable: "L’élément n’est plus disponible.",
        errorNotMovable: "macOS n’autorise pas le déplacement de cet élément.",
        errorUnresolved: "L’identité de l’élément n’est pas assez fiable.",
        errorMenuOpen: "Fermez le menu ouvert de l’élément et réessayez.",
        errorEvent: "Aster n’a pas pu créer l’opération de déplacement.",
        errorVerification: "L’élément n’a pas atteint la section demandée.",
        errorBusy: "Une autre opération est encore en cours."
    )

    static let it = MenuBarOrganizerStrings(
        pageTitle: "Barra dei menu",
        hubDescription: "Nascondi, mostra e ordina gli elementi della barra",
        unsupportedSystem: "Non è ancora compatibile con macOS 27. La configurazione salvata verrà conservata per un aggiornamento futuro.",
        enable: "Gestisci gli elementi della barra dei menu",
        enableCaption: "Aggiunge separatori mobili per elementi visibili, nascosti e sempre nascosti.",
        setupTitle: "Configura le sezioni",
        setupCaption: "Trascina gli elementi tra le sezioni. Nulla viene nascosto fino al completamento.",
        finishSetup: "Completa configurazione",
        visible: "Visibili",
        hidden: "Nascosti",
        alwaysHidden: "Sempre nascosti",
        emptySection: "Rilascia qui gli elementi",
        dragHint: "Trascina per riordinare. Ogni spostamento viene verificato nella barra reale.",
        manualHint: "Gli elementi non identificati o protetti restano bloccati per evitare spostamenti errati.",
        refresh: "Aggiorna",
        retry: "Riprova",
        undo: "Annulla ultimo spostamento",
        secondaryBar: "Mostra barra secondaria",
        accessibilityCaption: "Accessibilità consente a Aster di eseguire lo stesso gesto Comando-trascina manuale.",
        automaticMoveUnavailable: "L’ordinamento automatico non è disponibile finché l’accesso non è affidabile.",
        unresolvedCountFormat: "%d elementi non sono stati identificati e restano bloccati.",
        unresolvedItem: "Questo elemento non è stato identificato in modo affidabile e non verrà spostato.",
        protectedItem: "Gli elementi di Aster e quelli di sistema protetti non possono essere spostati qui.",
        conflictTitle: "È attivo un altro gestore della barra dei menu",
        conflictFormat: "Chiudi %@ prima di attivare il gestore di Aster. Due gestori possono danneggiare il layout.",
        sectionsTitle: "Sezioni",
        alwaysHiddenToggle: "Attiva la sezione sempre nascosta",
        showDividers: "Mantieni visibili i separatori",
        behaviorTitle: "Presentazione",
        presentationTitle: "Mostra elementi nascosti",
        presentationAutomatic: "Automatica",
        presentationMenuBar: "Barra dei menu",
        presentationSecondary: "Barra secondaria",
        presentationCaption: "La modalità automatica usa la barra secondaria con notch o spazio insufficiente.",
        attribution: "Comportamento basato su Ice e Thaw. Implementato per Aster sotto GPL.",
        contextShowHidden: "Mostra elementi nascosti",
        contextHideHidden: "Nascondi elementi",
        contextShowAlways: "Mostra sempre nascosti",
        contextHideAlways: "Nascondi sempre nascosti",
        contextSettings: "Impostazioni barra dei menu...",
        contextDisable: "Disattiva gestore",
        errorPermission: "È richiesta l’autorizzazione Accessibilità.",
        errorUnavailable: "L’elemento non è più disponibile.",
        errorNotMovable: "macOS non consente di spostare questo elemento.",
        errorUnresolved: "L’identità dell’elemento non è abbastanza affidabile.",
        errorMenuOpen: "Chiudi il menu aperto dell’elemento e riprova.",
        errorEvent: "Aster non ha potuto creare il trascinamento.",
        errorVerification: "L’elemento non ha raggiunto la sezione richiesta.",
        errorBusy: "È ancora in corso un’altra operazione."
    )

    static let ja = MenuBarOrganizerStrings(
        pageTitle: "メニューバー",
        hubDescription: "メニューバー項目を隠す、表示する、並べ替える",
        unsupportedSystem: "macOS 27にはまだ対応していません。保存済みの設定は今後のアップデート用に保持されます。",
        enable: "メニューバー項目を管理",
        enableCaption: "表示、非表示、常に非表示の項目を分ける移動可能な区切りを追加します。",
        setupTitle: "セクションを設定",
        setupCaption: "項目をセクション間でドラッグします。完了するまで項目は隠れません。",
        finishSetup: "設定を完了",
        visible: "表示",
        hidden: "非表示",
        alwaysHidden: "常に非表示",
        emptySection: "ここにメニューバー項目をドロップ",
        dragHint: "ドラッグして並べ替えます。移動結果は実際のメニューバーで確認されます。",
        manualHint: "誤った項目を動かさないよう、識別できない項目と保護項目はロックされます。",
        refresh: "更新",
        retry: "再試行",
        undo: "直前の移動を取り消す",
        secondaryBar: "セカンダリバーを表示",
        accessibilityCaption: "アクセシビリティにより、手動と同じCommandキーを押しながらのドラッグを実行できます。",
        automaticMoveUnavailable: "項目へのアクセスが安定するまで自動整列は利用できません。",
        unresolvedCountFormat: "%d個の項目を識別できなかったためロックしています。",
        unresolvedItem: "この項目は確実に識別できないため移動しません。",
        protectedItem: "Asterと保護されたシステム項目はここでは移動できません。",
        conflictTitle: "別のメニューバー管理アプリが実行中です",
        conflictFormat: "Asterを有効にする前に%@を終了してください。複数の管理アプリは配置を壊す可能性があります。",
        sectionsTitle: "セクション",
        alwaysHiddenToggle: "常に非表示のセクションを有効にする",
        showDividers: "セクション区切りを表示したままにする",
        behaviorTitle: "表示方法",
        presentationTitle: "非表示項目の表示",
        presentationAutomatic: "自動",
        presentationMenuBar: "メニューバー",
        presentationSecondary: "セカンダリバー",
        presentationCaption: "自動ではノッチ搭載画面や空き領域が不足する場合にセカンダリバーを使います。",
        attribution: "IceとThawの動作を参考にし、GPLの下でAster向けに実装しました。",
        contextShowHidden: "非表示項目を表示",
        contextHideHidden: "項目を隠す",
        contextShowAlways: "常に非表示の項目を表示",
        contextHideAlways: "常に非表示の項目を隠す",
        contextSettings: "メニューバー設定...",
        contextDisable: "メニューバー管理をオフ",
        errorPermission: "アクセシビリティ権限が必要です。",
        errorUnavailable: "メニューバー項目は利用できなくなりました。",
        errorNotMovable: "macOSではこの項目を移動できません。",
        errorUnresolved: "項目の識別情報が移動に十分な信頼性を持ちません。",
        errorMenuOpen: "開いているメニューを閉じて再試行してください。",
        errorEvent: "ドラッグ操作を作成できませんでした。",
        errorVerification: "項目が指定したセクションに移動しませんでした。",
        errorBusy: "別のメニューバー操作を実行中です。"
    )

    static let ko = MenuBarOrganizerStrings(
        pageTitle: "메뉴 막대",
        hubDescription: "메뉴 막대 항목을 숨기고 표시하고 정렬합니다",
        unsupportedSystem: "아직 macOS 27과 호환되지 않습니다. 저장된 설정은 향후 업데이트를 위해 유지됩니다.",
        enable: "메뉴 막대 항목 관리",
        enableCaption: "표시, 숨김, 항상 숨김 항목을 위한 이동 가능한 구분선을 추가합니다.",
        setupTitle: "섹션 설정",
        setupCaption: "항목을 섹션 사이로 드래그하세요. 완료 전에는 아무것도 숨겨지지 않습니다.",
        finishSetup: "설정 완료",
        visible: "표시",
        hidden: "숨김",
        alwaysHidden: "항상 숨김",
        emptySection: "메뉴 막대 항목을 여기에 놓으세요",
        dragHint: "드래그하여 정렬합니다. 이동 결과는 실제 메뉴 막대에서 확인됩니다.",
        manualHint: "잘못된 항목을 옮기지 않도록 식별되지 않거나 보호된 항목은 잠깁니다.",
        refresh: "새로 고침",
        retry: "다시 시도",
        undo: "마지막 이동 취소",
        secondaryBar: "보조 막대 표시",
        accessibilityCaption: "손쉬운 사용 권한으로 수동과 같은 Command-드래그 동작을 수행합니다.",
        automaticMoveUnavailable: "항목 접근이 안정될 때까지 자동 정렬을 사용할 수 없습니다.",
        unresolvedCountFormat: "%d개 항목을 식별하지 못해 잠긴 상태로 둡니다.",
        unresolvedItem: "이 항목을 안정적으로 식별하지 못해 이동하지 않습니다.",
        protectedItem: "Aster 및 보호된 시스템 항목은 여기서 이동할 수 없습니다.",
        conflictTitle: "다른 메뉴 막대 관리자가 실행 중입니다",
        conflictFormat: "Aster를 켜기 전에 %@을 종료하세요. 두 관리자는 배치를 손상시킬 수 있습니다.",
        sectionsTitle: "섹션",
        alwaysHiddenToggle: "항상 숨김 섹션 사용",
        showDividers: "섹션 구분선 계속 표시",
        behaviorTitle: "표시 방식",
        presentationTitle: "숨긴 항목 표시",
        presentationAutomatic: "자동",
        presentationMenuBar: "메뉴 막대",
        presentationSecondary: "보조 막대",
        presentationCaption: "자동 모드는 노치가 있거나 공간이 부족할 때 보조 막대를 사용합니다.",
        attribution: "Ice와 Thaw의 동작을 참고해 GPL에 따라 Aster용으로 구현했습니다.",
        contextShowHidden: "숨긴 항목 표시",
        contextHideHidden: "항목 숨기기",
        contextShowAlways: "항상 숨김 항목 표시",
        contextHideAlways: "항상 숨김 항목 숨기기",
        contextSettings: "메뉴 막대 설정...",
        contextDisable: "메뉴 막대 관리자 끄기",
        errorPermission: "손쉬운 사용 권한이 필요합니다.",
        errorUnavailable: "메뉴 막대 항목을 더 이상 사용할 수 없습니다.",
        errorNotMovable: "macOS에서 이 항목의 이동을 허용하지 않습니다.",
        errorUnresolved: "항목 신원이 이동하기에 충분히 안정적이지 않습니다.",
        errorMenuOpen: "열린 메뉴를 닫고 다시 시도하세요.",
        errorEvent: "드래그 동작을 만들 수 없습니다.",
        errorVerification: "항목이 요청한 섹션에 도달하지 않았습니다.",
        errorBusy: "다른 메뉴 막대 작업이 아직 진행 중입니다."
    )

    static let zhHans = MenuBarOrganizerStrings(
        pageTitle: "菜单栏",
        hubDescription: "隐藏、显示和排列菜单栏项目",
        unsupportedSystem: "暂不兼容 macOS 27。已保存的设置将保留，供未来更新使用。",
        enable: "管理菜单栏项目",
        enableCaption: "为显示、隐藏和始终隐藏的项目添加可移动分隔项。",
        setupTitle: "设置菜单栏分区",
        setupCaption: "在分区之间拖动项目。完成设置前不会隐藏任何项目。",
        finishSetup: "完成设置",
        visible: "显示",
        hidden: "隐藏",
        alwaysHidden: "始终隐藏",
        emptySection: "将菜单栏项目拖到这里",
        dragHint: "拖动即可排序。每次移动都会在实际菜单栏中验证。",
        manualHint: "无法识别或受保护的项目会保持锁定，避免移动错误的项目。",
        refresh: "刷新",
        retry: "重试",
        undo: "撤销上次移动",
        secondaryBar: "显示辅助栏",
        accessibilityCaption: "辅助功能权限让 Aster 执行与手动按住 Command 拖动相同的操作。",
        automaticMoveUnavailable: "只有可靠访问项目后才能自动排列。",
        unresolvedCountFormat: "有 %d 个项目无法识别，已保持锁定。",
        unresolvedItem: "无法可靠识别此项目，因此不会移动它。",
        protectedItem: "不能在此移动 Aster 自身和受保护的系统项目。",
        conflictTitle: "另一个菜单栏管理器正在运行",
        conflictFormat: "启用 Aster 前请退出 %@。同时运行两个管理器可能损坏布局。",
        sectionsTitle: "分区",
        alwaysHiddenToggle: "启用始终隐藏分区",
        showDividers: "始终显示分区分隔项",
        behaviorTitle: "显示方式",
        presentationTitle: "显示隐藏项目",
        presentationAutomatic: "自动",
        presentationMenuBar: "菜单栏",
        presentationSecondary: "辅助栏",
        presentationCaption: "自动模式会在刘海屏或空间不足时使用辅助栏。",
        attribution: "功能行为参考 Ice 和 Thaw，并以 GPL 许可为 Aster 独立实现。",
        contextShowHidden: "显示隐藏项目",
        contextHideHidden: "隐藏项目",
        contextShowAlways: "显示始终隐藏项目",
        contextHideAlways: "隐藏始终隐藏项目",
        contextSettings: "菜单栏设置...",
        contextDisable: "关闭菜单栏管理",
        errorPermission: "需要辅助功能权限。",
        errorUnavailable: "该菜单栏项目已不可用。",
        errorNotMovable: "macOS 不允许移动此项目。",
        errorUnresolved: "项目身份不够可靠，无法移动。",
        errorMenuOpen: "请关闭该项目已打开的菜单后重试。",
        errorEvent: "Aster 无法创建拖动操作。",
        errorVerification: "项目未到达指定分区。",
        errorBusy: "另一个菜单栏操作仍在进行中。"
    )

    static let zhTW = MenuBarOrganizerStrings(
        pageTitle: "選單列",
        hubDescription: "隱藏、顯示和排列選單列項目",
        unsupportedSystem: "尚未支援 macOS 27。已儲存的設定會保留，以供日後更新使用。",
        enable: "管理選單列項目",
        enableCaption: "為顯示、隱藏和永遠隱藏的項目加入可移動分隔項。",
        setupTitle: "設定選單列分區",
        setupCaption: "在分區之間拖移項目。完成設定前不會隱藏任何項目。",
        finishSetup: "完成設定",
        visible: "顯示",
        hidden: "隱藏",
        alwaysHidden: "永遠隱藏",
        emptySection: "將選單列項目拖到這裡",
        dragHint: "拖移即可排序。每次移動都會在實際選單列中驗證。",
        manualHint: "無法辨識或受保護的項目會保持鎖定，避免移動錯誤的項目。",
        refresh: "重新整理",
        retry: "再試一次",
        undo: "還原上次移動",
        secondaryBar: "顯示輔助列",
        accessibilityCaption: "輔助使用權限讓 Aster 執行與手動按住 Command 拖移相同的操作。",
        automaticMoveUnavailable: "只有可靠存取項目後才能自動排列。",
        unresolvedCountFormat: "有 %d 個項目無法辨識，已保持鎖定。",
        unresolvedItem: "無法可靠辨識此項目，因此不會移動它。",
        protectedItem: "不能在此移動 Aster 自身和受保護的系統項目。",
        conflictTitle: "另一個選單列管理器正在執行",
        conflictFormat: "啟用 Aster 前請結束 %@。同時執行兩個管理器可能破壞版面。",
        sectionsTitle: "分區",
        alwaysHiddenToggle: "啟用永遠隱藏分區",
        showDividers: "保持顯示分區分隔項",
        behaviorTitle: "顯示方式",
        presentationTitle: "顯示隱藏項目",
        presentationAutomatic: "自動",
        presentationMenuBar: "選單列",
        presentationSecondary: "輔助列",
        presentationCaption: "自動模式會在瀏海螢幕或空間不足時使用輔助列。",
        attribution: "功能行為參考 Ice 和 Thaw，並依 GPL 授權為 Aster 獨立實作。",
        contextShowHidden: "顯示隱藏項目",
        contextHideHidden: "隱藏項目",
        contextShowAlways: "顯示永遠隱藏項目",
        contextHideAlways: "隱藏永遠隱藏項目",
        contextSettings: "選單列設定...",
        contextDisable: "關閉選單列管理",
        errorPermission: "需要輔助使用權限。",
        errorUnavailable: "該選單列項目已無法使用。",
        errorNotMovable: "macOS 不允許移動此項目。",
        errorUnresolved: "項目身分不夠可靠，無法移動。",
        errorMenuOpen: "請關閉該項目已開啟的選單後再試。",
        errorEvent: "Aster 無法建立拖移操作。",
        errorVerification: "項目未到達指定分區。",
        errorBusy: "另一個選單列操作仍在進行中。"
    )

    static let zhHK = MenuBarOrganizerStrings(
        pageTitle: "選單列",
        hubDescription: "隱藏、顯示及排列選單列項目",
        unsupportedSystem: "暫未支援 macOS 27。已儲存的設定會保留，供日後更新使用。",
        enable: "管理選單列項目",
        enableCaption: "為顯示、隱藏及永遠隱藏的項目加入可移動分隔項。",
        setupTitle: "設定選單列分區",
        setupCaption: "在分區之間拖移項目。完成設定前不會隱藏任何項目。",
        finishSetup: "完成設定",
        visible: "顯示",
        hidden: "隱藏",
        alwaysHidden: "永遠隱藏",
        emptySection: "將選單列項目拖到這裡",
        dragHint: "拖移即可排序。每次移動都會在實際選單列中驗證。",
        manualHint: "未能辨識或受保護的項目會保持鎖定，避免移動錯誤項目。",
        refresh: "重新整理",
        retry: "再試一次",
        undo: "還原上次移動",
        secondaryBar: "顯示輔助列",
        accessibilityCaption: "輔助使用權限讓 Aster 執行與手動按住 Command 拖移相同的操作。",
        automaticMoveUnavailable: "只有可靠存取項目後才能自動排列。",
        unresolvedCountFormat: "有 %d 個項目未能辨識，已保持鎖定。",
        unresolvedItem: "未能可靠辨識此項目，因此不會移動它。",
        protectedItem: "不能在此移動 Aster 本身及受保護的系統項目。",
        conflictTitle: "另一個選單列管理器正在執行",
        conflictFormat: "啟用 Aster 前請結束 %@。同時執行兩個管理器可能破壞版面。",
        sectionsTitle: "分區",
        alwaysHiddenToggle: "啟用永遠隱藏分區",
        showDividers: "保持顯示分區分隔項",
        behaviorTitle: "顯示方式",
        presentationTitle: "顯示隱藏項目",
        presentationAutomatic: "自動",
        presentationMenuBar: "選單列",
        presentationSecondary: "輔助列",
        presentationCaption: "自動模式會在瀏海螢幕或空間不足時使用輔助列。",
        attribution: "功能行為參考 Ice 及 Thaw，並依 GPL 授權為 Aster 獨立實作。",
        contextShowHidden: "顯示隱藏項目",
        contextHideHidden: "隱藏項目",
        contextShowAlways: "顯示永遠隱藏項目",
        contextHideAlways: "隱藏永遠隱藏項目",
        contextSettings: "選單列設定...",
        contextDisable: "關閉選單列管理",
        errorPermission: "需要輔助使用權限。",
        errorUnavailable: "該選單列項目已無法使用。",
        errorNotMovable: "macOS 不允許移動此項目。",
        errorUnresolved: "項目身分不夠可靠，無法移動。",
        errorMenuOpen: "請關閉該項目已開啟的選單後再試。",
        errorEvent: "Aster 無法建立拖移操作。",
        errorVerification: "項目未到達指定分區。",
        errorBusy: "另一個選單列操作仍在進行中。"
    )
}

extension MenuBarOrganizerStrings {
    static let sk = MenuBarOrganizerStrings(
        pageTitle: "Panel s ponukami",
        hubDescription: "Skryte, zobrazte a usporiadajte ikony na paneli",
        unsupportedSystem: "Systém macOS 27 zatiaľ nie je podporovaný. Uložené nastavenia zostanú zachované.",
        enable: "Spravovať ikony na paneli",
        enableCaption: "Pridá presúvateľné oddeľovače pre viditeľné, skryté a vždy skryté položky.",
        setupTitle: "Nastavte sekcie",
        setupCaption: "Presuňte položky medzi sekciami. Až do dokončenia sa nič neskryje.",
        finishSetup: "Dokončiť nastavenie",
        visible: "Viditeľné",
        hidden: "Skryté",
        alwaysHidden: "Vždy skryté",
        emptySection: "Sem presuňte položky",
        dragHint: "Presúvaním zmeňte poradie. Každý presun sa overí na skutočnom paneli.",
        manualHint: "Neidentifikované a chránené položky zostávajú uzamknuté.",
        refresh: "Obnoviť",
        retry: "Skúsiť znova",
        undo: "Vrátiť posledný presun",
        secondaryBar: "Zobraziť vedľajší panel",
        accessibilityCaption: "Prístupnosť umožňuje aplikácii Aster presúvať položky pomocou klávesu Command.",
        automaticMoveUnavailable: "Automatické usporiadanie nie je dostupné, kým nie je prístup spoľahlivý.",
        unresolvedCountFormat: "%d položiek sa nepodarilo identifikovať a zostali uzamknuté.",
        unresolvedItem: "Túto položku sa nepodarilo spoľahlivo identifikovať.",
        protectedItem: "Položky aplikácie Aster a chránené systémové položky nemožno presunúť.",
        conflictTitle: "Je spustený iný správca panela",
        conflictFormat: "Pred zapnutím správcu Aster ukončite %@. Dvaja správcovia môžu poškodiť rozloženie.",
        sectionsTitle: "Sekcie",
        alwaysHiddenToggle: "Zapnúť vždy skrytú sekciu",
        showDividers: "Zobraziť oddeľovače sekcií",
        behaviorTitle: "Zobrazenie",
        presentationTitle: "Zobraziť skryté položky",
        presentationAutomatic: "Automaticky",
        presentationMenuBar: "Panel s ponukami",
        presentationSecondary: "Vedľajší panel",
        presentationCaption: "Automatický režim používa vedľajší panel pri výreze alebo nedostatku miesta.",
        attribution: "Správanie vychádza z Ice a Thaw. Upravené pre Aster podľa GPL.",
        contextShowHidden: "Zobraziť skryté položky",
        contextHideHidden: "Skryť položky",
        contextShowAlways: "Zobraziť vždy skryté položky",
        contextHideAlways: "Skryť vždy skryté položky",
        contextSettings: "Nastavenia panela…",
        contextDisable: "Vypnúť správcu panela",
        errorPermission: "Je potrebné povolenie prístupnosti.",
        errorUnavailable: "Položka už nie je dostupná.",
        errorNotMovable: "macOS neumožňuje presun tejto položky.",
        errorUnresolved: "Identita položky nie je dostatočne spoľahlivá.",
        errorMenuOpen: "Zatvorte otvorenú ponuku a skúste znova.",
        errorEvent: "Nepodarilo sa vytvoriť presun.",
        errorVerification: "Položka sa nepresunula do požadovanej sekcie.",
        errorBusy: "Práve prebieha iná operácia."
    )
}

extension MenuBarOrganizerStrings {
    static let uk = MenuBarOrganizerStrings(
        pageTitle: "Рядок меню",
        hubDescription: "Приховуйте, показуйте й упорядковуйте значки",
        unsupportedSystem: "macOS 27 поки не підтримується. Збережені налаштування залишаться.",
        enable: "Керувати значками рядка меню",
        enableCaption: "Додає пересувні роздільники видимих, прихованих і завжди прихованих значків.",
        setupTitle: "Налаштуйте розділи",
        setupCaption: "Перетягніть значки між розділами. До завершення нічого не приховується.",
        finishSetup: "Завершити налаштування",
        visible: "Видимі",
        hidden: "Приховані",
        alwaysHidden: "Завжди приховані",
        emptySection: "Перетягніть сюди значки",
        dragHint: "Перетягніть для зміни порядку. Кожне переміщення перевіряється.",
        manualHint: "Невизначені й захищені значки залишаються заблокованими.",
        refresh: "Оновити",
        retry: "Спробувати знову",
        undo: "Скасувати переміщення",
        secondaryBar: "Показати додаткову панель",
        accessibilityCaption: "Універсальний доступ дозволяє Aster перетягувати значки з клавішею Command.",
        automaticMoveUnavailable: "Автоматичне впорядкування недоступне до надійного доступу.",
        unresolvedCountFormat: "Не вдалося визначити %d значків. Вони заблоковані.",
        unresolvedItem: "Не вдалося надійно визначити цей значок.",
        protectedItem: "Значки Aster і захищені системні значки не можна переміщувати.",
        conflictTitle: "Працює інший менеджер рядка меню",
        conflictFormat: "Завершіть %@ перед увімкненням Aster. Два менеджери можуть пошкодити розташування.",
        sectionsTitle: "Розділи",
        alwaysHiddenToggle: "Увімкнути завжди прихований розділ",
        showDividers: "Показувати роздільники",
        behaviorTitle: "Відображення",
        presentationTitle: "Показувати приховані значки",
        presentationAutomatic: "Автоматично",
        presentationMenuBar: "Рядок меню",
        presentationSecondary: "Додаткова панель",
        presentationCaption: "Автоматичний режим використовує додаткову панель за наявності вирізу чи нестачі місця.",
        attribution: "Поведінка на основі Ice і Thaw. Адаптовано для Aster за GPL.",
        contextShowHidden: "Показати приховані значки",
        contextHideHidden: "Приховати значки",
        contextShowAlways: "Показати завжди приховані значки",
        contextHideAlways: "Приховати завжди приховані значки",
        contextSettings: "Налаштування рядка меню…",
        contextDisable: "Вимкнути менеджер",
        errorPermission: "Потрібен дозвіл універсального доступу.",
        errorUnavailable: "Значок більше недоступний.",
        errorNotMovable: "macOS не дозволяє перемістити цей значок.",
        errorUnresolved: "Ідентифікація значка недостатньо надійна.",
        errorMenuOpen: "Закрийте відкриту меню та повторіть.",
        errorEvent: "Не вдалося створити переміщення.",
        errorVerification: "Значок не досяг потрібного розділу.",
        errorBusy: "Інша операція ще триває."
    )
}
