// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchStrings {
    let title: String
    let combineActivities: String
    let enable: String
    let description: String
    let menuBarAccessHint: String
    let display: String
    let automatic: String
    let builtIn: String
    let mainDisplay: String
    let followPointer: String
    let hover: String
    let modules: String
    let events: String
    let clipboardActivity: String
    let captureActivity: String
    let privacy: String
    let open: String
    let collapse: String
    let pin: String
    let unpin: String
    let panel: String
    let dropHint: String
    let empty: String
    let volume: String
    let brightness: String
    let battery: String
    let onBattery: String
    let charging: String
    let charged: String
    let lowBattery: String
    let controls: String
    let system: String
    let disabled: String
    let files: String
    let hideInFullscreen: String
    let showInCaptures: String
    let clipboardWindow: String
    let tools: String
    let size: String
    let showOutline: String
    let compact: String
    let spacious: String
    let hoverExpand: String
    let shelfWindow: String
    let dragReveal: String
    let captureControls: String
    let quickPanel: String
    let appPanel: String
    let idleContent: String
    let idleNone: String
    let coverMenus: String
    let coverMenusHint: String
    let controlShortcuts: String
    let activity: String
    let playingMusic: String
    let custom: String
    let width: String
    let maximumHeight: String
    let sizeHint: String
    let cameraFit: String
    let height: String
    let cameraFitHint: String
    let hapticFeedback: String
    let hapticHint: String
    let playbackPosition: String
    let musicHint: String
    let music: String
    let captures: String
    let newTrack: String
    let customizeTools: String
    let switchSection: String
    let sectionsTitle: String
    let searchSections: String
    let sectionKeyboardHint: String
    let quickAccessLeft: String
    let quickAccessRight: String
}

extension FeatureStrings {
    static func notch(_ language: AppLanguage) -> NotchStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ru: return .ru
        case .tr: return .tr
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }
}

extension NotchStrings {
    static let enUS = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Combine",
        enable: "Enable Dynamic Island",
        description: "Your music, controls and everyday tools, together at the top of your screen. Optional. Turn it off to keep using the separate panels.",
        menuBarAccessHint: "Allow Accessibility so Dynamic Island can appear on this display without covering the menus.",
        display: "Display",
        automatic: "Automatic",
        builtIn: "Built-in display",
        mainDisplay: "Main display",
        followPointer: "Follow pointer",
        hover: "Open when the pointer rests on the Dynamic Island",
        modules: "What appears",
        events: "More options",
        clipboardActivity: "Notify when something is copied",
        captureActivity: "Show screenshot previews here",
        privacy: "Copied content stays private until you open the clipboard. These options follow the original feature’s settings.",
        open: "Open Dynamic Island",
        collapse: "Collapse",
        pin: "Keep open",
        unpin: "Allow automatic closing",
        panel: "Open app panel",
        dropHint: "Drop files here",
        empty: "Choose what appears in Dynamic Island settings.",
        volume: "Volume",
        brightness: "Brightness",
        battery: "Battery",
        onBattery: "On battery",
        charging: "Charging",
        charged: "Fully charged",
        lowBattery: "Low battery",
        controls: "Controls",
        system: "System",
        disabled: "Enable the corresponding feature to use it here.",
        files: "Files",
        hideInFullscreen: "Hide content in full screen",
        showInCaptures: "Show in screenshots and videos",
        clipboardWindow: "Open clipboard history in the Dynamic Island",
        tools: "Tools",
        size: "Size",
        showOutline: "Show outline",
        compact: "Compact",
        spacious: "Spacious",
        hoverExpand: "Expand fully on hover",
        shelfWindow: "Open the file shelf in the Dynamic Island",
        dragReveal: "Show a drop target while dragging",
        captureControls: "Show screen capture controls in the Dynamic Island",
        quickPanel: "Open the quick panel in the Dynamic Island",
        appPanel: "Open the app panel in the Dynamic Island",
        idleContent: "While inactive",
        idleNone: "Nothing",
        coverMenus: "Show over the menus",
        coverMenusHint: "Keeps the timer, music and other compact activity on screen when the menu bar has no room, covering the menus beside the camera.",
        controlShortcuts: "Controls and shortcuts",
        activity: "Activity",
        playingMusic: "Show music while playing",
        custom: "Custom",
        width: "Width",
        maximumHeight: "Maximum height",
        sizeHint: "Controls stay compact. Longer lists use up to this height.",
        cameraFit: "Notch fit",
        height: "Height",
        cameraFitHint: "If an edge of the notch shows around Dynamic Island, adjust these values until it disappears.",
        hapticFeedback: "Haptic feedback",
        hapticHint: "Gentle taps when opening, switching sections or adjusting timer minutes, on a compatible trackpad.",
        playbackPosition: "Playback position",
        musicHint: "Your music and playback controls appear here.",
        music: "Music",
        captures: "Captures",
        newTrack: "New track",
        customizeTools: "Customize tools",
        switchSection: "Switch section",
        sectionsTitle: "Explore",
        searchSections: "Find a section",
        sectionKeyboardHint: "Use the arrow keys, then press Return",
        quickAccessLeft: "Left",
        quickAccessRight: "Right"
    )

    static let ptBR = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Combinar",
        enable: "Ativar Dynamic Island",
        description: "Sua música, controles e ferramentas do dia a dia, juntos no topo da tela. Opcional. Desative para continuar usando os painéis separados.",
        menuBarAccessHint: "Permita Acessibilidade para a Dynamic Island aparecer nesta tela sem cobrir os menus.",
        display: "Tela",
        automatic: "Automática",
        builtIn: "Tela integrada",
        mainDisplay: "Tela principal",
        followPointer: "Seguir o ponteiro",
        hover: "Abrir ao repousar o ponteiro sobre o Dynamic Island",
        modules: "O que aparece",
        events: "Mais opções",
        clipboardActivity: "Avisar quando algo for copiado",
        captureActivity: "Mostrar prévias de capturas aqui",
        privacy: "O conteúdo copiado fica privado até você abrir o histórico. Estas opções respeitam os ajustes do recurso original.",
        open: "Abrir Dynamic Island",
        collapse: "Recolher",
        pin: "Manter aberto",
        unpin: "Permitir fechamento automático",
        panel: "Abrir painel do app",
        dropHint: "Solte arquivos aqui",
        empty: "Escolha o que aparece nos ajustes do Dynamic Island.",
        volume: "Volume",
        brightness: "Brilho",
        battery: "Bateria",
        onBattery: "Usando bateria",
        charging: "Carregando",
        charged: "Carga completa",
        lowBattery: "Bateria fraca",
        controls: "Controles",
        system: "Sistema",
        disabled: "Ative o recurso correspondente para usá-lo aqui.",
        files: "Arquivos",
        hideInFullscreen: "Ocultar conteúdo em tela cheia",
        showInCaptures: "Aparecer em capturas de tela e vídeos",
        clipboardWindow: "Abrir o histórico de cópias no Dynamic Island",
        tools: "Ferramentas",
        size: "Tamanho",
        showOutline: "Mostrar contorno",
        compact: "Compacto",
        spacious: "Amplo",
        hoverExpand: "Expandir completamente ao passar o mouse",
        shelfWindow: "Abrir a área de arquivos no Dynamic Island",
        dragReveal: "Mostrar um espaço para soltar ao arrastar",
        captureControls: "Mostrar os controles de captura no Dynamic Island",
        quickPanel: "Abrir o painel rápido no Dynamic Island",
        appPanel: "Abrir o painel do aplicativo no Dynamic Island",
        idleContent: "Em repouso",
        idleNone: "Nada",
        coverMenus: "Mostrar por cima dos menus",
        coverMenusHint: "Mantém o temporizador, a música e as outras atividades compactas na tela quando a barra de menus não tem espaço, cobrindo os menus ao lado da câmera.",
        controlShortcuts: "Controles e atalhos",
        activity: "Atividade",
        playingMusic: "Mostrar música durante a reprodução",
        custom: "Personalizado",
        width: "Largura",
        maximumHeight: "Altura máxima",
        sizeHint: "A área de controles fica compacta. Listas maiores usam até esta altura.",
        cameraFit: "Encaixe no notch",
        height: "Altura",
        cameraFitHint: "Se alguma borda do notch aparecer ao redor do Dynamic Island, ajuste estes valores até ela sumir.",
        hapticFeedback: "Resposta tátil",
        hapticHint: "Toques suaves ao abrir, trocar de seção ou ajustar os minutos do temporizador, em um trackpad compatível.",
        playbackPosition: "Posição da reprodução",
        musicHint: "Sua música e os controles de reprodução aparecem aqui.",
        music: "Música",
        captures: "Capturas",
        newTrack: "Nova música",
        customizeTools: "Personalizar ferramentas",
        switchSection: "Trocar de seção",
        sectionsTitle: "Explorar",
        searchSections: "Encontrar uma seção",
        sectionKeyboardHint: "Use as setas e pressione Return",
        quickAccessLeft: "Esquerdo",
        quickAccessRight: "Direito"
    )

    static let es = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Combinar",
        enable: "Activar Dynamic Island",
        description: "Tu música, controles y herramientas cotidianas, juntos en la parte superior de la pantalla. Opcional. Desactívalo para seguir usando los paneles por separado.",
        menuBarAccessHint: "Permite Accesibilidad para que Dynamic Island aparezca en esta pantalla sin cubrir los menús.",
        display: "Pantalla",
        automatic: "Automática",
        builtIn: "Pantalla integrada",
        mainDisplay: "Pantalla principal",
        followPointer: "Seguir el puntero",
        hover: "Abrir al dejar el puntero sobre el Dynamic Island",
        modules: "Qué aparece",
        events: "Más opciones",
        clipboardActivity: "Avisar cuando se copie algo",
        captureActivity: "Mostrar vistas previas de capturas aquí",
        privacy: "El contenido copiado permanece privado hasta que abras el historial. Estas opciones respetan los ajustes de cada función.",
        open: "Abrir Dynamic Island",
        collapse: "Contraer",
        pin: "Mantener abierto",
        unpin: "Permitir cierre automático",
        panel: "Abrir panel de la app",
        dropHint: "Suelta archivos aquí",
        empty: "Elige qué aparece en los ajustes de Dynamic Island.",
        volume: "Volumen",
        brightness: "Brillo",
        battery: "Batería",
        onBattery: "Usando batería",
        charging: "Cargando",
        charged: "Carga completa",
        lowBattery: "Batería baja",
        controls: "Controles",
        system: "Sistema",
        disabled: "Activa la función correspondiente para usarla aquí.",
        files: "Archivos",
        hideInFullscreen: "Ocultar contenido en pantalla completa",
        showInCaptures: "Mostrar en capturas de pantalla y vídeos",
        clipboardWindow: "Abrir el historial del portapapeles en el Dynamic Island",
        tools: "Herramientas",
        size: "Tamaño",
        showOutline: "Mostrar contorno",
        compact: "Compacto",
        spacious: "Amplio",
        hoverExpand: "Expandir por completo al pasar el puntero",
        shelfWindow: "Abrir la bandeja de archivos en el Dynamic Island",
        dragReveal: "Mostrar un destino al arrastrar",
        captureControls: "Mostrar controles de captura en el Dynamic Island",
        quickPanel: "Abrir el panel rápido en el Dynamic Island",
        appPanel: "Abrir el panel de la aplicación en el Dynamic Island",
        idleContent: "En reposo",
        idleNone: "Nada",
        coverMenus: "Mostrar sobre los menús",
        coverMenusHint: "Mantiene el temporizador, la música y otras actividades compactas en pantalla cuando la barra de menús no tiene espacio, cubriendo los menús junto a la cámara.",
        controlShortcuts: "Controles y atajos",
        activity: "Actividad",
        playingMusic: "Mostrar música durante la reproducción",
        custom: "Personalizado",
        width: "Ancho",
        maximumHeight: "Altura máxima",
        sizeHint: "Los controles se mantienen compactos. Las listas largas usan hasta esta altura.",
        cameraFit: "Ajuste al notch",
        height: "Altura",
        cameraFitHint: "Si se ve algún borde del notch alrededor del Dynamic Island, ajusta estos valores hasta que desaparezca.",
        hapticFeedback: "Respuesta háptica",
        hapticHint: "Toques suaves al abrir, cambiar de sección o ajustar los minutos del temporizador, en un trackpad compatible.",
        playbackPosition: "Posición de reproducción",
        musicHint: "Tu música y los controles de reproducción aparecen aquí.",
        music: "Música",
        captures: "Capturas",
        newTrack: "Nueva canción",
        customizeTools: "Personalizar herramientas",
        switchSection: "Cambiar de sección",
        sectionsTitle: "Explorar",
        searchSections: "Buscar una sección",
        sectionKeyboardHint: "Usa las flechas y pulsa Intro",
        quickAccessLeft: "Izquierdo",
        quickAccessRight: "Derecho"
    )

    static let sk = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Kombinovať",
        enable: "Zapnúť Dynamic Island",
        description: "Vaša hudba, ovládacie prvky a bežné nástroje na jednom mieste v hornej časti obrazovky. Voliteľné. Vypnutím budete naďalej používať samostatné panely.",
        menuBarAccessHint: "Povoľte Prístupnosť, aby sa Dynamic Island mohol zobraziť na tomto displeji bez prekrývania ponúk.",
        display: "Displej",
        automatic: "Automaticky",
        builtIn: "Vstavaný displej",
        mainDisplay: "Hlavný displej",
        followPointer: "Sledovať kurzor",
        hover: "Otvoriť, keď kurzor zostane na Dynamic Island",
        modules: "Čo sa zobrazuje",
        events: "Ďalšie možnosti",
        clipboardActivity: "Upozorniť pri skopírovaní",
        captureActivity: "Zobraziť tu náhľady snímok obrazovky",
        privacy: "Skopírovaný obsah zostáva súkromný, kým neotvoríte históriu. Tieto možnosti sa riadia nastaveniami danej funkcie.",
        open: "Otvoriť Dynamic Island",
        collapse: "Zbaliť",
        pin: "Ponechať otvorené",
        unpin: "Povoliť automatické zatvorenie",
        panel: "Otvoriť panel aplikácie",
        dropHint: "Súbory pretiahnite sem",
        empty: "Vyberte, čo sa má zobrazovať v nastaveniach Dynamic Island.",
        volume: "Hlasitosť",
        brightness: "Jas",
        battery: "Batéria",
        onBattery: "Na batérii",
        charging: "Nabíja sa",
        charged: "Úplne nabitá",
        lowBattery: "Nízky stav batérie",
        controls: "Ovládacie prvky",
        system: "Systém",
        disabled: "Zapnite príslušnú funkciu, aby ste ju tu mohli používať.",
        files: "Súbory",
        hideInFullscreen: "Skryť obsah v režime celej obrazovky",
        showInCaptures: "Zobraziť v snímkach obrazovky a videách",
        clipboardWindow: "Otvoriť históriu schránky v Dynamic Island",
        tools: "Nástroje",
        size: "Veľkosť",
        showOutline: "Zobraziť obrys",
        compact: "Kompaktná",
        spacious: "Priestranná",
        hoverExpand: "Pri prejdení kurzorom úplne rozbaliť",
        shelfWindow: "Otvoriť policu súborov v Dynamic Island",
        dragReveal: "Zobraziť cieľ presunu počas ťahania",
        captureControls: "Zobraziť ovládanie snímania obrazovky v Dynamic Island",
        quickPanel: "Otvoriť rýchly panel v Dynamic Island",
        appPanel: "Otvoriť panel aplikácie v Dynamic Island",
        idleContent: "V nečinnosti",
        idleNone: "Nič",
        coverMenus: "Zobraziť nad ponukami",
        coverMenusHint: "Ponechá časovač, hudbu a ostatnú kompaktnú aktivitu na obrazovke, keď lišta nemá miesto, pričom prekryje ponuky vedľa kamery.",
        controlShortcuts: "Ovládanie a skratky",
        activity: "Aktivita",
        playingMusic: "Zobraziť hudbu počas prehrávania",
        custom: "Vlastná",
        width: "Šírka",
        maximumHeight: "Maximálna výška",
        sizeHint: "Ovládacie prvky zostávajú kompaktné. Dlhšie zoznamy využijú až túto výšku.",
        cameraFit: "Prispôsobenie výrezu",
        height: "Výška",
        cameraFitHint: "Ak je okolo Dynamic Island vidieť okraj výrezu, upravte tieto hodnoty, kým nezmizne.",
        hapticFeedback: "Haptická odozva",
        hapticHint: "Jemné impulzy pri otváraní, prepínaní sekcií alebo úprave minút časovača na kompatibilnom trackpade.",
        playbackPosition: "Pozícia prehrávania",
        musicHint: "Tu sa zobrazí vaša hudba a ovládanie prehrávania.",
        music: "Hudba",
        captures: "Snímky",
        newTrack: "Nová skladba",
        customizeTools: "Prispôsobiť nástroje",
        switchSection: "Prepnúť sekciu",
        sectionsTitle: "Preskúmať",
        searchSections: "Nájsť sekciu",
        sectionKeyboardHint: "Použite šípky a stlačte Return",
        quickAccessLeft: "Vľavo",
        quickAccessRight: "Vpravo"
    )

    static let de = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Kombinieren",
        enable: "Dynamic Island aktivieren",
        description: "Musik, Steuerelemente und alltägliche Werkzeuge am oberen Bildschirmrand. Optional. Deaktiviere die Funktion, um die separaten Bereiche weiter zu nutzen.",
        menuBarAccessHint: "Erlaube die Bedienungshilfen, damit Dynamic Island auf diesem Bildschirm erscheint, ohne die Menüs zu verdecken.",
        display: "Bildschirm",
        automatic: "Automatisch",
        builtIn: "Integrierter Bildschirm",
        mainDisplay: "Hauptbildschirm",
        followPointer: "Zeiger folgen",
        hover: "Öffnen, wenn der Zeiger auf der Dynamic Island ruht",
        modules: "Angezeigte Inhalte",
        events: "Weitere Optionen",
        clipboardActivity: "Beim Kopieren benachrichtigen",
        captureActivity: "Bildschirmfoto-Vorschauen hier anzeigen",
        privacy: "Kopierte Inhalte bleiben privat, bis du den Verlauf öffnest. Diese Optionen beachten die Einstellungen der jeweiligen Funktion.",
        open: "Dynamic Island öffnen",
        collapse: "Einklappen",
        pin: "Geöffnet lassen",
        unpin: "Automatisches Schließen erlauben",
        panel: "App-Panel öffnen",
        dropHint: "Dateien hier ablegen",
        empty: "Wähle die Inhalte in den Dynamic Island-Einstellungen.",
        volume: "Lautstärke",
        brightness: "Helligkeit",
        battery: "Batterie",
        onBattery: "Batteriebetrieb",
        charging: "Wird geladen",
        charged: "Vollständig geladen",
        lowBattery: "Niedriger Batteriestand",
        controls: "Steuerung",
        system: "System",
        disabled: "Aktiviere die entsprechende Funktion, um sie hier zu nutzen.",
        files: "Dateien",
        hideInFullscreen: "Inhalt im Vollbild ausblenden",
        showInCaptures: "In Screenshots und Videos anzeigen",
        clipboardWindow: "Zwischenablageverlauf in der Dynamic Island öffnen",
        tools: "Werkzeuge",
        size: "Größe",
        showOutline: "Kontur anzeigen",
        compact: "Kompakt",
        spacious: "Geräumig",
        hoverExpand: "Beim Darüberfahren vollständig öffnen",
        shelfWindow: "Dateiablage im Dynamic Island öffnen",
        dragReveal: "Ablageziel beim Ziehen anzeigen",
        captureControls: "Aufnahmesteuerung im Dynamic Island anzeigen",
        quickPanel: "Schnellzugriff im Dynamic Island öffnen",
        appPanel: "App-Bereich im Dynamic Island öffnen",
        idleContent: "Im Ruhezustand",
        idleNone: "Nichts",
        coverMenus: "Über den Menüs anzeigen",
        coverMenusHint: "Zeigt Timer, Musik und andere kompakte Aktivitäten weiter an, wenn die Menüleiste keinen Platz hat, und verdeckt dabei die Menüs neben der Kamera.",
        controlShortcuts: "Steuerung und Kurzbefehle",
        activity: "Aktivität",
        playingMusic: "Musik während der Wiedergabe anzeigen",
        custom: "Eigene Größe",
        width: "Breite",
        maximumHeight: "Maximale Höhe",
        sizeHint: "Die Steuerung bleibt kompakt. Längere Listen nutzen bis zu dieser Höhe.",
        cameraFit: "Anpassung an die Notch",
        height: "Höhe",
        cameraFitHint: "Wenn rund um die Dynamic Island ein Rand der Notch zu sehen ist, passe diese Werte an, bis er verschwindet.",
        hapticFeedback: "Haptisches Feedback",
        hapticHint: "Sanfte Impulse beim Öffnen, beim Bereichswechsel oder beim Einstellen der Timer-Minuten auf einem kompatiblen Trackpad.",
        playbackPosition: "Wiedergabeposition",
        musicHint: "Deine Musik und die Wiedergabesteuerung erscheinen hier.",
        music: "Musik",
        captures: "Aufnahmen",
        newTrack: "Neuer Titel",
        customizeTools: "Werkzeuge anpassen",
        switchSection: "Bereich wechseln",
        sectionsTitle: "Entdecken",
        searchSections: "Bereich finden",
        sectionKeyboardHint: "Mit den Pfeiltasten wählen, mit Eingabe öffnen",
        quickAccessLeft: "Links",
        quickAccessRight: "Rechts"
    )

    static let fr = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Combiner",
        enable: "Activer Dynamic Island",
        description: "Votre musique, vos commandes et vos outils du quotidien, réunis en haut de l’écran. Facultatif. Désactivez cette option pour continuer à utiliser les panneaux séparés.",
        menuBarAccessHint: "Autorisez l’accessibilité pour afficher Dynamic Island sur cet écran sans masquer les menus.",
        display: "Écran",
        automatic: "Automatique",
        builtIn: "Écran intégré",
        mainDisplay: "Écran principal",
        followPointer: "Suivre le pointeur",
        hover: "Ouvrir lorsque le pointeur reste sur l’encoche",
        modules: "Contenu affiché",
        events: "Plus d’options",
        clipboardActivity: "Signaler les nouvelles copies",
        captureActivity: "Afficher les aperçus de captures ici",
        privacy: "Le contenu copié reste privé jusqu’à l’ouverture de l’historique. Ces options respectent les réglages de chaque fonction.",
        open: "Ouvrir Dynamic Island",
        collapse: "Réduire",
        pin: "Garder ouvert",
        unpin: "Autoriser la fermeture automatique",
        panel: "Ouvrir le panneau de l’app",
        dropHint: "Déposez des fichiers ici",
        empty: "Choisissez le contenu dans les réglages de Dynamic Island.",
        volume: "Volume",
        brightness: "Luminosité",
        battery: "Batterie",
        onBattery: "Sur batterie",
        charging: "En charge",
        charged: "Charge complète",
        lowBattery: "Batterie faible",
        controls: "Commandes",
        system: "Système",
        disabled: "Activez la fonction correspondante pour l’utiliser ici.",
        files: "Fichiers",
        hideInFullscreen: "Masquer le contenu en plein écran",
        showInCaptures: "Afficher dans les captures d’écran et les vidéos",
        clipboardWindow: "Ouvrir l’historique du presse-papiers dans l’encoche",
        tools: "Outils",
        size: "Taille",
        showOutline: "Afficher le contour",
        compact: "Compacte",
        spacious: "Spacieuse",
        hoverExpand: "Déployer au survol",
        shelfWindow: "Ouvrir la zone de fichiers dans le Dynamic Island",
        dragReveal: "Afficher une zone de dépôt pendant le glissement",
        captureControls: "Afficher les commandes de capture dans le Dynamic Island",
        quickPanel: "Ouvrir le panneau rapide dans le Dynamic Island",
        appPanel: "Ouvrir le panneau de l’application dans le Dynamic Island",
        idleContent: "Au repos",
        idleNone: "Rien",
        coverMenus: "Afficher par-dessus les menus",
        coverMenusHint: "Garde le minuteur, la musique et les autres activités compactes à l’écran quand la barre des menus manque de place, en masquant les menus à côté de la caméra.",
        controlShortcuts: "Commandes et raccourcis",
        activity: "Activité",
        playingMusic: "Afficher la musique pendant la lecture",
        custom: "Personnalisé",
        width: "Largeur",
        maximumHeight: "Hauteur maximale",
        sizeHint: "Les commandes restent compactes. Les longues listes utilisent au plus cette hauteur.",
        cameraFit: "Ajustement à l’encoche",
        height: "Hauteur",
        cameraFitHint: "Si un bord de l’encoche apparaît autour de Dynamic Island, modifiez ces valeurs jusqu’à ce qu’il disparaisse.",
        hapticFeedback: "Retour haptique",
        hapticHint: "De légères impulsions à l’ouverture, au changement de rubrique ou au réglage des minutes du minuteur, sur un trackpad compatible.",
        playbackPosition: "Position de lecture",
        musicHint: "Votre musique et ses commandes apparaissent ici.",
        music: "Musique",
        captures: "Captures",
        newTrack: "Nouveau morceau",
        customizeTools: "Personnaliser les outils",
        switchSection: "Changer de section",
        sectionsTitle: "Explorer",
        searchSections: "Rechercher une section",
        sectionKeyboardHint: "Utilisez les flèches, puis appuyez sur Retour",
        quickAccessLeft: "Gauche",
        quickAccessRight: "Droite"
    )

    static let it = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Combina",
        enable: "Attiva Dynamic Island",
        description: "Musica, controlli e strumenti quotidiani, insieme nella parte superiore dello schermo. Facoltativo. Disattiva questa opzione per continuare a usare i pannelli separati.",
        menuBarAccessHint: "Consenti Accessibilità per mostrare Dynamic Island su questo schermo senza coprire i menu.",
        display: "Schermo",
        automatic: "Automatico",
        builtIn: "Schermo integrato",
        mainDisplay: "Schermo principale",
        followPointer: "Segui il puntatore",
        hover: "Apri quando il puntatore si ferma sul Dynamic Island",
        modules: "Contenuti visibili",
        events: "Altre opzioni",
        clipboardActivity: "Avvisa quando viene copiato qualcosa",
        captureActivity: "Mostra qui le anteprime delle catture",
        privacy: "Il contenuto copiato resta privato finché non apri la cronologia. Queste opzioni rispettano le impostazioni della funzione originale.",
        open: "Apri Dynamic Island",
        collapse: "Riduci",
        pin: "Mantieni aperto",
        unpin: "Consenti chiusura automatica",
        panel: "Apri pannello dell’app",
        dropHint: "Rilascia i file qui",
        empty: "Scegli cosa mostrare nelle impostazioni di Dynamic Island.",
        volume: "Volume",
        brightness: "Luminosità",
        battery: "Batteria",
        onBattery: "A batteria",
        charging: "In carica",
        charged: "Carica completa",
        lowBattery: "Batteria scarica",
        controls: "Controlli",
        system: "Sistema",
        disabled: "Attiva la funzione corrispondente per usarla qui.",
        files: "File",
        hideInFullscreen: "Nascondi i contenuti a schermo intero",
        showInCaptures: "Mostra nelle schermate e nei video",
        clipboardWindow: "Apri la cronologia degli appunti nel Dynamic Island",
        tools: "Strumenti",
        size: "Dimensioni",
        showOutline: "Mostra contorno",
        compact: "Compatto",
        spacious: "Ampio",
        hoverExpand: "Espandi completamente al passaggio del puntatore",
        shelfWindow: "Apri il ripiano dei file nel Dynamic Island",
        dragReveal: "Mostra un’area di rilascio durante il trascinamento",
        captureControls: "Mostra i controlli di cattura nel Dynamic Island",
        quickPanel: "Apri il pannello rapido nel Dynamic Island",
        appPanel: "Apri il pannello dell’app nel Dynamic Island",
        idleContent: "A riposo",
        idleNone: "Niente",
        coverMenus: "Mostra sopra i menu",
        coverMenusHint: "Mantiene timer, musica e le altre attività compatte sullo schermo quando la barra dei menu non ha spazio, coprendo i menu accanto alla fotocamera.",
        controlShortcuts: "Controlli e scorciatoie",
        activity: "Attività",
        playingMusic: "Mostra la musica durante la riproduzione",
        custom: "Personalizzato",
        width: "Larghezza",
        maximumHeight: "Altezza massima",
        sizeHint: "I controlli restano compatti. Gli elenchi lunghi usano al massimo questa altezza.",
        cameraFit: "Adattamento al notch",
        height: "Altezza",
        cameraFitHint: "Se intorno al Dynamic Island si vede un bordo del notch, regola questi valori finché non scompare.",
        hapticFeedback: "Feedback aptico",
        hapticHint: "Tocchi leggeri quando apri, cambi sezione o regoli i minuti del timer, su un trackpad compatibile.",
        playbackPosition: "Posizione di riproduzione",
        musicHint: "La tua musica e i controlli di riproduzione appaiono qui.",
        music: "Musica",
        captures: "Catture",
        newTrack: "Nuovo brano",
        customizeTools: "Personalizza strumenti",
        switchSection: "Cambia sezione",
        sectionsTitle: "Esplora",
        searchSections: "Trova una sezione",
        sectionKeyboardHint: "Usa le frecce, poi premi Invio",
        quickAccessLeft: "Sinistra",
        quickAccessRight: "Destra"
    )

    static let ru = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Объединить",
        enable: "Включить Dynamic Island",
        description: "Музыка, управление и повседневные инструменты в верхней части экрана. Необязательно. Отключите, чтобы продолжить пользоваться отдельными панелями.",
        menuBarAccessHint: "Разрешите универсальный доступ, чтобы Dynamic Island отображалась на этом экране, не закрывая меню.",
        display: "Экран",
        automatic: "Автоматически",
        builtIn: "Встроенный экран",
        mainDisplay: "Основной экран",
        followPointer: "Следовать за указателем",
        hover: "Открывать при наведении указателя",
        modules: "Что показывать",
        events: "Дополнительные параметры",
        clipboardActivity: "Сообщать о копировании",
        captureActivity: "Показывать здесь миниатюры снимков",
        privacy: "Скопированное содержимое скрыто до открытия истории. Эти параметры учитывают настройки соответствующей функции.",
        open: "Открыть Dynamic Island",
        collapse: "Свернуть",
        pin: "Оставить открытым",
        unpin: "Разрешить автоматическое закрытие",
        panel: "Открыть панель приложения",
        dropHint: "Перетащите файлы сюда",
        empty: "Выберите содержимое в настройках Dynamic Island.",
        volume: "Громкость",
        brightness: "Яркость",
        battery: "Аккумулятор",
        onBattery: "От аккумулятора",
        charging: "Заряжается",
        charged: "Полностью заряжен",
        lowBattery: "Низкий заряд",
        controls: "Управление",
        system: "Система",
        disabled: "Включите соответствующую функцию, чтобы использовать её здесь.",
        files: "Файлы",
        hideInFullscreen: "Скрывать содержимое в полноэкранном режиме",
        showInCaptures: "Показывать на снимках экрана и в видео",
        clipboardWindow: "Открывать историю буфера обмена в вырезе",
        tools: "Инструменты",
        size: "Размер",
        showOutline: "Показывать контур",
        compact: "Компактный",
        spacious: "Просторный",
        hoverExpand: "Полностью раскрывать при наведении",
        shelfWindow: "Открывать полку файлов в вырезе",
        dragReveal: "Показывать область при перетаскивании",
        captureControls: "Показывать управление захватом в вырезе",
        quickPanel: "Открывать быструю панель в вырезе",
        appPanel: "Открывать панель приложения в вырезе",
        idleContent: "В состоянии покоя",
        idleNone: "Ничего",
        coverMenus: "Показывать поверх меню",
        coverMenusHint: "Оставляет таймер, музыку и другую компактную активность на экране, когда в строке меню нет места, закрывая меню рядом с камерой.",
        controlShortcuts: "Управление и быстрые действия",
        activity: "Активность",
        playingMusic: "Показывать музыку во время воспроизведения",
        custom: "Свой размер",
        width: "Ширина",
        maximumHeight: "Максимальная высота",
        sizeHint: "Панель управления остаётся компактной. Длинные списки используют не более этой высоты.",
        cameraFit: "Подгонка под вырез",
        height: "Высота",
        cameraFitHint: "Если вокруг Dynamic Island виден край выреза, настройте эти значения так, чтобы он исчез.",
        hapticFeedback: "Тактильный отклик",
        hapticHint: "Лёгкий отклик при открытии, смене раздела или настройке минут таймера на совместимом трекпаде.",
        playbackPosition: "Позиция воспроизведения",
        musicHint: "Здесь появятся музыка и управление воспроизведением.",
        music: "Музыка",
        captures: "Снимки",
        newTrack: "Новый трек",
        customizeTools: "Настроить инструменты",
        switchSection: "Сменить раздел",
        sectionsTitle: "Обзор",
        searchSections: "Найти раздел",
        sectionKeyboardHint: "Выберите стрелками и нажмите Return",
        quickAccessLeft: "Слева",
        quickAccessRight: "Справа"
    )

    static let tr = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Birleştir",
        enable: "Dynamic Island’u etkinleştir",
        description: "Müziğiniz, denetimleriniz ve günlük araçlarınız ekranın üst kısmında bir arada. İsteğe bağlıdır. Ayrı panelleri kullanmaya devam etmek için kapatın.",
        menuBarAccessHint: "Dynamic Island’ın bu ekranda menüleri kapatmadan görünmesi için Erişilebilirlik izni verin.",
        display: "Ekran",
        automatic: "Otomatik",
        builtIn: "Yerleşik ekran",
        mainDisplay: "Ana ekran",
        followPointer: "İşaretçiyi takip et",
        hover: "İşaretçi çentikte durduğunda aç",
        modules: "Gösterilenler",
        events: "Daha fazla seçenek",
        clipboardActivity: "Bir şey kopyalandığında bildir",
        captureActivity: "Ekran görüntüsü önizlemelerini burada göster",
        privacy: "Kopyalanan içerik, geçmişi açana kadar gizli kalır. Bu seçenekler ilgili özelliğin ayarlarına uyar.",
        open: "Dynamic Island’u aç",
        collapse: "Daralt",
        pin: "Açık tut",
        unpin: "Otomatik kapanmaya izin ver",
        panel: "Uygulama panelini aç",
        dropHint: "Dosyaları buraya bırakın",
        empty: "Dynamic Island ayarlarında gösterilecek içeriği seçin.",
        volume: "Ses düzeyi",
        brightness: "Parlaklık",
        battery: "Pil",
        onBattery: "Pil kullanılıyor",
        charging: "Şarj oluyor",
        charged: "Tam dolu",
        lowBattery: "Düşük pil",
        controls: "Denetimler",
        system: "Sistem",
        disabled: "Burada kullanmak için ilgili özelliği etkinleştirin.",
        files: "Dosyalar",
        hideInFullscreen: "Tam ekranda içeriği gizle",
        showInCaptures: "Ekran görüntülerinde ve videolarda göster",
        clipboardWindow: "Pano geçmişini çentikte aç",
        tools: "Araçlar",
        size: "Boyut",
        showOutline: "Kenarlığı göster",
        compact: "Kompakt",
        spacious: "Geniş",
        hoverExpand: "İşaretçi üzerine geldiğinde tamamen aç",
        shelfWindow: "Dosya rafını çentikte aç",
        dragReveal: "Sürüklerken bırakma alanını göster",
        captureControls: "Ekran yakalama kontrollerini çentikte göster",
        quickPanel: "Hızlı paneli çentikte aç",
        appPanel: "Uygulama panelini çentikte aç",
        idleContent: "Boştayken",
        idleNone: "Hiçbir şey",
        coverMenus: "Menülerin üzerinde göster",
        coverMenusHint: "Menü çubuğunda yer kalmadığında zamanlayıcıyı, müziği ve diğer kompakt etkinlikleri ekranda tutar ve kameranın yanındaki menüleri kapatır.",
        controlShortcuts: "Kontroller ve kısayollar",
        activity: "Etkinlik",
        playingMusic: "Çalarken müziği göster",
        custom: "Özel",
        width: "Genişlik",
        maximumHeight: "En fazla yükseklik",
        sizeHint: "Denetimler kompakt kalır. Uzun listeler en fazla bu yüksekliği kullanır.",
        cameraFit: "Çentiğe uyum",
        height: "Yükseklik",
        cameraFitHint: "Dynamic Island’ın çevresinde çentiğin bir kenarı görünüyorsa, kaybolana kadar bu değerleri ayarlayın.",
        hapticFeedback: "Dokunsal geri bildirim",
        hapticHint: "Uyumlu bir izleme dörtgeninde açarken, bölüm değiştirirken veya zamanlayıcı dakikalarını ayarlarken hafif dokunuşlar.",
        playbackPosition: "Oynatma konumu",
        musicHint: "Müziğiniz ve oynatma denetimleri burada görünür.",
        music: "Müzik",
        captures: "Yakalamalar",
        newTrack: "Yeni şarkı",
        customizeTools: "Araçları özelleştir",
        switchSection: "Bölüm değiştir",
        sectionsTitle: "Keşfet",
        searchSections: "Bölüm bul",
        sectionKeyboardHint: "Ok tuşlarıyla seçin, Return ile açın",
        quickAccessLeft: "Sol",
        quickAccessRight: "Sağ"
    )

    static let ja = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "組み合わせる",
        enable: "Dynamic Islandを有効にする",
        description: "音楽、コントロール、毎日のツールを画面上部にまとめます。 必要に応じて有効にできます。オフにすると、個別のパネルを引き続き使用できます。",
        menuBarAccessHint: "メニューを隠さずにこのディスプレイにDynamic Islandを表示するには、アクセシビリティを許可してください。",
        display: "ディスプレイ",
        automatic: "自動",
        builtIn: "内蔵ディスプレイ",
        mainDisplay: "メインディスプレイ",
        followPointer: "ポインタに追従",
        hover: "Dynamic Islandにポインタを置くと開く",
        modules: "表示する内容",
        events: "その他のオプション",
        clipboardActivity: "コピーしたときに通知",
        captureActivity: "スクリーンショットのプレビューをここに表示",
        privacy: "コピーした内容は履歴を開くまで表示されません。各機能の設定が適用されます。",
        open: "Dynamic Islandを開く",
        collapse: "閉じる",
        pin: "開いたままにする",
        unpin: "自動で閉じる",
        panel: "アプリのパネルを開く",
        dropHint: "ここにファイルをドロップ",
        empty: "Dynamic Islandの設定で表示する内容を選んでください。",
        volume: "音量",
        brightness: "明るさ",
        battery: "バッテリー",
        onBattery: "バッテリー使用中",
        charging: "充電中",
        charged: "充電完了",
        lowBattery: "バッテリー残量低下",
        controls: "コントロール",
        system: "システム",
        disabled: "対応する機能を有効にすると、ここで使用できます。",
        files: "ファイル",
        hideInFullscreen: "フルスクリーン時に内容を非表示",
        showInCaptures: "スクリーンショットと動画に表示",
        clipboardWindow: "クリップボード履歴をDynamic Islandで開く",
        tools: "ツール",
        size: "サイズ",
        showOutline: "輪郭を表示",
        compact: "コンパクト",
        spacious: "広め",
        hoverExpand: "ポインタを重ねたときに完全に開く",
        shelfWindow: "ファイルシェルフをDynamic Islandで開く",
        dragReveal: "ドラッグ中にドロップ先を表示",
        captureControls: "画面キャプチャの操作をDynamic Islandに表示",
        quickPanel: "クイックパネルをDynamic Islandで開く",
        appPanel: "アプリのパネルをDynamic Islandで開く",
        idleContent: "待機中",
        idleNone: "なし",
        coverMenus: "メニューの上に表示",
        coverMenusHint: "メニューバーに空きがないときも、タイマーやミュージックなどのコンパクトな表示を画面に残し、カメラ横のメニューを覆います。",
        controlShortcuts: "操作とショートカット",
        activity: "アクティビティ",
        playingMusic: "再生中の音楽を表示",
        custom: "カスタム",
        width: "幅",
        maximumHeight: "最大の高さ",
        sizeHint: "コントロールはコンパクトに保たれ、長いリストはこの高さまで広がります。",
        cameraFit: "ノッチに合わせる",
        height: "高さ",
        cameraFitHint: "Dynamic Islandの周りにノッチの縁が見える場合は、見えなくなるまでこれらの値を調整してください。",
        hapticFeedback: "触覚フィードバック",
        hapticHint: "対応するトラックパッドで、開くとき、セクションの切り替え時、タイマーの分数を調整するときに軽い触覚を伝えます。",
        playbackPosition: "再生位置",
        musicHint: "再生中の音楽と操作ボタンがここに表示されます。",
        music: "ミュージック",
        captures: "キャプチャ",
        newTrack: "新しい曲",
        customizeTools: "ツールをカスタマイズ",
        switchSection: "セクションを切り替える",
        sectionsTitle: "見つける",
        searchSections: "セクションを検索",
        sectionKeyboardHint: "矢印キーで選び、Returnキーで開きます",
        quickAccessLeft: "左",
        quickAccessRight: "右"
    )

    static let ko = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "함께 표시",
        enable: "Dynamic Island 활성화",
        description: "음악, 제어 기능과 일상 도구를 화면 상단에 모아 보세요. 선택 기능입니다. 끄면 기존의 개별 패널을 계속 사용할 수 있습니다.",
        menuBarAccessHint: "이 디스플레이에서 메뉴를 가리지 않고 Dynamic Island를 표시하려면 손쉬운 사용을 허용하세요.",
        display: "디스플레이",
        automatic: "자동",
        builtIn: "내장 디스플레이",
        mainDisplay: "주 디스플레이",
        followPointer: "포인터 따라가기",
        hover: "Dynamic Island에 포인터를 두면 열기",
        modules: "표시할 항목",
        events: "추가 옵션",
        clipboardActivity: "복사할 때 알림",
        captureActivity: "스크린샷 미리보기를 여기에 표시",
        privacy: "복사한 내용은 기록을 열 때까지 비공개로 유지됩니다. 각 기능의 설정이 적용됩니다.",
        open: "Dynamic Island 열기",
        collapse: "접기",
        pin: "열린 상태 유지",
        unpin: "자동으로 닫기 허용",
        panel: "앱 패널 열기",
        dropHint: "여기에 파일을 놓으세요",
        empty: "Dynamic Island 설정에서 표시할 항목을 선택하세요.",
        volume: "음량",
        brightness: "밝기",
        battery: "배터리",
        onBattery: "배터리 사용 중",
        charging: "충전 중",
        charged: "충전 완료",
        lowBattery: "배터리 부족",
        controls: "제어",
        system: "시스템",
        disabled: "여기서 사용하려면 해당 기능을 활성화하세요.",
        files: "파일",
        hideInFullscreen: "전체 화면에서 콘텐츠 숨기기",
        showInCaptures: "스크린샷 및 동영상에 표시",
        clipboardWindow: "Dynamic Island에서 클립보드 기록 열기",
        tools: "도구",
        size: "크기",
        showOutline: "테두리 표시",
        compact: "작게",
        spacious: "넓게",
        hoverExpand: "포인터를 올리면 완전히 펼치기",
        shelfWindow: "파일 선반을 Dynamic Island에서 열기",
        dragReveal: "드래그 중 놓을 영역 표시",
        captureControls: "화면 캡처 제어를 Dynamic Island에 표시",
        quickPanel: "빠른 패널을 Dynamic Island에서 열기",
        appPanel: "앱 패널을 Dynamic Island에서 열기",
        idleContent: "대기 중",
        idleNone: "없음",
        coverMenus: "메뉴 위에 표시",
        coverMenusHint: "메뉴 막대에 공간이 없어도 타이머, 음악 등 컴팩트 활동을 화면에 유지하고 카메라 옆의 메뉴를 가립니다.",
        controlShortcuts: "제어 및 단축키",
        activity: "활동",
        playingMusic: "재생 중인 음악 표시",
        custom: "사용자 지정",
        width: "너비",
        maximumHeight: "최대 높이",
        sizeHint: "제어 영역은 작게 유지되고 긴 목록은 이 높이까지 늘어납니다.",
        cameraFit: "노치에 맞추기",
        height: "높이",
        cameraFitHint: "Dynamic Island 주위로 노치 가장자리가 보이면 보이지 않을 때까지 이 값을 조정하세요.",
        hapticFeedback: "햅틱 피드백",
        hapticHint: "호환되는 트랙패드에서 열거나 섹션을 바꾸거나 타이머의 분을 조절할 때 가볍게 진동합니다.",
        playbackPosition: "재생 위치",
        musicHint: "재생 중인 음악과 재생 제어가 여기에 표시됩니다.",
        music: "음악",
        captures: "캡처",
        newTrack: "새 곡",
        customizeTools: "도구 사용자화",
        switchSection: "섹션 전환",
        sectionsTitle: "둘러보기",
        searchSections: "섹션 찾기",
        sectionKeyboardHint: "방향키로 선택하고 Return 키로 열기",
        quickAccessLeft: "왼쪽",
        quickAccessRight: "오른쪽"
    )

    static let zhHans = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "组合显示",
        enable: "启用Dynamic Island",
        description: "音乐、控制和日常工具，汇聚在屏幕顶部。 可选功能。关闭后可继续使用独立面板。",
        menuBarAccessHint: "请允许辅助功能权限，让 Dynamic Island 在此显示器上显示而不遮挡菜单。",
        display: "显示器",
        automatic: "自动",
        builtIn: "内建显示器",
        mainDisplay: "主显示器",
        followPointer: "跟随指针",
        hover: "指针停留在Dynamic Island上时打开",
        modules: "显示内容",
        events: "更多选项",
        clipboardActivity: "复制时通知",
        captureActivity: "在此显示截屏预览",
        privacy: "复制的内容会保持私密，直到你打开历史记录。这些选项遵循原功能的设置。",
        open: "打开Dynamic Island",
        collapse: "收起",
        pin: "保持打开",
        unpin: "允许自动关闭",
        panel: "打开应用面板",
        dropHint: "将文件拖到这里",
        empty: "在Dynamic Island设置中选择要显示的内容。",
        volume: "音量",
        brightness: "亮度",
        battery: "电池",
        onBattery: "使用电池",
        charging: "正在充电",
        charged: "已充满",
        lowBattery: "电量低",
        controls: "控制",
        system: "系统",
        disabled: "启用相应功能后即可在此使用。",
        files: "文件",
        hideInFullscreen: "全屏时隐藏内容",
        showInCaptures: "在截图和视频中显示",
        clipboardWindow: "在Dynamic Island中打开剪贴板历史记录",
        tools: "工具",
        size: "大小",
        showOutline: "显示边框",
        compact: "紧凑",
        spacious: "宽敞",
        hoverExpand: "悬停时完全展开",
        shelfWindow: "在Dynamic Island中打开文件架",
        dragReveal: "拖动时显示放置区域",
        captureControls: "在Dynamic Island中显示屏幕捕获控制",
        quickPanel: "在Dynamic Island中打开快捷面板",
        appPanel: "在Dynamic Island中打开应用面板",
        idleContent: "闲置时",
        idleNone: "无",
        coverMenus: "显示在菜单上方",
        coverMenusHint: "菜单栏没有空间时，仍在屏幕上保留计时器、音乐等紧凑活动，并遮挡摄像头旁的菜单。",
        controlShortcuts: "控制与快捷操作",
        activity: "活动",
        playingMusic: "播放时显示音乐",
        custom: "自定义",
        width: "宽度",
        maximumHeight: "最大高度",
        sizeHint: "控制区域保持紧凑，较长的列表最多使用此高度。",
        cameraFit: "贴合刘海",
        height: "高度",
        cameraFitHint: "如果Dynamic Island周围露出刘海的边缘，请调整这些数值直到它消失。",
        hapticFeedback: "触觉反馈",
        hapticHint: "在兼容的触控板上，打开、切换区域或调整计时器分钟数时提供轻微触感。",
        playbackPosition: "播放进度",
        musicHint: "音乐和播放控制会显示在这里。",
        music: "音乐",
        captures: "截图",
        newTrack: "新歌曲",
        customizeTools: "自定义工具",
        switchSection: "切换分区",
        sectionsTitle: "探索",
        searchSections: "查找分区",
        sectionKeyboardHint: "使用方向键选择，然后按回车键打开",
        quickAccessLeft: "左侧",
        quickAccessRight: "右侧"
    )

    static let zhTW = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "組合顯示",
        enable: "啟用Dynamic Island",
        description: "音樂、控制項與日常工具，匯聚在螢幕頂端。 選用功能。關閉後可繼續使用獨立面板。",
        menuBarAccessHint: "請允許輔助使用權限，讓 Dynamic Island 在此顯示器上顯示而不遮擋選單。",
        display: "顯示器",
        automatic: "自動",
        builtIn: "內建顯示器",
        mainDisplay: "主顯示器",
        followPointer: "跟隨指標",
        hover: "指標停留在Dynamic Island上時開啟",
        modules: "顯示內容",
        events: "更多選項",
        clipboardActivity: "複製時通知",
        captureActivity: "在此顯示截圖預覽",
        privacy: "複製的內容會保持私密，直到你開啟記錄。這些選項會遵循原功能的設定。",
        open: "開啟Dynamic Island",
        collapse: "收合",
        pin: "保持開啟",
        unpin: "允許自動關閉",
        panel: "開啟 App 面板",
        dropHint: "將檔案拖到這裡",
        empty: "在Dynamic Island設定中選擇要顯示的內容。",
        volume: "音量",
        brightness: "亮度",
        battery: "電池",
        onBattery: "使用電池",
        charging: "充電中",
        charged: "已充滿",
        lowBattery: "電量不足",
        controls: "控制項",
        system: "系統",
        disabled: "啟用對應功能後即可在此使用。",
        files: "檔案",
        hideInFullscreen: "全螢幕時隱藏內容",
        showInCaptures: "在截圖與影片中顯示",
        clipboardWindow: "在Dynamic Island中開啟剪貼簿記錄",
        tools: "工具",
        size: "大小",
        showOutline: "顯示邊框",
        compact: "緊湊",
        spacious: "寬敞",
        hoverExpand: "游標停留時完全展開",
        shelfWindow: "在Dynamic Island中開啟檔案架",
        dragReveal: "拖移時顯示放置區域",
        captureControls: "在Dynamic Island中顯示螢幕擷取控制",
        quickPanel: "在Dynamic Island中開啟快捷面板",
        appPanel: "在Dynamic Island中開啟應用程式面板",
        idleContent: "閒置時",
        idleNone: "無",
        coverMenus: "顯示在選單上方",
        coverMenusHint: "選單列沒有空間時，仍在畫面上保留計時器、音樂等精簡活動，並遮住相機旁的選單。",
        controlShortcuts: "控制與快捷操作",
        activity: "活動",
        playingMusic: "播放時顯示音樂",
        custom: "自訂",
        width: "寬度",
        maximumHeight: "最大高度",
        sizeHint: "控制區域保持精簡，較長的列表最多使用此高度。",
        cameraFit: "貼合瀏海",
        height: "高度",
        cameraFitHint: "如果Dynamic Island周圍露出瀏海的邊緣，請調整這些數值直到它消失。",
        hapticFeedback: "觸覺回饋",
        hapticHint: "在相容的觸控式軌跡板上，開啟、切換區域或調整計時器分鐘數時提供輕微觸感。",
        playbackPosition: "播放進度",
        musicHint: "音樂與播放控制會顯示在這裡。",
        music: "音樂",
        captures: "擷取",
        newTrack: "新歌曲",
        customizeTools: "自訂工具",
        switchSection: "切換區域",
        sectionsTitle: "探索",
        searchSections: "尋找區域",
        sectionKeyboardHint: "使用方向鍵選取，再按 Return 鍵開啟",
        quickAccessLeft: "左側",
        quickAccessRight: "右側"
    )

    static let zhHK = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "組合顯示",
        enable: "啟用Dynamic Island",
        description: "音樂、控制項與日常工具，集中在螢幕頂端。 選用功能。關閉後可繼續使用獨立面板。",
        menuBarAccessHint: "請允許輔助使用權限，讓 Dynamic Island 在此顯示器上顯示而不遮擋選單。",
        display: "顯示器",
        automatic: "自動",
        builtIn: "內置顯示器",
        mainDisplay: "主顯示器",
        followPointer: "跟隨指標",
        hover: "指標停留在Dynamic Island上時開啟",
        modules: "顯示內容",
        events: "更多選項",
        clipboardActivity: "複製時通知",
        captureActivity: "在此顯示螢幕截圖預覽",
        privacy: "複製的內容會保持私密，直到你開啟記錄。這些選項會遵從原功能的設定。",
        open: "開啟Dynamic Island",
        collapse: "收合",
        pin: "保持開啟",
        unpin: "允許自動關閉",
        panel: "開啟 App 面板",
        dropHint: "將檔案拖到這裏",
        empty: "在Dynamic Island設定中選擇要顯示的內容。",
        volume: "音量",
        brightness: "亮度",
        battery: "電池",
        onBattery: "使用電池",
        charging: "充電中",
        charged: "已充滿",
        lowBattery: "電量不足",
        controls: "控制項",
        system: "系統",
        disabled: "啟用相應功能後即可在此使用。",
        files: "檔案",
        hideInFullscreen: "全螢幕時隱藏內容",
        showInCaptures: "在截圖與影片中顯示",
        clipboardWindow: "在Dynamic Island中開啟剪貼簿記錄",
        tools: "工具",
        size: "大小",
        showOutline: "顯示邊框",
        compact: "精簡",
        spacious: "寬敞",
        hoverExpand: "游標停留時完全展開",
        shelfWindow: "在Dynamic Island中開啟檔案架",
        dragReveal: "拖移時顯示放置區域",
        captureControls: "在Dynamic Island中顯示螢幕擷取控制",
        quickPanel: "在Dynamic Island中開啟快捷面板",
        appPanel: "在Dynamic Island中開啟應用程式面板",
        idleContent: "閒置時",
        idleNone: "無",
        coverMenus: "顯示在選單上方",
        coverMenusHint: "選單列沒有空間時，仍在畫面上保留計時器、音樂等精簡活動，並遮住相機旁的選單。",
        controlShortcuts: "控制與快捷操作",
        activity: "活動",
        playingMusic: "播放時顯示音樂",
        custom: "自訂",
        width: "寬度",
        maximumHeight: "最大高度",
        sizeHint: "控制區域保持精簡，較長的列表最多使用此高度。",
        cameraFit: "貼合瀏海",
        height: "高度",
        cameraFitHint: "如果Dynamic Island周圍露出瀏海的邊緣，請調整這些數值直到它消失。",
        hapticFeedback: "觸覺回饋",
        hapticHint: "在兼容的觸控板上，開啟、切換區域或調整計時器分鐘數時提供輕微觸感。",
        playbackPosition: "播放進度",
        musicHint: "音樂和播放控制會顯示在這裡。",
        music: "音樂",
        captures: "擷取",
        newTrack: "新歌曲",
        customizeTools: "自訂工具",
        switchSection: "切換區域",
        sectionsTitle: "探索",
        searchSections: "尋找區域",
        sectionKeyboardHint: "使用方向鍵選取，再按 Return 鍵開啟",
        quickAccessLeft: "左側",
        quickAccessRight: "右側"
    )

    static let uk = NotchStrings(
        title: "Dynamic Island",
        combineActivities: "Поєднати",
        enable: "Увімкнути Dynamic Island",
        description: "Ваша музика, елементи керування та повсякденні інструменти, зібрані у верхній частині екрана. Необов’язково. Вимкніть, щоб і надалі користуватися окремими панелями.",
        menuBarAccessHint: "Надайте дозвіл «Доступність», щоб Dynamic Island з’являвся на цьому дисплеї, не затуляючи меню.",
        display: "Дисплей",
        automatic: "Автоматично",
        builtIn: "Вбудований дисплей",
        mainDisplay: "Основний дисплей",
        followPointer: "За вказівником",
        hover: "Відкривати, коли вказівник зупиняється на Dynamic Island",
        modules: "Що показувати",
        events: "Більше опцій",
        clipboardActivity: "Сповіщати, коли щось скопійовано",
        captureActivity: "Показувати мініатюри знімків тут",
        privacy: "Скопійований вміст залишається приватним, доки ви не відкриєте буфер обміну. Ці опції дотримуються налаштувань відповідної функції.",
        open: "Відкрити Dynamic Island",
        collapse: "Згорнути",
        pin: "Тримати відкритим",
        unpin: "Дозволити автоматичне закриття",
        panel: "Відкрити панель програми",
        dropHint: "Перетягніть файли сюди",
        empty: "Виберіть, що показувати, у налаштуваннях Dynamic Island.",
        volume: "Гучність",
        brightness: "Яскравість",
        battery: "Акумулятор",
        onBattery: "Від акумулятора",
        charging: "Заряджається",
        charged: "Повністю заряджено",
        lowBattery: "Низький заряд",
        controls: "Елементи керування",
        system: "Система",
        disabled: "Увімкніть відповідну функцію, щоб використовувати її тут.",
        files: "Файли",
        hideInFullscreen: "Приховувати вміст у повноекранному режимі",
        showInCaptures: "Показувати на знімках і відео",
        clipboardWindow: "Відкривати історію буфера обміну у Dynamic Island",
        tools: "Інструменти",
        size: "Розмір",
        showOutline: "Показувати контур",
        compact: "Компактний",
        spacious: "Просторий",
        hoverExpand: "Розгортати повністю при наведенні",
        shelfWindow: "Відкривати полицю файлів у Dynamic Island",
        dragReveal: "Показувати зону скидання під час перетягування",
        captureControls: "Показувати елементи захоплення екрана у Dynamic Island",
        quickPanel: "Відкривати швидку панель у Dynamic Island",
        appPanel: "Відкривати панель програми у Dynamic Island",
        idleContent: "Поки неактивний",
        idleNone: "Нічого",
        coverMenus: "Показувати поверх меню",
        coverMenusHint: "Залишає таймер, музику й інші компактні елементи на екрані, коли на смузі меню бракує місця, перекриваючи меню поруч із камерою.",
        controlShortcuts: "Керування та скорочення",
        activity: "Активність",
        playingMusic: "Показувати музику під час відтворення",
        custom: "Власне",
        width: "Ширина",
        maximumHeight: "Максимальна висота",
        sizeHint: "Елементи керування залишаються компактними. Довші списки використовують щонайбільше цю висоту.",
        cameraFit: "Підгонка під виріз",
        height: "Висота",
        cameraFitHint: "Якщо навколо Dynamic Island видно край вирізу, налаштуйте ці значення, щоб він зник.",
        hapticFeedback: "Тактильний відгук",
        hapticHint: "Легкі дотики при відкритті, перемиканні розділів або зміні хвилин таймера на сумісному трекпеді.",
        playbackPosition: "Позиція відтворення",
        musicHint: "Ваша музика та елементи керування відтворенням з’являються тут.",
        music: "Музика",
        captures: "Зйомки",
        newTrack: "Новий трек",
        customizeTools: "Налаштувати інструменти",
        switchSection: "Перемкнути розділ",
        sectionsTitle: "Огляд",
        searchSections: "Знайти розділ",
        sectionKeyboardHint: "Використовуйте стрілки, потім натисніть Return",
        quickAccessLeft: "Ліворуч",
        quickAccessRight: "Праворуч"
    )

}
