// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchAgentStrings {
    let title: String
    let hubDescription: String
    let settingsDescription: String
    let restingTitle: String
    let limitsCard: String
    let spendCard: String
    let liveCard: String
    let trendCard: String
    let modelsCard: String
    let projectsCard: String
    let activityCard: String
    let today: String
    let week: String
    let month: String
    let session: String
    let weekly: String
    let estimated: String
    let claudeLimitsHint: String
    let waitingForLimits: String
    let noSession: String
    let apiValue: String
    let tokensFormat: String
    let cachedFormat: String
    let writtenFormat: String
    let savedFormat: String
    let planMultipleFormat: String
    let idle: String
    let noActivity: String
    let empty: String
    let loading: String
    let noCards: String
    let unpriced: String
    let streak: String
    let activeDays: String
    let busiestDay: String
    let finishedFormat: String
    let limitRenewed: String
    let budgetTitle: String
    let leftFormat: String
    let usedFormat: String
    let agents: String
    let found: String
    let notFound: String
    let cardsTitle: String
    let cardsHint: String
    let limitsAs: String
    let remaining: String
    let used: String
    let liveTitle: String
    let liveActivity: String
    let readout: String
    let readoutElapsed: String
    let readoutTokens: String
    let readoutLimit: String
    let alerts: String
    let finishAlert: String
    let finishAfter: String
    let anyLength: String
    let limitAlert: String
    let limitAt: String
    let budget: String
    let off: String
    let updatedFormat: String
    let claudeLimitsTitle: String
    let claudeLimitsCurrentFormat: String
    let claudeLimitsStaleFormat: String
    let claudeLimitsMenuBar: String
    let claudeLimitsNoApp: String
    let claudeLimitsPrivacy: String
    let openClaude: String
    let getClaude: String
    let priceUpdates: String
    let priceUpdatesHint: String
    let pricesFromFormat: String
    let valueNote: String

    func tokens(_ count: String) -> String { String(format: tokensFormat, count) }
    func cached(_ share: String) -> String { String(format: cachedFormat, share) }
    func written(_ count: String) -> String { String(format: writtenFormat, count) }
    func saved(_ amount: String) -> String { String(format: savedFormat, amount) }
    func planMultiple(_ multiple: String, plan: String) -> String { String(format: planMultipleFormat, multiple, plan) }
    func finished(_ agent: String) -> String { String(format: finishedFormat, agent) }
    func left(_ share: String) -> String { String(format: leftFormat, share) }
    func usedShare(_ share: String) -> String { String(format: usedFormat, share) }
    func updated(_ when: String) -> String { String(format: updatedFormat, when) }
    func claudeLimitsCurrent(_ when: String) -> String { String(format: claudeLimitsCurrentFormat, when) }
    func claudeLimitsStale(_ when: String) -> String { String(format: claudeLimitsStaleFormat, when) }
    func pricesFrom(_ day: String) -> String { String(format: pricesFromFormat, day) }

    func period(_ period: AgentPeriod) -> String {
        switch period {
        case .today: return today
        case .week: return week
        case .month: return month
        }
    }

    func card(_ card: NotchAgentCard) -> String {
        switch card {
        case .limits: return limitsCard
        case .spend: return spendCard
        case .live: return liveCard
        case .trend: return trendCard
        case .models: return modelsCard
        case .projects: return projectsCard
        case .activity: return activityCard
        }
    }

    func readout(_ readout: NotchAgentReadout) -> String {
        switch readout {
        case .elapsed: return readoutElapsed
        case .tokens: return readoutTokens
        case .cost: return apiValue.prefix(1).uppercased() + apiValue.dropFirst()
        case .limit: return readoutLimit
        }
    }
}

extension FeatureStrings {
    static func notchAgents(_ language: AppLanguage) -> NotchAgentStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ru: return .ru
        case .tr: return .tr
        case .ja: return .ja
        case .ko: return .ko
        case .uk: return .uk
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension NotchAgentStrings {
    static let enUS = NotchAgentStrings(
        title: "AI Agents",
        hubDescription: "Follow plan limits, tokens, API value and the work in progress of Claude and Codex in the Dynamic Island.",
        settingsDescription: "Reads the usage Claude Code and Codex record on this Mac and the plan limits the Claude app saves. Prompts, replies and files are never kept, and your usage never leaves your Mac.",
        restingTitle: "AI limits",
        limitsCard: "Limits",
        spendCard: "Spending",
        liveCard: "Now",
        trendCard: "Trend",
        modelsCard: "Models",
        projectsCard: "Projects",
        activityCard: "Activity",
        today: "Today",
        week: "7 days",
        month: "30 days",
        session: "Session",
        weekly: "Week",
        estimated: "Estimated from this Mac",
        claudeLimitsHint: "Set up plan limits…",
        waitingForLimits: "Limits appear after the next reply",
        noSession: "No session running",
        apiValue: "API value",
        tokensFormat: "%@ tokens",
        cachedFormat: "%@ from cache",
        writtenFormat: "%@ written",
        savedFormat: "%@ saved by the cache",
        planMultipleFormat: "%1$@ the price of %2$@",
        idle: "Idle",
        noActivity: "Nothing in this period",
        empty: "No usage from Claude Code or Codex yet. It appears here as soon as either one works on this Mac.",
        loading: "Reading usage…",
        noCards: "Choose what this page shows in Dynamic Island settings.",
        unpriced: "Some models have no known price, so this is a minimum.",
        streak: "Days in a row",
        activeDays: "Active days",
        busiestDay: "Busiest day",
        finishedFormat: "%@ finished",
        limitRenewed: "Limit renewed",
        budgetTitle: "Daily budget",
        leftFormat: "%@ left",
        usedFormat: "%@ used",
        agents: "Agents",
        found: "Found on this Mac",
        notFound: "Not found on this Mac",
        cardsTitle: "Cards",
        cardsHint: "Drag to reorder. Charts take the full width of the island.",
        limitsAs: "Show limits as",
        remaining: "Left",
        used: "Used",
        liveTitle: "While an agent works",
        liveActivity: "Show it in the closed Dynamic Island",
        readout: "Beside the camera",
        readoutElapsed: "Time",
        readoutTokens: "Tokens written",
        readoutLimit: "Limit",
        alerts: "Alerts",
        finishAlert: "When a task finishes",
        finishAfter: "For tasks longer than",
        anyLength: "Any length",
        limitAlert: "Near a plan limit",
        limitAt: "Warn at",
        budget: "Daily API value budget",
        off: "Off",
        updatedFormat: "Updated %@",
        claudeLimitsTitle: "Claude plan limits",
        claudeLimitsCurrentFormat: "Read from the Claude app, updated %@",
        claudeLimitsStaleFormat: "The Claude app last checked them %@.",
        claudeLimitsMenuBar: "Claude checks your limits only while its icon is in the menu bar. Turn the icon on in the Claude app settings, and your limits appear here within minutes.",
        claudeLimitsNoApp: "Plan limits come from the Claude app, which is not on this Mac. Until then, the 5-hour session is estimated from Claude Code activity.",
        claudeLimitsPrivacy: "Aster reads the percentages the Claude app saves on this Mac. No sign-in is used and nothing is sent.",
        openClaude: "Open Claude",
        getClaude: "Get the Claude app",
        priceUpdates: "Keep prices up to date",
        priceUpdatesHint: "Downloads the public price list from GitHub once a day, so new models get an API value without an app update. Nothing about your usage is sent.",
        pricesFromFormat: "Price list of %@",
        valueNote: "API value is what the same work would cost at API list prices. Plans charge a fixed price instead.")

    static let uk = NotchAgentStrings(
        title: "ШІ-агенти",
        hubDescription: "Стежте за лімітами плану, токенами, вартістю API та поточною роботою Claude і Codex у Dynamic Island.",
        settingsDescription: "Читає дані про використання, які Claude Code і Codex записують на цьому Mac, та ліміти плану, збережені програмою Claude. Запити, відповіді й файли не зберігаються, а дані про використання не залишають ваш Mac.",
        restingTitle: "Ліміти ШІ",
        limitsCard: "Ліміти",
        spendCard: "Витрати",
        liveCard: "Зараз",
        trendCard: "Тенденція",
        modelsCard: "Моделі",
        projectsCard: "Проєкти",
        activityCard: "Активність",
        today: "Сьогодні",
        week: "7 днів",
        month: "30 днів",
        session: "Сеанс",
        weekly: "Тиждень",
        estimated: "Оцінка за даними цього Mac",
        claudeLimitsHint: "Налаштувати ліміти плану…",
        waitingForLimits: "Ліміти з’являться після наступної відповіді",
        noSession: "Немає активного сеансу",
        apiValue: "вартість API",
        tokensFormat: "Токенів: %@",
        cachedFormat: "Із кешу: %@",
        writtenFormat: "Записано: %@",
        savedFormat: "Заощаджено кешем: %@",
        planMultipleFormat: "%1$@ від ціни %2$@",
        idle: "Неактивно",
        noActivity: "За цей період нічого немає",
        empty: "Claude Code або Codex ще не використовувалися. Дані з’являться тут, щойно один із них почне працювати на цьому Mac.",
        loading: "Читання даних…",
        noCards: "Виберіть, що показувати на цій сторінці в налаштуваннях Dynamic Island.",
        unpriced: "Ціна деяких моделей невідома, тому це мінімальна оцінка.",
        streak: "Днів поспіль",
        activeDays: "Активних днів",
        busiestDay: "Найактивніший день",
        finishedFormat: "%@ завершив роботу",
        limitRenewed: "Ліміт поновлено",
        budgetTitle: "Денний бюджет",
        leftFormat: "Залишилося: %@",
        usedFormat: "Використано: %@",
        agents: "Агенти",
        found: "Знайдено на цьому Mac",
        notFound: "Не знайдено на цьому Mac",
        cardsTitle: "Картки",
        cardsHint: "Перетягуйте, щоб змінити порядок. Діаграми займають усю ширину острівця.",
        limitsAs: "Показувати ліміти як",
        remaining: "Залишок",
        used: "Використано",
        liveTitle: "Поки агент працює",
        liveActivity: "Показувати в закритому Dynamic Island",
        readout: "Поруч із камерою",
        readoutElapsed: "Час",
        readoutTokens: "Записані токени",
        readoutLimit: "Ліміт",
        alerts: "Сповіщення",
        finishAlert: "Коли завдання завершено",
        finishAfter: "Для завдань довших за",
        anyLength: "Будь-яка тривалість",
        limitAlert: "Поблизу ліміту плану",
        limitAt: "Попереджати при",
        budget: "Денний бюджет вартості API",
        off: "Вимкнено",
        updatedFormat: "Оновлено %@",
        claudeLimitsTitle: "Ліміти плану Claude",
        claudeLimitsCurrentFormat: "Прочитано з програми Claude, оновлено %@",
        claudeLimitsStaleFormat: "Програма Claude востаннє перевіряла їх %@.",
        claudeLimitsMenuBar: "Claude перевіряє ліміти, лише коли його значок є на смузі меню. Увімкніть значок у налаштуваннях програми Claude, і ліміти з’являться тут протягом кількох хвилин.",
        claudeLimitsNoApp: "Ліміти плану надходять із програми Claude, якої немає на цьому Mac. Поки що п’ятигодинний сеанс оцінюється за активністю Claude Code.",
        claudeLimitsPrivacy: "Aster читає відсотки, які програма Claude зберігає на цьому Mac. Вхід в обліковий запис не потрібен, і нічого не надсилається.",
        openClaude: "Відкрити Claude",
        getClaude: "Завантажити програму Claude",
        priceUpdates: "Підтримувати ціни актуальними",
        priceUpdatesHint: "Раз на день завантажує публічний список цін із GitHub, щоб нові моделі отримували вартість API без оновлення програми. Дані про ваше використання не надсилаються.",
        pricesFromFormat: "Список цін від %@",
        valueNote: "Вартість API показує, скільки така сама робота коштувала б за цінами API. Плани натомість мають фіксовану ціну.")

    static let ptBR = NotchAgentStrings(
        title: "Agentes de IA",
        hubDescription: "Acompanhe no Dynamic Island os limites do plano, os tokens, o valor de API e o trabalho em andamento do Claude e do Codex.",
        settingsDescription: "Lê o uso que o Claude Code e o Codex registram neste Mac e os limites do plano que o app Claude salva. Prompts, respostas e arquivos nunca são guardados, e o seu uso nunca sai do seu Mac.",
        restingTitle: "Limites de IA",
        limitsCard: "Limites",
        spendCard: "Gastos",
        liveCard: "Agora",
        trendCard: "Tendência",
        modelsCard: "Modelos",
        projectsCard: "Projetos",
        activityCard: "Atividade",
        today: "Hoje",
        week: "7 dias",
        month: "30 dias",
        session: "Sessão",
        weekly: "Semana",
        estimated: "Estimado a partir deste Mac",
        claudeLimitsHint: "Configurar limites do plano…",
        waitingForLimits: "Os limites aparecem após a próxima resposta",
        noSession: "Nenhuma sessão em andamento",
        apiValue: "valor de API",
        tokensFormat: "%@ tokens",
        cachedFormat: "%@ do cache",
        writtenFormat: "%@ escritos",
        savedFormat: "%@ economizados pelo cache",
        planMultipleFormat: "%1$@ o preço do %2$@",
        idle: "Parado",
        noActivity: "Nada neste período",
        empty: "Ainda não há uso do Claude Code nem do Codex. Ele aparece aqui assim que um deles trabalhar neste Mac.",
        loading: "Lendo o uso…",
        noCards: "Escolha o que esta página mostra nos ajustes do Dynamic Island.",
        unpriced: "Alguns modelos não têm preço conhecido, então este é um valor mínimo.",
        streak: "Dias seguidos",
        activeDays: "Dias ativos",
        busiestDay: "Dia mais intenso",
        finishedFormat: "%@ terminou",
        limitRenewed: "Limite renovado",
        budgetTitle: "Orçamento diário",
        leftFormat: "%@ restantes",
        usedFormat: "%@ usados",
        agents: "Agentes",
        found: "Encontrado neste Mac",
        notFound: "Não encontrado neste Mac",
        cardsTitle: "Cartões",
        cardsHint: "Arraste para reordenar. Gráficos ocupam toda a largura do Dynamic Island.",
        limitsAs: "Mostrar limites como",
        remaining: "Restante",
        used: "Usado",
        liveTitle: "Enquanto um agente trabalha",
        liveActivity: "Mostrar no Dynamic Island fechado",
        readout: "Ao lado da câmera",
        readoutElapsed: "Tempo",
        readoutTokens: "Tokens escritos",
        readoutLimit: "Limite",
        alerts: "Alertas",
        finishAlert: "Quando uma tarefa terminar",
        finishAfter: "Para tarefas com mais de",
        anyLength: "Qualquer duração",
        limitAlert: "Perto de um limite do plano",
        limitAt: "Avisar em",
        budget: "Orçamento diário em valor de API",
        off: "Desativado",
        updatedFormat: "Atualizado %@",
        claudeLimitsTitle: "Limites do plano do Claude",
        claudeLimitsCurrentFormat: "Lidos do app Claude, atualizados %@",
        claudeLimitsStaleFormat: "O app Claude verificou os limites pela última vez %@.",
        claudeLimitsMenuBar: "O Claude só verifica os limites enquanto o ícone dele está na barra de menus. Ative o ícone nos ajustes do app Claude, e os limites aparecem aqui em poucos minutos.",
        claudeLimitsNoApp: "Os limites do plano vêm do app Claude, que não está neste Mac. Até lá, a sessão de 5 horas é estimada pela atividade do Claude Code.",
        claudeLimitsPrivacy: "O Aster lê os percentuais que o app Claude salva neste Mac. Nenhum login é usado e nada é enviado.",
        openClaude: "Abrir o Claude",
        getClaude: "Baixar o app Claude",
        priceUpdates: "Manter os preços atualizados",
        priceUpdatesHint: "Baixa uma vez por dia a lista pública de preços no GitHub, para que modelos novos ganhem valor de API sem atualizar o app. Nada sobre o seu uso é enviado.",
        pricesFromFormat: "Lista de preços de %@",
        valueNote: "Valor de API é quanto o mesmo trabalho custaria pelos preços de tabela da API. Os planos cobram um preço fixo.")

    static let es = NotchAgentStrings(
        title: "Agentes de IA",
        hubDescription: "Sigue en el Dynamic Island los límites del plan, los tokens, el valor de API y el trabajo en curso de Claude y Codex.",
        settingsDescription: "Lee el uso que Claude Code y Codex registran en este Mac y los límites del plan que guarda la app de Claude. Nunca se guardan instrucciones, respuestas ni archivos, y tu uso nunca sale de tu Mac.",
        restingTitle: "Límites de IA",
        limitsCard: "Límites",
        spendCard: "Gasto",
        liveCard: "Ahora",
        trendCard: "Tendencia",
        modelsCard: "Modelos",
        projectsCard: "Proyectos",
        activityCard: "Actividad",
        today: "Hoy",
        week: "7 días",
        month: "30 días",
        session: "Sesión",
        weekly: "Semana",
        estimated: "Estimado desde este Mac",
        claudeLimitsHint: "Configurar límites del plan…",
        waitingForLimits: "Los límites aparecen tras la próxima respuesta",
        noSession: "Ninguna sesión en curso",
        apiValue: "valor de API",
        tokensFormat: "%@ tokens",
        cachedFormat: "%@ desde la caché",
        writtenFormat: "%@ escritos",
        savedFormat: "%@ ahorrados por la caché",
        planMultipleFormat: "%1$@ el precio de %2$@",
        idle: "Inactivo",
        noActivity: "Nada en este periodo",
        empty: "Aún no hay uso de Claude Code ni de Codex. Aparece aquí en cuanto cualquiera de los dos trabaje en este Mac.",
        loading: "Leyendo el uso…",
        noCards: "Elige qué muestra esta página en los ajustes del Dynamic Island.",
        unpriced: "Algunos modelos no tienen precio conocido, así que es un mínimo.",
        streak: "Días seguidos",
        activeDays: "Días activos",
        busiestDay: "Día de más uso",
        finishedFormat: "%@ terminó",
        limitRenewed: "Límite renovado",
        budgetTitle: "Presupuesto diario",
        leftFormat: "%@ restante",
        usedFormat: "%@ usado",
        agents: "Agentes",
        found: "Encontrado en este Mac",
        notFound: "No encontrado en este Mac",
        cardsTitle: "Tarjetas",
        cardsHint: "Arrastra para reordenar. Los gráficos ocupan todo el ancho del Dynamic Island.",
        limitsAs: "Mostrar límites como",
        remaining: "Restante",
        used: "Usado",
        liveTitle: "Mientras un agente trabaja",
        liveActivity: "Mostrarlo en el Dynamic Island cerrado",
        readout: "Junto a la cámara",
        readoutElapsed: "Tiempo",
        readoutTokens: "Tokens escritos",
        readoutLimit: "Límite",
        alerts: "Avisos",
        finishAlert: "Cuando termine una tarea",
        finishAfter: "Para tareas de más de",
        anyLength: "Cualquier duración",
        limitAlert: "Cerca de un límite del plan",
        limitAt: "Avisar al",
        budget: "Presupuesto diario en valor de API",
        off: "Desactivado",
        updatedFormat: "Actualizado %@",
        claudeLimitsTitle: "Límites del plan de Claude",
        claudeLimitsCurrentFormat: "Leídos de la app de Claude, actualizados %@",
        claudeLimitsStaleFormat: "La app de Claude los revisó por última vez %@.",
        claudeLimitsMenuBar: "Claude solo revisa los límites mientras su icono está en la barra de menús. Activa el icono en los ajustes de la app de Claude, y los límites aparecerán aquí en pocos minutos.",
        claudeLimitsNoApp: "Los límites del plan vienen de la app de Claude, que no está en este Mac. Mientras tanto, la sesión de 5 horas se estima a partir de la actividad de Claude Code.",
        claudeLimitsPrivacy: "Aster lee los porcentajes que la app de Claude guarda en este Mac. No se usa ningún inicio de sesión y no se envía nada.",
        openClaude: "Abrir Claude",
        getClaude: "Descargar la app de Claude",
        priceUpdates: "Mantener los precios al día",
        priceUpdatesHint: "Descarga una vez al día la lista pública de precios desde GitHub, para que los modelos nuevos tengan valor de API sin actualizar la app. No se envía nada sobre tu uso.",
        pricesFromFormat: "Lista de precios del %@",
        valueNote: "El valor de API es lo que costaría el mismo trabajo con los precios de lista de la API. Los planes cobran un precio fijo.")

    static let sk = NotchAgentStrings(
        title: "AI agenti",
        hubDescription: "Sledujte v Dynamic Island limity plánu, tokeny, hodnotu API a to, na čom práve pracujú Claude a Codex.",
        settingsDescription: "Číta využitie, ktoré si Claude Code a Codex zaznamenávajú na tomto Macu, a limity plánu, ktoré ukladá aplikácia Claude. Prompty, odpovede ani súbory sa neuchovávajú a vaše využitie nikdy neopustí váš Mac.",
        restingTitle: "Limity AI",
        limitsCard: "Limity",
        spendCard: "Výdavky",
        liveCard: "Teraz",
        trendCard: "Vývoj",
        modelsCard: "Modely",
        projectsCard: "Projekty",
        activityCard: "Aktivita",
        today: "Dnes",
        week: "7 dní",
        month: "30 dní",
        session: "Relácia",
        weekly: "Týždeň",
        estimated: "Odhadnuté z tohto Macu",
        claudeLimitsHint: "Nastaviť limity plánu…",
        waitingForLimits: "Limity sa zobrazia po ďalšej odpovedi",
        noSession: "Nebeží žiadna relácia",
        apiValue: "hodnota API",
        tokensFormat: "Tokeny: %@",
        cachedFormat: "%@ z vyrovnávacej pamäte",
        writtenFormat: "Zapísané: %@",
        savedFormat: "Vyrovnávacia pamäť ušetrila %@",
        planMultipleFormat: "%1$@ ceny %2$@",
        idle: "Nečinné",
        noActivity: "V tomto období nič",
        empty: "Zatiaľ žiadne využitie z Claude Code ani Codexu. Zobrazí sa tu hneď, ako niektorý z nich začne na tomto Macu pracovať.",
        loading: "Načítava sa využitie…",
        noCards: "V nastaveniach Dynamic Island vyberte, čo má táto stránka zobrazovať.",
        unpriced: "Pri niektorých modeloch nie je známa cena, takže ide o minimum.",
        streak: "Dni po sebe",
        activeDays: "Aktívne dni",
        busiestDay: "Najrušnejší deň",
        finishedFormat: "%@ skončil",
        limitRenewed: "Limit sa obnovil",
        budgetTitle: "Denný rozpočet",
        leftFormat: "Zostáva %@",
        usedFormat: "Využité %@",
        agents: "Agenti",
        found: "Nájdené na tomto Macu",
        notFound: "Na tomto Macu sa nenašlo",
        cardsTitle: "Karty",
        cardsHint: "Presunutím zmeníte poradie. Grafy zaberajú celú šírku Dynamic Island.",
        limitsAs: "Zobraziť limity ako",
        remaining: "Zostatok",
        used: "Využité",
        liveTitle: "Kým agent pracuje",
        liveActivity: "Zobraziť v zatvorenom Dynamic Island",
        readout: "Vedľa kamery",
        readoutElapsed: "Čas",
        readoutTokens: "Zapísané tokeny",
        readoutLimit: "Limit",
        alerts: "Upozornenia",
        finishAlert: "Keď sa úloha dokončí",
        finishAfter: "Pri úlohách dlhších ako",
        anyLength: "Ľubovoľná dĺžka",
        limitAlert: "Blízko limitu plánu",
        limitAt: "Upozorniť pri",
        budget: "Denný rozpočet hodnoty API",
        off: "Vypnuté",
        updatedFormat: "Aktualizované %@",
        claudeLimitsTitle: "Limity plánu Claude",
        claudeLimitsCurrentFormat: "Načítané z aplikácie Claude, aktualizované %@",
        claudeLimitsStaleFormat: "Aplikácia Claude ich naposledy skontrolovala %@.",
        claudeLimitsMenuBar: "Claude kontroluje vaše limity, len kým je jeho ikona v lište. Zapnite ikonu v nastaveniach aplikácie Claude a limity sa tu zobrazia do niekoľkých minút.",
        claudeLimitsNoApp: "Limity plánu pochádzajú z aplikácie Claude, ktorá na tomto Macu nie je. Dovtedy sa 5-hodinová relácia odhaduje z aktivity Claude Code.",
        claudeLimitsPrivacy: "Aster číta percentá, ktoré aplikácia Claude ukladá na tomto Macu. Nepoužíva sa žiadne prihlásenie a nič sa neodosiela.",
        openClaude: "Otvoriť Claude",
        getClaude: "Získať aplikáciu Claude",
        priceUpdates: "Udržiavať ceny aktuálne",
        priceUpdatesHint: "Raz denne stiahne verejný cenník z GitHubu, aby nové modely dostali hodnotu API aj bez aktualizácie aplikácie. O vašom využití sa neodosiela nič.",
        pricesFromFormat: "Cenník z %@",
        valueNote: "Hodnota API je suma, ktorú by tá istá práca stála v cenníkových cenách API. Plány si namiesto toho účtujú pevnú cenu.")

    static let de = NotchAgentStrings(
        title: "KI-Agenten",
        hubDescription: "Verfolge im Dynamic Island die Planlimits, Tokens, den API-Wert und die laufende Arbeit von Claude und Codex.",
        settingsDescription: "Liest die Nutzung, die Claude Code und Codex auf diesem Mac protokollieren, und die Planlimits, die die Claude-App speichert. Prompts, Antworten und Dateien werden nie gespeichert, und deine Nutzung verlässt nie deinen Mac.",
        restingTitle: "KI-Limits",
        limitsCard: "Limits",
        spendCard: "Ausgaben",
        liveCard: "Jetzt",
        trendCard: "Verlauf",
        modelsCard: "Modelle",
        projectsCard: "Projekte",
        activityCard: "Aktivität",
        today: "Heute",
        week: "7 Tage",
        month: "30 Tage",
        session: "Sitzung",
        weekly: "Woche",
        estimated: "Geschätzt anhand dieses Macs",
        claudeLimitsHint: "Planlimits einrichten…",
        waitingForLimits: "Limits erscheinen nach der nächsten Antwort",
        noSession: "Keine laufende Sitzung",
        apiValue: "API-Wert",
        tokensFormat: "%@ Tokens",
        cachedFormat: "%@ aus dem Cache",
        writtenFormat: "%@ geschrieben",
        savedFormat: "%@ durch den Cache gespart",
        planMultipleFormat: "%1$@ so viel wie %2$@",
        idle: "Inaktiv",
        noActivity: "Nichts in diesem Zeitraum",
        empty: "Noch keine Nutzung von Claude Code oder Codex. Sie erscheint hier, sobald eines davon auf diesem Mac arbeitet.",
        loading: "Nutzung wird gelesen…",
        noCards: "Wähle in den Dynamic Island-Einstellungen, was diese Seite zeigt.",
        unpriced: "Für einige Modelle ist kein Preis bekannt, daher ist dies ein Mindestwert.",
        streak: "Tage in Folge",
        activeDays: "Aktive Tage",
        busiestDay: "Stärkster Tag",
        finishedFormat: "%@ ist fertig",
        limitRenewed: "Limit erneuert",
        budgetTitle: "Tagesbudget",
        leftFormat: "%@ übrig",
        usedFormat: "%@ genutzt",
        agents: "Agenten",
        found: "Auf diesem Mac gefunden",
        notFound: "Auf diesem Mac nicht gefunden",
        cardsTitle: "Karten",
        cardsHint: "Zum Neuordnen ziehen. Diagramme nutzen die volle Breite des Dynamic Island.",
        limitsAs: "Limits anzeigen als",
        remaining: "Übrig",
        used: "Genutzt",
        liveTitle: "Während ein Agent arbeitet",
        liveActivity: "Im geschlossenen Dynamic Island zeigen",
        readout: "Neben der Kamera",
        readoutElapsed: "Zeit",
        readoutTokens: "Geschriebene Tokens",
        readoutLimit: "Limit",
        alerts: "Hinweise",
        finishAlert: "Wenn eine Aufgabe fertig ist",
        finishAfter: "Bei Aufgaben länger als",
        anyLength: "Jede Dauer",
        limitAlert: "Nahe an einem Planlimit",
        limitAt: "Warnen bei",
        budget: "Tagesbudget für den API-Wert",
        off: "Aus",
        updatedFormat: "Aktualisiert %@",
        claudeLimitsTitle: "Planlimits von Claude",
        claudeLimitsCurrentFormat: "Aus der Claude-App gelesen, aktualisiert %@",
        claudeLimitsStaleFormat: "Die Claude-App hat sie zuletzt %@ geprüft.",
        claudeLimitsMenuBar: "Claude prüft die Limits nur, solange sein Symbol in der Menüleiste ist. Schalte das Symbol in den Einstellungen der Claude-App ein, dann erscheinen die Limits hier innerhalb weniger Minuten.",
        claudeLimitsNoApp: "Die Planlimits kommen aus der Claude-App, die nicht auf diesem Mac ist. Bis dahin wird die 5-Stunden-Sitzung aus der Aktivität von Claude Code geschätzt.",
        claudeLimitsPrivacy: "Aster liest die Prozentwerte, die die Claude-App auf diesem Mac speichert. Es wird keine Anmeldung verwendet und nichts gesendet.",
        openClaude: "Claude öffnen",
        getClaude: "Claude-App laden",
        priceUpdates: "Preise aktuell halten",
        priceUpdatesHint: "Lädt einmal am Tag die öffentliche Preisliste von GitHub, damit neue Modelle ohne App-Update einen API-Wert bekommen. Über deine Nutzung wird nichts gesendet.",
        pricesFromFormat: "Preisliste vom %@",
        valueNote: "Der API-Wert ist, was dieselbe Arbeit zu API-Listenpreisen kosten würde. Pläne kosten stattdessen einen festen Preis.")

    static let fr = NotchAgentStrings(
        title: "Agents IA",
        hubDescription: "Suivez dans le Dynamic Island les limites du forfait, les jetons, la valeur API et le travail en cours de Claude et Codex.",
        settingsDescription: "Lit l’usage que Claude Code et Codex enregistrent sur ce Mac et les limites du forfait que l’app Claude enregistre. Les requêtes, réponses et fichiers ne sont jamais conservés, et votre usage ne quitte jamais votre Mac.",
        restingTitle: "Limites IA",
        limitsCard: "Limites",
        spendCard: "Dépenses",
        liveCard: "En cours",
        trendCard: "Tendance",
        modelsCard: "Modèles",
        projectsCard: "Projets",
        activityCard: "Activité",
        today: "Aujourd’hui",
        week: "7 jours",
        month: "30 jours",
        session: "Session",
        weekly: "Semaine",
        estimated: "Estimé depuis ce Mac",
        claudeLimitsHint: "Configurer les limites du forfait…",
        waitingForLimits: "Les limites apparaissent après la prochaine réponse",
        noSession: "Aucune session en cours",
        apiValue: "valeur API",
        tokensFormat: "%@ jetons",
        cachedFormat: "%@ depuis le cache",
        writtenFormat: "%@ écrits",
        savedFormat: "%@ économisés grâce au cache",
        planMultipleFormat: "%1$@ le prix de %2$@",
        idle: "Inactif",
        noActivity: "Rien sur cette période",
        empty: "Aucun usage de Claude Code ou de Codex pour l’instant. Il apparaît ici dès que l’un d’eux travaille sur ce Mac.",
        loading: "Lecture de l’usage…",
        noCards: "Choisissez ce que montre cette page dans les réglages du Dynamic Island.",
        unpriced: "Certains modèles n’ont pas de prix connu, ce montant est donc un minimum.",
        streak: "Jours d’affilée",
        activeDays: "Jours actifs",
        busiestDay: "Jour le plus chargé",
        finishedFormat: "%@ a terminé",
        limitRenewed: "Limite renouvelée",
        budgetTitle: "Budget quotidien",
        leftFormat: "%@ restant",
        usedFormat: "%@ utilisé",
        agents: "Agents",
        found: "Trouvé sur ce Mac",
        notFound: "Introuvable sur ce Mac",
        cardsTitle: "Cartes",
        cardsHint: "Faites glisser pour réorganiser. Les graphiques occupent toute la largeur du Dynamic Island.",
        limitsAs: "Afficher les limites en",
        remaining: "Restant",
        used: "Utilisé",
        liveTitle: "Pendant qu’un agent travaille",
        liveActivity: "L’afficher dans le Dynamic Island fermé",
        readout: "À côté de la caméra",
        readoutElapsed: "Durée",
        readoutTokens: "Jetons écrits",
        readoutLimit: "Limite",
        alerts: "Alertes",
        finishAlert: "Quand une tâche se termine",
        finishAfter: "Pour les tâches de plus de",
        anyLength: "Toute durée",
        limitAlert: "Près d’une limite du forfait",
        limitAt: "Avertir à",
        budget: "Budget quotidien en valeur API",
        off: "Désactivé",
        updatedFormat: "Mis à jour %@",
        claudeLimitsTitle: "Limites du forfait Claude",
        claudeLimitsCurrentFormat: "Lues dans l’app Claude, mises à jour %@",
        claudeLimitsStaleFormat: "L’app Claude les a vérifiées pour la dernière fois %@.",
        claudeLimitsMenuBar: "Claude ne vérifie les limites que lorsque son icône est dans la barre des menus. Activez l’icône dans les réglages de l’app Claude, et les limites apparaîtront ici en quelques minutes.",
        claudeLimitsNoApp: "Les limites du forfait viennent de l’app Claude, absente de ce Mac. En attendant, la session de 5 heures est estimée d’après l’activité de Claude Code.",
        claudeLimitsPrivacy: "Aster lit les pourcentages que l’app Claude enregistre sur ce Mac. Aucune connexion n’est utilisée et rien n’est envoyé.",
        openClaude: "Ouvrir Claude",
        getClaude: "Télécharger l’app Claude",
        priceUpdates: "Garder les prix à jour",
        priceUpdatesHint: "Télécharge une fois par jour la liste publique des prix depuis GitHub, pour que les nouveaux modèles aient une valeur API sans mise à jour de l’app. Rien sur votre usage n’est envoyé.",
        pricesFromFormat: "Liste des prix du %@",
        valueNote: "La valeur API est ce que le même travail coûterait aux tarifs publics de l’API. Les forfaits facturent un prix fixe.")

    static let it = NotchAgentStrings(
        title: "Agenti IA",
        hubDescription: "Segui nel Dynamic Island i limiti del piano, i token, il valore API e il lavoro in corso di Claude e Codex.",
        settingsDescription: "Legge l’utilizzo che Claude Code e Codex registrano su questo Mac e i limiti del piano che l’app Claude salva. Prompt, risposte e file non vengono mai conservati, e il tuo utilizzo non lascia mai il tuo Mac.",
        restingTitle: "Limiti IA",
        limitsCard: "Limiti",
        spendCard: "Spesa",
        liveCard: "Adesso",
        trendCard: "Andamento",
        modelsCard: "Modelli",
        projectsCard: "Progetti",
        activityCard: "Attività",
        today: "Oggi",
        week: "7 giorni",
        month: "30 giorni",
        session: "Sessione",
        weekly: "Settimana",
        estimated: "Stimato da questo Mac",
        claudeLimitsHint: "Configura i limiti del piano…",
        waitingForLimits: "I limiti compaiono dopo la prossima risposta",
        noSession: "Nessuna sessione in corso",
        apiValue: "valore API",
        tokensFormat: "%@ token",
        cachedFormat: "%@ dalla cache",
        writtenFormat: "%@ scritti",
        savedFormat: "%@ risparmiati grazie alla cache",
        planMultipleFormat: "%1$@ il prezzo di %2$@",
        idle: "Inattivo",
        noActivity: "Niente in questo periodo",
        empty: "Ancora nessun utilizzo di Claude Code o Codex. Compare qui appena uno dei due lavora su questo Mac.",
        loading: "Lettura dell’utilizzo…",
        noCards: "Scegli cosa mostra questa pagina nelle impostazioni del Dynamic Island.",
        unpriced: "Alcuni modelli non hanno un prezzo noto, quindi questo è un minimo.",
        streak: "Giorni di fila",
        activeDays: "Giorni attivi",
        busiestDay: "Giorno più intenso",
        finishedFormat: "%@ ha finito",
        limitRenewed: "Limite rinnovato",
        budgetTitle: "Budget giornaliero",
        leftFormat: "%@ rimasto",
        usedFormat: "%@ usato",
        agents: "Agenti",
        found: "Trovato su questo Mac",
        notFound: "Non trovato su questo Mac",
        cardsTitle: "Schede",
        cardsHint: "Trascina per riordinare. I grafici occupano tutta la larghezza del Dynamic Island.",
        limitsAs: "Mostra i limiti come",
        remaining: "Rimasto",
        used: "Usato",
        liveTitle: "Mentre un agente lavora",
        liveActivity: "Mostralo nel Dynamic Island chiuso",
        readout: "Accanto alla fotocamera",
        readoutElapsed: "Tempo",
        readoutTokens: "Token scritti",
        readoutLimit: "Limite",
        alerts: "Avvisi",
        finishAlert: "Quando un’attività finisce",
        finishAfter: "Per attività più lunghe di",
        anyLength: "Qualsiasi durata",
        limitAlert: "Vicino a un limite del piano",
        limitAt: "Avvisa al",
        budget: "Budget giornaliero in valore API",
        off: "Disattivato",
        updatedFormat: "Aggiornato %@",
        claudeLimitsTitle: "Limiti del piano di Claude",
        claudeLimitsCurrentFormat: "Letti dall’app Claude, aggiornati %@",
        claudeLimitsStaleFormat: "L’app Claude li ha controllati l’ultima volta %@.",
        claudeLimitsMenuBar: "Claude controlla i limiti solo mentre la sua icona è nella barra dei menu. Attiva l’icona nelle impostazioni dell’app Claude, e i limiti compariranno qui in pochi minuti.",
        claudeLimitsNoApp: "I limiti del piano arrivano dall’app Claude, che non è su questo Mac. Nel frattempo, la sessione di 5 ore è stimata dall’attività di Claude Code.",
        claudeLimitsPrivacy: "Aster legge le percentuali che l’app Claude salva su questo Mac. Non usa alcun accesso e non invia nulla.",
        openClaude: "Apri Claude",
        getClaude: "Scarica l’app Claude",
        priceUpdates: "Mantieni i prezzi aggiornati",
        priceUpdatesHint: "Scarica una volta al giorno il listino prezzi pubblico da GitHub, così i nuovi modelli hanno un valore API senza aggiornare l’app. Non viene inviato nulla sul tuo utilizzo.",
        pricesFromFormat: "Listino del %@",
        valueNote: "Il valore API è quanto costerebbe lo stesso lavoro ai prezzi di listino dell’API. I piani hanno invece un prezzo fisso.")

    static let ru = NotchAgentStrings(
        title: "ИИ-агенты",
        hubDescription: "Следите в Dynamic Island за лимитами тарифа, токенами, стоимостью по API и текущей работой Claude и Codex.",
        settingsDescription: "Читает сведения об использовании, которые Claude Code и Codex записывают на этом Mac, и лимиты тарифа, которые сохраняет приложение Claude. Запросы, ответы и файлы не сохраняются, а сведения об использовании никогда не покидают ваш Mac.",
        restingTitle: "Лимиты ИИ",
        limitsCard: "Лимиты",
        spendCard: "Расходы",
        liveCard: "Сейчас",
        trendCard: "Динамика",
        modelsCard: "Модели",
        projectsCard: "Проекты",
        activityCard: "Активность",
        today: "Сегодня",
        week: "7 дней",
        month: "30 дней",
        session: "Сессия",
        weekly: "Неделя",
        estimated: "Оценка по этому Mac",
        claudeLimitsHint: "Настроить лимиты тарифа…",
        waitingForLimits: "Лимиты появятся после следующего ответа",
        noSession: "Нет активной сессии",
        apiValue: "стоимость по API",
        tokensFormat: "Токенов: %@",
        cachedFormat: "Из кэша: %@",
        writtenFormat: "Написано: %@",
        savedFormat: "Кэш сэкономил %@",
        planMultipleFormat: "%1$@ от цены %2$@",
        idle: "Простой",
        noActivity: "За этот период ничего нет",
        empty: "Пока нет данных об использовании Claude Code или Codex. Они появятся здесь, как только один из них начнёт работу на этом Mac.",
        loading: "Чтение данных…",
        noCards: "Выберите, что показывает эта страница, в настройках Dynamic Island.",
        unpriced: "Для некоторых моделей цена неизвестна, поэтому это минимальная сумма.",
        streak: "Дней подряд",
        activeDays: "Активные дни",
        busiestDay: "Самый активный день",
        finishedFormat: "%@ завершил работу",
        limitRenewed: "Лимит обновлён",
        budgetTitle: "Дневной бюджет",
        leftFormat: "Осталось %@",
        usedFormat: "Использовано %@",
        agents: "Агенты",
        found: "Найден на этом Mac",
        notFound: "Не найден на этом Mac",
        cardsTitle: "Карточки",
        cardsHint: "Перетащите, чтобы изменить порядок. Графики занимают всю ширину Dynamic Island.",
        limitsAs: "Показывать лимиты",
        remaining: "Остаток",
        used: "Использовано",
        liveTitle: "Пока агент работает",
        liveActivity: "Показывать в закрытом Dynamic Island",
        readout: "Рядом с камерой",
        readoutElapsed: "Время",
        readoutTokens: "Написанные токены",
        readoutLimit: "Лимит",
        alerts: "Уведомления",
        finishAlert: "Когда задача завершена",
        finishAfter: "Для задач дольше",
        anyLength: "Любой длительности",
        limitAlert: "Около лимита тарифа",
        limitAt: "Предупреждать при",
        budget: "Дневной бюджет по стоимости API",
        off: "Выкл.",
        updatedFormat: "Обновлено %@",
        claudeLimitsTitle: "Лимиты тарифа Claude",
        claudeLimitsCurrentFormat: "Из приложения Claude, обновлено %@",
        claudeLimitsStaleFormat: "Приложение Claude в последний раз проверяло их %@.",
        claudeLimitsMenuBar: "Claude проверяет лимиты, только пока его значок есть в строке меню. Включите значок в настройках приложения Claude, и лимиты появятся здесь через несколько минут.",
        claudeLimitsNoApp: "Лимиты тарифа берутся из приложения Claude, которого нет на этом Mac. Пока его нет, 5-часовая сессия оценивается по активности Claude Code.",
        claudeLimitsPrivacy: "Aster читает проценты, которые приложение Claude сохраняет на этом Mac. Вход в аккаунт не используется, и ничего не отправляется.",
        openClaude: "Открыть Claude",
        getClaude: "Скачать приложение Claude",
        priceUpdates: "Обновлять цены",
        priceUpdatesHint: "Раз в день загружает общедоступный прейскурант с GitHub, чтобы новые модели получали стоимость по API без обновления приложения. Сведения об использовании не отправляются.",
        pricesFromFormat: "Прейскурант от %@",
        valueNote: "Стоимость по API показывает, сколько стоила бы та же работа по прейскуранту API. Тарифы же стоят фиксированную сумму.")

    static let tr = NotchAgentStrings(
        title: "YZ Ajanları",
        hubDescription: "Claude ve Codex için plan sınırlarını, token’ları, API değerini ve süren işleri Dynamic Island’dan izleyin.",
        settingsDescription: "Claude Code ve Codex’in bu Mac’e kaydettiği kullanımı ve Claude uygulamasının kaydettiği plan sınırlarını okur. İstemler, yanıtlar ve dosyalar asla saklanmaz ve kullanımınız Mac’inizden asla çıkmaz.",
        restingTitle: "YZ sınırları",
        limitsCard: "Sınırlar",
        spendCard: "Harcama",
        liveCard: "Şimdi",
        trendCard: "Eğilim",
        modelsCard: "Modeller",
        projectsCard: "Projeler",
        activityCard: "Etkinlik",
        today: "Bugün",
        week: "7 gün",
        month: "30 gün",
        session: "Oturum",
        weekly: "Hafta",
        estimated: "Bu Mac’e göre tahmin",
        claudeLimitsHint: "Plan sınırlarını ayarla…",
        waitingForLimits: "Sınırlar bir sonraki yanıttan sonra görünür",
        noSession: "Süren oturum yok",
        apiValue: "API değeri",
        tokensFormat: "%@ token",
        cachedFormat: "Önbellekten %@",
        writtenFormat: "%@ yazıldı",
        savedFormat: "Önbellek %@ tasarruf sağladı",
        planMultipleFormat: "%2$@ fiyatının %1$@",
        idle: "Boşta",
        noActivity: "Bu dönemde bir şey yok",
        empty: "Henüz Claude Code veya Codex kullanımı yok. İkisinden biri bu Mac’te çalışır çalışmaz burada görünür.",
        loading: "Kullanım okunuyor…",
        noCards: "Bu sayfada nelerin görüneceğini Dynamic Island ayarlarından seçin.",
        unpriced: "Bazı modellerin fiyatı bilinmediğinden bu bir alt sınırdır.",
        streak: "Art arda gün",
        activeDays: "Aktif günler",
        busiestDay: "En yoğun gün",
        finishedFormat: "%@ bitirdi",
        limitRenewed: "Sınır yenilendi",
        budgetTitle: "Günlük bütçe",
        leftFormat: "%@ kaldı",
        usedFormat: "%@ kullanıldı",
        agents: "Ajanlar",
        found: "Bu Mac’te bulundu",
        notFound: "Bu Mac’te bulunamadı",
        cardsTitle: "Kartlar",
        cardsHint: "Sıralamak için sürükleyin. Grafikler Dynamic Island’ın tüm genişliğini kaplar.",
        limitsAs: "Sınırları göster",
        remaining: "Kalan",
        used: "Kullanılan",
        liveTitle: "Bir ajan çalışırken",
        liveActivity: "Kapalı Dynamic Island’da göster",
        readout: "Kameranın yanında",
        readoutElapsed: "Süre",
        readoutTokens: "Yazılan token",
        readoutLimit: "Sınır",
        alerts: "Uyarılar",
        finishAlert: "Bir görev bittiğinde",
        finishAfter: "Şundan uzun görevler için",
        anyLength: "Her süre",
        limitAlert: "Plan sınırına yaklaşınca",
        limitAt: "Uyarı eşiği",
        budget: "Günlük API değeri bütçesi",
        off: "Kapalı",
        updatedFormat: "%@ güncellendi",
        claudeLimitsTitle: "Claude plan sınırları",
        claudeLimitsCurrentFormat: "Claude uygulamasından okundu, %@ güncellendi",
        claudeLimitsStaleFormat: "Claude uygulaması bunları en son %@ kontrol etti.",
        claudeLimitsMenuBar: "Claude, sınırları yalnızca simgesi menü çubuğundayken kontrol eder. Simgeyi Claude uygulamasının ayarlarından açtığınızda sınırlar birkaç dakika içinde burada görünür.",
        claudeLimitsNoApp: "Plan sınırları, bu Mac’te olmayan Claude uygulamasından gelir. O zamana kadar 5 saatlik oturum, Claude Code etkinliğinden tahmin edilir.",
        claudeLimitsPrivacy: "Aster, Claude uygulamasının bu Mac’e kaydettiği yüzdeleri okur. Hiçbir oturum açma bilgisi kullanılmaz ve hiçbir şey gönderilmez.",
        openClaude: "Claude’u Aç",
        getClaude: "Claude uygulamasını indir",
        priceUpdates: "Fiyatları güncel tut",
        priceUpdatesHint: "Genel fiyat listesini günde bir kez GitHub’dan indirir; böylece yeni modeller uygulama güncellemesi olmadan API değeri alır. Kullanımınızla ilgili hiçbir şey gönderilmez.",
        pricesFromFormat: "%@ tarihli fiyat listesi",
        valueNote: "API değeri, aynı işin API liste fiyatlarıyla tutacağı tutardır. Planlar ise sabit bir ücret alır.")

    static let ja = NotchAgentStrings(
        title: "AIエージェント",
        hubDescription: "ClaudeとCodexのプラン上限、トークン、API換算額、進行中の作業をDynamic Islandで確認できます。",
        settingsDescription: "Claude CodeとCodexがこのMacに記録する使用状況と、Claudeアプリが保存するプラン上限を読み取ります。プロンプト、応答、ファイルは保持せず、使用状況がMacの外に送信されることはありません。",
        restingTitle: "AIの上限",
        limitsCard: "上限",
        spendCard: "使用額",
        liveCard: "実行中",
        trendCard: "推移",
        modelsCard: "モデル",
        projectsCard: "プロジェクト",
        activityCard: "アクティビティ",
        today: "今日",
        week: "7日間",
        month: "30日間",
        session: "セッション",
        weekly: "週",
        estimated: "このMacの記録から推定",
        claudeLimitsHint: "プラン上限を設定…",
        waitingForLimits: "次の応答のあとに上限が表示されます",
        noSession: "実行中のセッションはありません",
        apiValue: "API換算額",
        tokensFormat: "%@トークン",
        cachedFormat: "キャッシュ %@",
        writtenFormat: "%@ 出力",
        savedFormat: "キャッシュで%@節約",
        planMultipleFormat: "%2$@の料金の%1$@",
        idle: "待機中",
        noActivity: "この期間の記録はありません",
        empty: "Claude CodeとCodexの使用状況はまだありません。どちらかがこのMacで動作するとここに表示されます。",
        loading: "使用状況を読み込み中…",
        noCards: "このページに表示する内容はDynamic Islandの設定で選べます。",
        unpriced: "一部のモデルは料金が不明なため、最低額を表示しています。",
        streak: "連続日数",
        activeDays: "アクティブな日数",
        busiestDay: "最も多かった日",
        finishedFormat: "%@が完了しました",
        limitRenewed: "上限がリセットされました",
        budgetTitle: "1日の予算",
        leftFormat: "残り%@",
        usedFormat: "%@使用",
        agents: "エージェント",
        found: "このMacで見つかりました",
        notFound: "このMacで見つかりません",
        cardsTitle: "カード",
        cardsHint: "ドラッグで並べ替えできます。グラフはDynamic Islandの横幅いっぱいに表示されます。",
        limitsAs: "上限の表示",
        remaining: "残り",
        used: "使用済み",
        liveTitle: "エージェントの作業中",
        liveActivity: "閉じたDynamic Islandに表示",
        readout: "カメラの横",
        readoutElapsed: "時間",
        readoutTokens: "出力トークン",
        readoutLimit: "上限",
        alerts: "通知",
        finishAlert: "タスクが完了したとき",
        finishAfter: "対象のタスクの長さ",
        anyLength: "すべて",
        limitAlert: "プラン上限に近づいたとき",
        limitAt: "通知するしきい値",
        budget: "API換算額の1日の予算",
        off: "オフ",
        updatedFormat: "最終更新：%@",
        claudeLimitsTitle: "Claudeのプラン上限",
        claudeLimitsCurrentFormat: "Claudeアプリから取得（最終更新：%@）",
        claudeLimitsStaleFormat: "Claudeアプリが最後に確認したのは%@です。",
        claudeLimitsMenuBar: "Claudeは、アイコンがメニューバーにあるあいだだけ上限を確認します。Claudeアプリの設定でアイコンをオンにすると、数分で上限がここに表示されます。",
        claudeLimitsNoApp: "プラン上限はClaudeアプリから取得しますが、このMacにはありません。それまでは、5時間のセッションをClaude Codeのアクティビティから推定します。",
        claudeLimitsPrivacy: "Asterは、ClaudeアプリがこのMacに保存する割合を読み取ります。サインイン情報は使わず、何も送信しません。",
        openClaude: "Claudeを開く",
        getClaude: "Claudeアプリを入手",
        priceUpdates: "価格を最新に保つ",
        priceUpdatesHint: "公開価格表を1日1回GitHubからダウンロードし、新しいモデルにもアプリのアップデートなしでAPI換算額を表示します。使用状況は送信しません。",
        pricesFromFormat: "%@時点の価格表",
        valueNote: "API換算額は、同じ作業をAPIの定価で行った場合の料金です。プランは定額です。")

    static let ko = NotchAgentStrings(
        title: "AI 에이전트",
        hubDescription: "Claude와 Codex의 플랜 한도, 토큰, API 환산 금액, 진행 중인 작업을 Dynamic Island에서 확인하세요.",
        settingsDescription: "Claude Code와 Codex가 이 Mac에 기록하는 사용량과 Claude 앱이 저장하는 플랜 한도를 읽습니다. 프롬프트, 응답, 파일은 보관하지 않으며, 사용량은 Mac 밖으로 나가지 않습니다.",
        restingTitle: "AI 한도",
        limitsCard: "한도",
        spendCard: "사용 금액",
        liveCard: "지금",
        trendCard: "추이",
        modelsCard: "모델",
        projectsCard: "프로젝트",
        activityCard: "활동",
        today: "오늘",
        week: "7일",
        month: "30일",
        session: "세션",
        weekly: "주간",
        estimated: "이 Mac의 기록으로 추정",
        claudeLimitsHint: "플랜 한도 설정…",
        waitingForLimits: "다음 응답 후에 한도가 표시됩니다",
        noSession: "진행 중인 세션 없음",
        apiValue: "API 환산 금액",
        tokensFormat: "토큰 %@개",
        cachedFormat: "캐시 %@",
        writtenFormat: "%@ 작성",
        savedFormat: "캐시로 %@ 절약",
        planMultipleFormat: "%2$@ 요금의 %1$@",
        idle: "대기 중",
        noActivity: "이 기간에는 기록이 없습니다",
        empty: "아직 Claude Code나 Codex 사용량이 없습니다. 둘 중 하나가 이 Mac에서 작업하면 바로 여기에 표시됩니다.",
        loading: "사용량을 읽는 중…",
        noCards: "Dynamic Island 설정에서 이 페이지에 표시할 항목을 선택하세요.",
        unpriced: "일부 모델은 가격을 알 수 없어 최소 금액으로 표시합니다.",
        streak: "연속 일수",
        activeDays: "활동한 날",
        busiestDay: "가장 많이 쓴 날",
        finishedFormat: "%@ 작업 완료",
        limitRenewed: "한도가 초기화됨",
        budgetTitle: "일일 예산",
        leftFormat: "%@ 남음",
        usedFormat: "%@ 사용",
        agents: "에이전트",
        found: "이 Mac에서 찾음",
        notFound: "이 Mac에서 찾을 수 없음",
        cardsTitle: "카드",
        cardsHint: "드래그하여 순서를 바꾸세요. 그래프는 Dynamic Island의 전체 너비를 사용합니다.",
        limitsAs: "한도 표시 방식",
        remaining: "남은 양",
        used: "사용량",
        liveTitle: "에이전트가 작업하는 동안",
        liveActivity: "닫힌 Dynamic Island에 표시",
        readout: "카메라 옆",
        readoutElapsed: "시간",
        readoutTokens: "작성한 토큰",
        readoutLimit: "한도",
        alerts: "알림",
        finishAlert: "작업이 끝났을 때",
        finishAfter: "다음보다 긴 작업",
        anyLength: "모든 길이",
        limitAlert: "플랜 한도에 가까울 때",
        limitAt: "알림 기준",
        budget: "API 환산 금액 일일 예산",
        off: "끔",
        updatedFormat: "%@ 업데이트됨",
        claudeLimitsTitle: "Claude 플랜 한도",
        claudeLimitsCurrentFormat: "Claude 앱에서 읽음, %@ 업데이트됨",
        claudeLimitsStaleFormat: "Claude 앱이 %@ 마지막으로 확인했습니다.",
        claudeLimitsMenuBar: "Claude는 아이콘이 메뉴 막대에 있을 때만 한도를 확인합니다. Claude 앱 설정에서 아이콘을 켜면 몇 분 안에 한도가 여기에 표시됩니다.",
        claudeLimitsNoApp: "플랜 한도는 Claude 앱에서 가져오지만 이 Mac에는 앱이 없습니다. 그동안에는 5시간 세션을 Claude Code 활동으로 추정합니다.",
        claudeLimitsPrivacy: "Aster는 Claude 앱이 이 Mac에 저장하는 비율을 읽습니다. 로그인 정보는 사용하지 않으며 아무것도 전송하지 않습니다.",
        openClaude: "Claude 열기",
        getClaude: "Claude 앱 받기",
        priceUpdates: "가격을 최신으로 유지",
        priceUpdatesHint: "공개 가격표를 하루에 한 번 GitHub에서 내려받아, 새 모델도 앱 업데이트 없이 API 환산 금액을 표시합니다. 사용량 정보는 전송하지 않습니다.",
        pricesFromFormat: "%@ 기준 가격표",
        valueNote: "API 환산 금액은 같은 작업을 API 정가로 계산한 비용입니다. 플랜은 정액 요금입니다.")

    static let zhHans = NotchAgentStrings(
        title: "AI 智能体",
        hubDescription: "在 Dynamic Island 中查看 Claude 和 Codex 的套餐额度、令牌、API 价值与正在进行的工作。",
        settingsDescription: "读取 Claude Code 和 Codex 在这台 Mac 上记录的用量，以及 Claude App 保存的套餐额度。不会保留提示、回复和文件，你的用量也不会离开你的 Mac。",
        restingTitle: "AI 额度",
        limitsCard: "额度",
        spendCard: "花费",
        liveCard: "当前",
        trendCard: "趋势",
        modelsCard: "模型",
        projectsCard: "项目",
        activityCard: "活动",
        today: "今天",
        week: "7 天",
        month: "30 天",
        session: "会话",
        weekly: "本周",
        estimated: "根据这台 Mac 估算",
        claudeLimitsHint: "设置套餐额度…",
        waitingForLimits: "下次回复后显示额度",
        noSession: "没有进行中的会话",
        apiValue: "API 价值",
        tokensFormat: "%@ 个令牌",
        cachedFormat: "缓存 %@",
        writtenFormat: "已写 %@",
        savedFormat: "缓存节省 %@",
        planMultipleFormat: "%2$@ 价格的 %1$@",
        idle: "空闲",
        noActivity: "此期间没有记录",
        empty: "还没有 Claude Code 或 Codex 的用量。只要其中任何一个在这台 Mac 上工作，就会显示在这里。",
        loading: "正在读取用量…",
        noCards: "在 Dynamic Island 设置中选择此页面显示的内容。",
        unpriced: "部分模型价格未知，因此这是最低金额。",
        streak: "连续天数",
        activeDays: "活跃天数",
        busiestDay: "用量最多的一天",
        finishedFormat: "%@ 已完成",
        limitRenewed: "额度已重置",
        budgetTitle: "每日预算",
        leftFormat: "剩余 %@",
        usedFormat: "已用 %@",
        agents: "智能体",
        found: "已在这台 Mac 上找到",
        notFound: "未在这台 Mac 上找到",
        cardsTitle: "卡片",
        cardsHint: "拖动以重新排序。图表会占满 Dynamic Island 的宽度。",
        limitsAs: "额度显示为",
        remaining: "剩余",
        used: "已用",
        liveTitle: "智能体工作时",
        liveActivity: "在收起的 Dynamic Island 中显示",
        readout: "摄像头旁",
        readoutElapsed: "时间",
        readoutTokens: "已写令牌",
        readoutLimit: "额度",
        alerts: "提醒",
        finishAlert: "任务完成时",
        finishAfter: "任务时长超过",
        anyLength: "任意时长",
        limitAlert: "接近套餐额度时",
        limitAt: "提醒阈值",
        budget: "每日 API 价值预算",
        off: "关闭",
        updatedFormat: "上次更新：%@",
        claudeLimitsTitle: "Claude 套餐额度",
        claudeLimitsCurrentFormat: "读取自 Claude App，上次更新：%@",
        claudeLimitsStaleFormat: "Claude App 上次检查是%@。",
        claudeLimitsMenuBar: "只有当 Claude 的图标在菜单栏中时，它才会检查额度。在 Claude App 的设置中打开图标，几分钟内额度就会显示在这里。",
        claudeLimitsNoApp: "套餐额度来自 Claude App，但这台 Mac 上没有安装。在此之前，5 小时会话根据 Claude Code 的活动估算。",
        claudeLimitsPrivacy: "Aster 读取 Claude App 在这台 Mac 上保存的百分比。不使用任何登录信息，也不发送任何内容。",
        openClaude: "打开 Claude",
        getClaude: "获取 Claude App",
        priceUpdates: "保持价格最新",
        priceUpdatesHint: "每天从 GitHub 下载一次公开价目表，新模型无需更新 App 也能显示 API 价值。不会发送任何用量信息。",
        pricesFromFormat: "%@的价目表",
        valueNote: "API 价值是按 API 标价完成同样工作的费用。套餐则按固定价格收费。")

    static let zhTW = NotchAgentStrings(
        title: "AI 代理",
        hubDescription: "在 Dynamic Island 中查看 Claude 與 Codex 的方案額度、Token、API 價值與進行中的工作。",
        settingsDescription: "讀取 Claude Code 與 Codex 在這台 Mac 上記錄的用量，以及 Claude App 儲存的方案額度。不會保留提示、回覆與檔案，你的用量也不會離開你的 Mac。",
        restingTitle: "AI 額度",
        limitsCard: "額度",
        spendCard: "花費",
        liveCard: "目前",
        trendCard: "趨勢",
        modelsCard: "模型",
        projectsCard: "專案",
        activityCard: "活動",
        today: "今天",
        week: "7 天",
        month: "30 天",
        session: "工作階段",
        weekly: "本週",
        estimated: "依這台 Mac 估算",
        claudeLimitsHint: "設定方案額度…",
        waitingForLimits: "下次回覆後會顯示額度",
        noSession: "沒有進行中的工作階段",
        apiValue: "API 價值",
        tokensFormat: "%@ 個 Token",
        cachedFormat: "快取 %@",
        writtenFormat: "已寫 %@",
        savedFormat: "快取省下 %@",
        planMultipleFormat: "%2$@ 價格的 %1$@",
        idle: "閒置",
        noActivity: "此期間沒有紀錄",
        empty: "目前還沒有 Claude Code 或 Codex 的用量。只要其中一個在這台 Mac 上運作，就會顯示在這裡。",
        loading: "正在讀取用量…",
        noCards: "在 Dynamic Island 設定中選擇此頁面顯示的內容。",
        unpriced: "部分模型價格不明，因此這是最低金額。",
        streak: "連續天數",
        activeDays: "活躍天數",
        busiestDay: "用量最多的一天",
        finishedFormat: "%@ 已完成",
        limitRenewed: "額度已重設",
        budgetTitle: "每日預算",
        leftFormat: "剩餘 %@",
        usedFormat: "已用 %@",
        agents: "代理",
        found: "已在這台 Mac 上找到",
        notFound: "未在這台 Mac 上找到",
        cardsTitle: "卡片",
        cardsHint: "拖移以重新排序。圖表會占滿 Dynamic Island 的寬度。",
        limitsAs: "額度顯示為",
        remaining: "剩餘",
        used: "已用",
        liveTitle: "代理運作時",
        liveActivity: "在收合的 Dynamic Island 中顯示",
        readout: "相機旁",
        readoutElapsed: "時間",
        readoutTokens: "已寫 Token",
        readoutLimit: "額度",
        alerts: "提醒",
        finishAlert: "任務完成時",
        finishAfter: "任務時間超過",
        anyLength: "任何長度",
        limitAlert: "接近方案額度時",
        limitAt: "提醒門檻",
        budget: "每日 API 價值預算",
        off: "關閉",
        updatedFormat: "上次更新：%@",
        claudeLimitsTitle: "Claude 方案額度",
        claudeLimitsCurrentFormat: "讀取自 Claude App，上次更新：%@",
        claudeLimitsStaleFormat: "Claude App 上次檢查是%@。",
        claudeLimitsMenuBar: "只有當 Claude 的圖像在選單列中時，它才會檢查額度。在 Claude App 的設定中開啟圖像，幾分鐘內額度就會顯示在這裡。",
        claudeLimitsNoApp: "方案額度來自 Claude App，但這台 Mac 上沒有安裝。在此之前，5 小時工作階段會依 Claude Code 的活動估算。",
        claudeLimitsPrivacy: "Aster 讀取 Claude App 在這台 Mac 上儲存的百分比。不會使用任何登入資訊，也不會傳送任何內容。",
        openClaude: "打開 Claude",
        getClaude: "取得 Claude App",
        priceUpdates: "保持價格最新",
        priceUpdatesHint: "每天從 GitHub 下載一次公開價目表，新模型不必更新 App 也能顯示 API 價值。不會傳送任何用量資訊。",
        pricesFromFormat: "%@的價目表",
        valueNote: "API 價值是以 API 定價完成同樣工作的費用。方案則以固定價格收費。")

    static let zhHK = NotchAgentStrings(
        title: "AI 代理",
        hubDescription: "在 Dynamic Island 中查看 Claude 與 Codex 的計劃額度、Token、API 價值與進行中的工作。",
        settingsDescription: "讀取 Claude Code 與 Codex 在這部 Mac 上記錄的用量，以及 Claude App 儲存的計劃額度。不會保留提示、回覆與檔案，你的用量也不會離開你的 Mac。",
        restingTitle: "AI 額度",
        limitsCard: "額度",
        spendCard: "花費",
        liveCard: "目前",
        trendCard: "趨勢",
        modelsCard: "模型",
        projectsCard: "項目",
        activityCard: "活動",
        today: "今天",
        week: "7 天",
        month: "30 天",
        session: "工作階段",
        weekly: "本週",
        estimated: "按這部 Mac 估算",
        claudeLimitsHint: "設定計劃額度…",
        waitingForLimits: "下次回覆後會顯示額度",
        noSession: "沒有進行中的工作階段",
        apiValue: "API 價值",
        tokensFormat: "%@ 個 Token",
        cachedFormat: "快取 %@",
        writtenFormat: "已寫 %@",
        savedFormat: "快取節省 %@",
        planMultipleFormat: "%2$@ 價格的 %1$@",
        idle: "閒置",
        noActivity: "此期間沒有記錄",
        empty: "目前還沒有 Claude Code 或 Codex 的用量。只要其中一個在這部 Mac 上運作，就會顯示在這裡。",
        loading: "正在讀取用量…",
        noCards: "在 Dynamic Island 設定中選擇此頁面顯示的內容。",
        unpriced: "部分模型價格不明，因此這是最低金額。",
        streak: "連續天數",
        activeDays: "活躍日數",
        busiestDay: "用量最多的一天",
        finishedFormat: "%@ 已完成",
        limitRenewed: "額度已重設",
        budgetTitle: "每日預算",
        leftFormat: "剩餘 %@",
        usedFormat: "已用 %@",
        agents: "代理",
        found: "已在這部 Mac 上找到",
        notFound: "未在這部 Mac 上找到",
        cardsTitle: "卡片",
        cardsHint: "拖移以重新排序。圖表會佔滿 Dynamic Island 的闊度。",
        limitsAs: "額度顯示為",
        remaining: "剩餘",
        used: "已用",
        liveTitle: "代理運作時",
        liveActivity: "在收合的 Dynamic Island 中顯示",
        readout: "相機旁",
        readoutElapsed: "時間",
        readoutTokens: "已寫 Token",
        readoutLimit: "額度",
        alerts: "提示",
        finishAlert: "任務完成時",
        finishAfter: "任務時間超過",
        anyLength: "任何長度",
        limitAlert: "接近計劃額度時",
        limitAt: "提示門檻",
        budget: "每日 API 價值預算",
        off: "關閉",
        updatedFormat: "上次更新：%@",
        claudeLimitsTitle: "Claude 計劃額度",
        claudeLimitsCurrentFormat: "讀取自 Claude App，上次更新：%@",
        claudeLimitsStaleFormat: "Claude App 上次檢查是%@。",
        claudeLimitsMenuBar: "只有當 Claude 的圖示在選單列中時，它才會檢查額度。在 Claude App 的設定中開啟圖示，幾分鐘內額度就會顯示在這裡。",
        claudeLimitsNoApp: "計劃額度來自 Claude App，但這部 Mac 上沒有安裝。在此之前，5 小時工作階段會按 Claude Code 的活動估算。",
        claudeLimitsPrivacy: "Aster 讀取 Claude App 在這部 Mac 上儲存的百分比。不會使用任何登入資料，也不會傳送任何內容。",
        openClaude: "打開 Claude",
        getClaude: "取得 Claude App",
        priceUpdates: "保持價格最新",
        priceUpdatesHint: "每天從 GitHub 下載一次公開價目表，新模型毋須更新 App 也能顯示 API 價值。不會傳送任何用量資料。",
        pricesFromFormat: "%@的價目表",
        valueNote: "API 價值是以 API 定價完成同樣工作的費用。計劃則以固定價格收費。")
}
