// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchCalendarStrings {
    let title: String
    let description: String
    let permission: String
    let allow: String
    let denied: String
    let settings: String
    let empty: String
    let next: String
    let ongoing: String
    let allDay: String
    let untitled: String
    let openCalendar: String
    let week: String
    let today: String
    let requestFailed: String
    let previousMonth: String
    let nextMonth: String
    let previousWeek: String
    let nextWeek: String
    /// The month grid, offered from the week strip of a short island.
    let month: String
    let emptyDay: String
    let hasEvents: String
    let countdown: String
    let countdownHint: String
    /// Heads the per-calendar checkboxes in Settings.
    let calendars: String
}

extension FeatureStrings {
    static func notchCalendar(_ language: AppLanguage) -> NotchCalendarStrings {
        switch language {
        case .enUS: return NotchCalendarStrings(
            title: "Calendar",
            description: "Browse the month and your upcoming appointments in the Dynamic Island.",
            permission: "Read your calendars to show upcoming appointments. Events stay on this Mac.",
            allow: "Allow Calendar Access",
            denied: "Allow calendar access in System Settings to see your appointments.",
            settings: "Open System Settings",
            empty: "No upcoming appointments",
            next: "Up next",
            ongoing: "Happening now",
            allDay: "All day",
            untitled: "Untitled event",
            openCalendar: "Open Calendar",
            week: "Next 7 days",
            today: "Today",
            requestFailed: "Could not request calendar access. Please try again.",
            previousMonth: "Previous month",
            nextMonth: "Next month",
            previousWeek: "Previous week",
            nextWeek: "Next week",
            month: "Month",
            emptyDay: "No appointments on this day",
            hasEvents: "Has appointments",
            countdown: "Event countdown",
            countdownHint: "Show the next timed event in the closed island during the hour before it starts. Its title may appear in screen captures.",
            calendars: "Calendars shown")
        case .ptBR: return NotchCalendarStrings(
            title: "Calendário",
            description: "Veja o mês e seus próximos compromissos no Dynamic Island.",
            permission: "Leia seus calendários para mostrar os próximos compromissos. Os eventos ficam neste Mac.",
            allow: "Permitir acesso ao calendário",
            denied: "Permita o acesso ao calendário nos Ajustes do Sistema para ver seus compromissos.",
            settings: "Abrir Ajustes do Sistema",
            empty: "Nenhum compromisso por enquanto",
            next: "Próximo compromisso",
            ongoing: "Acontecendo agora",
            allDay: "Dia inteiro",
            untitled: "Evento sem título",
            openCalendar: "Abrir calendário",
            week: "Próximos 7 dias",
            today: "Hoje",
            requestFailed: "Não foi possível pedir acesso ao calendário. Tente novamente.",
            previousMonth: "Mês anterior",
            nextMonth: "Próximo mês",
            previousWeek: "Semana anterior",
            nextWeek: "Próxima semana",
            month: "Mês",
            emptyDay: "Nenhum compromisso neste dia",
            hasEvents: "Tem compromissos",
            countdown: "Contagem para o próximo evento",
            countdownHint: "Mostra o próximo evento com horário no notch durante a hora anterior. O título pode aparecer em capturas de tela.",
            calendars: "Calendários exibidos")
        case .es: return NotchCalendarStrings(
            title: "Calendario",
            description: "Consulta el mes y tus próximas citas en el Dynamic Island.",
            permission: "Lee tus calendarios para mostrar las próximas citas. Los eventos se quedan en este Mac.",
            allow: "Permitir acceso al calendario",
            denied: "Permite el acceso al calendario en Ajustes del Sistema para ver tus citas.",
            settings: "Abrir Ajustes del Sistema",
            empty: "No hay próximas citas",
            next: "A continuación",
            ongoing: "En curso",
            allDay: "Todo el día",
            untitled: "Evento sin título",
            openCalendar: "Abrir Calendario",
            week: "Próximos 7 días",
            today: "Hoy",
            requestFailed: "No se pudo solicitar acceso al calendario. Inténtalo de nuevo.",
            previousMonth: "Mes anterior",
            nextMonth: "Mes siguiente",
            previousWeek: "Semana anterior",
            nextWeek: "Semana siguiente",
            month: "Mes",
            emptyDay: "No hay citas este día",
            hasEvents: "Tiene citas",
            countdown: "Cuenta atrás para el próximo evento",
            countdownHint: "Muestra el próximo evento con hora en el notch durante la hora anterior. El título puede aparecer en capturas de pantalla.",
            calendars: "Calendarios mostrados")
        case .sk: return NotchCalendarStrings(
            title: "Kalendár",
            description: "Prezerajte mesiac a nadchádzajúce stretnutia v Dynamic Island.",
            permission: "Číta vaše kalendáre, aby zobrazil nadchádzajúce stretnutia. Udalosti zostávajú na tomto Macu.",
            allow: "Povoliť prístup ku kalendáru",
            denied: "Ak chcete vidieť svoje stretnutia, povoľte prístup ku kalendáru v Systémových nastaveniach.",
            settings: "Otvoriť Systémové nastavenia",
            empty: "Žiadne nadchádzajúce stretnutia",
            next: "Nasleduje",
            ongoing: "Prebieha teraz",
            allDay: "Celý deň",
            untitled: "Udalosť bez názvu",
            openCalendar: "Otvoriť Kalendár",
            week: "Nasledujúcich 7 dní",
            today: "Dnes",
            requestFailed: "Nepodarilo sa požiadať o prístup ku kalendáru. Skúste to znova.",
            previousMonth: "Predchádzajúci mesiac",
            nextMonth: "Nasledujúci mesiac",
            previousWeek: "Predchádzajúci týždeň",
            nextWeek: "Nasledujúci týždeň",
            month: "Mesiac",
            emptyDay: "V tento deň nemáte žiadne stretnutia",
            hasEvents: "Má stretnutia",
            countdown: "Odpočítavanie do udalosti",
            countdownHint: "Zobrazí ďalšiu udalosť s časom v zatvorenom výreze počas hodiny pred jej začiatkom. Názov sa môže zobraziť na snímkach obrazovky.",
            calendars: "Zobrazené kalendáre")
        case .de: return NotchCalendarStrings(
            title: "Kalender",
            description: "Den Monat und deine nächsten Termine im Dynamic Island ansehen.",
            permission: "Liest deine Kalender, um kommende Termine anzuzeigen. Die Ereignisse bleiben auf diesem Mac.",
            allow: "Kalenderzugriff erlauben",
            denied: "Erlaube den Kalenderzugriff in den Systemeinstellungen, um deine Termine zu sehen.",
            settings: "Systemeinstellungen öffnen",
            empty: "Keine anstehenden Termine",
            next: "Nächster Termin",
            ongoing: "Findet gerade statt",
            allDay: "Ganztägig",
            untitled: "Ereignis ohne Titel",
            openCalendar: "Kalender öffnen",
            week: "Nächste 7 Tage",
            today: "Heute",
            requestFailed: "Der Kalenderzugriff konnte nicht angefordert werden. Versuche es erneut.",
            previousMonth: "Vorheriger Monat",
            nextMonth: "Nächster Monat",
            previousWeek: "Vorherige Woche",
            nextWeek: "Nächste Woche",
            month: "Monat",
            emptyDay: "Keine Termine an diesem Tag",
            hasEvents: "Termine vorhanden",
            countdown: "Countdown zum nächsten Termin",
            countdownHint: "Zeigt den nächsten Termin mit Uhrzeit in der geschlossenen Insel in der Stunde vor Beginn. Der Titel kann in Bildschirmaufnahmen erscheinen.",
            calendars: "Angezeigte Kalender")
        case .fr: return NotchCalendarStrings(
            title: "Calendrier",
            description: "Consultez le mois et vos prochains rendez-vous dans le Dynamic Island.",
            permission: "Lit vos calendriers pour afficher les prochains rendez-vous. Les événements restent sur ce Mac.",
            allow: "Autoriser l’accès au calendrier",
            denied: "Autorisez l’accès au calendrier dans les Réglages Système pour voir vos rendez-vous.",
            settings: "Ouvrir les Réglages Système",
            empty: "Aucun rendez-vous à venir",
            next: "À venir",
            ongoing: "En cours",
            allDay: "Toute la journée",
            untitled: "Événement sans titre",
            openCalendar: "Ouvrir Calendrier",
            week: "7 prochains jours",
            today: "Aujourd’hui",
            requestFailed: "Impossible de demander l’accès au calendrier. Réessayez.",
            previousMonth: "Mois précédent",
            nextMonth: "Mois suivant",
            previousWeek: "Semaine précédente",
            nextWeek: "Semaine suivante",
            month: "Mois",
            emptyDay: "Aucun rendez-vous ce jour-là",
            hasEvents: "Rendez-vous prévus",
            countdown: "Compte à rebours du prochain événement",
            countdownHint: "Affiche le prochain événement avec une heure dans l’encoche pendant l’heure qui précède. Son titre peut apparaître dans les captures d’écran.",
            calendars: "Calendriers affichés")
        case .it: return NotchCalendarStrings(
            title: "Calendario",
            description: "Consulta il mese e i prossimi appuntamenti nel Dynamic Island.",
            permission: "Legge i calendari per mostrare i prossimi appuntamenti. Gli eventi restano su questo Mac.",
            allow: "Consenti accesso al calendario",
            denied: "Consenti l’accesso al calendario in Impostazioni di Sistema per vedere gli appuntamenti.",
            settings: "Apri Impostazioni di Sistema",
            empty: "Nessun appuntamento in programma",
            next: "Prossimo appuntamento",
            ongoing: "In corso",
            allDay: "Tutto il giorno",
            untitled: "Evento senza titolo",
            openCalendar: "Apri Calendario",
            week: "Prossimi 7 giorni",
            today: "Oggi",
            requestFailed: "Impossibile richiedere l’accesso al calendario. Riprova.",
            previousMonth: "Mese precedente",
            nextMonth: "Mese successivo",
            previousWeek: "Settimana precedente",
            nextWeek: "Settimana successiva",
            month: "Mese",
            emptyDay: "Nessun appuntamento in questo giorno",
            hasEvents: "Appuntamenti presenti",
            countdown: "Conto alla rovescia per il prossimo evento",
            countdownHint: "Mostra il prossimo evento con un orario nell’isola chiusa durante l’ora precedente. Il titolo può apparire nelle acquisizioni dello schermo.",
            calendars: "Calendari mostrati")
        case .ru: return NotchCalendarStrings(
            title: "Календарь",
            description: "Просматривайте месяц и ближайшие встречи в вырезе экрана.",
            permission: "Чтение календарей для показа предстоящих встреч. События остаются на этом Mac.",
            allow: "Разрешить доступ к календарю",
            denied: "Разрешите доступ к календарю в Системных настройках, чтобы видеть встречи.",
            settings: "Открыть Системные настройки",
            empty: "Предстоящих встреч нет",
            next: "Следующая встреча",
            ongoing: "Сейчас",
            allDay: "Весь день",
            untitled: "Событие без названия",
            openCalendar: "Открыть Календарь",
            week: "Ближайшие 7 дней",
            today: "Сегодня",
            requestFailed: "Не удалось запросить доступ к календарю. Повторите попытку.",
            previousMonth: "Предыдущий месяц",
            nextMonth: "Следующий месяц",
            previousWeek: "Предыдущая неделя",
            nextWeek: "Следующая неделя",
            month: "Месяц",
            emptyDay: "В этот день встреч нет",
            hasEvents: "Есть встречи",
            countdown: "Отсчёт до следующего события",
            countdownHint: "Показывает следующее событие со временем за час до начала. Название может попасть на снимки экрана.",
            calendars: "Показываемые календари")
        case .tr: return NotchCalendarStrings(
            title: "Takvim",
            description: "Ayı ve yaklaşan randevularınızı çentikte görüntüleyin.",
            permission: "Yaklaşan randevuları göstermek için takvimlerinizi okur. Etkinlikler bu Mac’te kalır.",
            allow: "Takvim Erişimine İzin Ver",
            denied: "Randevularınızı görmek için Sistem Ayarları’nda takvim erişimine izin verin.",
            settings: "Sistem Ayarları’nı Aç",
            empty: "Yaklaşan randevu yok",
            next: "Sıradaki",
            ongoing: "Şu anda",
            allDay: "Tüm gün",
            untitled: "Başlıksız etkinlik",
            openCalendar: "Takvimi Aç",
            week: "Önümüzdeki 7 gün",
            today: "Bugün",
            requestFailed: "Takvim erişimi istenemedi. Tekrar deneyin.",
            previousMonth: "Önceki ay",
            nextMonth: "Sonraki ay",
            previousWeek: "Önceki hafta",
            nextWeek: "Sonraki hafta",
            month: "Ay",
            emptyDay: "Bu gün için randevu yok",
            hasEvents: "Randevu var",
            countdown: "Sonraki etkinliğe geri sayım",
            countdownHint: "Saatli bir sonraki etkinliği başlamadan önceki bir saat boyunca çentikte gösterir. Başlığı ekran görüntülerinde görünebilir.",
            calendars: "Gösterilen takvimler")
        case .ja: return NotchCalendarStrings(
            title: "カレンダー",
            description: "Dynamic Islandで月のカレンダーと今後の予定を確認できます。",
            permission: "カレンダーを読み取り、今後の予定を表示します。予定の情報はこのMacに保持されます。",
            allow: "カレンダーへのアクセスを許可",
            denied: "予定を表示するには、システム設定でカレンダーへのアクセスを許可してください。",
            settings: "システム設定を開く",
            empty: "今後の予定はありません",
            next: "次の予定",
            ongoing: "進行中",
            allDay: "終日",
            untitled: "名称未設定の予定",
            openCalendar: "カレンダーを開く",
            week: "今後7日間",
            today: "今日",
            requestFailed: "カレンダーへのアクセスを要求できませんでした。もう一度お試しください。",
            previousMonth: "前の月",
            nextMonth: "次の月",
            previousWeek: "前の週",
            nextWeek: "次の週",
            month: "月",
            emptyDay: "この日の予定はありません",
            hasEvents: "予定あり",
            countdown: "次の予定までのカウントダウン",
            countdownHint: "開始1時間前から、時刻がある次の予定を閉じたノッチに表示します。タイトルが画面収録やスクリーンショットに映る場合があります。",
            calendars: "表示するカレンダー")
        case .ko: return NotchCalendarStrings(
            title: "캘린더",
            description: "Dynamic Island에서 월별 달력과 다가오는 일정을 확인하세요.",
            permission: "다가오는 일정을 표시하기 위해 캘린더를 읽습니다. 일정은 이 Mac에만 보관됩니다.",
            allow: "캘린더 접근 허용",
            denied: "일정을 보려면 시스템 설정에서 캘린더 접근을 허용하세요.",
            settings: "시스템 설정 열기",
            empty: "예정된 일정 없음",
            next: "다음 일정",
            ongoing: "진행 중",
            allDay: "하루 종일",
            untitled: "제목 없는 일정",
            openCalendar: "캘린더 열기",
            week: "앞으로 7일",
            today: "오늘",
            requestFailed: "캘린더 접근을 요청할 수 없습니다. 다시 시도하세요.",
            previousMonth: "이전 달",
            nextMonth: "다음 달",
            previousWeek: "이전 주",
            nextWeek: "다음 주",
            month: "월",
            emptyDay: "이 날의 일정 없음",
            hasEvents: "일정 있음",
            countdown: "다음 일정 카운트다운",
            countdownHint: "시작 1시간 전부터 시간이 지정된 다음 일정을 닫힌 노치에 표시합니다. 제목이 화면 캡처에 나타날 수 있습니다.",
            calendars: "표시할 캘린더")
        case .zhHans: return NotchCalendarStrings(
            title: "日历",
            description: "在Dynamic Island中浏览月历和即将开始的日程。",
            permission: "读取日历以显示即将开始的日程。日程信息仅保留在此 Mac 上。",
            allow: "允许访问日历",
            denied: "请在系统设置中允许访问日历，以查看日程。",
            settings: "打开系统设置",
            empty: "暂无即将开始的日程",
            next: "下一个日程",
            ongoing: "正在进行",
            allDay: "全天",
            untitled: "无标题日程",
            openCalendar: "打开日历",
            week: "未来 7 天",
            today: "今天",
            requestFailed: "无法请求日历访问权限，请重试。",
            previousMonth: "上个月",
            nextMonth: "下个月",
            previousWeek: "上一周",
            nextWeek: "下一周",
            month: "月",
            emptyDay: "当天没有日程",
            hasEvents: "有日程",
            countdown: "下个日程倒计时",
            countdownHint: "在开始前一小时，于收起的刘海区域显示下个定时日程。标题可能出现在屏幕截图中。",
            calendars: "显示的日历")
        case .zhTW: return NotchCalendarStrings(
            title: "行事曆",
            description: "在Dynamic Island中瀏覽月曆與即將到來的行程。",
            permission: "讀取行事曆以顯示即將到來的行程。行程資訊僅保留在這部 Mac 上。",
            allow: "允許取用行事曆",
            denied: "請在系統設定中允許取用行事曆，以查看行程。",
            settings: "打開系統設定",
            empty: "沒有即將到來的行程",
            next: "下一個行程",
            ongoing: "進行中",
            allDay: "整天",
            untitled: "未命名行程",
            openCalendar: "打開行事曆",
            week: "未來 7 天",
            today: "今天",
            requestFailed: "無法要求行事曆取用權限，請再試一次。",
            previousMonth: "上個月",
            nextMonth: "下個月",
            previousWeek: "上一週",
            nextWeek: "下一週",
            month: "月",
            emptyDay: "當天沒有行程",
            hasEvents: "有行程",
            countdown: "下一個行程倒數",
            countdownHint: "在開始前一小時，於收合的動態島顯示下一個有時間的行程。標題可能出現在螢幕截圖中。",
            calendars: "顯示的行事曆")
        case .zhHK: return NotchCalendarStrings(
            title: "日曆",
            description: "在Dynamic Island中瀏覽月曆及即將到來的行程。",
            permission: "讀取日曆以顯示即將到來的行程。行程資料只保留在此 Mac 上。",
            allow: "允許取用日曆",
            denied: "請在系統設定中允許取用日曆，以查看行程。",
            settings: "開啟系統設定",
            empty: "沒有即將到來的行程",
            next: "下一個行程",
            ongoing: "進行中",
            allDay: "全天",
            untitled: "未命名行程",
            openCalendar: "開啟日曆",
            week: "未來 7 天",
            today: "今天",
            requestFailed: "無法要求日曆取用權限，請重試。",
            previousMonth: "上個月",
            nextMonth: "下個月",
            previousWeek: "上一週",
            nextWeek: "下一週",
            month: "月",
            emptyDay: "當天沒有行程",
            hasEvents: "有行程",
            countdown: "下一個行程倒數",
            countdownHint: "在開始前一小時，於收合的動態島顯示下一個有時間的行程。標題可能出現在螢幕截圖中。",
            calendars: "顯示的日曆")
        case .uk: return NotchCalendarStrings(
            title: "Календар",
            description: "Переглядайте місяць та майбутні події у Dynamic Island.",
            permission: "Читає ваші календарі, щоб показувати майбутні події. Події залишаються на цьому Mac.",
            allow: "Дозволити доступ до календаря",
            denied: "Дозвольте доступ до календаря в Системних параметрах, щоб бачити свої події.",
            settings: "Відкрити Системні параметри",
            empty: "Немає майбутніх подій",
            next: "Далі",
            ongoing: "Зараз триває",
            allDay: "Увесь день",
            untitled: "Подія без назви",
            openCalendar: "Відкрити Календар",
            week: "Наступні 7 днів",
            today: "Сьогодні",
            requestFailed: "Не вдалося запросити доступ до календаря. Спробуйте ще раз.",
            previousMonth: "Попередній місяць",
            nextMonth: "Наступний місяць",
            previousWeek: "Попередній тиждень",
            nextWeek: "Наступний тиждень",
            month: "Місяць",
            emptyDay: "Цього дня немає подій",
            hasEvents: "Є події",
            countdown: "Відлік до наступної події",
            countdownHint: "Показує наступну подію з визначеним часом за годину до початку. Назва може потрапити на знімки екрана.",
            calendars: "Календарі для показу")
        }
    }
}
