// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchEditorStrings {
    let layout: String
    let content: String
    let activity: String
    let behavior: String
    let layoutHint: String
    let addButton: String
    let editButton: String
    let removeButton: String
    let buttonName: String
    let position: String
    let bottom: String
    let sectionActions: String
    let quickActions: String
    let findAction: String
    let reorderHint: String
    let opening: String
    let clickOpen: String
    let hoverPreview: String
    let hoverExpand: String
    let hiddenUntilHover: String
    let resting: String
    let destinations: String
    let separate: String
    let feedback: String
    let privacy: String
    let reopening: String
    let lastPage: String
    let activationTime: String
    let activationTimeHint: String
    let activationTimeFormat: String
    let enableFeatureFormat: String
    let enableSettingFormat: String
    let showPageFormat: String
    let keyboardLightUnavailable: String
    let appPanelHint: String
    let hideMenuBarIcon: String
    let hideMenuBarIconHint: String
    let sections: String
    let sectionsHint: String
    let preview: String
    let hiddenInIsland: String
    let openFeatures: String
    let cameraPreview: String
    let noOptions: String
    let controlsSummary: String
    let mixerSummary: String
    let musicSummary: String
    let clipboardSummary: String
    let capturesSummary: String
    let filesSummary: String
    let systemSummary: String
    let toolsSummary: String
    let calendarSummary: String
    let notificationsSummary: String
    let timerSummary: String
    let cameraSummary: String
    let downloadsSummary: String
    let scratchpadSummary: String
    let agentsSummary: String

    func enableFeature(_ title: String) -> String { String(format: enableFeatureFormat, title) }
    func enableSetting(_ title: String) -> String { String(format: enableSettingFormat, title) }
    func showPage(_ title: String) -> String { String(format: showPageFormat, title) }

    /// One line on what a section of the island shows.
    func summary(_ module: NotchModule) -> String {
        switch module {
        case .controls: return controlsSummary
        case .mixer: return mixerSummary
        case .music: return musicSummary
        case .clipboard: return clipboardSummary
        case .captures: return capturesSummary
        case .files: return filesSummary
        case .system: return systemSummary
        case .tools: return toolsSummary
        case .calendar: return calendarSummary
        case .notifications: return notificationsSummary
        case .timer: return timerSummary
        case .camera: return cameraSummary
        case .downloads: return downloadsSummary
        case .scratchpad: return scratchpadSummary
        case .agents: return agentsSummary
        }
    }
}

extension FeatureStrings {
    static func notchEditor(_ language: AppLanguage) -> NotchEditorStrings {
        switch language {
        case .enUS: return NotchEditorStrings(
            layout: "Layout",
            content: "Content",
            activity: "Activity",
            behavior: "Behavior",
            layoutHint: "Click + to add a button. Drag buttons around the island. Click a button to edit it.",
            addButton: "Add button",
            editButton: "Edit button",
            removeButton: "Remove button",
            buttonName: "Name",
            position: "Position",
            bottom: "Bottom",
            sectionActions: "Open a section",
            quickActions: "Quick actions",
            findAction: "Find an action",
            reorderHint: "Drag to reorder. Click the checkmark to show or hide.",
            opening: "Opening",
            clickOpen: "Click to open",
            hoverPreview: "Preview on hover",
            hoverExpand: "Expand on hover",
            hiddenUntilHover: "Hidden until hover",
            resting: "At rest",
            destinations: "Where things open",
            separate: "Separate window",
            feedback: "Indicators",
            privacy: "Privacy",
            reopening: "When reopening",
            lastPage: "Last page",
            activationTime: "Activation time",
            activationTimeHint: "Keep the pointer over the island for this long to open it.",
            activationTimeFormat: "%.2f s",
            enableFeatureFormat: "Enable “%@” in Features.",
            enableSettingFormat: "Enable “%@” in its settings.",
            showPageFormat: "Show “%@” on the Content tab.",
            keyboardLightUnavailable: "Keyboard backlight control is unavailable on this Mac.",
            appPanelHint: "Choose where clicking the Aster menu bar icon opens the app panel, on any display.",
            hideMenuBarIcon: "Hide the menu bar icon",
            hideMenuBarIconHint: "Settings and the app panel open from Dynamic Island. The icon returns when the island is off or hidden in full screen, or when an update is ready or the microphone is muted.",
            sections: "Sections",
            sectionsHint: "Drag to reorder. Uncheck a section to hide it from the island.",
            preview: "Preview",
            hiddenInIsland: "Hidden from the island",
            openFeatures: "Open Features",
            cameraPreview: "The camera turns on only in the island.",
            noOptions: "This section has no options.",
            controlsSummary: "Playback, volume, brightness and your shortcuts.",
            mixerSummary: "The volume of each app, and where sound plays.",
            musicSummary: "The song playing now, with its controls.",
            clipboardSummary: "What you copied recently, ready to paste again.",
            capturesSummary: "Your latest screenshots and recordings.",
            filesSummary: "A shelf for the files you drop on the island.",
            systemSummary: "CPU, memory, disk, network and battery at a glance.",
            toolsSummary: "Tools and utilities, one click away.",
            calendarSummary: "Today’s events and the month ahead.",
            notificationsSummary: "Your Mac’s notifications, kept in the island.",
            timerSummary: "Timer, Pomodoro and stopwatch.",
            cameraSummary: "A mirror to check yourself before a call.",
            downloadsSummary: "Downloads in progress and just finished.",
            scratchpadSummary: "Quick notes that save by themselves.",
            agentsSummary: "Claude Code and Codex usage, limits and costs."
        )
        case .ptBR: return NotchEditorStrings(
            layout: "Layout",
            content: "Conteúdo",
            activity: "Atividade",
            behavior: "Comportamento",
            layoutHint: "Clique em + para adicionar. Arraste as bolinhas ao redor da ilha. Clique em uma para editar.",
            addButton: "Adicionar bolinha",
            editButton: "Editar bolinha",
            removeButton: "Remover bolinha",
            buttonName: "Nome",
            position: "Posição",
            bottom: "Embaixo",
            sectionActions: "Abrir uma seção",
            quickActions: "Ações rápidas",
            findAction: "Encontrar uma ação",
            reorderHint: "Arraste para reordenar. Clique na marca para mostrar ou ocultar.",
            opening: "Abertura",
            clickOpen: "Abrir por clique",
            hoverPreview: "Prévia ao aproximar",
            hoverExpand: "Expandir ao aproximar",
            hiddenUntilHover: "Ocultar até aproximar",
            resting: "Em repouso",
            destinations: "Onde abrir",
            separate: "Janela separada",
            feedback: "Indicadores",
            privacy: "Privacidade",
            reopening: "Ao reabrir",
            lastPage: "Última página",
            activationTime: "Tempo de ativação",
            activationTimeHint: "Mantenha o ponteiro sobre a ilha por esse tempo para abrir.",
            activationTimeFormat: "%.2f s",
            enableFeatureFormat: "Ative “%@” em Recursos.",
            enableSettingFormat: "Ative “%@” nas configurações do recurso.",
            showPageFormat: "Mostre “%@” na aba Conteúdo.",
            keyboardLightUnavailable: "O controle da luz do teclado não está disponível neste Mac.",
            appPanelHint: "Escolha onde o painel abre ao clicar no ícone do Aster na barra de menus, em qualquer tela.",
            hideMenuBarIcon: "Ocultar o ícone da barra de menus",
            hideMenuBarIconHint: "Os Ajustes e o painel do app abrem pela Dynamic Island. O ícone volta quando a ilha está desligada ou oculta em tela cheia, ou quando há atualização pronta ou microfone silenciado.",
            sections: "Seções",
            sectionsHint: "Arraste para reordenar. Desmarque uma seção para ocultá-la da ilha.",
            preview: "Prévia",
            hiddenInIsland: "Oculta na ilha",
            openFeatures: "Abrir Recursos",
            cameraPreview: "A câmera só liga na própria ilha.",
            noOptions: "Esta seção não tem opções.",
            controlsSummary: "Reprodução, volume, brilho e seus atalhos.",
            mixerSummary: "O volume de cada app e onde o som toca.",
            musicSummary: "A música tocando agora, com os controles.",
            clipboardSummary: "O que você copiou há pouco, pronto para colar de novo.",
            capturesSummary: "Suas capturas de tela e gravações mais recentes.",
            filesSummary: "Uma prateleira para os arquivos que você solta na ilha.",
            systemSummary: "CPU, memória, disco, rede e bateria num relance.",
            toolsSummary: "Ferramentas e utilitários a um clique.",
            calendarSummary: "Os eventos de hoje e o mês inteiro.",
            notificationsSummary: "As notificações do Mac, guardadas na ilha.",
            timerSummary: "Temporizador, Pomodoro e cronômetro.",
            cameraSummary: "Um espelho para se ver antes de uma chamada.",
            downloadsSummary: "Downloads em andamento e os que acabaram de terminar.",
            scratchpadSummary: "Anotações rápidas que se salvam sozinhas.",
            agentsSummary: "Uso, limites e custos do Claude Code e do Codex."
        )
        case .es: return NotchEditorStrings(
            layout: "Diseño",
            content: "Contenido",
            activity: "Actividad",
            behavior: "Comportamiento",
            layoutHint: "Pulsa + para añadir un botón. Arrastra los botones alrededor de la isla. Pulsa uno para editarlo.",
            addButton: "Añadir botón",
            editButton: "Editar botón",
            removeButton: "Eliminar botón",
            buttonName: "Nombre",
            position: "Posición",
            bottom: "Abajo",
            sectionActions: "Abrir una sección",
            quickActions: "Acciones rápidas",
            findAction: "Buscar una acción",
            reorderHint: "Arrastra para ordenar. Pulsa la marca para mostrar u ocultar.",
            opening: "Apertura",
            clickOpen: "Abrir con un clic",
            hoverPreview: "Vista previa al acercarse",
            hoverExpand: "Expandir al acercarse",
            hiddenUntilHover: "Ocultar hasta acercarse",
            resting: "En reposo",
            destinations: "Dónde abrir",
            separate: "Ventana separada",
            feedback: "Indicadores",
            privacy: "Privacidad",
            reopening: "Al reabrir",
            lastPage: "Última página",
            activationTime: "Tiempo de activación",
            activationTimeHint: "Mantén el puntero sobre la isla durante este tiempo para abrirla.",
            activationTimeFormat: "%.2f s",
            enableFeatureFormat: "Activa “%@” en Funciones.",
            enableSettingFormat: "Activa “%@” en sus ajustes.",
            showPageFormat: "Muestra “%@” en la pestaña Contenido.",
            keyboardLightUnavailable: "El control de la luz del teclado no está disponible en este Mac.",
            appPanelHint: "Elige dónde se abre el panel al pulsar el icono de Aster en la barra de menús, en cualquier pantalla.",
            hideMenuBarIcon: "Ocultar el icono de la barra de menús",
            hideMenuBarIconHint: "Los Ajustes y el panel de la app se abren desde Dynamic Island. El icono vuelve cuando la isla está desactivada u oculta en pantalla completa, o cuando hay una actualización lista o el micrófono está silenciado.",
            sections: "Secciones",
            sectionsHint: "Arrastra para ordenar. Desmarca una sección para ocultarla de la isla.",
            preview: "Vista previa",
            hiddenInIsland: "Oculta en la isla",
            openFeatures: "Abrir Funciones",
            cameraPreview: "La cámara solo se enciende en la isla.",
            noOptions: "Esta sección no tiene opciones.",
            controlsSummary: "Reproducción, volumen, brillo y tus atajos.",
            mixerSummary: "El volumen de cada app y dónde suena el audio.",
            musicSummary: "La canción que suena ahora, con sus controles.",
            clipboardSummary: "Lo que copiaste hace poco, listo para pegar otra vez.",
            capturesSummary: "Tus capturas y grabaciones más recientes.",
            filesSummary: "Un estante para los archivos que sueltas en la isla.",
            systemSummary: "CPU, memoria, disco, red y batería de un vistazo.",
            toolsSummary: "Herramientas y utilidades a un clic.",
            calendarSummary: "Los eventos de hoy y el mes completo.",
            notificationsSummary: "Las notificaciones de tu Mac, reunidas en la isla.",
            timerSummary: "Temporizador, Pomodoro y cronómetro.",
            cameraSummary: "Un espejo para verte antes de una llamada.",
            downloadsSummary: "Descargas en curso y las recién terminadas.",
            scratchpadSummary: "Notas rápidas que se guardan solas.",
            agentsSummary: "Uso, límites y costes de Claude Code y Codex."
        )
        case .sk: return NotchEditorStrings(
            layout: "Rozloženie",
            content: "Obsah",
            activity: "Aktivita",
            behavior: "Správanie",
            layoutHint: "Kliknutím na + pridáte tlačidlo. Tlačidlá presúvajte po Dynamic Island. Kliknutím na tlačidlo ho upravíte.",
            addButton: "Pridať tlačidlo",
            editButton: "Upraviť tlačidlo",
            removeButton: "Odstrániť tlačidlo",
            buttonName: "Názov",
            position: "Poloha",
            bottom: "Dole",
            sectionActions: "Otvoriť sekciu",
            quickActions: "Rýchle akcie",
            findAction: "Nájsť akciu",
            reorderHint: "Presunutím zmeníte poradie. Kliknutím na fajku zobrazíte alebo skryjete.",
            opening: "Otváranie",
            clickOpen: "Otvoriť kliknutím",
            hoverPreview: "Náhľad pri prejdení myšou",
            hoverExpand: "Rozbaliť pri prejdení myšou",
            hiddenUntilHover: "Skryté, kým naň neprejdete myšou",
            resting: "V pokoji",
            destinations: "Kde sa veci otvárajú",
            separate: "Samostatné okno",
            feedback: "Indikátory",
            privacy: "Súkromie",
            reopening: "Pri opätovnom otvorení",
            lastPage: "Posledná stránka",
            activationTime: "Čas aktivácie",
            activationTimeHint: "Podržte kurzor nad Dynamic Island takto dlho, aby sa otvoril.",
            activationTimeFormat: "%.2f s",
            enableFeatureFormat: "Zapnite „%@“ vo Funkciách.",
            enableSettingFormat: "Zapnite „%@“ v jeho nastaveniach.",
            showPageFormat: "Zobrazte „%@“ na karte Obsah.",
            keyboardLightUnavailable: "Ovládanie podsvietenia klávesnice nie je na tomto Macu k dispozícii.",
            appPanelHint: "Vyberte, kde sa otvorí panel aplikácie po kliknutí na ikonu Aster v lište, na ktoromkoľvek displeji.",
            hideMenuBarIcon: "Skryť ikonu v lište",
            hideMenuBarIconHint: "Nastavenia a panel aplikácie sa otvárajú z Dynamic Island. Ikona sa vráti, keď je Dynamic Island vypnutý alebo skrytý v režime celej obrazovky, alebo keď je pripravená aktualizácia či stlmený mikrofón.",
            sections: "Sekcie",
            sectionsHint: "Presunutím zmeníte poradie. Zrušením fajky sekciu skryjete z Dynamic Island.",
            preview: "Náhľad",
            hiddenInIsland: "Skryté v Dynamic Island",
            openFeatures: "Otvoriť Funkcie",
            cameraPreview: "Kamera sa zapne len v Dynamic Island.",
            noOptions: "Táto sekcia nemá žiadne možnosti.",
            controlsSummary: "Prehrávanie, hlasitosť, jas a vaše skratky.",
            mixerSummary: "Hlasitosť jednotlivých aplikácií a kam ide zvuk.",
            musicSummary: "Skladba, ktorá práve hrá, aj s ovládaním.",
            clipboardSummary: "Čo ste nedávno skopírovali, pripravené na opätovné vloženie.",
            capturesSummary: "Vaše najnovšie snímky obrazovky a nahrávky.",
            filesSummary: "Polica na súbory, ktoré pustíte na Dynamic Island.",
            systemSummary: "CPU, pamäť, disk, sieť a batéria na jeden pohľad.",
            toolsSummary: "Nástroje a pomôcky na jedno kliknutie.",
            calendarSummary: "Dnešné udalosti a nadchádzajúci mesiac.",
            notificationsSummary: "Hlásenia vášho Macu, zhromaždené v Dynamic Island.",
            timerSummary: "Časovač, Pomodoro a stopky.",
            cameraSummary: "Zrkadlo, v ktorom sa pred hovorom skontrolujete.",
            downloadsSummary: "Prebiehajúce a práve dokončené sťahovania.",
            scratchpadSummary: "Rýchle poznámky, ktoré sa ukladajú samy.",
            agentsSummary: "Využitie, limity a náklady Claude Code a Codexu."
        )
        case .de: return NotchEditorStrings(
            layout: "Layout",
            content: "Inhalt",
            activity: "Aktivität",
            behavior: "Verhalten",
            layoutHint: "Mit + eine Taste hinzufügen. Tasten um die Insel ziehen. Zum Bearbeiten eine Taste anklicken.",
            addButton: "Taste hinzufügen",
            editButton: "Taste bearbeiten",
            removeButton: "Taste entfernen",
            buttonName: "Name",
            position: "Position",
            bottom: "Unten",
            sectionActions: "Bereich öffnen",
            quickActions: "Schnellaktionen",
            findAction: "Aktion finden",
            reorderHint: "Zum Sortieren ziehen. Mit dem Häkchen ein- oder ausblenden.",
            opening: "Öffnen",
            clickOpen: "Per Klick öffnen",
            hoverPreview: "Vorschau bei Annäherung",
            hoverExpand: "Bei Annäherung erweitern",
            hiddenUntilHover: "Bis zur Annäherung ausblenden",
            resting: "Im Ruhezustand",
            destinations: "Öffnungsort",
            separate: "Eigenes Fenster",
            feedback: "Anzeigen",
            privacy: "Datenschutz",
            reopening: "Beim erneuten Öffnen",
            lastPage: "Letzte Seite",
            activationTime: "Aktivierungszeit",
            activationTimeHint: "Halte den Zeiger so lange über der Insel, um sie zu öffnen.",
            activationTimeFormat: "%.2f s",
            enableFeatureFormat: "Aktiviere „%@“ unter Funktionen.",
            enableSettingFormat: "Aktiviere „%@“ in den zugehörigen Einstellungen.",
            showPageFormat: "Blende „%@“ im Tab Inhalt ein.",
            keyboardLightUnavailable: "Die Tastaturbeleuchtung lässt sich auf diesem Mac nicht steuern.",
            appPanelHint: "Wähle, wo ein Klick auf das Aster-Menüleistensymbol das App-Panel öffnet, auf jedem Bildschirm.",
            hideMenuBarIcon: "Menüleistensymbol ausblenden",
            hideMenuBarIconHint: "Einstellungen und das App-Panel öffnen sich über die Dynamic Island. Das Symbol kehrt zurück, wenn Dynamic Island ausgeschaltet oder im Vollbild ausgeblendet ist, oder wenn ein Update bereitsteht oder das Mikrofon stummgeschaltet ist.",
            sections: "Bereiche",
            sectionsHint: "Zum Sortieren ziehen. Entferne das Häkchen, um einen Bereich auf der Insel auszublenden.",
            preview: "Vorschau",
            hiddenInIsland: "Auf der Insel ausgeblendet",
            openFeatures: "Funktionen öffnen",
            cameraPreview: "Die Kamera schaltet sich nur auf der Insel ein.",
            noOptions: "Dieser Bereich hat keine Optionen.",
            controlsSummary: "Wiedergabe, Lautstärke, Helligkeit und deine Kurzbefehle.",
            mixerSummary: "Die Lautstärke jeder App und wo der Ton spielt.",
            musicSummary: "Der aktuelle Titel mit seinen Steuerelementen.",
            clipboardSummary: "Was du zuletzt kopiert hast, bereit zum erneuten Einsetzen.",
            capturesSummary: "Deine neuesten Bildschirmfotos und Aufnahmen.",
            filesSummary: "Eine Ablage für Dateien, die du auf der Insel ablegst.",
            systemSummary: "CPU, Speicher, Festplatte, Netzwerk und Batterie auf einen Blick.",
            toolsSummary: "Werkzeuge und Dienstprogramme, einen Klick entfernt.",
            calendarSummary: "Die Termine von heute und der ganze Monat.",
            notificationsSummary: "Die Mitteilungen deines Mac, gesammelt auf der Insel.",
            timerSummary: "Timer, Pomodoro und Stoppuhr.",
            cameraSummary: "Ein Spiegel, um dich vor einem Anruf zu sehen.",
            downloadsSummary: "Laufende und gerade fertige Downloads.",
            scratchpadSummary: "Schnelle Notizen, die sich selbst sichern.",
            agentsSummary: "Nutzung, Limits und Kosten von Claude Code und Codex."
        )
        case .fr: return NotchEditorStrings(
            layout: "Disposition",
            content: "Contenu",
            activity: "Activité",
            behavior: "Comportement",
            layoutHint: "Cliquez sur + pour ajouter un bouton. Faites glisser les boutons autour de l’îlot. Cliquez pour modifier.",
            addButton: "Ajouter un bouton",
            editButton: "Modifier le bouton",
            removeButton: "Retirer le bouton",
            buttonName: "Nom",
            position: "Position",
            bottom: "En bas",
            sectionActions: "Ouvrir une section",
            quickActions: "Actions rapides",
            findAction: "Rechercher une action",
            reorderHint: "Glissez pour réordonner. Cliquez sur la coche pour afficher ou masquer.",
            opening: "Ouverture",
            clickOpen: "Ouvrir au clic",
            hoverPreview: "Aperçu au survol",
            hoverExpand: "Déployer au survol",
            hiddenUntilHover: "Masquer jusqu’au survol",
            resting: "Au repos",
            destinations: "Lieu d’ouverture",
            separate: "Fenêtre séparée",
            feedback: "Indicateurs",
            privacy: "Confidentialité",
            reopening: "À la réouverture",
            lastPage: "Dernière page",
            activationTime: "Délai d’activation",
            activationTimeHint: "Laissez le pointeur sur l’île pendant cette durée pour l’ouvrir.",
            activationTimeFormat: "%.2f s",
            enableFeatureFormat: "Activez « %@ » dans Fonctionnalités.",
            enableSettingFormat: "Activez « %@ » dans ses réglages.",
            showPageFormat: "Affichez « %@ » dans l’onglet Contenu.",
            keyboardLightUnavailable: "Le contrôle du rétroéclairage du clavier est indisponible sur ce Mac.",
            appPanelHint: "Choisissez où un clic sur l’icône Aster de la barre des menus ouvre le panneau, sur tout écran.",
            hideMenuBarIcon: "Masquer l’icône de la barre des menus",
            hideMenuBarIconHint: "Les Réglages et le panneau de l’app s’ouvrent depuis Dynamic Island. L’icône revient quand Dynamic Island est désactivée ou masquée en plein écran, ou quand une mise à jour est prête ou que le micro est coupé.",
            sections: "Sections",
            sectionsHint: "Glissez pour réordonner. Décochez une section pour la masquer de l’îlot.",
            preview: "Aperçu",
            hiddenInIsland: "Masquée dans l’îlot",
            openFeatures: "Ouvrir Fonctionnalités",
            cameraPreview: "La caméra ne s’allume que dans l’îlot.",
            noOptions: "Cette section n’a pas d’options.",
            controlsSummary: "Lecture, volume, luminosité et vos raccourcis.",
            mixerSummary: "Le volume de chaque app et la sortie du son.",
            musicSummary: "Le morceau en cours, avec ses commandes.",
            clipboardSummary: "Ce que vous avez copié récemment, prêt à être recollé.",
            capturesSummary: "Vos dernières captures d’écran et vidéos.",
            filesSummary: "Une étagère pour les fichiers déposés sur l’îlot.",
            systemSummary: "Processeur, mémoire, disque, réseau et batterie en un coup d’œil.",
            toolsSummary: "Outils et utilitaires à portée de clic.",
            calendarSummary: "Les événements du jour et le mois entier.",
            notificationsSummary: "Les notifications de votre Mac, réunies dans l’îlot.",
            timerSummary: "Minuteur, Pomodoro et chronomètre.",
            cameraSummary: "Un miroir pour vous voir avant un appel.",
            downloadsSummary: "Les téléchargements en cours et ceux qui viennent de finir.",
            scratchpadSummary: "Des notes rapides qui s’enregistrent seules.",
            agentsSummary: "Utilisation, limites et coûts de Claude Code et Codex."
        )
        case .it: return NotchEditorStrings(
            layout: "Layout",
            content: "Contenuto",
            activity: "Attività",
            behavior: "Comportamento",
            layoutHint: "Fai clic su + per aggiungere un pulsante. Trascina i pulsanti intorno all’isola. Fai clic per modificarli.",
            addButton: "Aggiungi pulsante",
            editButton: "Modifica pulsante",
            removeButton: "Rimuovi pulsante",
            buttonName: "Nome",
            position: "Posizione",
            bottom: "In basso",
            sectionActions: "Apri una sezione",
            quickActions: "Azioni rapide",
            findAction: "Trova un’azione",
            reorderHint: "Trascina per riordinare. Fai clic sulla spunta per mostrare o nascondere.",
            opening: "Apertura",
            clickOpen: "Apri con un clic",
            hoverPreview: "Anteprima al passaggio",
            hoverExpand: "Espandi al passaggio",
            hiddenUntilHover: "Nascondi fino al passaggio",
            resting: "A riposo",
            destinations: "Dove aprire",
            separate: "Finestra separata",
            feedback: "Indicatori",
            privacy: "Privacy",
            reopening: "Alla riapertura",
            lastPage: "Ultima pagina",
            activationTime: "Tempo di attivazione",
            activationTimeHint: "Mantieni il puntatore sull’isola per questo tempo per aprirla.",
            activationTimeFormat: "%.2f s",
            enableFeatureFormat: "Attiva “%@” in Funzioni.",
            enableSettingFormat: "Attiva “%@” nelle relative impostazioni.",
            showPageFormat: "Mostra “%@” nella scheda Contenuto.",
            keyboardLightUnavailable: "Il controllo della retroilluminazione della tastiera non è disponibile su questo Mac.",
            appPanelHint: "Scegli dove si apre il pannello facendo clic sull’icona di Aster nella barra dei menu, su qualsiasi schermo.",
            hideMenuBarIcon: "Nascondi l’icona nella barra dei menu",
            hideMenuBarIconHint: "Le Impostazioni e il pannello dell’app si aprono da Dynamic Island. L’icona torna quando Dynamic Island è disattivata o nascosta a schermo intero, oppure quando è pronto un aggiornamento o il microfono è silenziato.",
            sections: "Sezioni",
            sectionsHint: "Trascina per riordinare. Deseleziona una sezione per nasconderla dall’isola.",
            preview: "Anteprima",
            hiddenInIsland: "Nascosta nell’isola",
            openFeatures: "Apri Funzioni",
            cameraPreview: "La fotocamera si accende solo nell’isola.",
            noOptions: "Questa sezione non ha opzioni.",
            controlsSummary: "Riproduzione, volume, luminosità e le tue scorciatoie.",
            mixerSummary: "Il volume di ogni app e dove suona l’audio.",
            musicSummary: "Il brano in riproduzione, con i suoi controlli.",
            clipboardSummary: "Ciò che hai copiato di recente, pronto da incollare di nuovo.",
            capturesSummary: "Le tue ultime istantanee e registrazioni.",
            filesSummary: "Uno scaffale per i file che trascini sull’isola.",
            systemSummary: "CPU, memoria, disco, rete e batteria a colpo d’occhio.",
            toolsSummary: "Strumenti e utility a portata di clic.",
            calendarSummary: "Gli eventi di oggi e il mese intero.",
            notificationsSummary: "Le notifiche del Mac, raccolte nell’isola.",
            timerSummary: "Timer, Pomodoro e cronometro.",
            cameraSummary: "Uno specchio per guardarti prima di una chiamata.",
            downloadsSummary: "Download in corso e appena completati.",
            scratchpadSummary: "Note veloci che si salvano da sole.",
            agentsSummary: "Uso, limiti e costi di Claude Code e Codex."
        )
        case .ru: return NotchEditorStrings(
            layout: "Макет",
            content: "Содержимое",
            activity: "Активность",
            behavior: "Поведение",
            layoutHint: "Нажмите +, чтобы добавить кнопку. Перетаскивайте кнопки вокруг острова. Нажмите для изменения.",
            addButton: "Добавить кнопку",
            editButton: "Изменить кнопку",
            removeButton: "Удалить кнопку",
            buttonName: "Название",
            position: "Расположение",
            bottom: "Снизу",
            sectionActions: "Открыть раздел",
            quickActions: "Быстрые действия",
            findAction: "Найти действие",
            reorderHint: "Перетащите для сортировки. Нажмите галочку, чтобы показать или скрыть.",
            opening: "Открытие",
            clickOpen: "По щелчку",
            hoverPreview: "Просмотр при наведении",
            hoverExpand: "Развернуть при наведении",
            hiddenUntilHover: "Скрывать до наведения",
            resting: "В покое",
            destinations: "Где открывать",
            separate: "Отдельное окно",
            feedback: "Индикаторы",
            privacy: "Конфиденциальность",
            reopening: "При повторном открытии",
            lastPage: "Последняя страница",
            activationTime: "Время активации",
            activationTimeHint: "Удерживайте указатель над островом в течение этого времени, чтобы открыть его.",
            activationTimeFormat: "%.2f с",
            enableFeatureFormat: "Включите «%@» в разделе функций.",
            enableSettingFormat: "Включите «%@» в соответствующих настройках.",
            showPageFormat: "Покажите «%@» на вкладке содержимого.",
            keyboardLightUnavailable: "Управление подсветкой клавиатуры недоступно на этом Mac.",
            appPanelHint: "Выберите, где открывать панель при нажатии значка Aster в строке меню на любом экране.",
            hideMenuBarIcon: "Скрывать значок в строке меню",
            hideMenuBarIconHint: "Настройки и панель приложения открываются из Dynamic Island. Значок возвращается, когда Dynamic Island выключена или скрыта в полноэкранном режиме, а также когда готово обновление или выключен микрофон.",
            sections: "Разделы",
            sectionsHint: "Перетащите для сортировки. Снимите флажок, чтобы скрыть раздел с острова.",
            preview: "Предпросмотр",
            hiddenInIsland: "Скрыт на острове",
            openFeatures: "Открыть функции",
            cameraPreview: "Камера включается только на самом острове.",
            noOptions: "У этого раздела нет настроек.",
            controlsSummary: "Воспроизведение, громкость, яркость и ваши быстрые действия.",
            mixerSummary: "Громкость каждого приложения и вывод звука.",
            musicSummary: "Текущий трек и управление им.",
            clipboardSummary: "Недавно скопированное, готовое к повторной вставке.",
            capturesSummary: "Ваши последние снимки экрана и записи.",
            filesSummary: "Полка для файлов, которые вы бросаете на остров.",
            systemSummary: "Процессор, память, диск, сеть и батарея одним взглядом.",
            toolsSummary: "Инструменты и утилиты в один клик.",
            calendarSummary: "События на сегодня и весь месяц.",
            notificationsSummary: "Уведомления Mac, собранные на острове.",
            timerSummary: "Таймер, помидоро и секундомер.",
            cameraSummary: "Зеркало, чтобы посмотреть на себя перед звонком.",
            downloadsSummary: "Текущие и только что завершённые загрузки.",
            scratchpadSummary: "Быстрые заметки, которые сохраняются сами.",
            agentsSummary: "Использование, лимиты и стоимость Claude Code и Codex."
        )
        case .tr: return NotchEditorStrings(
            layout: "Yerleşim",
            content: "İçerik",
            activity: "Etkinlik",
            behavior: "Davranış",
            layoutHint: "Düğme eklemek için + işaretine tıklayın. Düğmeleri adanın çevresine sürükleyin. Düzenlemek için tıklayın.",
            addButton: "Düğme ekle",
            editButton: "Düğmeyi düzenle",
            removeButton: "Düğmeyi kaldır",
            buttonName: "Ad",
            position: "Konum",
            bottom: "Alt",
            sectionActions: "Bölüm aç",
            quickActions: "Hızlı eylemler",
            findAction: "Eylem bul",
            reorderHint: "Sıralamak için sürükleyin. Göstermek veya gizlemek için onay işaretine tıklayın.",
            opening: "Açılış",
            clickOpen: "Tıklayarak aç",
            hoverPreview: "Üzerine gelince önizle",
            hoverExpand: "Üzerine gelince genişlet",
            hiddenUntilHover: "Üzerine gelene kadar gizle",
            resting: "Beklerken",
            destinations: "Açılacak yer",
            separate: "Ayrı pencere",
            feedback: "Göstergeler",
            privacy: "Gizlilik",
            reopening: "Yeniden açıldığında",
            lastPage: "Son sayfa",
            activationTime: "Etkinleştirme süresi",
            activationTimeHint: "Açmak için imleci bu süre boyunca adanın üzerinde tutun.",
            activationTimeFormat: "%.2f sn",
            enableFeatureFormat: "Özellikler’de “%@” özelliğini etkinleştirin.",
            enableSettingFormat: "İlgili ayarlarda “%@” seçeneğini etkinleştirin.",
            showPageFormat: "İçerik sekmesinde “%@” sayfasını gösterin.",
            keyboardLightUnavailable: "Bu Mac’te klavye aydınlatması denetimi kullanılamıyor.",
            appPanelHint: "Herhangi bir ekranda menü çubuğundaki Aster simgesine tıklanınca panelin nerede açılacağını seçin.",
            hideMenuBarIcon: "Menü çubuğu simgesini gizle",
            hideMenuBarIconHint: "Ayarlar ve uygulama paneli Dynamic Island’dan açılır. Dynamic Island kapatıldığında veya tam ekranda gizlendiğinde ya da bir güncelleme hazır olduğunda veya mikrofon sessize alındığında simge geri döner.",
            sections: "Bölümler",
            sectionsHint: "Sıralamak için sürükleyin. Bir bölümü adada gizlemek için işaretini kaldırın.",
            preview: "Önizleme",
            hiddenInIsland: "Adada gizli",
            openFeatures: "Özellikler’i aç",
            cameraPreview: "Kamera yalnızca adanın içinde açılır.",
            noOptions: "Bu bölümün seçeneği yok.",
            controlsSummary: "Oynatma, ses, parlaklık ve kısayollarınız.",
            mixerSummary: "Her uygulamanın ses düzeyi ve sesin çaldığı yer.",
            musicSummary: "Şu an çalan şarkı ve denetimleri.",
            clipboardSummary: "Son kopyaladıklarınız, yeniden yapıştırmaya hazır.",
            capturesSummary: "En son ekran görüntüleriniz ve kayıtlarınız.",
            filesSummary: "Adaya bıraktığınız dosyalar için bir raf.",
            systemSummary: "İşlemci, bellek, disk, ağ ve pil tek bakışta.",
            toolsSummary: "Araçlar ve yardımcılar bir tık uzakta.",
            calendarSummary: "Bugünün etkinlikleri ve ayın tamamı.",
            notificationsSummary: "Mac’inizin bildirimleri, adada bir arada.",
            timerSummary: "Zamanlayıcı, Pomodoro ve kronometre.",
            cameraSummary: "Aramadan önce kendinize bakmak için bir ayna.",
            downloadsSummary: "Süren ve yeni biten indirmeler.",
            scratchpadSummary: "Kendi kendine kaydedilen hızlı notlar.",
            agentsSummary: "Claude Code ve Codex kullanımı, sınırları ve maliyetleri."
        )
        case .ja: return NotchEditorStrings(
            layout: "レイアウト",
            content: "コンテンツ",
            activity: "アクティビティ",
            behavior: "動作",
            layoutHint: "＋でボタンを追加します。島の周りにドラッグして移動し、クリックして編集します。",
            addButton: "ボタンを追加",
            editButton: "ボタンを編集",
            removeButton: "ボタンを削除",
            buttonName: "名前",
            position: "位置",
            bottom: "下",
            sectionActions: "セクションを開く",
            quickActions: "クイックアクション",
            findAction: "アクションを検索",
            reorderHint: "ドラッグして並べ替え、チェックマークで表示を切り替えます。",
            opening: "開き方",
            clickOpen: "クリックで開く",
            hoverPreview: "ポイントでプレビュー",
            hoverExpand: "ポイントで展開",
            hiddenUntilHover: "ポイントするまで非表示",
            resting: "待機中",
            destinations: "開く場所",
            separate: "別のウインドウ",
            feedback: "インジケータ",
            privacy: "プライバシー",
            reopening: "開き直したとき",
            lastPage: "前回のページ",
            activationTime: "開くまでの時間",
            activationTimeHint: "島の上にポインタをこの時間置くと開きます。",
            activationTimeFormat: "%.2f 秒",
            enableFeatureFormat: "機能で「%@」を有効にしてください。",
            enableSettingFormat: "該当する設定で「%@」を有効にしてください。",
            showPageFormat: "コンテンツタブで「%@」を表示してください。",
            keyboardLightUnavailable: "このMacではキーボードのバックライトを制御できません。",
            appPanelHint: "どの画面でも、メニューバーのAsterアイコンをクリックしたときにパネルを開く場所を選択します。",
            hideMenuBarIcon: "メニューバーのアイコンを隠す",
            hideMenuBarIconHint: "設定とアプリのパネルはDynamic Islandから開けます。Dynamic Islandがオフかフルスクリーンで非表示のとき、またはアップデートの準備ができたときやマイクを消音したときは、アイコンが戻ります。",
            sections: "セクション",
            sectionsHint: "ドラッグして並べ替えます。チェックを外したセクションは島に表示されません。",
            preview: "プレビュー",
            hiddenInIsland: "島に非表示",
            openFeatures: "機能を開く",
            cameraPreview: "カメラは島の中でのみオンになります。",
            noOptions: "このセクションには設定項目がありません。",
            controlsSummary: "再生、音量、明るさ、ショートカット。",
            mixerSummary: "アプリごとの音量と出力先。",
            musicSummary: "再生中の曲とそのコントロール。",
            clipboardSummary: "最近コピーした内容をもう一度ペースト。",
            capturesSummary: "最新のスクリーンショットと収録。",
            filesSummary: "島にドロップしたファイルを置いておく棚。",
            systemSummary: "CPU、メモリ、ディスク、ネットワーク、バッテリーをひと目で。",
            toolsSummary: "ツールとユーティリティをワンクリックで。",
            calendarSummary: "今日の予定と1か月の予定。",
            notificationsSummary: "Macの通知を島にまとめて表示。",
            timerSummary: "タイマー、ポモドーロ、ストップウォッチ。",
            cameraSummary: "通話前に身だしなみを確認できるミラー。",
            downloadsSummary: "進行中と完了したばかりのダウンロード。",
            scratchpadSummary: "自動で保存されるクイックメモ。",
            agentsSummary: "Claude CodeとCodexの使用量、上限、コスト。"
        )
        case .ko: return NotchEditorStrings(
            layout: "레이아웃",
            content: "콘텐츠",
            activity: "활동",
            behavior: "동작",
            layoutHint: "+를 눌러 버튼을 추가하세요. 섬 주변으로 드래그하여 옮기고 클릭하여 편집하세요.",
            addButton: "버튼 추가",
            editButton: "버튼 편집",
            removeButton: "버튼 제거",
            buttonName: "이름",
            position: "위치",
            bottom: "아래",
            sectionActions: "섹션 열기",
            quickActions: "빠른 동작",
            findAction: "동작 찾기",
            reorderHint: "드래그하여 순서를 바꾸고 체크 표시로 표시 여부를 바꾸세요.",
            opening: "열기",
            clickOpen: "클릭하여 열기",
            hoverPreview: "포인터로 미리보기",
            hoverExpand: "포인터로 펼치기",
            hiddenUntilHover: "포인터를 올릴 때만 표시",
            resting: "대기 중",
            destinations: "열리는 위치",
            separate: "별도 윈도우",
            feedback: "표시기",
            privacy: "개인정보 보호",
            reopening: "다시 열 때",
            lastPage: "마지막 페이지",
            activationTime: "활성화 시간",
            activationTimeHint: "이 시간 동안 섬 위에 포인터를 두면 열립니다.",
            activationTimeFormat: "%.2f초",
            enableFeatureFormat: "기능에서 “%@”을(를) 활성화하세요.",
            enableSettingFormat: "해당 설정에서 “%@”을(를) 활성화하세요.",
            showPageFormat: "콘텐츠 탭에서 “%@”을(를) 표시하세요.",
            keyboardLightUnavailable: "이 Mac에서는 키보드 백라이트를 제어할 수 없습니다.",
            appPanelHint: "어느 화면에서든 메뉴 막대의 Aster 아이콘을 클릭할 때 패널이 열릴 위치를 선택하세요.",
            hideMenuBarIcon: "메뉴 막대 아이콘 숨기기",
            hideMenuBarIconHint: "설정과 앱 패널은 Dynamic Island에서 열 수 있습니다. Dynamic Island를 끄거나 전체 화면에서 숨기거나, 업데이트가 준비되거나 마이크를 음소거하면 아이콘이 다시 나타납니다.",
            sections: "섹션",
            sectionsHint: "드래그하여 순서를 바꾸세요. 체크를 해제하면 섬에서 숨겨집니다.",
            preview: "미리보기",
            hiddenInIsland: "섬에서 숨김",
            openFeatures: "기능 열기",
            cameraPreview: "카메라는 섬 안에서만 켜집니다.",
            noOptions: "이 섹션에는 옵션이 없습니다.",
            controlsSummary: "재생, 음량, 밝기와 단축키.",
            mixerSummary: "앱별 음량과 소리가 나오는 곳.",
            musicSummary: "지금 재생 중인 곡과 컨트롤.",
            clipboardSummary: "최근에 복사한 항목을 다시 붙여넣기.",
            capturesSummary: "최근 스크린샷과 녹화.",
            filesSummary: "섬에 놓은 파일을 두는 선반.",
            systemSummary: "CPU, 메모리, 디스크, 네트워크, 배터리를 한눈에.",
            toolsSummary: "도구와 유틸리티를 클릭 한 번으로.",
            calendarSummary: "오늘의 일정과 한 달 전체.",
            notificationsSummary: "Mac의 알림을 섬에 모아 보기.",
            timerSummary: "타이머, 뽀모도로, 스톱워치.",
            cameraSummary: "통화 전에 모습을 확인하는 거울.",
            downloadsSummary: "진행 중이거나 방금 끝난 다운로드.",
            scratchpadSummary: "저절로 저장되는 빠른 메모.",
            agentsSummary: "Claude Code와 Codex의 사용량, 한도, 비용."
        )
        case .zhHans: return NotchEditorStrings(
            layout: "布局",
            content: "内容",
            activity: "活动",
            behavior: "行为",
            layoutHint: "点击 + 添加按钮。将按钮拖到岛的周围，点击按钮进行编辑。",
            addButton: "添加按钮",
            editButton: "编辑按钮",
            removeButton: "移除按钮",
            buttonName: "名称",
            position: "位置",
            bottom: "底部",
            sectionActions: "打开分区",
            quickActions: "快捷操作",
            findAction: "查找操作",
            reorderHint: "拖动以排序。点击勾选标记来显示或隐藏。",
            opening: "打开方式",
            clickOpen: "点击打开",
            hoverPreview: "悬停时预览",
            hoverExpand: "悬停时展开",
            hiddenUntilHover: "悬停时才显示",
            resting: "空闲时",
            destinations: "打开位置",
            separate: "单独窗口",
            feedback: "提示",
            privacy: "隐私",
            reopening: "重新打开时",
            lastPage: "上次的页面",
            activationTime: "激活时间",
            activationTimeHint: "将指针在岛上停留此时长即可打开。",
            activationTimeFormat: "%.2f 秒",
            enableFeatureFormat: "在功能中启用“%@”。",
            enableSettingFormat: "在相应设置中启用“%@”。",
            showPageFormat: "在内容标签页中显示“%@”。",
            keyboardLightUnavailable: "此 Mac 无法控制键盘背光。",
            appPanelHint: "选择在任意显示器上点击菜单栏的 Aster 图标时打开面板的位置。",
            hideMenuBarIcon: "隐藏菜单栏图标",
            hideMenuBarIconHint: "设置和应用面板可从 Dynamic Island 打开。关闭 Dynamic Island、在全屏模式下隐藏它，或有更新就绪或麦克风静音时，图标会自动回来。",
            sections: "分区",
            sectionsHint: "拖动以排序。取消勾选某个分区即可在岛上隐藏它。",
            preview: "预览",
            hiddenInIsland: "已在岛上隐藏",
            openFeatures: "打开功能",
            cameraPreview: "摄像头只会在岛内开启。",
            noOptions: "此分区没有可设置的选项。",
            controlsSummary: "播放、音量、亮度和你的快捷操作。",
            mixerSummary: "每个应用的音量，以及声音从哪里播放。",
            musicSummary: "正在播放的歌曲及其控制。",
            clipboardSummary: "最近复制的内容，随时再次粘贴。",
            capturesSummary: "最近的截图和录屏。",
            filesSummary: "存放拖到岛上的文件的架子。",
            systemSummary: "CPU、内存、磁盘、网络和电池一目了然。",
            toolsSummary: "工具和实用程序，一键即达。",
            calendarSummary: "今天的日程和整个月。",
            notificationsSummary: "Mac 的通知，汇集在岛上。",
            timerSummary: "计时器、番茄钟和秒表。",
            cameraSummary: "通话前照一照的镜子。",
            downloadsSummary: "进行中和刚完成的下载。",
            scratchpadSummary: "自动保存的快速笔记。",
            agentsSummary: "Claude Code 和 Codex 的用量、限额和费用。"
        )
        case .zhTW: return NotchEditorStrings(
            layout: "佈局",
            content: "內容",
            activity: "活動",
            behavior: "行為",
            layoutHint: "按一下 + 新增按鈕。將按鈕拖到島的周圍，按一下按鈕即可編輯。",
            addButton: "新增按鈕",
            editButton: "編輯按鈕",
            removeButton: "移除按鈕",
            buttonName: "名稱",
            position: "位置",
            bottom: "下方",
            sectionActions: "開啟區域",
            quickActions: "快速操作",
            findAction: "尋找操作",
            reorderHint: "拖移以排序。按一下勾選標記來顯示或隱藏。",
            opening: "開啟方式",
            clickOpen: "按一下開啟",
            hoverPreview: "停留時預覽",
            hoverExpand: "停留時展開",
            hiddenUntilHover: "停留時才顯示",
            resting: "閒置時",
            destinations: "開啟位置",
            separate: "獨立視窗",
            feedback: "提示",
            privacy: "隱私",
            reopening: "重新開啟時",
            lastPage: "上次的頁面",
            activationTime: "啟用時間",
            activationTimeHint: "將指標停留在島上達此時間即可開啟。",
            activationTimeFormat: "%.2f 秒",
            enableFeatureFormat: "在功能中啟用「%@」。",
            enableSettingFormat: "在對應設定中啟用「%@」。",
            showPageFormat: "在內容標籤頁中顯示「%@」。",
            keyboardLightUnavailable: "此 Mac 無法控制鍵盤背光。",
            appPanelHint: "選擇在任何螢幕上按一下選單列的 Aster 圖像時開啟面板的位置。",
            hideMenuBarIcon: "隱藏選單列圖示",
            hideMenuBarIconHint: "設定和 App 面板可從 Dynamic Island 開啟。關閉 Dynamic Island、在全螢幕模式下隱藏它，或有更新就緒或麥克風靜音時，圖示會自動回來。",
            sections: "區域",
            sectionsHint: "拖移以排序。取消勾選某個區域即可在島上隱藏它。",
            preview: "預覽",
            hiddenInIsland: "已在島上隱藏",
            openFeatures: "開啟功能",
            cameraPreview: "相機只會在島內開啟。",
            noOptions: "此區域沒有可設定的選項。",
            controlsSummary: "播放、音量、亮度和你的快捷操作。",
            mixerSummary: "每個 App 的音量，以及聲音從哪裡播放。",
            musicSummary: "正在播放的歌曲及其控制項。",
            clipboardSummary: "最近拷貝的內容，隨時再次貼上。",
            capturesSummary: "最近的截圖和錄影。",
            filesSummary: "存放拖到島上檔案的架子。",
            systemSummary: "CPU、記憶體、磁碟、網路和電池一目了然。",
            toolsSummary: "工具和工具程式，一按即達。",
            calendarSummary: "今天的行程和整個月份。",
            notificationsSummary: "Mac 的通知，集中在島上。",
            timerSummary: "計時器、番茄鐘和碼錶。",
            cameraSummary: "通話前照一照的鏡子。",
            downloadsSummary: "進行中和剛完成的下載。",
            scratchpadSummary: "自動儲存的快速筆記。",
            agentsSummary: "Claude Code 和 Codex 的用量、限額和費用。"
        )
        case .zhHK: return NotchEditorStrings(
            layout: "佈局",
            content: "內容",
            activity: "活動",
            behavior: "行為",
            layoutHint: "按一下 + 新增按鈕。將按鈕拖到島的周圍，按一下按鈕即可編輯。",
            addButton: "新增按鈕",
            editButton: "編輯按鈕",
            removeButton: "移除按鈕",
            buttonName: "名稱",
            position: "位置",
            bottom: "下方",
            sectionActions: "開啟區域",
            quickActions: "快速操作",
            findAction: "尋找操作",
            reorderHint: "拖移以排序。按一下勾選標記來顯示或隱藏。",
            opening: "開啟方式",
            clickOpen: "按一下開啟",
            hoverPreview: "停留時預覽",
            hoverExpand: "停留時展開",
            hiddenUntilHover: "停留時才顯示",
            resting: "閒置時",
            destinations: "開啟位置",
            separate: "獨立視窗",
            feedback: "提示",
            privacy: "私隱",
            reopening: "重新開啟時",
            lastPage: "上次的頁面",
            activationTime: "啟用時間",
            activationTimeHint: "將指標停留在島上達此時間即可開啟。",
            activationTimeFormat: "%.2f 秒",
            enableFeatureFormat: "在功能中啟用「%@」。",
            enableSettingFormat: "在相應設定中啟用「%@」。",
            showPageFormat: "在內容標籤頁中顯示「%@」。",
            keyboardLightUnavailable: "此 Mac 無法控制鍵盤背光。",
            appPanelHint: "選擇在任何螢幕上按一下選單列的 Aster 圖像時開啟面板的位置。",
            hideMenuBarIcon: "隱藏選單列圖示",
            hideMenuBarIconHint: "設定和 App 面板可從 Dynamic Island 開啟。關閉 Dynamic Island、在全螢幕模式下隱藏它，或有更新就緒或麥克風靜音時，圖示會自動回來。",
            sections: "區域",
            sectionsHint: "拖移以排序。取消勾選某個區域即可在島上隱藏它。",
            preview: "預覽",
            hiddenInIsland: "已在島上隱藏",
            openFeatures: "開啟功能",
            cameraPreview: "相機只會在島內開啟。",
            noOptions: "此區域沒有可設定的選項。",
            controlsSummary: "播放、音量、亮度和你的快捷操作。",
            mixerSummary: "每個 App 的音量，以及聲音從哪裡播放。",
            musicSummary: "正在播放的歌曲及其控制項。",
            clipboardSummary: "最近拷貝的內容，隨時再次貼上。",
            capturesSummary: "最近的截圖和錄影。",
            filesSummary: "存放拖到島上檔案的架子。",
            systemSummary: "CPU、記憶體、磁碟、網路和電池一目了然。",
            toolsSummary: "工具和工具程式，一按即達。",
            calendarSummary: "今天的行程和整個月份。",
            notificationsSummary: "Mac 的通知，集中在島上。",
            timerSummary: "計時器、番茄鐘和碼錶。",
            cameraSummary: "通話前照一照的鏡子。",
            downloadsSummary: "進行中和剛完成的下載。",
            scratchpadSummary: "自動儲存的快速筆記。",
            agentsSummary: "Claude Code 和 Codex 的用量、限額和費用。"
        )
        case .uk: return NotchEditorStrings(
            layout: "Розкладка",
            content: "Вміст",
            activity: "Активність",
            behavior: "Поведінка",
            layoutHint: "Натисніть +, щоб додати кнопку. Перетягуйте кнопки навколо острівця. Натисніть кнопку, щоб редагувати її.",
            addButton: "Додати кнопку",
            editButton: "Редагувати кнопку",
            removeButton: "Видалити кнопку",
            buttonName: "Назва",
            position: "Позиція",
            bottom: "Унизу",
            sectionActions: "Відкрити розділ",
            quickActions: "Швидкі дії",
            findAction: "Знайти дію",
            reorderHint: "Перетягуйте, щоб змінити порядок. Натисніть галочку, щоб показати або сховати.",
            opening: "Відкриття",
            clickOpen: "Відкривати клацанням",
            hoverPreview: "Перегляд при наведенні",
            hoverExpand: "Розгортати при наведенні",
            hiddenUntilHover: "Приховано до наведення",
            resting: "У стані спокою",
            destinations: "Де відкривається",
            separate: "Окреме вікно",
            feedback: "Індикатори",
            privacy: "Приватність",
            reopening: "При повторному відкритті",
            lastPage: "Остання сторінка",
            activationTime: "Час активації",
            activationTimeHint: "Тримайте вказівник над острівцем стільки часу, щоб відкрити його.",
            activationTimeFormat: "%.2f с",
            enableFeatureFormat: "Увімкніть «%@» у Функціях.",
            enableSettingFormat: "Увімкніть «%@» у налаштуваннях функції.",
            showPageFormat: "Покажіть «%@» на вкладці Вміст.",
            keyboardLightUnavailable: "Керування підсвічуванням клавіатури недоступне на цьому Mac.",
            appPanelHint: "Виберіть, де на будь-якому дисплеї відкриватиметься панель програми після натискання значка Aster на смузі меню.",
            hideMenuBarIcon: "Ховати значок на смузі меню",
            hideMenuBarIconHint: "Налаштування й панель програми відкриваються з Dynamic Island. Значок повертається, коли Dynamic Island вимкнено або приховано в повноекранному режимі, а також коли готове оновлення чи вимкнено мікрофон.",
            sections: "Розділи",
            sectionsHint: "Перетягуйте, щоб змінити порядок. Зніміть позначку з розділу, щоб сховати його з острівця.",
            preview: "Попередній перегляд",
            hiddenInIsland: "Приховано з острівця",
            openFeatures: "Відкрити Функції",
            cameraPreview: "Камера вмикається лише в острівці.",
            noOptions: "Цей розділ не має налаштувань.",
            controlsSummary: "Відтворення, гучність, яскравість і ваші швидкі дії.",
            mixerSummary: "Гучність кожної програми та пристрій відтворення звуку.",
            musicSummary: "Поточна пісня та елементи керування нею.",
            clipboardSummary: "Нещодавно скопійоване, готове до повторного вставлення.",
            capturesSummary: "Останні знімки та записи екрана.",
            filesSummary: "Полиця для файлів, які ви перетягуєте на острівець.",
            systemSummary: "CPU, пам’ять, диски, мережа й акумулятор з першого погляду.",
            toolsSummary: "Інструменти й утиліти в один клік.",
            calendarSummary: "Сьогоднішні події та майбутній місяць.",
            notificationsSummary: "Сповіщення Mac, зібрані в острівці.",
            timerSummary: "Таймер, Pomodoro й секундомір.",
            cameraSummary: "Дзеркало, щоб перевірити себе перед викликом.",
            downloadsSummary: "Завантаження, що тривають або щойно завершилися.",
            scratchpadSummary: "Швидкі нотатки, що зберігаються автоматично.",
            agentsSummary: "Використання Claude Code і Codex, ліміти й витрати."
        )
        }
    }
}
