// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Localized strings for the scratchpad, the floating pad for short-lived text.
struct ScratchpadFeatureStrings {
    let pageTitle: String
    let hubDescription: String
    let panelCaption: String
    let openButton: String
    let placeholder: String
    let copyAll: String
    let copied: String
    let exportAction: String
    let exportFailed: String
    let loadFailed: String
    let saveFailed: String
    let clearAction: String
    let retentionTitle: String
    let retentionNever: String
    let retentionDay: String
    let retentionWeek: String
    let retentionMonth: String
    let retentionCaption: String
    let closeOnClickOutside: String
    let keepOpen: String
    let backgroundOpacity: String
    let backgroundTranslucent: String
    let backgroundOpaque: String
    let newPad: String
    let padActions: String
    let renamePad: String
    let closePad: String
    let saveName: String
    let cancel: String
    let deletePadMessageFormat: String
    let padLimitFormat: String
    let previewFormatting: String
    let editText: String
    let markBold: String
    let markItalic: String
    let markStrikethrough: String
    let markHeading: String
    let markBullet: String
    let markNumbered: String
    let markQuote: String
    let markCode: String
    let markLink: String
    let formatMarks: String
    let textSize: String
}

extension FeatureStrings {
    static func scratchpad(_ language: AppLanguage) -> ScratchpadFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }
}

extension ScratchpadFeatureStrings {
    static let enUS = ScratchpadFeatureStrings(
        pageTitle: "Scratchpad",
        hubDescription: "Floating pads for short-lived notes",
        panelCaption: "Quick notes in separate tabs",
        openButton: "Open scratchpad",
        placeholder: "Type anything. It saves by itself.",
        copyAll: "Copy all",
        copied: "Copied",
        exportAction: "Save as file",
        exportFailed: "The file could not be saved",
        loadFailed: "Your notes could not be opened. They were left unchanged.",
        saveFailed: "Your notes could not be saved. Copy them elsewhere before quitting.",
        clearAction: "Clear",
        retentionTitle: "Clear on its own",
        retentionNever: "Never",
        retentionDay: "After a day unused",
        retentionWeek: "After a week unused",
        retentionMonth: "After a month unused",
        retentionCaption: "The pad empties itself once the text goes that long without edits.",
        closeOnClickOutside: "Close when I click outside",
        keepOpen: "Keep open",
        backgroundOpacity: "Pad background",
        backgroundTranslucent: "Translucent",
        backgroundOpaque: "Opaque",
        newPad: "New scratchpad",
        padActions: "Scratchpad actions",
        renamePad: "Rename scratchpad",
        closePad: "Close scratchpad",
        saveName: "Save",
        cancel: "Cancel",
        deletePadMessageFormat: "Delete “%@” and everything in it?",
        padLimitFormat: "You can keep up to %d scratchpads",
        previewFormatting: "Show formatting",
        editText: "Edit text",
        markBold: "Bold",
        markItalic: "Italic",
        markStrikethrough: "Strikethrough",
        markHeading: "Heading",
        markBullet: "Bulleted list",
        markNumbered: "Numbered list",
        markQuote: "Quote",
        markCode: "Code",
        markLink: "Link",
        formatMarks: "Formatting",
        textSize: "Text size"
    )

    static let ptBR = ScratchpadFeatureStrings(
        pageTitle: "Rascunho",
        hubDescription: "Blocos flutuantes para anotações passageiras",
        panelCaption: "Notas rápidas em abas separadas",
        openButton: "Abrir rascunho",
        placeholder: "Digite qualquer coisa. Salva sozinho.",
        copyAll: "Copiar tudo",
        copied: "Copiado",
        exportAction: "Salvar como arquivo",
        exportFailed: "Não foi possível salvar o arquivo",
        loadFailed: "Não foi possível abrir as notas. O conteúdo foi preservado.",
        saveFailed: "Não foi possível salvar as notas. Copie-as para outro lugar antes de sair.",
        clearAction: "Limpar",
        retentionTitle: "Limpar sozinho",
        retentionNever: "Nunca",
        retentionDay: "Após um dia sem uso",
        retentionWeek: "Após uma semana sem uso",
        retentionMonth: "Após um mês sem uso",
        retentionCaption: "O bloco se esvazia quando o texto passa esse tempo sem edições.",
        closeOnClickOutside: "Fechar ao clicar fora",
        keepOpen: "Manter aberto",
        backgroundOpacity: "Fundo do bloco",
        backgroundTranslucent: "Translúcido",
        backgroundOpaque: "Opaco",
        newPad: "Novo rascunho",
        padActions: "Ações do rascunho",
        renamePad: "Renomear rascunho",
        closePad: "Fechar rascunho",
        saveName: "Salvar",
        cancel: "Cancelar",
        deletePadMessageFormat: "Apagar “%@” e todo o conteúdo?",
        padLimitFormat: "Você pode manter até %d rascunhos",
        previewFormatting: "Ver formatação",
        editText: "Editar texto",
        markBold: "Negrito",
        markItalic: "Itálico",
        markStrikethrough: "Tachado",
        markHeading: "Título",
        markBullet: "Lista com marcadores",
        markNumbered: "Lista numerada",
        markQuote: "Citação",
        markCode: "Código",
        markLink: "Link",
        formatMarks: "Formatação",
        textSize: "Tamanho do texto"
    )

    static let tr = ScratchpadFeatureStrings(
        pageTitle: "Karalama defteri",
        hubDescription: "Kısa süreli notlar için sekmeli yüzen not alanları",
        panelCaption: "Ayrı sekmelerde hızlı notlar",
        openButton: "Karalama defterini aç",
        placeholder: "Bir şeyler yazın. Kendiliğinden kaydedilir.",
        copyAll: "Tümünü kopyala",
        copied: "Kopyalandı",
        exportAction: "Dosya olarak kaydet",
        exportFailed: "Dosya kaydedilemedi",
        loadFailed: "Notlar açılamadı. İçerik değiştirilmeden korundu.",
        saveFailed: "Notlar kaydedilemedi. Çıkmadan önce başka bir yere kopyalayın.",
        clearAction: "Temizle",
        retentionTitle: "Kendiliğinden temizle",
        retentionNever: "Hiçbir zaman",
        retentionDay: "Bir gün kullanılmayınca",
        retentionWeek: "Bir hafta kullanılmayınca",
        retentionMonth: "Bir ay kullanılmayınca",
        retentionCaption: "Metin bu süre boyunca düzenlenmezse defter kendini boşaltır.",
        closeOnClickOutside: "Dışarı tıklayınca kapat",
        keepOpen: "Açık tut",
        backgroundOpacity: "Defter arka planı",
        backgroundTranslucent: "Yarı saydam",
        backgroundOpaque: "Opak",
        newPad: "Yeni karalama defteri",
        padActions: "Karalama defteri işlemleri",
        renamePad: "Karalama defterini yeniden adlandır",
        closePad: "Karalama defterini kapat",
        saveName: "Kaydet",
        cancel: "Vazgeç",
        deletePadMessageFormat: "“%@” ve içindeki her şey silinsin mi?",
        padLimitFormat: "%d adede kadar karalama defteri tutabilirsiniz",
        previewFormatting: "Biçimlendirmeyi göster",
        editText: "Metni düzenle",
        markBold: "Kalın",
        markItalic: "İtalik",
        markStrikethrough: "Üstü çizili",
        markHeading: "Başlık",
        markBullet: "Madde işaretli liste",
        markNumbered: "Numaralı liste",
        markQuote: "Alıntı",
        markCode: "Kod",
        markLink: "Bağlantı",
        formatMarks: "Biçimlendirme",
        textSize: "Metin boyutu"
    )

    static let ru = ScratchpadFeatureStrings(
        pageTitle: "Черновик",
        hubDescription: "Плавающие блокноты с вкладками для коротких заметок",
        panelCaption: "Быстрые заметки в отдельных вкладках",
        openButton: "Открыть черновик",
        placeholder: "Напишите что угодно. Сохраняется само.",
        copyAll: "Скопировать всё",
        copied: "Скопировано",
        exportAction: "Сохранить как файл",
        exportFailed: "Не удалось сохранить файл",
        loadFailed: "Не удалось открыть заметки. Они сохранены без изменений.",
        saveFailed: "Не удалось сохранить заметки. Скопируйте их в другое место перед выходом.",
        clearAction: "Очистить",
        retentionTitle: "Очищать автоматически",
        retentionNever: "Никогда",
        retentionDay: "Через день без правок",
        retentionWeek: "Через неделю без правок",
        retentionMonth: "Через месяц без правок",
        retentionCaption: "Черновик очищается сам, если текст столько времени не редактировался.",
        closeOnClickOutside: "Закрывать при щелчке снаружи",
        keepOpen: "Оставить открытым",
        backgroundOpacity: "Фон черновика",
        backgroundTranslucent: "Полупрозрачный",
        backgroundOpaque: "Непрозрачный",
        newPad: "Новый черновик",
        padActions: "Действия с черновиком",
        renamePad: "Переименовать черновик",
        closePad: "Закрыть черновик",
        saveName: "Сохранить",
        cancel: "Отмена",
        deletePadMessageFormat: "Удалить «%@» вместе со всем содержимым?",
        padLimitFormat: "Можно хранить до %d черновиков",
        previewFormatting: "Показать форматирование",
        editText: "Редактировать текст",
        markBold: "Полужирный",
        markItalic: "Курсив",
        markStrikethrough: "Зачёркнутый",
        markHeading: "Заголовок",
        markBullet: "Маркированный список",
        markNumbered: "Нумерованный список",
        markQuote: "Цитата",
        markCode: "Код",
        markLink: "Ссылка",
        formatMarks: "Форматирование",
        textSize: "Размер текста"
    )

    static let es = ScratchpadFeatureStrings(
        pageTitle: "Borrador",
        hubDescription: "Blocs flotantes con pestañas para notas pasajeras",
        panelCaption: "Notas rápidas en pestañas separadas",
        openButton: "Abrir borrador",
        placeholder: "Escribe cualquier cosa. Se guarda solo.",
        copyAll: "Copiar todo",
        copied: "Copiado",
        exportAction: "Guardar como archivo",
        exportFailed: "No se pudo guardar el archivo",
        loadFailed: "No se pudieron abrir las notas. Se conservaron sin cambios.",
        saveFailed: "No se pudieron guardar las notas. Cópialas en otro lugar antes de salir.",
        clearAction: "Limpiar",
        retentionTitle: "Limpiar solo",
        retentionNever: "Nunca",
        retentionDay: "Tras un día sin uso",
        retentionWeek: "Tras una semana sin uso",
        retentionMonth: "Tras un mes sin uso",
        retentionCaption: "El bloc se vacía cuando el texto pasa ese tiempo sin cambios.",
        closeOnClickOutside: "Cerrar al hacer clic fuera",
        keepOpen: "Mantener abierto",
        backgroundOpacity: "Fondo del borrador",
        backgroundTranslucent: "Translúcido",
        backgroundOpaque: "Opaco",
        newPad: "Nuevo borrador",
        padActions: "Acciones del borrador",
        renamePad: "Renombrar borrador",
        closePad: "Cerrar borrador",
        saveName: "Guardar",
        cancel: "Cancelar",
        deletePadMessageFormat: "¿Eliminar “%@” y todo su contenido?",
        padLimitFormat: "Puedes guardar hasta %d borradores",
        previewFormatting: "Ver formato",
        editText: "Editar texto",
        markBold: "Negrita",
        markItalic: "Cursiva",
        markStrikethrough: "Tachado",
        markHeading: "Título",
        markBullet: "Lista con viñetas",
        markNumbered: "Lista numerada",
        markQuote: "Cita",
        markCode: "Código",
        markLink: "Enlace",
        formatMarks: "Formato",
        textSize: "Tamaño del texto"
    )

    static let sk = ScratchpadFeatureStrings(
        pageTitle: "Poznámkový blok",
        hubDescription: "Plávajúce bloky pre krátkodobé poznámky",
        panelCaption: "Rýchle poznámky v samostatných kartách",
        openButton: "Otvoriť poznámkový blok",
        placeholder: "Napíšte čokoľvek. Ukladá sa samo.",
        copyAll: "Kopírovať všetko",
        copied: "Skopírované",
        exportAction: "Uložiť ako súbor",
        exportFailed: "Súbor sa nepodarilo uložiť",
        loadFailed: "Poznámky sa nepodarilo otvoriť. Zostali bez zmeny.",
        saveFailed: "Poznámky sa nepodarilo uložiť. Pred ukončením ich skopírujte inam.",
        clearAction: "Vymazať",
        retentionTitle: "Vymazať automaticky",
        retentionNever: "Nikdy",
        retentionDay: "Po dni bez použitia",
        retentionWeek: "Po týždni bez použitia",
        retentionMonth: "Po mesiaci bez použitia",
        retentionCaption: "Blok sa sám vyprázdni, keď text zostane taký dlho bez úprav.",
        closeOnClickOutside: "Zavrieť pri kliknutí mimo",
        keepOpen: "Nechať otvorené",
        backgroundOpacity: "Pozadie bloku",
        backgroundTranslucent: "Priesvitné",
        backgroundOpaque: "Nepriehľadné",
        newPad: "Nový poznámkový blok",
        padActions: "Akcie poznámkového bloku",
        renamePad: "Premenovať poznámkový blok",
        closePad: "Zavrieť poznámkový blok",
        saveName: "Uložiť",
        cancel: "Zrušiť",
        deletePadMessageFormat: "Vymazať „%@“ a celý jeho obsah?",
        padLimitFormat: "Maximálny počet poznámkových blokov: %d",
        previewFormatting: "Zobraziť formátovanie",
        editText: "Upraviť text",
        markBold: "Tučné",
        markItalic: "Kurzíva",
        markStrikethrough: "Prečiarknuté",
        markHeading: "Nadpis",
        markBullet: "Zoznam s odrážkami",
        markNumbered: "Číslovaný zoznam",
        markQuote: "Citát",
        markCode: "Kód",
        markLink: "Odkaz",
        formatMarks: "Formátovanie",
        textSize: "Veľkosť textu"
    )

    static let de = ScratchpadFeatureStrings(
        pageTitle: "Schmierzettel",
        hubDescription: "Schwebende Zettel mit Tabs für kurzlebige Notizen",
        panelCaption: "Schnelle Notizen in eigenen Tabs",
        openButton: "Schmierzettel öffnen",
        placeholder: "Einfach lostippen. Wird von selbst gesichert.",
        copyAll: "Alles kopieren",
        copied: "Kopiert",
        exportAction: "Als Datei sichern",
        exportFailed: "Die Datei konnte nicht gesichert werden",
        loadFailed: "Die Notizen konnten nicht geöffnet werden. Sie bleiben unverändert.",
        saveFailed: "Die Notizen konnten nicht gesichert werden. Kopiere sie vor dem Beenden an einen anderen Ort.",
        clearAction: "Leeren",
        retentionTitle: "Automatisch leeren",
        retentionNever: "Nie",
        retentionDay: "Nach einem Tag ohne Änderung",
        retentionWeek: "Nach einer Woche ohne Änderung",
        retentionMonth: "Nach einem Monat ohne Änderung",
        retentionCaption: "Der Zettel leert sich, wenn der Text so lange nicht bearbeitet wurde.",
        closeOnClickOutside: "Beim Klick außerhalb schließen",
        keepOpen: "Offen halten",
        backgroundOpacity: "Hintergrund des Zettels",
        backgroundTranslucent: "Durchscheinend",
        backgroundOpaque: "Deckend",
        newPad: "Neuer Schmierzettel",
        padActions: "Schmierzettelaktionen",
        renamePad: "Schmierzettel umbenennen",
        closePad: "Schmierzettel schließen",
        saveName: "Sichern",
        cancel: "Abbrechen",
        deletePadMessageFormat: "„%@“ und den gesamten Inhalt löschen?",
        padLimitFormat: "Du kannst bis zu %d Schmierzettel behalten",
        previewFormatting: "Formatierung zeigen",
        editText: "Text bearbeiten",
        markBold: "Fett",
        markItalic: "Kursiv",
        markStrikethrough: "Durchgestrichen",
        markHeading: "Überschrift",
        markBullet: "Aufzählung",
        markNumbered: "Nummerierte Liste",
        markQuote: "Zitat",
        markCode: "Code",
        markLink: "Link",
        formatMarks: "Formatierung",
        textSize: "Textgröße"
    )

    static let fr = ScratchpadFeatureStrings(
        pageTitle: "Brouillon",
        hubDescription: "Des blocs flottants à onglets pour les notes éphémères",
        panelCaption: "Des notes rapides dans des onglets séparés",
        openButton: "Ouvrir le brouillon",
        placeholder: "Écrivez ce que vous voulez. Tout s’enregistre tout seul.",
        copyAll: "Tout copier",
        copied: "Copié",
        exportAction: "Enregistrer dans un fichier",
        exportFailed: "Impossible d’enregistrer le fichier",
        loadFailed: "Impossible d’ouvrir les notes. Elles restent inchangées.",
        saveFailed: "Impossible d’enregistrer les notes. Copiez-les ailleurs avant de quitter.",
        clearAction: "Effacer",
        retentionTitle: "Effacer automatiquement",
        retentionNever: "Jamais",
        retentionDay: "Après un jour sans modification",
        retentionWeek: "Après une semaine sans modification",
        retentionMonth: "Après un mois sans modification",
        retentionCaption: "Le bloc se vide quand le texte reste aussi longtemps sans modification.",
        closeOnClickOutside: "Fermer si je clique à l’extérieur",
        keepOpen: "Garder ouvert",
        backgroundOpacity: "Fond du brouillon",
        backgroundTranslucent: "Translucide",
        backgroundOpaque: "Opaque",
        newPad: "Nouveau brouillon",
        padActions: "Actions du brouillon",
        renamePad: "Renommer le brouillon",
        closePad: "Fermer le brouillon",
        saveName: "Enregistrer",
        cancel: "Annuler",
        deletePadMessageFormat: "Supprimer «\u{00A0}%@\u{00A0}» et tout son contenu\u{00A0}?",
        padLimitFormat: "Vous pouvez conserver jusqu’à %d brouillons",
        previewFormatting: "Afficher la mise en forme",
        editText: "Modifier le texte",
        markBold: "Gras",
        markItalic: "Italique",
        markStrikethrough: "Barré",
        markHeading: "Titre",
        markBullet: "Liste à puces",
        markNumbered: "Liste numérotée",
        markQuote: "Citation",
        markCode: "Code",
        markLink: "Lien",
        formatMarks: "Mise en forme",
        textSize: "Taille du texte"
    )

    static let it = ScratchpadFeatureStrings(
        pageTitle: "Bozza",
        hubDescription: "Blocchi fluttuanti a schede per note usa e getta",
        panelCaption: "Note rapide in schede separate",
        openButton: "Apri bozza",
        placeholder: "Scrivi qualsiasi cosa. Si salva da sola.",
        copyAll: "Copia tutto",
        copied: "Copiato",
        exportAction: "Salva come file",
        exportFailed: "Impossibile salvare il file",
        loadFailed: "Impossibile aprire le note. Sono state conservate senza modifiche.",
        saveFailed: "Impossibile salvare le note. Copiale altrove prima di uscire.",
        clearAction: "Svuota",
        retentionTitle: "Svuota automaticamente",
        retentionNever: "Mai",
        retentionDay: "Dopo un giorno senza modifiche",
        retentionWeek: "Dopo una settimana senza modifiche",
        retentionMonth: "Dopo un mese senza modifiche",
        retentionCaption: "Il blocco si svuota quando il testo resta così a lungo senza modifiche.",
        closeOnClickOutside: "Chiudi quando clicco fuori",
        keepOpen: "Mantieni aperto",
        backgroundOpacity: "Sfondo della bozza",
        backgroundTranslucent: "Traslucido",
        backgroundOpaque: "Opaco",
        newPad: "Nuova bozza",
        padActions: "Azioni della bozza",
        renamePad: "Rinomina bozza",
        closePad: "Chiudi bozza",
        saveName: "Salva",
        cancel: "Annulla",
        deletePadMessageFormat: "Eliminare “%@” e tutto il contenuto?",
        padLimitFormat: "Puoi conservare fino a %d bozze",
        previewFormatting: "Mostra formattazione",
        editText: "Modifica testo",
        markBold: "Grassetto",
        markItalic: "Corsivo",
        markStrikethrough: "Barrato",
        markHeading: "Titolo",
        markBullet: "Elenco puntato",
        markNumbered: "Elenco numerato",
        markQuote: "Citazione",
        markCode: "Codice",
        markLink: "Collegamento",
        formatMarks: "Formattazione",
        textSize: "Dimensione del testo"
    )

    static let ja = ScratchpadFeatureStrings(
        pageTitle: "クイックメモ",
        hubDescription: "一時的なメモをタブで分けられるフローティングパッド",
        panelCaption: "タブで分けて自動保存するクイックメモ",
        openButton: "クイックメモを開く",
        placeholder: "何でも入力してください。自動で保存されます。",
        copyAll: "すべてコピー",
        copied: "コピーしました",
        exportAction: "ファイルとして保存",
        exportFailed: "ファイルを保存できませんでした",
        loadFailed: "メモを開けませんでした。内容は変更されていません。",
        saveFailed: "メモを保存できませんでした。終了する前に別の場所へコピーしてください。",
        clearAction: "消去",
        retentionTitle: "自動で消去",
        retentionNever: "しない",
        retentionDay: "1日使わなかったら",
        retentionWeek: "1週間使わなかったら",
        retentionMonth: "1か月使わなかったら",
        retentionCaption: "その期間編集がないと、メモは自動で空になります。",
        closeOnClickOutside: "外側をクリックしたら閉じる",
        keepOpen: "開いたままにする",
        backgroundOpacity: "メモの背景",
        backgroundTranslucent: "半透明",
        backgroundOpaque: "不透明",
        newPad: "新しいクイックメモ",
        padActions: "クイックメモの操作",
        renamePad: "名前を変更",
        closePad: "クイックメモを閉じる",
        saveName: "保存",
        cancel: "キャンセル",
        deletePadMessageFormat: "「%@」とその内容をすべて削除しますか？",
        padLimitFormat: "クイックメモは最大%d個まで作成できます",
        previewFormatting: "書式を表示",
        editText: "テキストを編集",
        markBold: "太字",
        markItalic: "斜体",
        markStrikethrough: "取り消し線",
        markHeading: "見出し",
        markBullet: "箇条書き",
        markNumbered: "番号付きリスト",
        markQuote: "引用",
        markCode: "コード",
        markLink: "リンク",
        formatMarks: "書式",
        textSize: "文字サイズ"
    )

    static let ko = ScratchpadFeatureStrings(
        pageTitle: "빠른 메모",
        hubDescription: "짧은 메모를 탭으로 나누는 플로팅 메모판",
        panelCaption: "각 탭에 따로 저장되는 빠른 메모",
        openButton: "빠른 메모 열기",
        placeholder: "아무거나 입력하세요. 자동으로 저장됩니다.",
        copyAll: "전체 복사",
        copied: "복사됨",
        exportAction: "파일로 저장",
        exportFailed: "파일을 저장할 수 없습니다",
        loadFailed: "메모를 열 수 없습니다. 내용은 변경되지 않았습니다.",
        saveFailed: "메모를 저장할 수 없습니다. 종료하기 전에 다른 곳에 복사해 두세요.",
        clearAction: "지우기",
        retentionTitle: "자동으로 지우기",
        retentionNever: "안 함",
        retentionDay: "하루 동안 사용하지 않으면",
        retentionWeek: "일주일 동안 사용하지 않으면",
        retentionMonth: "한 달 동안 사용하지 않으면",
        retentionCaption: "그 기간 동안 편집이 없으면 메모가 자동으로 비워집니다.",
        closeOnClickOutside: "바깥을 클릭하면 닫기",
        keepOpen: "열어 두기",
        backgroundOpacity: "메모 배경",
        backgroundTranslucent: "반투명",
        backgroundOpaque: "불투명",
        newPad: "새 빠른 메모",
        padActions: "빠른 메모 동작",
        renamePad: "빠른 메모 이름 변경",
        closePad: "빠른 메모 닫기",
        saveName: "저장",
        cancel: "취소",
        deletePadMessageFormat: "“%@” 및 모든 내용을 삭제할까요?",
        padLimitFormat: "빠른 메모는 최대 %d개까지 만들 수 있습니다",
        previewFormatting: "서식 보기",
        editText: "텍스트 편집",
        markBold: "굵게",
        markItalic: "기울임꼴",
        markStrikethrough: "취소선",
        markHeading: "제목",
        markBullet: "글머리 기호 목록",
        markNumbered: "번호 목록",
        markQuote: "인용",
        markCode: "코드",
        markLink: "링크",
        formatMarks: "서식",
        textSize: "텍스트 크기"
    )

    static let zhHans = ScratchpadFeatureStrings(
        pageTitle: "草稿板",
        hubDescription: "用标签页整理临时笔记的浮动记事板",
        panelCaption: "在独立标签页中自动保存的速记",
        openButton: "打开草稿板",
        placeholder: "随便写点什么，会自动保存。",
        copyAll: "全部拷贝",
        copied: "已拷贝",
        exportAction: "存储为文件",
        exportFailed: "无法存储文件",
        loadFailed: "无法打开笔记。内容已保留，未作更改。",
        saveFailed: "无法保存笔记。退出前请把内容拷贝到别处。",
        clearAction: "清空",
        retentionTitle: "自动清空",
        retentionNever: "从不",
        retentionDay: "一天未使用后",
        retentionWeek: "一周未使用后",
        retentionMonth: "一个月未使用后",
        retentionCaption: "文本超过该时间没有编辑时，草稿板会自动清空。",
        closeOnClickOutside: "点击外部时关闭",
        keepOpen: "保持打开",
        backgroundOpacity: "草稿板背景",
        backgroundTranslucent: "半透明",
        backgroundOpaque: "不透明",
        newPad: "新建草稿板",
        padActions: "草稿板操作",
        renamePad: "重命名草稿板",
        closePad: "关闭草稿板",
        saveName: "保存",
        cancel: "取消",
        deletePadMessageFormat: "删除“%@”及其中的全部内容？",
        padLimitFormat: "最多可保留 %d 个草稿板",
        previewFormatting: "显示格式",
        editText: "编辑文本",
        markBold: "粗体",
        markItalic: "斜体",
        markStrikethrough: "删除线",
        markHeading: "标题",
        markBullet: "项目符号列表",
        markNumbered: "编号列表",
        markQuote: "引用",
        markCode: "代码",
        markLink: "链接",
        formatMarks: "格式",
        textSize: "文字大小"
    )

    static let zhTW = ScratchpadFeatureStrings(
        pageTitle: "草稿板",
        hubDescription: "用分頁整理臨時筆記的浮動記事板",
        panelCaption: "在不同分頁中自動儲存的快速筆記",
        openButton: "打開草稿板",
        placeholder: "隨手寫點什麼，會自動儲存。",
        copyAll: "全部拷貝",
        copied: "已拷貝",
        exportAction: "儲存為檔案",
        exportFailed: "無法儲存檔案",
        loadFailed: "無法開啟筆記。內容已保留，未作更改。",
        saveFailed: "無法儲存筆記。結束前請把內容拷貝到別處。",
        clearAction: "清空",
        retentionTitle: "自動清空",
        retentionNever: "永不",
        retentionDay: "一天未使用後",
        retentionWeek: "一週未使用後",
        retentionMonth: "一個月未使用後",
        retentionCaption: "文字超過該時間沒有編輯時，草稿板會自動清空。",
        closeOnClickOutside: "點一下外部時關閉",
        keepOpen: "保持開啟",
        backgroundOpacity: "草稿板背景",
        backgroundTranslucent: "半透明",
        backgroundOpaque: "不透明",
        newPad: "新增草稿板",
        padActions: "草稿板操作",
        renamePad: "重新命名草稿板",
        closePad: "關閉草稿板",
        saveName: "儲存",
        cancel: "取消",
        deletePadMessageFormat: "刪除「%@」和其中的所有內容？",
        padLimitFormat: "最多可保留 %d 個草稿板",
        previewFormatting: "顯示格式",
        editText: "編輯文字",
        markBold: "粗體",
        markItalic: "斜體",
        markStrikethrough: "刪除線",
        markHeading: "標題",
        markBullet: "項目符號列表",
        markNumbered: "編號清單",
        markQuote: "引用",
        markCode: "程式碼",
        markLink: "連結",
        formatMarks: "格式",
        textSize: "文字大小"
    )

    static let zhHK = ScratchpadFeatureStrings(
        pageTitle: "草稿板",
        hubDescription: "用分頁整理臨時筆記的浮動記事板",
        panelCaption: "在不同分頁中自動儲存的快速筆記",
        openButton: "開啟草稿板",
        placeholder: "隨手寫些什麼，會自動儲存。",
        copyAll: "全部拷貝",
        copied: "已拷貝",
        exportAction: "儲存為檔案",
        exportFailed: "無法儲存檔案",
        loadFailed: "無法開啟筆記。內容已保留，未有更改。",
        saveFailed: "無法儲存筆記。結束前請把內容拷貝到別處。",
        clearAction: "清空",
        retentionTitle: "自動清空",
        retentionNever: "永不",
        retentionDay: "一天未使用後",
        retentionWeek: "一星期未使用後",
        retentionMonth: "一個月未使用後",
        retentionCaption: "文字超過該時間沒有編輯，草稿板會自動清空。",
        closeOnClickOutside: "點一下外部時關閉",
        keepOpen: "保持開啟",
        backgroundOpacity: "草稿板背景",
        backgroundTranslucent: "半透明",
        backgroundOpaque: "不透明",
        newPad: "新增草稿板",
        padActions: "草稿板操作",
        renamePad: "重新命名草稿板",
        closePad: "關閉草稿板",
        saveName: "儲存",
        cancel: "取消",
        deletePadMessageFormat: "刪除「%@」及當中的所有內容？",
        padLimitFormat: "最多可保留 %d 個草稿板",
        previewFormatting: "顯示格式",
        editText: "編輯文字",
        markBold: "粗體",
        markItalic: "斜體",
        markStrikethrough: "刪除線",
        markHeading: "標題",
        markBullet: "項目符號列表",
        markNumbered: "編號清單",
        markQuote: "引用",
        markCode: "程式碼",
        markLink: "連結",
        formatMarks: "格式",
        textSize: "文字大小"
    )
    static let uk = ScratchpadFeatureStrings(
        pageTitle: "Нотатник",
        hubDescription: "Плаваючі блокноти для короткочасних нотаток",
        panelCaption: "Швидкі нотатки в окремих вкладках",
        openButton: "Відкрити нотатник",
        placeholder: "Пишіть будь-що. Зберігається сам.",
        copyAll: "Скопіювати все",
        copied: "Скопійовано",
        exportAction: "Зберегти як файл",
        exportFailed: "Не вдалося зберегти файл.",
        loadFailed: "Не вдалося відкрити нотатку. Вміст збережено і не змінено.",
        saveFailed: "Не вдалося зберегти нотатки. Перш ніж вийти, скопіюйте їх в інше місце.",
        clearAction: "Очистити",
        retentionTitle: "Очищати сам",
        retentionNever: "Ніколи",
        retentionDay: "Через день без використання",
        retentionWeek: "Через тиждень без використання",
        retentionMonth: "Через місяць без використання",
        retentionCaption: "Блокнот очищається сам, коли текст залишається без редагувань стільки часу.",
        closeOnClickOutside: "Закривати при клаці зовні",
        keepOpen: "Тримати відкритою",
        backgroundOpacity: "Фон панелі",
        backgroundTranslucent: "Напівпрозорий",
        backgroundOpaque: "Непрозорий",
        newPad: "Новий нотатник",
        padActions: "Дії нотатника",
        renamePad: "Перейменувати нотатник",
        closePad: "Закрити нотатник",
        saveName: "Зберегти",
        cancel: "Скасувати",
        deletePadMessageFormat: "Видалити «%@» та все в ньому?",
        padLimitFormat: "Ви можете зберігати до %d нотатників",
        previewFormatting: "Показувати форматування",
        editText: "Редагувати текст",
        markBold: "Жирний",
        markItalic: "Курсив",
        markStrikethrough: "Закреслений",
        markHeading: "Заголовок",
        markBullet: "Маркований список",
        markNumbered: "Нумерований список",
        markQuote: "Цитата",
        markCode: "Код",
        markLink: "Посилання",
        formatMarks: "Форматування",
        textSize: "Розмір тексту"
    )
}

extension ScratchpadFeatureStrings {
    /// One place both toolbars read their labels from, so the floating pad and
    /// the island cannot drift into calling the same mark different things.
    func label(for mark: ScratchpadMark) -> String {
        switch mark {
        case .bold: return markBold
        case .italic: return markItalic
        case .strikethrough: return markStrikethrough
        case .heading: return markHeading
        case .bullet: return markBullet
        case .numbered: return markNumbered
        case .quote: return markQuote
        case .code: return markCode
        case .link: return markLink
        }
    }
}
