// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Slovenčina — translated and hand-checked, not machine output.
extension Strings {
    static let sk = Strings(
        statusIdleTooltip: "Aster: normálny spánok",
        statusActiveUntil: "Aster: bdie do",
        statusActiveIndefinite: "Aster: bdie natrvalo",
        menuEnableAwake: "Zapnúť bdelý režim",
        menuDisableAwake: "Vypnúť bdelý režim",
        menuActivateFor: "Aktivovať na…",
        menuSettings: "Nastavenia…",
        menuAbout: "O aplikácii Aster",
        menuQuit: "Ukončiť Aster",
        menuHide: "Skryť Aster",
        menuHideOthers: "Skryť ostatné",
        menuShowAll: "Zobraziť všetko",
        menuEdit: "Upraviť",
        menuUndo: "Vrátiť späť",
        menuRedo: "Znova",
        actionClear: "Vymazať",
        actionRemove: "Odstrániť",
        actionBack: "Späť",
        actionSearch: "Hľadať",
        actionMute: "Stlmiť",
        actionUnmute: "Zrušiť stlmenie",
        actionPlay: "Prehrať",
        actionPause: "Pozastaviť",
        menuCut: "Vystrihnúť",
        menuCopy: "Kopírovať",
        menuPaste: "Vložiť",
        menuSelectAll: "Vybrať všetko",
        menuWindow: "Okno",
        menuMinimize: "Minimalizovať",
        menuZoom: "Zväčšiť",
        menuClose: "Zavrieť",

        minutes15: "15 minút",
        minutes30: "30 minút",
        hour1: "1 hodina",
        hours2: "2 hodiny",
        hours4: "4 hodiny",
        hours8: "8 hodín",
        indefinitely: "Natrvalo",
        indefinite: "Neobmedzene",

        panelSettings: "Nastavenia",
        panelQuit: "Ukončiť",
        panelHotkeyHint: "Skratka prepína",

        keepAwakeTitle: "Bdelý režim",
        keepAwakeEndsIn: "Skončí o",
        keepAwakeUntilDisabled: "Aktívny, kým ho nevypnete",
        keepAwakeNormalRules: "Mac sa riadi bežnými pravidlami úspory energie",
        keepAwakeUntilLabel: "Do",
        keepAwakeUntilStart: "Spustiť",
        keepAwakeOptions: "Možnosti",
        keepAwakeMouseJiggle: "Jemne pohybovať kurzorom",
        keepAwakeMouseJiggleCaption: "Počas relácie jemne pohne kurzorom vo zvolenom intervale.",
        keepAwakeMouseJiggleInterval: "Interval",
        keepAwakeActiveIconLabel: "Ikona pri aktivite",
        keepAwakeActiveIconVorssaint: "Aster",
        keepAwakeActiveIconCoffee: "Káva",
        keepAwakeActiveIconEye: "Oko",
        keepAwakeActiveIconMoon: "Mesiac",
        keepAwakeActiveIconLight: "Žiarovka",
        keepAwakeIconTintLabel: "Farba aktívnej ikony",
        keepAwakeIconTintOrange: "Oranžová",
        keepAwakeIconTintGreen: "Zelená",
        keepAwakeIconTintBlue: "Modrá",
        keepAwakeIconTintPurple: "Fialová",
        keepAwakeIconTintPink: "Ružová",
        keepAwakeIconTintNone: "Bez farby",
        durationLabel: "Trvanie",
        clamshellTitle: "Pokračovať so zatvoreným vekom",
        clamshellOnCaption: "Spánok je úplne vypnutý. Sledujte napájanie",
        clamshellNeedsSession: "Použije sa vždy, keď je „Bdelý režim“ aktívny",
        clamshellReady: "Pripravené. Prepína sa bez hesla",
        clamshellNeedsPassword: "Raz si vyžiada heslo správcu",

        systemSection: "Systém",
        temperatures: "Teploty",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batéria",
        usageSection: "Využitie hardvéru",
        memorySection: "Pamäť",
        memoryPressure: "Zaťaženie",
        memorySwapUsed: "Využitý swap",
        memoryCompressed: "Komprimované",
        memoryCachedFiles: "Súbory v cache",
        pressureNormal: "Normálne",
        pressureWarning: "Zvýšené",
        pressureCritical: "Kritické",
        monitorUnavailable: "Senzory na tomto Macu nie sú dostupné",
        energyAppsTitle: "Aplikácie s vysokou spotrebou energie",
        energyAppsIdle: "Žiadna výrazná spotreba energie",

        notifySessionEndedTitle: "Relácia skončila",
        notifySessionEndedBody: "Čas vypršal. Mac bude opäť normálne zaspávať.",
        notifyBatteryTitle: "Aster je vypnutý",
        notifyBatteryBody: "Slabá batéria. Kvôli úspore sa obnovil normálny spánok.",
        adminPromptClamshellOn: "Aster potrebuje vaše heslo, aby Mac fungoval so zatvoreným vekom.",
        adminPromptClamshellOff: "Aster potrebuje vaše heslo, aby obnovil normálny spánok Macu.",
        adminPromptRecover: "Aster sa ukončil, kým bol spánok Macu vypnutý. Zadajte heslo na obnovenie normálneho spánku.",
        adminPromptUpdate: "Aster potrebuje vaše heslo na inštaláciu aktualizácie.",
        adminPromptSudoersInstall: "Aster vytvorí obmedzené pravidlo (iba pmset disablesleep), aby sa režim zatvoreného veka prepínal bez hesla. Heslo je potrebné len teraz.",
        adminPromptSudoersRemove: "Aster odstráni pravidlo pre režim zatvoreného veka bez hesla.",

        settingsTitle: "Nastavenia Asteru",
        tabGeneral: "Všeobecné",
        tabEnergy: "Energia",
        tabMouse: "Myš a trackpad",
        tabSwitcher: "Prepínač",
        tabAdvanced: "Pokročilé",
        tabAbout: "O aplikácii",
        tabReleaseNotes: "Novinky",
        releaseNotesOnUpdateToggle: "Po aktualizácii zobraziť novinky",
        minimalWindowPreviews: "Minimalistické náhľady",
        minimalWindowPreviewsCaption: "Skryje názvy, tlačidlá a dekoratívne detaily v náhľadoch v Docku a v prepínači. Výber ostáva viditeľný.",
        previewSizeLabel: "Veľkosť náhľadu",
        previewSizeNormal: "Normálna",
        previewSizeLarge: "Veľká",
        previewSizeXLarge: "Extra veľká",
        settingsGroupFeatures: "Funkcie",
        advancedResetSection: "Povolenia",
        advancedResetDescription: "Odstráni všetky povolenia, ktoré ste Asteru udelili (Prístupnosť, Nahrávanie obrazovky, Plný prístup k disku a ďalšie), položku po prihlásení aj pravidlo pre zatvorené veko. Hodí sa na čistý začiatok alebo pred odinštalovaním. Aplikácia ostane nainštalovaná.",
        advancedClearButton: "Vymazať všetky povolenia",
        advancedCleared: "Povolenia sú vymazané.",
        advancedClearFailed: "Niektoré povolenia alebo pravidlo pre zatvorené veko sa nepodarilo odstrániť. Skúste to znova a potvrďte požiadavku na heslo, ak sa objaví.",
        advancedClearConfirmTitle: "Vymazať všetky povolenia?",
        advancedClearConfirmBody: "Funkcie, ktoré povolenia potrebujú, prestanú fungovať, kým ich znova neudelíte. Vaše nastavenia ostanú zachované.",
        advancedUninstallSection: "Odinštalovanie",
        advancedUninstallDescription: "Urobí všetko uvedené vyššie, potom odstráni predvoľby a presunie Aster do Koša, takže nič neostane. Aplikácia sa na konci ukončí. Kedykoľvek ju môžete nainštalovať znova.",
        advancedUninstallButton: "Úplne odinštalovať Aster",
        advancedUninstallConfirmTitle: "Odinštalovať Aster?",
        advancedUninstallConfirmBody: "Aster vymaže svoje povolenia, odstráni predvoľby, presunie sa do Koša a ukončí sa. Z aplikácie sa to už nedá vrátiť späť, ale ostane v Koši, kým ho nevyprázdnite.",
        advancedUninstallFailedTitle: "Odinštalovanie sa zastavilo",
        advancedUninstallFailedBody: "Aster nedokázal vrátiť systémové nastavenie, ktoré zmenil: spánok, otáčky ventilátora alebo akceleráciu myši. Nič sa neodstránilo. Skúste to znova a potvrďte požiadavku na heslo, ak sa objaví.",

        launchAtLogin: "Spustiť po prihlásení",
        languageLabel: "Jazyk",
        menuBarSection: "Lišta s ponukami",
        showCountdown: "Zobraziť zostávajúci čas vedľa ikony",
        globalHotkeySection: "Globálna skratka",
        hotkeyToggle: "Zapnúť skratku pre „Bdelý režim“",
        hotkeyCaption: "Funguje v každej aplikácii, bez ďalších povolení.",

        sessionSection: "Relácia",
        defaultDurationLabel: "Predvolené trvanie",
        keepAwakeAutoStart: "Zapnúť bdelý režim po otvorení Asteru",
        keepAwakeAutoStartCaption: "Spustí reláciu s predvoleným trvaním.",
        batteryProtectionSection: "Ochrana batérie",
        batteryDisableBelow: "Vypnúť, keď batéria klesne pod",
        batteryNever: "Nikdy",
        batteryProtectionCaption: "Zabráni tomu, aby zabudnutá relácia vybila batériu MacBooku.",
        clamshellSection: "Zatvorené veko",
        configuring: "Nastavuje sa…",
        sudoersFailed: "Režim zatvoreného veka sa nepodarilo zapnúť. Skúste to znova.",
        clamshellExplanation: "„Pokračovať so zatvoreným vekom“ úplne vypne spánok, kým je aktívny „Bdelý režim“, a po skončení relácie alebo ukončení aplikácie sa automaticky vráti späť. Používajte ho radšej pri napájaní zo siete.",
        dimScreenOnLidCloseTitle: "Úplne stmaviť obrazovku",
        dimScreenOnLidCloseCaption: "Pri zatvorení veka stmaví obrazovku a po otvorení vráti jas.",

        scrollSection: "Rolovanie",
        invertMouseScroll: "Obrátiť rolovanie myšou",
        invertMouseScrollCaption: "Obráti smer kolieska myši.",
        scrollTrackpadNote: "Trackpadu sa to netýka: ostáva mu prirodzené rolovanie macOS.",
        scrollActiveNow: "Rolovanie myšou je práve obrátené",
        mouseNavigationActiveNow: "Bočné tlačidlá sú práve aktívne",
        smoothScrollName: "Plynulé rolovanie",
        smoothScrollCaption: "Zmení každý krok kolieska myši na krátky, jemný pohyb. Trackpadu sa to netýka.",
        smoothScrollStepLabel: "Rýchlosť rolovania",
        mouseNavigationSection: "Navigácia",
        mouseNavigationEnable: "Používať bočné tlačidlá na Späť a Dopredu",
        mouseNavigationCaption: "Zmení tlačidlá Späť a Dopredu na myši na navigačné príkazy vo Finderi, prehliadačoch a kompatibilných aplikáciách.",
        middleClickSection: "Stredné kliknutie",
        middleClickEnable: "Kliknutie tromi prstami funguje ako stredné kliknutie",
        middleClickEnableCaption: "Stlačenie trackpadu tromi prstami funguje ako kliknutie kolieskom myši: otvorí odkazy na novej karte, zatvorí karty a urobí všetko ostatné, čo stredné tlačidlo.",
        middleClickDragConflict: "V macOS je zapnuté ťahanie tromi prstami, ktoré používa rovnaké gesto. Vypnite ho v Systémových nastaveniach v časti Prístupnosť, Ovládanie kurzora, Možnosti trackpadu, a stredné kliknutie začne fungovať.",
        middleClickTapPicker: "Klikne aj jemné ťuknutie",
        middleClickTapOff: "Vypnuté",
        middleClickTapThreeFingers: "3 prsty",
        middleClickTapFourFingers: "4 prsty",
        middleClickTapCaption: "Jemné ťuknutie takýmto počtom prstov bez stlačenia tiež vyvolá stredné kliknutie. Posunutie sa nikdy nepočíta. Ak je ťuknutie tromi prstami v macOS priradené k funkcii Vyhľadať, vypnite ho, aby sa nespúšťali obe naraz.",
        quickToolsTab: "Rýchly panel",
        quickToolShortcutToggle: "Globálna skratka",
        ocrName: "Kopírovať text z obrazovky",
        ocrCaption: "Vyberte oblasť obrazovky a rozpoznaný text sa skopíruje, pripravený na vloženie.",
        ocrCopied: "Text skopírovaný",
        ocrNoText: "Nenašiel sa žiadny text",
        colorPickerName: "Výber farby",
        colorPickerCaption: "Zoberte farbu ľubovoľného pixelu na obrazovke a skopírujte ju vo svojom obľúbenom formáte.",
        colorPickerFormatLabel: "Formát kopírovania",
        colorPickerBareHexToggle: "Kopírovať bez predpony #",
        colorPickerPickNow: "Vybrať farbu",
        micMuteName: "Stlmiť mikrofón",
        micUnmuteName: "Zrušiť stlmenie mikrofónu",
        micMuteCaption: "Vypne mikrofón Macu kliknutím alebo skratkou, vo všetkých aplikáciách.",
        micMutedHUD: "Mikrofón je stlmený",
        micUnmutedHUD: "Mikrofón je späť zapnutý",
        micMutePartialHUD: "Niektoré mikrofóny sa nepodarilo stlmiť",
        micUnmutePartialHUD: "Niektoré mikrofóny sú stále stlmené",
        micMuteMenuBarToggle: "Zobraziť v lište s ponukami počas stlmenia",
        micMuteMenuBarCaption: "Vedľa ikony aplikácie v lište s ponukami sa objaví červený prečiarknutý mikrofón.",
        pastePlainName: "Vložiť ako čistý text",
        pastePlainCaption: "Vloží skopírovaný obsah bez farieb, písiem a formátovania. Originál ostáva v schránke.",
        launcherName: "Rýchly panel",
        launcherCaption: "Plávajúci panel s vašimi obľúbenými nástrojmi, vyvolaný skratkou odkiaľkoľvek.",
        launcherOpenNow: "Otvoriť rýchly panel",
        launcherEditHint: "Tlačidlom na úpravy vyberiete, skryjete a presuniete nástroje.",
        launcherEmptyState: "Všetky nástroje sú skryté. Tlačidlom na úpravy ich pridáte späť.",
        launcherAddSection: "Pridať späť",
        launcherKeysHint: "Šípky navigujú, Enter otvára, 1 až 9 otvárajú priamo",
        switcherSection: "Prepínač aplikácií",
        switcherEnable: "Používať prepínač Aster",
        switcherEnableCaption: "Prepínajte medzi aplikáciami a oknami vrátane minimalizovaných okien a viacerých okien tej istej aplikácie.",
        switcherUsageHint: "Podržte skratku na prechádzanie; pustením okno aktivujete. Shift alebo ← ide späť; W zatvorí okno; Q ukončí aplikáciu; Esc zruší.",
        switcherNoWindows: "Žiadne otvorené okná",
        switcherIconRowMode: "Zobraziť %@ s veľkými ikonami",
        switcherIconRowModeCaption: "Zobrazí jednu ikonu na aplikáciu a nad ňou náhľady jej okien.",
        switcherSimpleModeCaption: "Zobrazí ikony aplikácií a názvy okien, bez náhľadov a bez snímania obrazovky prepínačom.",
        switcherShortcutHintApps: "Aplikácie",
        switcherShortcutHintWindows: "Okná",
        switcherWindowShortcutCaption: "Otvorí prepínač okien aplikácie v popredí. Kým je otvorený prepínač aplikácií, prechádza medzi oknami vybranej aplikácie.",
        switcherTakeOverSystemShortcuts: "Nahradiť ⌘Tab a ⌘` v macOS",
        switcherTakeOverSystemShortcutsCaption: "Vypne zodpovedajúce skratky macOS pre aplikácie a okná len na čas, keď je prepínač Asteru aktívny. Všetky spustené aplikácie ostanú dostupné.",
        switcherAppearanceDelay: "Oneskorenie zobrazenia",
        switcherAppearanceDelayCaption: "Ako dlho treba skratku podržať, kým sa prepínač objaví.",
        switcherInstantSelection: "Okamžitý výber",
        switcherInstantSelectionCaption: "Pri prechádzaní aplikácií a okien okamžite presunie zvýraznenie a posunie zoznam.",
        switcherMergeTabs: "Zobraziť jednu položku na aplikáciu",
        switcherMergeTabsCaption: "Zlúči všetky okná aplikácie do jednej položky v prepínači namiesto jednej položky na každé okno.",
        switcherWindowlessApps: "Aplikácie bez otvoreného okna",
        switcherWindowlessAppsCaption: "Určuje, ktoré spustené aplikácie úplne bez okna sa zobrazia v prepínači.",
        switcherWindowlessAppsOff: "Nezobrazovať",
        switcherWindowlessAppsFinder: "Iba Finder",
        switcherWindowlessAppsAll: "Všetky aplikácie",
        switcherNoOpenWindow: "Žiadne otvorené okno",
        switcherOtherDesktop: "Iná plocha",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Náhľady okien z Docku",
        dockPreviewEnableCaption: "Podržte kurzor nad otvorenou aplikáciou v Docku, uvidíte jej okná a kliknutím vyberiete to, ktoré chcete.",
        dockPreviewCurrentSpaceOnlyCaption: "Keď je vypnuté, zobrazí okná zo všetkých plôch. Výberom okna na inej ploche prejdete na ňu.",
        dockPreviewBackgroundOpacity: "Pozadie panela",
        dockPreviewBackgroundOpacityCaption: "Znížte ho, aby bolo viac vidieť to, čo je za panelom.",
        dockPreviewOpenDelay: "Oneskorenie otvorenia",
        dockPreviewOpenDelayCaption: "Ako dlho musí kurzor ostať na ikone, kým sa jej panel otvorí.",
        dockPreviewQuitAppOnClose: "Tlačidlom × ukončiť aplikáciu",
        dockPreviewQuitAppOnCloseCaption: "V Dock Preview × ukončí celú aplikáciu namiesto zatvorenia jediného okna.",
        dockPreviewKeepDockVisible: "Ponechať Dock viditeľný (experimentálne)",
        dockPreviewKeepDockVisibleCaption: "Pozastaví automatické skrývanie, kým je náhľad otvorený, a po odchode ho obnoví. Môže zmeniť veľkosť okien. Ak sa aplikácia preruší, otvorte ju znova a Dock sa obnoví.",
        dockPreviewOrderByCreation: "Zoradiť okná podľa času vytvorenia",
        dockPreviewOrderByCreationCaption: "Zobrazí staršie okná ako prvé namiesto tých naposledy použitých.",
        dockClickMinimize: "Kliknutím na ikonu v Docku minimalizovať",
        dockClickMinimizeCaption: "Okná aktívnej aplikácie sa minimalizujú, keď kliknete na jej ikonu v Docku. Ďalším kliknutím ich vrátite späť.",
        dockClickCycleWindows: "Kliknutím na ikonu v Docku prechádzať okná",
        dockClickCycleWindowsCaption: "Kliknutím na ikonu aktívnej aplikácie v Docku prechádzate jej oknami, podobne ako ⌘`.",
        dockPreviewActiveNow: "Aktívne v Docku",
        dockPreviewDockUnavailable: "Položky Docku sa nepodarilo načítať.",
        dockPreviewAutohideBeta: "Beta. Môžete naraziť na chyby.",
        dockPreviewOpenWindow: "Otvoriť okno",
        dockPreviewCloseWindow: "Zavrieť okno",
        dockPreviewMinimizeWindow: "Minimalizovať okno",
        dockPreviewRestoreWindow: "Obnoviť okno",
        dockPreviewPinPanel: "Pripnúť náhľad",
        dockPreviewUnpinPanel: "Odopnúť náhľad",
        dockPreviewPinned: "Pripnuté",
        dockPreviewClosePanel: "Zavrieť náhľad",
        dockPreviewPreviousWindow: "Predchádzajúce okno",
        dockPreviewNextWindow: "Ďalšie okno",

        cutPasteName: "Vystrihnúť a vložiť",
        cutPasteEnable: "Vystrihovať a vkladať súbory vo Finderi",
        cutPasteEnableCaption: "Pomocou ⌘X vystrihnete a pomocou ⌘V presuniete súbory a priečinky vo Finderi.",
        cutPasteShowHUD: "Zobraziť plávajúci panel",
        cutPasteShowHUDCaption: "Zobrazí plávajúci indikátor s vystrihnutými súbormi, kým je Finder aktívny.",
        cutPasteHowTitle: "Ako sa to používa",
        cutPasteStep1: "Vyberte položky vo Finderi a stlačením ⌘X ich vystrihnite.",
        cutPasteStep2: "Otvorte cieľový priečinok a stlačením ⌘V ich tam presuňte.",
        cutPasteTextNote: "V textových poliach (napríklad pri premenovaní) ⌘X a ⌘V fungujú ako obvykle.",
        cutPasteActiveNow: "Pripravené na vystrihnutie vo Finderi",
        cutPasteAutomationNote: "macOS si pri prvom použití vyžiada povolenie na ovládanie Findera.",
        cutReadyTitle: "Vystrihnuté",
        cutReadyHint: "v cieľovom priečinku na presunutie",
        cutCancel: "Zrušiť vystrihnutie",
        cutDoneTitle: "Presunuté!",
        cutMovedSingular: "Presunutá 1 položka",
        cutMovedPluralFormat: "Presunutých položiek: %d",
        cutSomeFailed: "Niektoré položky sa nepodarilo presunúť",
        cutMovingTitle: "Presúva sa…",
        cutMovingCountFormat: "%d z %d",

        autoQuitName: "Ukončiť po zatvorení",
        autoQuitEnable: "Ukončiť aplikáciu po zatvorení jej posledného okna",
        autoQuitEnableCaption: "Zatvorením posledného okna aplikácie sa aplikácia aj ukončí.",
        autoQuitActiveNow: "Práve aktívne",
        autoQuitHowTitle: "Ako to funguje",
        autoQuitStep1: "Zatvorte posledné okno aplikácie (⌘W alebo červené tlačidlo).",
        autoQuitStep2: "Aplikácia sa sama ukončí. Dialógy „Uložiť zmeny?“ sa stále zobrazujú.",
        autoQuitPredictableNote: "Aplikácie, ktoré bežne bežia bez okna, sa nikdy neukončia.",
        autoQuitOngoingWorkNote: "Niektoré aplikácie zatvoria posledné okno, ale pracujú ďalej, napríklad nahrávanie obrazovky po spustení záznamu. Ak nie sú v zozname výnimiek, ukončia sa tiež.",
        autoQuitExceptionsTitle: "Výnimky",
        autoQuitExceptionsCaption: "Aplikácie v tomto zozname ostanú otvorené aj bez okien.",
        autoQuitExceptionsEmpty: "Žiadne výnimky",
        autoQuitAddApp: "Pridať aplikáciu…",

        uninstallerName: "Odinštalátor",
        uninstallerEnableCaption: "Odstráni aplikáciu spolu s cache, predvoľbami, protokolmi a zvyškami, ktoré po sebe zanechá.",
        uninstallerStep1: "Potiahnite aplikáciu do Nastavení alebo ju vyberte zo zoznamu.",
        uninstallerStep2: "Prezrite si nájdené súbory a koľko miesta zaberajú.",
        uninstallerStep3: "Presuňte do Koša to, čo chcete. Nič sa nemaže natrvalo.",
        uninstallerMenuItem: "Odinštalovať aplikáciu…",
        uninstallerDropTitle: "Potiahnite sem aplikáciu",
        uninstallerDropSubtitle: "alebo vyberte tú, ktorú chcete prehľadať",
        uninstallerChoose: "Vybrať aplikáciu…",
        uninstallerPickerTitle: "Vybrať aplikáciu",
        uninstallerPickerSearch: "Hľadať aplikácie",
        uninstallerPickerEmpty: "Nenašli sa žiadne aplikácie",
        uninstallerEmptyNote: "Nič sa neodstráni bez vášho potvrdenia.",
        uninstallerFDANote: "Udeľte Plný prístup k disku pre dôkladnejšie prehľadanie.",
        uninstallerFDAGrant: "Udeliť prístup…",
        uninstallerFDAHint: "Zapnite Aster v zozname. Ak tam nie je, kliknite na + a vyberte Aster z priečinka Aplikácie. Prístup sa prejaví až po opätovnom otvorení aplikácie.",
        uninstallerFDARelaunch: "Reštartovať teraz",
        uninstallerScanning: "Prehľadávajú sa súbory…",
        uninstallerRemoving: "Presúva sa do Koša…",
        uninstallerFoundTitle: "nájdené",
        uninstallerSelectedFormat: "Vybrané: %d z %d",
        uninstallerRemove: "Presunúť do Koša",
        uninstallerCancel: "Zrušiť",
        uninstallerConfirmationExpired: "Toto potvrdenie už neplatí. Skontrolujte aktuálne položky a potvrďte znova.",
        uninstallerDoneTitle: "Hotovo!",
        uninstallerFreedFormat: "Uvoľnené: %@",
        uninstallerSomeFailed: "Niektoré položky sa nepodarilo presunúť do Koša.",
        uninstallerFailedNeedsFDA: "Dáta aplikácií v sandboxe sa dajú presunúť len s Plným prístupom k disku. Heslo správcu ho nenahradí.",
        uninstallerFailedMoreFormat: "a ešte %d",
        uninstallerAnother: "Odinštalovať ďalšiu",
        uninstallerCatApp: "Aplikácia",
        uninstallerCatSupport: "Podporné súbory",
        uninstallerCatCaches: "Cache",
        uninstallerCatPreferences: "Predvoľby",
        uninstallerCatContainers: "Kontajnery",
        uninstallerCatLogs: "Protokoly",
        uninstallerCatState: "Uložený stav",
        uninstallerCatOther: "Ostatné",
        uninstallerCommandBarBrowseTitle: "Odinštalovať aplikáciu",
        uninstallerCommandBarToggle: "Zobraziť v príkazovej lište",
        uninstallerCommandBarCaption: "Vyberte a odinštalujte aplikácie v príkazovej lište.",
        uninstallerCommandBarFinderTitle: "Odinštalovať aplikáciu vybranú vo Finderi",
        uninstallerSelectionUnavailable: "Vyberte vo Finderi aplikáciu, ktorú možno odstrániť, alebo vyberte inú zo zoznamu.",

        urlCleanerName: "Vyčistiť URL",
        urlCleanerEnable: "Čistiť URL pri kopírovaní",
        urlCleanerEnableCaption: "Odstráni sledovacie parametre z odkazu hneď, ako sa dostane do schránky.",
        urlCleanerActiveNow: "Práve aktívne",
        urlCleanerManualTitle: "Vyčistiť teraz",
        urlCleanerInputPlaceholder: "Vložte URL",
        urlCleanerOutputPlaceholder: "Tu sa objaví čistá URL",
        urlCleanerCleanButton: "Vyčistiť",
        urlCleanerPasteButton: "Vložiť",
        urlCleanerCopyButton: "Kopírovať",
        urlCleanerClearButton: "Vymazať pole",
        urlCleanerNoURL: "Vložte platnú URL.",
        urlCleanerNoChange: "Nie je čo čistiť.",
        urlCleanerCleaned: "URL je vyčistená.",
        urlCleanerCopied: "Skopírované.",
        urlCleanerLocalNote: "Lokálne. Bez siete.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Hľadajte, inštalujte a odstraňujte formulae a casks.",
        homebrewMissingTitle: "Homebrew sa nenašiel",
        homebrewMissingBody: "Aster môže otvoriť Terminál s oficiálnym inštalátorom Homebrew. Terminál zobrazí jednotlivé kroky a v prípade potreby si vyžiada vaše heslo.",
        homebrewInstallHomebrew: "Nainštalovať Homebrew",
        homebrewInstallHomebrewCaption: "Keď Terminál skončí, vráťte sa sem a kliknite na Obnoviť.",
        homebrewInstallHomebrewOpened: "Inštalátor sa otvoril v Termináli.",
        homebrewShellSetupTitle: "Dokončite nastavenie Terminálu",
        homebrewShellSetupBody: "Homebrew je nainštalovaný, ale Terminál ešte nemusí nájsť príkaz brew. Aster môže otvoriť Terminál s potrebným príkazom.",
        homebrewShellSetupButton: "Nastaviť Terminál",
        homebrewShellSetupOpened: "Príkaz sa otvoril v Termináli. Potom sa vráťte sem a kliknite na Obnoviť.",
        homebrewRefresh: "Obnoviť",
        homebrewCheckPackages: "Skontrolovať balíky",
        homebrewTrustTitle: "Tap ešte nie je dôveryhodný",
        homebrewTrustCaption: "Homebrew teraz pred použitím tapov tretích strán žiada vaše potvrdenie. Ak chcete pokračovať, dôverujte %@.",
        homebrewTrustButton: "Dôverovať a pokračovať",
        homebrewSearchPlaceholder: "Hľadať balíky",
        homebrewKeyboardHint: "Medzerník alebo Return zatvorí panel macOS. Použite tlačidlo hľadania.",
        homebrewSearchButton: "Hľadať",
        homebrewSearchResults: "Výsledky",
        homebrewInstalled: "Nainštalované",
        homebrewAll: "Všetko",
        homebrewFormulas: "Formulae",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Nenašli sa žiadne balíky",
        homebrewDependencies: "Závislosti",
        homebrewGroupDependencies: "Zoskupiť závislosti",
        homebrewNoSelection: "Vyberte nainštalovaný balík alebo vyhľadajte nový.",
        homebrewDetailsTitle: "Detaily balíka",
        homebrewInstall: "Inštalovať",
        homebrewUninstall: "Odinštalovať",
        homebrewUpgrade: "Aktualizovať",
        homebrewUpgradeAll: "Aktualizovať všetko",
        homebrewUpdateHomebrew: "Aktualizovať Homebrew",
        homebrewAllPackages: "balíky",
        homebrewOpenTerminal: "Otvoriť Terminál",
        homebrewCancelOperation: "Zrušiť",
        homebrewClearLog: "Vymazať protokol",
        homebrewLogTitle: "Protokol",
        homebrewVersion: "Verzia",
        homebrewDescription: "Typ",
        homebrewHomepage: "Otvoriť webstránku",
        homebrewPopularity: "Popularita",
        homebrewPopularityFormat: "%@ inštalácií za %@ dní",
        homebrewInstalledBadge: "Nainštalované",
        homebrewNotInstalledBadge: "Nenainštalované",
        homebrewUpdates: "Aktualizácie",
        homebrewUpdateAvailableBadge: "Dostupná aktualizácia",
        homebrewLatestVersion: "Najnovšia",
        homebrewConfirmInstallTitle: "Nainštalovať cez Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew stiahne a nainštaluje %@. Môžu sa nainštalovať aj závislosti.",
        homebrewConfirmUninstallTitle: "Odinštalovať cez Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew odinštaluje %@. Konfiguračné súbory môžu v systéme ostať.",
        homebrewConfirmUpgradeTitle: "Aktualizovať cez Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew stiahne a nainštaluje najnovšiu verziu %@. Môžu sa aktualizovať aj závislosti.",
        homebrewConfirmUpgradeAllTitle: "Aktualizovať všetko cez Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew stiahne a nainštaluje najnovšie verzie balíkov, pre ktoré je dostupná aktualizácia. Môžu sa aktualizovať aj závislosti.",
        homebrewConfirmUpdateHomebrewTitle: "Aktualizovať Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew načíta najnovšie informácie a potom znova načíta vaše balíky.",
        homebrewTerminalFallback: "Táto operácia potrebuje Terminál, aby si vyžiadal heslo správcu. Aster heslá nezachytáva.",
        homebrewLoading: "Načítava sa…",
        homebrewSearchEmpty: "Žiadne výsledky",
        homebrewOperationInstallFormat: "Inštaluje sa %@",
        homebrewOperationUninstallFormat: "Odinštaluje sa %@",
        homebrewOperationUpgradeFormat: "Aktualizuje sa %@",
        homebrewOperationUpgradeAll: "Aktualizujú sa balíky",
        homebrewOperationUpdateHomebrew: "Aktualizuje sa Homebrew",
        homebrewOperationInstalledFormat: "%@ je nainštalovaný.",
        homebrewOperationUninstalledFormat: "%@ je odinštalovaný.",
        homebrewOperationUpgradedFormat: "%@ je aktualizovaný.",
        homebrewOperationUpgradedAll: "Balíky sú aktualizované.",
        homebrewOperationUpdatedHomebrew: "Homebrew je aktualizovaný.",
        homebrewOperationFailedFormat: "Operáciu pre %@ sa nepodarilo dokončiť.",
        homebrewOperationCancelled: "Operácia bola zrušená.",
        homebrewOperationPreparing: "Pripravuje sa…",
        homebrewOperationDownloading: "Sťahujú sa súbory…",
        homebrewOperationInstalling: "Inštalujú sa súbory…",
        homebrewOperationUninstalling: "Odstraňujú sa súbory…",
        homebrewOperationUpgrading: "Aktualizujú sa súbory…",
        homebrewOperationFinalizing: "Dokončuje sa…",
        homebrewOperationRefreshing: "Obnovuje sa zoznam…",
        homebrewOperationTerminal: "Pokračujte v Termináli.",
        homebrewOperationElapsedFormat: "uplynulo %@",
        homebrewOperationShowDetails: "Zobraziť detaily",
        homebrewOperationHideDetails: "Skryť detaily",
        homebrewOperationTechnicalLog: "Technické detaily",
        homebrewOperationProgressUnknown: "Homebrew zatiaľ neoznámil percentá.",

        mediaName: "Médiá",
        mediaEnableCaption: "Komprimujte videá, konvertujte a upravujte obrázky, vytvárajte GIF a extrahujte text lokálne.",
        mediaLocalNote: "Lokálne. Bez siete.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Obrázok",
        mediaToolText: "Text",
        mediaSelectFile: "Vybrať súbor",
        mediaDropHint: "Potiahnite sem súbor alebo ho kliknutím vyberte.",
        mediaOutput: "Výstup",
        mediaOutputAutomatic: "Automaticky",
        mediaChooseOutput: "Cieľ",
        mediaStartVideo: "Komprimovať video",
        mediaStartGIF: "Vytvoriť GIF",
        mediaStartImage: "Spracovať obrázok",
        mediaStartConvertPDF: "Konvertovať do PDF",
        mediaStartText: "Extrahovať text",
        mediaCancel: "Zrušiť",
        mediaStartTime: "Začiatok",
        mediaEndTime: "Koniec",
        mediaQuality: "Kompresia",
        mediaCompressionLow: "Nízka",
        mediaCompressionMedium: "Stredná",
        mediaCompressionHigh: "Vysoká",
        mediaCompressionLowDescription: "Vysoká kvalita, veľký súbor",
        mediaCompressionMediumDescription: "Vyvážená kvalita a veľkosť súboru",
        mediaCompressionHighDescription: "Nízka kvalita, malý súbor",
        mediaMaxSize: "Veľkosť",
        mediaSizingResolution: "Rozlíšenie",
        mediaSizingFileSize: "Veľkosť súboru",
        mediaTargetSize: "Cieľová veľkosť",
        mediaTargetSizeHint: "Rozlíšenie sa prispôsobí tak, aby sa zmestilo pod limit.",
        mediaErrorTargetTooSmall: "Cieľová veľkosť je pre tento klip príliš malá. Skráťte ho alebo zvýšte limit.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Šírka",
        mediaFPS: "FPS",
        mediaKeepAudio: "Zachovať zvuk",
        mediaCodec: "Kodek",
        mediaFormat: "Formát",
        mediaStripMetadata: "Odstrániť metadáta",
        mediaLoopGIF: "Opakovať GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Presné",
        mediaOCRFast: "Rýchle",
        mediaLanguageCorrection: "Jazyková korekcia",
        mediaTextOutputNote: "Extrahovaný text možno skopírovať a uložiť ako TXT.",
        mediaRunning: "Spracúva sa",
        mediaCompleted: "Hotovo",
        mediaCancelled: "Zrušené.",
        mediaOpenInFinder: "Zobraziť",
        mediaCopyText: "Kopírovať text",
        mediaRunAgain: "Spustiť znova",
        mediaEmptyText: "Nenašiel sa žiadny text.",
        mediaResultSavedFormat: "Uložené ako %@",
        mediaResultSizeFormat: "%@ na %@",
        mediaResultGrewCaption: "Konvertovaný súbor vyšiel väčší ako originál.",
        mediaErrorNoFile: "Najprv vyberte súbor.",
        mediaErrorNoVideo: "Tento súbor nemá videostopu.",
        mediaErrorSameOutput: "Vyberte cieľ odlišný od pôvodného súboru.",
        mediaErrorUnsupported: "Formát, ktorý macOS nepodporuje.",

        shelfName: "Polica",
        shelfEnable: "Dočasné miesto na ťahanie súborov",
        shelfEnableCaption: "Plávajúce miesto, kam zhromaždíte súbory, obrázky a text a neskôr ich potiahnete kamkoľvek.",
        shelfHowTitle: "Ako sa to používa",
        shelfStep1: "Otvorte ju skratkou alebo zatrasením myšou počas ťahania.",
        shelfStep2: "Pustite na ňu súbory, obrázky, odkazy alebo text a ona ich podrží.",
        shelfStep3: "Každú položku z nej potiahnite späť do ľubovoľnej aplikácie, keď ju potrebujete.",
        shelfShakeToggle: "Otvoriť zatrasením myšou počas ťahania",
        shelfShakeCaption: "Rýchlo zatraste kurzorom, kým držíte položku, a polica sa objaví pri kurzore.",
        shelfDropZoneToggle: "Ponechať ťahané súbory v lište s ponukami",
        shelfDropZoneCaption: "Kým ťaháte súbor, polica sa objaví pod ikonou v lište s ponukami. Čokoľvek pustíte, ostane priamo tam, v tlačidle, ktoré zmenšíte a otvoríte kliknutím a ktoré zmizne, len čo je polica prázdna.",
        shelfDropZoneCaptionTopCenter: "Kým ťaháte súbor, polica sa objaví ako odznak hore v strede obrazovky. Čokoľvek pustíte, ostane priamo tam, v odznaku, ktorý otvoríte kliknutím a ktorý zmizne, len čo je polica prázdna.",
        shelfDropZoneLabel: "Pustite sem",
        shelfDockPlacement: "Poloha",
        shelfDockMenuBar: "Pod ikonou v lište",
        shelfDockTopCenter: "Hore v strede obrazovky",
        shelfDockIslandNote: "Kým je Dynamic Island zapnutý, hore v strede je jeho miesto.",
        shelfCollapse: "Zbaliť",
        shelfBehaviorTitle: "Po použití",
        shelfCloseAfterDrop: "Zavrieť po pustení do inej aplikácie",
        shelfCloseAfterDropCaption: "Zavrie policu, keď cieľ položky prijme. Pripnutie v paneli ju ponechá otvorenú.",
        shelfRemoveAfterDrop: "Odstrániť položky po pustení",
        shelfRemoveAfterDropCaption: "Položky, ktoré prijme iná aplikácia, policu opustia. Vypnite to, ak tam má ostať kópia. Pripnuté položky tam ostanú vždy.",
        shelfExclusionsTitle: "Automatické výnimky",
        shelfExclusionsEmpty: "Nepridali ste žiadne aplikácie.",
        shelfExclusionsCaption: "Zatrasenie a zóna na pustenie v lište s ponukami ostanú vypnuté pri ťahaní spustenom v týchto aplikáciách. Skratka a Otvoriť teraz fungujú ďalej.",
        shelfPin: "Nechať otvorené",
        shelfUnpin: "Povoliť zatvorenie po použití",
        extraBrightnessName: "Extra jas",
        extraBrightnessCaption: "Využíva HDR rezervu displeja, aby prekročil maximálny jas. Spotrebuje viac batérie a Mac sa môže zahrievať.",
        extraBrightnessLevelLabel: "Intenzita",
        extraBrightnessUnsupported: "Dostupné len na XDR displejoch, napríklad na 14 a 16 palcovom MacBooku Pro.",
        shelfHotkeyLabel: "Skratka",
        shelfOpenNow: "Otvoriť teraz",
        shelfNoPermission: "Nevyžaduje žiadne povolenia.",
        shelfMenuItem: "Otvoriť policu",
        shelfTitle: "Polica",
        shelfEmpty: "Potiahnite sem položky",
        shelfClearAll: "Vymazať všetko",
        shelfRemoveSelected: "Odstrániť vybrané",
        shelfSelectedFormat: "Vybrané: %d",
        shelfHint: "Kliknutím vyberiete. Potiahnutím von položku použijete, pravým kliknutím získate ďalšie akcie.",
        shelfItemImage: "Obrázok",
        shelfTooltipItemsFormat: "%d položiek",
        shelfTooltipItemsFew: "%d položky",
        shelfTooltipImageSingular: "%d obrázok",
        shelfTooltipImageFew: "%d obrázky",
        shelfTooltipImagePlural: "%d obrázkov",
        shelfTooltipFileSingular: "%d súbor",
        shelfTooltipFileFew: "%d súbory",
        shelfTooltipFilePlural: "%d súborov",
        shelfTooltipNoteSingular: "%d poznámka",
        shelfTooltipNoteFew: "%d poznámky",
        shelfTooltipNotePlural: "%d poznámok",
        shelfTooltipLinkSingular: "%d odkaz",
        shelfTooltipLinkFew: "%d odkazy",
        shelfTooltipLinkPlural: "%d odkazov",
        shelfActionOpen: "Otvoriť",
        shelfActionOpenWith: "Otvoriť v aplikácii",
        shelfActionShare: "Zdieľať",
        shelfActionPin: "Pripnúť",
        shelfActionUnpin: "Odopnúť",

        breakdownMeasuring: "Meria sa…",

        mixerSection: "Mixér hlasitosti",
        mixerEmpty: "Aplikácie, ktoré používajú zvuk, sa objavia tu",
        mixerUnavailable: "Dostupné na macOS 14.4 a novšom",
        mixerPermissionBody: "Ak chcete upravovať hlasitosť jednotlivých aplikácií, povoľte „Nahrávanie obrazovky a systémového audia“ v Systémových nastaveniach. Zvuk sa nikdy nenahráva.",
        mixerResetTooltip: "Obnoviť na 100 %",
        mixerOutputDefault: "Predvolený",
        mixerOutputCurrent: "aktuálny",
        mixerOutputUnavailable: "Výstup nie je dostupný",
        mixerOutputFallback: "Kým sa toto zariadenie nevráti, používa sa predvolené.",
        mixerBypassedCaption: "Táto aplikácia si spravuje zvuk sama.",
        mixerOutputTooltip: "Vybrať výstup",
        mixerSystemOutputTitle: "Výstup",
        mixerSystemOutputNoDevices: "Nenašli sa žiadne výstupy",
        mixerSystemOutputTooltip: "Vybrať systémový výstup",
        mixerSystemOutputErrorFormat: "Nepodarilo sa prepnúť: %@",
        mixerLowerOnHeadphonesDisconnect: "Znížiť hlasitosť pri odpojení slúchadiel",
        mixerLowerOnHeadphonesDisconnectCaption: "Upraví výstup, keď sa odpoja káblové alebo Bluetooth slúchadlá.",
        mixerHeadphonesDisconnectVolume: "Hlasitosť po odpojení",
        preciseVolumeRollerEnable: "Používať jemnejšie kroky hlasitosti",
        preciseVolumeRollerCaption: "Zmení kolieska a klávesy hlasitosti na menšie kroky systémovej hlasitosti.",
        preciseVolumeRollerTapFailed: "Klávesy hlasitosti sa nepodarilo sledovať.",
        soundOutputSwitcherTitle: "Prepínač výstupov",
        soundOutputSwitcherEnable: "Prepínať výstupy skratkou",
        soundOutputSwitcherCaption: "Vyberte výstupy a skratkou prejdete na ďalší dostupný.",
        soundOutputSwitcherDevices: "Výstupy v cykle",
        soundOutputSwitcherNoAvailableSelection: "Vyberte aspoň jeden dostupný výstup.",
        mixerInputTitle: "Mikrofón",
        mixerInputNoDevices: "Nenašli sa žiadne mikrofóny",
        mixerInputUnavailable: "Mikrofón nie je dostupný",
        mixerInputFallback: "Kým sa tento mikrofón nevráti, používa sa predvolený.",
        mixerInputTooltip: "Vybrať mikrofón",
        mixerInputErrorFormat: "Nepodarilo sa prepnúť: %@",
        mixerVisibleApps: "Aplikácie v zozname",
        mixerAllShown: "Všetky",
        mixerHiddenCountLabel: "Skryté",
        mixerHideFromList: "Skryť zo zoznamu",
        audioPrioritySection: "Priorita zvukových zariadení",
        audioPriorityOutputEnable: "Automaticky prepnúť na výstup s najvyššou prioritou",
        audioPriorityInputEnable: "Automaticky prepnúť na mikrofón s najvyššou prioritou",
        audioPriorityOutputList: "Priorita výstupov",
        audioPriorityInputList: "Priorita mikrofónov",
        audioPriorityMoveUp: "Presunúť nahor",
        audioPriorityMoveDown: "Presunúť nadol",
        audioPriorityUnavailable: "Nedostupné",
        audioPriorityCurrent: "Používa sa",
        audioPriorityCaption: "Zariadenia sa vyberajú podľa poradia priority. Keď sa pripojí zariadenie s vyššou prioritou, začne sa používať. Keď sa aktívne zariadenie odpojí, nahradí ho ďalšie dostupné.",

        updatesSection: "Aktualizácie",
        autoCheckToggle: "Automaticky kontrolovať aktualizácie",
        includeBetaUpdatesToggle: "Dostávať beta aktualizácie",
        includeBetaUpdatesCaption: "Beta verzie obsahujú funkcie vo vývoji a môžu mať chyby alebo nedokončené správanie.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Skontrolovať teraz",
        updateChecking: "Kontroluje sa…",
        updateUpToDate: "Máte najnovšiu verziu.",
        updateAvailablePrefix: "Dostupná aktualizácia:",
        updateInstallButton: "Stiahnuť a nainštalovať",
        updateDownloading: "Sťahuje sa aktualizácia…",
        updateInstalling: "Inštaluje sa a reštartuje…",
        updateFailedPrefix: "Nepodarilo sa skontrolovať:",
        updateLastChecked: "Naposledy skontrolované:",
        updateNotifyTitle: "Aktualizácia Asteru",
        updateInstallFailedBody: "Aktualizácia sa stiahla, ale nepodarilo sa ju použiť. Stiahnite si najnovšiu verziu zo stránky vydaní na GitHube a potiahnite aplikáciu na tú súčasnú.",
        updateNeedsApplicationsTitle: "Presuňte Aster do priečinka Aplikácie",
        updateNeedsApplicationsBody: "Aplikácia beží z miesta, ktoré sa nedá aktualizovať, napríklad z obrazu disku alebo dočasného systémového umiestnenia. Potiahnite Aster do priečinka Aplikácie, otvorte ho odtiaľ a skúste to znova.",
        menuCheckUpdates: "Skontrolovať aktualizácie…",

        permissionRequired: "Vyžaduje sa povolenie",
        permissionAccessibility: "Prístupnosť",
        permissionScreenRecording: "Nahrávanie obrazovky",
        permissionGranted: "Udelené",
        permissionMissing: "Neudelené",
        permissionOpenSettings: "Otvoriť Systémové nastavenia…",
        permissionRequest: "Udeliť prístup",
        permissionRestartNote: "macOS môže po udelení požiadať o opätovné otvorenie aplikácie.",
        secureInputTitle: "Zabezpečený vstup je zapnutý",
        secureInputHeldFormat: "Drží ho %@, takže Aster nemôže písať za vás. Zavrite jeho pole s heslom alebo ho ukončite, aby ho uvoľnil.",
        secureInputUnattributed: "Nehlási sa k nemu žiadna spustená aplikácia. Odhláste sa a znova prihláste, aby sa uvoľnil.",
        secureInputUnidentified: "Aplikáciu, ktorá ho drží, sa nepodarilo identifikovať, takže Aster nemôže písať za vás.",
        secureInputRevealFormat: "Zobraziť %@",

        aboutDescription: "Centrum nástrojov pre váš Mac.\nEnergia, monitor systému, rolovanie a prepínač okien priamo v lište s ponukami.",
        versionPrefix: "Verzia",
        reviewIntro: "Znova zobraziť úvod",
        reviewHighlights: "Znova zobraziť novinky",
        viewOnGitHub: "Zobraziť na GitHube",

        obContinue: "Pokračovať",
        obBack: "Späť",
        obSkipStep: "Preskočiť tento krok",
        obStart: "Otvoriť Aster",
        obStepWelcomeTitle: "Vitajte vo Astere",
        obStepWelcomeBody: "Nenápadný nástroj v lište s ponukami, ktorý robí každodenný macOS praktickejším.",
        obWelcomeBullet1Title: "Energia pod kontrolou",
        obWelcomeBullet1Body: "Udržte Mac bdelý tak dlho, ako chcete, aj so zatvoreným vekom.",
        obWelcomeBullet2Title: "Prehľad o systéme",
        obWelcomeBullet2Body: "Teploty CPU, GPU a batérie, využitie hardvéru a zaťaženie pamäte v reálnom čase.",
        obWelcomeBullet3Title: "Myš a okná po vašom",
        obWelcomeBullet3Body: "Obrátené rolovanie myšou a prepínač okien s náhľadmi.",
        obLanguageLabel: "Jazyk",
        obStepAccessibilityTitle: "Prístupnosť",
        obStepAccessibilityBody: "Potrebná na obrátenie rolovania myšou a na to, aby prepínač okien reagoval na klávesnicu.",
        obAccessibilityWhy: "Aplikácia sleduje len koliesko myši a skratku prepínača. Nič sa nenahráva ani nikam neodosiela.",
        obStepRecordingTitle: "Nahrávanie obrazovky",
        obStepRecordingBody: "Umožní prepínaču zobraziť skutočné náhľady okien namiesto samotných ikon.",
        obRecordingWhy: "Náhľady vznikajú priebežne, ostávajú v pamäti a nikdy neopustia váš Mac. Bez tohto povolenia prepínač funguje s ikonami.",
        obStepMonitorTitle: "Monitor systému",
        obStepMonitorBody: "Panel zobrazuje teploty CPU, GPU a batérie, využitie hardvéru a zaťaženie pamäte.",
        obMonitorNoPermission: "Nevyžaduje žiadne povolenie. Senzory sa čítajú priamo zo systému.",
        obStepOptionalTitle: "Voliteľné funkcie",
        obStepOptionalBody: "Zapnite si to, čo chcete používať teraz. Všetko sa dá neskôr zmeniť v Nastaveniach.",
        obStepStatusTitle: "Kontrola",
        obStepStatusBody: "Uistite sa, že je všetko pripravené pre funkcie, ktoré chcete.",
        obStatusRecheck: "Skontrolovať znova",
        obStepDoneTitle: "Hotovo!",
        obStepDoneBody: "Aster sa už stará o váš Mac.",
        obDoneHint: "Hľadajte čiernu dieru v lište s ponukami, vpravo hore na obrazovke.",
        obWhatsNewTitle: "Novinky v tejto verzii",
        obWhatsNewFallback: "Táto aktualizácia obsahuje najnovšie opravy a vylepšenia.",
        obLanguageUpdateTitle: "Teraz aj vo vašom jazyku",
        obLanguageUpdateBody: "Aster teraz hovorí viacerými jazykmi. Vyberte si ten, ktorý chcete používať; kedykoľvek ho zmeníte v Nastaveniach.",
        obPurposeTitle: "Čo vás sem priviedlo?",
        obPurposeBody: "Vyberte si hotové nastavenie alebo presne to, čo chcete používať.",
        obPurposeSkip: "Funkcie môžete neskôr pridať alebo odstrániť v Nastaveniach.",

        tabMonitor: "Monitor",
        monitorMenuBarSection: "V lište s ponukami",
        monitorMenuBarCaption: "Vyberte, čo sa zobrazí vedľa ikony v lište s ponukami.",
        monitorCombineTemperatures: "Spojiť využitie a teplotu",
        monitorCombineTemperaturesCaption: "Keď sú pre tú istú položku zapnuté využitie aj teplota, zobrazia sa v jednom bloku.",
        monitorSeparateMenuBarMetrics: "Rozdeliť metriky do samostatných položiek",
        monitorSeparateMenuBarMetricsCaption: "Rozdelí aktívne bloky v lište s ponukami a pri zapnutom spájaní ponechá využitie a teplotu spolu.",
        monitorNetworkUploadFirst: "Odosielanie nad sťahovaním",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Pamäť",
        monitorShowNetwork: "Sieť",
        monitorShowPowerLabel: "Napájanie",
        monitorIntervalLabel: "Interval aktualizácie",
        monitorInterval1: "1 sekunda",
        monitorInterval2: "2 sekundy",
        monitorInterval5: "5 sekúnd",
        monitorPanelSection: "V paneli",
        panelNavigationMode: "Prechádzať panel po sekciách",
        panelNavigationCaption: "Zobrazí jednu sekciu naraz. Vyberte Zoznam, ak chcete vidieť všetko v jednom súvislom rolovaní.",
        panelFooterSections: "Sekcie",
        panelFooterList: "Zoznam",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Môžete naraziť na chyby.",

        networkSection: "Sieť",
        networkIPAddresses: "IP adresy",
        networkLocalIP: "Lokálna IPv4",
        networkDownload: "Sťahovanie",
        networkUpload: "Odosielanie",
        networkThisSession: "Táto relácia",
        networkMeasuring: "Meria sa…",
        networkApps: "Aplikácie používajúce sieť",
        networkAppsIdle: "Sieť teraz nepoužíva žiadna aplikácia",

        diskSection: "Disky",
        diskUsed: "využité",
        diskFree: "voľné",
        diskMenuBarStyleLabel: "Zobrazenie disku",
        diskMenuBarUsedPercentage: "Zaplnená časť",
        diskMenuBarAvailableSpace: "Dostupné miesto",
        diskMenuBarUsedSpace: "Zaplnené miesto",
        diskAvailable: "dostupné",
        diskPurgeable: "uvoľniteľné",
        diskInternal: "Interný",
        diskExternal: "Externý",
        diskSelect: "Vybrať disk",
        diskRead: "Čítanie",
        diskWrite: "Zápis",
        diskSMARTStatus: "Stav",
        diskSMARTUnavailable: "SMART nie je pre tento disk dostupný",
        diskTotalRead: "Celkovo prečítané",
        diskTotalWritten: "Celkovo zapísané",
        diskTemperature: "Teplota",
        diskHealth: "Kondícia",
        diskPowerCycles: "Cykly napájania",
        diskPowerOnHours: "Hodiny prevádzky",
        diskUnsafeShutdowns: "Nebezpečné vypnutia",
        diskMediaErrors: "Chyby média",
        diskEject: "Vysunúť",
        diskEjectAll: "Vysunúť všetko",
        diskEjecting: "Vysúva sa…",
        diskReadyToRemove: "Pripravené na odpojenie",
        diskEjectFailed: "Nepodarilo sa vysunúť",
        diskProtectionCaption: "Pred odpojením disk vysuňte.",
        diskNoExternal: "Žiadny externý disk na vysunutie.",
        diskOpenInFinder: "Otvoriť",
        diskStorageSettings: "Úložisko",
        diskNoDisks: "Nenašli sa žiadne pripojené disky.",

        powerSection: "Napájanie",
        powerSystem: "Systém",
        powerAdapter: "Adaptér",
        powerBattery: "Batéria",
        powerCharging: "Nabíja sa",
        powerOnBattery: "Na batérii",
        powerPluggedIn: "Pripojené k sieti",
        powerUnavailable: "Metriky napájania na tomto Macu nie sú dostupné",
        powerAdapterMaxFormat: "max. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Teplota CPU",
        monitorShowGPUTemperature: "Teplota GPU",
        monitorShowBatteryTemperature: "Teplota batérie",
        monitorShowPeripheralBattery: "Batéria príslušenstva",
        peripheralBatteryNoDevices: "Nenašli sa žiadne zariadenia",
        monitorGraphsSection: "Grafy",
        monitorGraphsCaption: "Vyberte, ktoré metriky majú zobrazovať graf v čase.",

        updateBannerTitle: "Dostupná aktualizácia",
        updateBannerAction: "Aktualizovať",
        obStepMenuBarTitle: "Metriky v lište s ponukami",
        obStepMenuBarBody: "Vyberte, čo sa má zobraziť vedľa ikony. Náhľad vyššie sa aktualizuje naživo.",
        obStepMenuBarNote: "Novinka: bloky Sieť a Napájanie a grafy v paneli. Všetko doladíte neskôr v Nastaveniach › Monitor.",
        monitorMenuBarPresetLabel: "Štýl",
        menuBarPresetReadable: "Čitateľný",
        menuBarPresetDense: "Hustý",
        menuBarSpacingLabel: "Rozostupy v lište s ponukami",
        menuBarSpacingStandard: "Štandardné",
        menuBarSpacingCompact: "Kompaktné",
        menuBarHideIconToggle: "Skryť ikonu aplikácie, kým sú zobrazené metriky",
        menuBarHideIconCaption: "Ikona sa vráti sama, keď metriky z lišty zmiznú a keď treba niečo signalizovať (pripravenú aktualizáciu alebo stlmený mikrofón).",
        monitorLabelStyleLabel: "Označenia",
        menuBarLabelStyleCompact: "Kompaktné",
        menuBarLabelStyleClassic: "Klasické",
        monitorMemoryStyleLabel: "Zobraziť pamäť ako",
        monitorMemoryPressureDot: "Bodka zaťaženia",
        memoryStyleDot: "Bodka",
        memoryStylePercent: "%",
        memoryStyleBoth: "Oboje",
        systemUptime: "Beží",
        batteryCharge: "Nabitie",
        powerHealth: "Kondícia batérie",
        powerCycles: "Cykly",
        speedTestRun: "Test rýchlosti",
        speedTestAgain: "Testovať znova",
        speedTestLatency: "Odozva",
        speedTestTesting: "Testuje sa…",
        speedTestFailed: "Test zlyhal",

        monitorShowInPanel: "Zobraziť v paneli",
        disclosureExpanded: "Rozbalené",
        disclosureCollapsed: "Zbalené",
        panelHideItem: "Skryť z panela",
        panelShowItem: "Zobraziť v paneli",
        panelHiddenItem: "Skryté",
        monitorItemUptime: "Doba behu",
        monitorItemNetSpeed: "Aktuálna rýchlosť",
        monitorItemNetTotals: "Súčty relácie",
        monitorItemNetTest: "Test rýchlosti",
        monitorItemDiskUsage: "Využitie disku",
        monitorItemDiskActivity: "Aktuálna aktivita",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Ochrana externých diskov",
        monitorItemDiskTools: "Nástroje",
        monitorPanelConfigHint: "Otvorením bloku vyberiete, čo sa v ňom zobrazí.",
        monitorOrderHint: "Potiahnutím zmeníte poradie sekcií panela a okom každú z nich zobrazíte alebo skryjete.",
        obStepPanelTitle: "Čo je v paneli",
        obStepPanelBody: "Otvorte každý blok a vyberte presne to, čo sa zobrazí po kliknutí na ikonu.",
        obStepPanelNavigationTitle: "Panel po sekciách",
        obStepPanelNavigationBody: "Panel teraz vie zobraziť jednu sekciu naraz. Medzi Sekciami a Zoznamom prepnete v Nastaveniach.",

        cleaningMenuItem: "Režim čistenia",
        utilitiesSection: "Nástroje",
        quickControlsSection: "Ovládanie",
        panelCategoryWindows: "Okná",
        panelCategoryInput: "Myš a klávesnica",
        panelCategoryFiles: "Súbory",
        windowMaximizeName: "Maximalizovať okná",
        windowMaximizeCaption: "Zelené tlačidlo maximalizuje okno bez vytvorenia ďalšej plochy.",
        windowMaximizeActiveNow: "Prevzatie zeleného tlačidla je aktívne",
        windowMaximizeNeedsAccessibility: "Na fungovanie potrebuje Prístupnosť.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Filtrovať duplicitné stlačenia",
        keyDebounceCaption: "Odfiltruje veľmi rýchle duplicitné stlačenia klávesov.",
        keyDebounceActiveNow: "Filter je aktívny",
        keyDebounceGlobalWindow: "Globálne okno",
        keyDebouncePerKeySection: "Konkrétne klávesy",
        keyDebouncePerKeyCaption: "Hodnoty pre jednotlivé klávesy majú prednosť pred globálnym oknom. Hodnotou 0 ms filtrovanie klávesu vypnete.",
        keyDebounceKeyLabel: "Kláves",
        keyDebounceWindowLabel: "Okno",
        keyDebounceAddKey: "Pridať kláves",
        keyDebounceNoOverrides: "Žiadne konkrétne klávesy nie sú nastavené.",
        keyDebounceRemoveKey: "Odstrániť kláves",
        cleaningPanelCaption: "Uzamkne klávesnicu, aby ste ju mohli bezpečne vyčistiť.",
        cleaningOverlayTitle: "Klávesnica je uzamknutá na čistenie",
        cleaningOverlaySubtitle: "Odomknete piatimi stlačeniami Escape",
        cleaningOverlayUnlock: "Odomknúť",
        cleaningOverlayMouseHint: "Myš a trackpad fungujú ďalej",
        cleaningKeepScreenVisibleToggle: "Ponechať obrazovku viditeľnú",
        cleaningKeepScreenVisibleCaption: "Zobrazí nenápadný indikátor v rohu obrazovky namiesto zatmenia obsahu.",
        cleaningStartNow: "Uzamknúť klávesnicu teraz",
        cleaningNeedsAxTitle: "Potrebná je Prístupnosť",
        cleaningNeedsAxBody: "Na bezpečné uzamknutie klávesnice potrebuje Aster povolenie Prístupnosť. Udeľte ho v Systémových nastaveniach a skúste to znova.",

        tabSupport: "Podpora",
        shortcutsPageCaption: "Upravte všetky globálne skratky funkcií nainštalovaných na tomto Macu. Neaktívne skratky ostávajú uložené, ale nespúšťajú sa.",
        shortcutsPageTitle: "Klávesové skratky",
        settingsSearchPlaceholder: "Hľadať v nastaveniach",
        donateHeading: "Pomôžte Asteru rásť",
        donateMessage: "Aster je zadarmo, nezávislý a vzniká v mojom voľnom čase. Ak chcete prispieť finančne, Buy Me a Coffee mi priamo pomáha posúvať vývoj vpred.",
        donateButton: "Podporiť cez Buy Me a Coffee",
        donateThanks: "Ďakujem, že ste tu. 🖤",
        supportIntroTitle: "Pomôžte Asteru rásť",
        supportIntroMessage: "Ak chcete podporiť vývoj finančne, Buy Me a Coffee je jediné miesto, kde sa to dá.",
        supportIntroStarButton: "Dajte Asteru hviezdu na GitHube",
        supportIntroStarMessage: "Finančnú podporu nikdy neočakávam. Hviezda na GitHube pomáha objaviť Aster viacerým ľuďom a pre jeho vývoj naozaj veľa znamená.",
        supportIntroCoffeeButton: "Podporiť cez Buy Me a Coffee",
        supportIntroLaterButton: "Teraz nie",
        supportIntroDoneButton: "Hotovo",
        discordIntroTitle: "Discord komunita Asteru sa práve rozbieha",
        discordIntroMessage: "Komunita Asteru je nová a stále sa buduje. Pridajte sa hneď na začiatku, spoznajte ďalších používateľov a pomôžte vytvoriť priateľský priestor okolo aplikácie.",
        discordIntroJoinButton: "Pridať sa do komunity na Discorde",
        communityIntroTitle: "Uvidíte to skôr ako ostatní",
        communityIntroMessage: "Tí, čo ma už sledujú na X, videli viaceré zmeny z tejto aktualizácie skôr ako ktokoľvek iný. Zverejňujem ukážky toho, čo prichádza, a ukazujem, ako to funguje, takže základy poznáte ešte pred vydaním aktualizácie. Sledujte ma a uvidíte, čo príde ďalej!",
        communityIntroFollowButton: "Sledovať @vorssaint na X",
        homebrewOfficialIntroTitle: "Teraz v oficiálnom katalógu Homebrew",
        homebrewOfficialIntroMessage: "Aster sa teraz dá nainštalovať priamo z oficiálneho katalógu Homebrew.",
        homebrewOfficialIntroInstallLabel: "Nová inštalácia",
        homebrewOfficialIntroMigrationTitle: "Používali ste starý tap?",
        homebrewOfficialIntroMigrationMessage: "Stačí tap raz odstrániť. Aplikácia aj vaše nastavenia ostanú na mieste.",
        homebrewOfficialIntroCopyButton: "Kopírovať príkaz",
        updateShowcaseTitle: "Novinky v 3.1.4",
        updateShowcaseMessage: "Pozrite si v rýchlosti hlavné vylepšenia tejto aktualizácie.",
        updateShowcaseUnavailable: "Video sa teraz nepodarilo načítať. Pokračovať môžete aj tak.",
        updateShowcaseRestart: "Prehrať znova",
        showMenuBarIcon: "Zobraziť ikonu v lište s ponukami",
        menuBarIconStillHiddenTitle: "Ikona je stále skrytá",
        menuBarIconStillHiddenBody: "Ikona sa znova vytvorila, ale macOS jej nedal viditeľné miesto. Lišta s ponukami je pravdepodobne plná: odstráňte niektoré ikony (alebo zatvorte aplikácie s dlhými ponukami) a skúste to znova.",
        menuBarIconManagerHintFormat: "%@ je spustený a môže držať ikonu vo svojej skrytej časti. Pohľadajte tam Aster alebo v %@ nastavte, aby sa Aster zobrazoval vždy.",
        menuBarIconDisallowedBody: "macOS nepúšťa Aster do lišty s ponukami. Otvorte Systémové nastavenia › Lišta, nájdite Aster v zozname aplikácií a zapnite „Povoliť položky v lište“. Ikona sa objaví hneď po zapnutí.",
        shortcutRecording: "Stlačte novú skratku",
        shortcutReset: "Obnoviť",
        shortcutNone: "Žiadna",
        shortcutClear: "Odstrániť skratku",
        shortcutInvalid: "Použite aspoň Control, Option alebo Command spolu s klávesom.",
        shortcutPressKeys: "Stlačte klávesy",
        shortcutEscapeHint: "Escape zruší.",
        shortcutDeleteHint: "Delete vymaže.",
        shortcutNotCaptured: "Nič sa nezachytilo. Túto kombináciu už používa macOS alebo iná aplikácia. Skúste inú.",
        shortcutConflictFormat: "Túto skratku už používa %@.",
        shortcutTakeOverOffer: "macOS používa %@ pre jednu zo svojich skratiek.",
        shortcutTakeOverAction: "Prevziať, kým Aster beží",
        shortcutTakeOverCaption: "macOS dostane kláves späť vždy, keď Aster nebeží alebo je táto funkcia vypnutá.",
        shortcutTakeOverDismiss: "Nepreberať",
        shortcutUnavailable: "macOS túto skratku odmietol. Vyberte inú.",
        shelfShortcutToggle: "Skratka police",
        switcherUsageHintFormat: "Podržaním %@ prechádzate oknami; pustením okno aktivujete. Shift alebo ← ide späť; W zatvorí okno; Q ukončí aplikáciu; Esc zruší.",
        musicBlockSection: "Multimediálne klávesy",
        musicBlockTitle: "Zabrániť samovoľnému otváraniu Hudby",
        musicBlockCaption: "Zablokuje otvorenie hudobnej aplikácie po rozpoznanom multimediálnom klávese. Vyžaduje prístup Prístupnosť. Príkazy zo slúchadiel bez rozpoznaného klávesu ostávajú nedotknuté.",
        musicBlockUnavailable: "Táto ochrana je teraz nedostupná. Vypnite ju a znova zapnite, aby ste to skúsili ešte raz.",
        musicBlockReplacementLabel: "Otvoriť namiesto toho",
        musicBlockReplacementNone: "Žiadne",
        musicBlockReplacementBlocked: "Hudba a iTunes sú aplikácie, ktoré sa blokujú, preto sa nemôžu otvoriť namiesto nich. Vyberte inú aplikáciu.",
        musicBlockChooseApp: "Vybrať aplikáciu…",
        musicBlockPlayReplacement: "Prehrať po otvorení náhradnej aplikácie",
        cleanerName: "Čistenie",
        cleanerIntroTitle: "Vyčistite si Mac",
        cleanerIntroCaption: "Vyhľadá zvyšky po odinštalovaných aplikáciách, cache, protokoly a Kôš. Najprv si všetko prezriete a odstránené položky idú do Koša.",
        cleanerScan: "Prehľadať",
        cleanerScanning: "Prehľadáva sa…",
        cleanerCleaning: "Čistí sa…",
        cleanerCatLeftovers: "Zvyšky po odinštalovaných aplikáciách",
        cleanerCatLoginItems: "Osirelé položky po spustení",
        cleanerCatCaches: "Cache",
        cleanerCatLogs: "Protokoly",
        cleanerCatDeveloper: "Vývojársky odpad",
        cleanerCatTrash: "Kôš",
        cleanerLeftoversNote: "Nájdené analýzou a ponechané neoznačené. Pred označením skontrolujte cestu.",
        cleanerLoginItemsNote: "Položka v časti Položky a rozšírenia spúšťané pri prihlásení zmizne po reštarte Macu.",
        cleanerTrashNote: "Vyprázdnenie Koša je nezvratné.",
        cleanerCatDeviceBackups: "Zálohy iPhonu",
        cleanerDeviceBackupsCaption: "Staré zálohy iPhonu a iPadu zaberajú veľkú časť úložiska, ktoré macOS označuje ako Ostatné. Odstráňte len tie, ktoré už nepotrebujete; nová záloha vznikne, keď zariadenie znova pripojíte.",
        cleanerCatScreenshots: "Zabudnuté snímky obrazovky",
        cleanerScreenshotsCaptionFormat: "Snímky obrazovky, ktoré ste neotvorili %d dní a ktoré majú stále názov a priečinok od macOS. Premenované alebo presunuté sa tu nikdy nezobrazia.",
        cleanerScreenshotsSettingCaption: "Kontrola zobrazí neoznačené snímky obrazovky, ktoré ste tak dlho neotvorili, aj s ich celkovou veľkosťou.",
        cleanerScreenshotsAfterFormat: "Po %d dňoch",
        cleanerNothingFound: "Nie je čo čistiť. Váš Mac je uprataný.",
        cleanerClean: "Vyčistiť",
        cleanerDoneNote: "Položky putovali do Koša a dajú sa odtiaľ obnoviť.",
        cleanerAgain: "Prehľadať znova",
        cleanerRevealInFinder: "Zobraziť vo Finderi",
        cleanerPanelCaption: "Zvyšky aplikácií, cache a protokoly",
        cleanerSafeSection: "Bezpečné čistenie",
        cleanerOptionalSection: "Voliteľné, najprv skontrolujte",
        cleanerCatOtherCaches: "Ostatné cache",
        cleanerCachesCaption: "Dočasné súbory, ktoré si aplikácie samy obnovia.",
        cleanerLogsCaption: "Staré diagnostické protokoly.",
        cleanerDeveloperCaption: "Zvyšky zostavení Xcode a simulátorov.",
        cleanerLoginItemsCaption: "Položky po spustení, ktoré zanechali už neexistujúce aplikácie.",
        cleanerLeftoversCaption: "Súbory, ktoré po sebe nechali odinštalované aplikácie.",
        cleanerOtherCachesCaption: "Bezpečne sa dajú odstrániť, nič sa nepokazí. Aplikácie sa raz otvoria pomalšie a stiahnutý obsah, napríklad hudba offline, sa stiahne znova.",
        cleanerCleanSizeFormat: "Vyčistiť %@",
        cleanerScheduleTitle: "Automatické čistenie",
        cleanerScheduleOff: "Vypnuté",
        cleanerScheduleDaily: "Denne",
        cleanerScheduleWeekly: "Týždenne",
        cleanerScheduleCaption: "Vo zvolenom čase sám vyčistí len bezpečnú časť a všetko pošle do Koša.",
        cleanerScheduleLastFormat: "Posledné automatické čistenie uvoľnilo %@.",
        cleanerAutoNotificationFormat: "Čistenie uvoľnilo %@ a položky presunulo do Koša.",
        cleanerScheduleNextFormat: "Ďalšie čistenie %@.",
        cleanerScheduleRanFormat: "Posledné automatické čistenie %@.",
        cleanerScheduleNotifyToggle: "Upozorniť po dokončení",
        cleanerNotifDenied: "Hlásenia Asteru sú v systéme vypnuté.",
        cleanerNotifOpenSettings: "Otvoriť nastavenia hlásení…",
        launchAtLoginNeedsApplications: "Aplikácia beží z miesta, z ktorého sa nedá otvárať po prihlásení. Potiahnite Aster do priečinka Aplikácie, otvorte ho odtiaľ a znova to zapnite.",
        launchAtLoginNeedsApproval: "Položka po prihlásení je zaregistrovaná, ale v Systémových nastaveniach je stále vypnutá. Otvorte Systémové nastavenia › Všeobecné › Položky a rozšírenia spúšťané pri prihlásení a zapnite Aster v časti Otvoriť po prihlásení.",
        ocrRemoveLineBreaksToggle: "Odstrániť zalomenia riadkov",
        ocrRemoveLineBreaksCaption: "Odstráni zalomenia riadkov, takže skopírovaný text sa vloží ako jeden odsek.",
        ocrQRToggle: "Čítať QR kódy",
        ocrQRCaption: "Ak je v oblasti QR kód, jeho obsah sa zobrazí na skopírovanie alebo otvorenie.",
        ocrQRCopied: "QR kód skopírovaný",
        qrResultTitle: "QR kód",
        qrResultCopy: "Kopírovať",
        qrResultOpen: "Otvoriť odkaz",
        highlightsTitle: "Novinky v tejto aktualizácii",
        highlightsTitleClipboardRedesign: "Prepracovaná schránka",
        highlightsTitleWindowLayout: "Rozloženie okien",
        highlightsTitleQuitProtection: "Ochrana pred ukončením a zatvorením",
        highlightsTitleRecorderBlur: "Rozmazanie súkromia pri nahrávaní",
        highlightsCaptionDockPreview: "Dock Preview teraz funguje aj so zapnutým zväčšovaním Docku",
        highlightsCaptionScreenshot: "Nástroj na snímky obrazovky získal pixelovú lupu a čítanie QR kódov",
        highlightsCaptionSnippetLibrary: "Prehľadávateľná ponuka fragmentov napíše ktorýkoľvek fragment priamo na pozíciu kurzora",
        highlightsCaptionCapturePalette: "Jedna skratka teraz otvorí plávajúcu paletu pre snímky, nahrávky, text z obrazovky a farby spolu s ovládaním po ruke.",
        highlightsCaptionClipboardRedesign: "História schránky sa teraz otvára ako kompaktná paleta s prehľadnými riadkami a náhľadom na požiadanie, v ktorom si celú položku prečítate alebo upravíte.",
        highlightsCaptionWindowLayout: "Rozmiestnite okná smerovým prstencom pomocou skratky a kurzora alebo ich potiahnite k okrajom obrazovky a prichytia sa s vlastnými medzerami.",
        highlightsCaptionQuitProtection: "Vyhnite sa nechcenému ukončeniu aplikácií a zatvoreniu okien pomocou podržania, dvojitého stlačenia alebo ďalšieho modifikátora, nastaviteľného pre každú aplikáciu.",
        highlightsCaptionRecorderBlur: "Skryte súkromné údaje, heslá a citlivé miesta kdekoľvek v nahratom videu ešte pred zdieľaním alebo exportom.",
        highlightsConfigure: "Nastaviť",
        highlightsTry: "Vyskúšať",
        highlightsSeeAll: "Zobraziť všetky zmeny",
        switcherCurrentSpaceOnly: "Zobraziť len aktuálnu plochu",
        switcherCurrentSpaceOnlyCaption: "Vypíše len okná z plochy, na ktorej ste. Výber okna vás nikdy neprenesie na inú plochu.",
        shelfFileMissing: "Súbor už neexistuje",
        previewSizeSmall: "Malá",
        mixerSoundEffectsOutputTitle: "Systémové zvuky",
        mixerSoundEffectsOutputTooltip: "Vyberte, kde sa prehrávajú výstrahy a zvukové efekty",
        monitorOpenActivityMonitor: "Otvoriť Monitor aktivity",
        dockClickHide: "Kliknutím na ikonu v Docku skryť aplikáciu",
        dockClickHideCaption: "Aktívna aplikácia sa skryje, keď kliknete na jej ikonu v Docku. Ďalším kliknutím ju vrátite späť.",
        monitorMemoryMetricLabel: "Merať pamäť ako",
        memoryMetricUsed: "Využitá pamäť",
        memoryMetricApp: "Pamäť aplikácií",
        keepAwakeRightClickToggle: "Pravým kliknutím na ikonu v lište prepínať bdelý režim",
        keepAwakeRightClickToggleCaption: "Nahradí kontextovú ponuku po pravom kliknutí.",
        urlCleanerRulesTitle: "Pravidlá čistenia",
        urlCleanerRulesCaption: "Stránka pripája tieto parametre k vlastným odkazom na zdieľanie, aby sledovala, odkiaľ odkaz prišiel. Keď je názov zapnutý, pri čistení odkazu sa odstráni; keď je vypnutý, ostane. Názvy, ktoré pridáte, sa dajú zmazať.",
        urlCleanerRulesCoverageCaption: "Zoznam pokrýva rôzne cesty zdieľania jednej stránky (webová stránka, aplikácia, živá miestnosť), preto je taký dlhý; skutočný odkaz ich zvyčajne nesie len dva až štyri.",
        urlCleanerRulesAllSites: "Všetky stránky",
        urlCleanerRulesCountSingular: "1 parameter",
        urlCleanerRulesCountPluralFormat: "Parametrov: %d",
        urlCleanerRulesAddSite: "Pridať stránku",
        urlCleanerRulesParameterPlaceholder: "Názov parametra",
        urlCleanerRulesMatchCaption: "Napíšte názov naľavo od = , napríklad utm_source. Zhodný názov odstráni z odkazu práve tento jeden parameter a zvyšok nechá tak, ako bol.",
        urlCleanerRulesAddButton: "Pridať",
        urlCleanerRulesRemoveButton: "Zmazať názov",
        urlCleanerRulesRemoveSiteButton: "Vypnúť všetky pravidlá pre túto stránku",
        urlCleanerRemovedFormat: "Odstránené: %@",
        switcherSearchPin: "Pripnúť hľadanie klávesom S",
        switcherSearchPinCaption: "S spustí hľadanie a pripne prepínač otvorený, takže písanie už nevytvára špeciálne znaky, keď vaša skratka používa ⌥, a hľadanie začínajúce na Q alebo W už omylom nezatvorí okno ani neukončí aplikáciu.",
        invertVerticalScroll: "Obrátiť zvislé rolovanie",
        invertHorizontalScroll: "Obrátiť vodorovné rolovanie",
        scrollHorizontalName: "Rolovať do strán pri podržaní klávesu",
        scrollHorizontalModifierLabel: "Modifikačný kláves",
        scrollHorizontalCommandKey: "Command",
        scrollHorizontalCaption: "Podržaním samotného zvoleného modifikátora budete zvislým kolieskom myši rolovať vodorovne. Ostatné kombinácie klávesov ostávajú nezmenené.",
        switcherShowShortcutHints: "Zobraziť nápovedu ku skratkám",
        switcherShowShortcutHintsCaption: "Zobrazí skratky pre aplikácie a okná pod ikonami.",
        uninstallerHomebrewPackageFormat: "%@ sa odstráni aj z Homebrew.",
        shelfEdgeToggle: "Otvoriť pri okraji obrazovky",
        shelfEdgeCaption: "Potiahnite súbor k okraju obrazovky a polica sa vysunie. Buď na ňu súbor pustíte, alebo sa potiahnutím späť zasunie.",
        focusFollowsMouseName: "Zameranie sleduje myš",
        focusFollowsMouseCaption: "Po krátkej pauze zameria a vynesie dopredu okno pod kurzorom.",
        focusFollowsMouseDelay: "Oneskorenie pri prejdení",
        switcherMinimizedPlacementLabel: "Minimalizované okná",
        switcherTreatHiddenAppsLikeMinimized: "Považovať skryté aplikácie za minimalizované okná",
        switcherMinimizedPlacementNormal: "Bežné poradie",
        switcherMinimizedPlacementEnd: "Umiestniť na koniec",
        switcherMinimizedPlacementHidden: "Skryť",
        switcherShowFullscreenWindows: "Zobraziť okná na celej obrazovke",
        switcherScreenPlacementLabel: "Zobraziť na",
        switcherScreenPlacementPointer: "Obrazovke s kurzorom",
        switcherScreenPlacementMenuBar: "Obrazovke s lištou s ponukami",
        switcherScreenPlacementActiveWindow: "Obrazovke s aktívnym oknom",
        switcherScreenPlacementCaption: "Na ktorom displeji sa prepínač otvorí, keď je pripojených viac displejov.",
        switcherCurrentDisplayOnly: "Zobraziť len aktuálny displej",
        switcherCurrentDisplayOnlyCaption: "Vypíše len okná na displeji pod kurzorom. Ak na tom displeji nie sú okná, prepínač sa neotvorí.",
        smoothScrollResponseLabel: "Odozva",
        smoothScrollCoastLabel: "Dobeh",
        mouseAccelerationName: "Vypnúť akceleráciu myši",
        mouseAccelerationCaption: "Odstráni akceleráciu kurzora pre pripojené myši. Predchádzajúce nastavenie sa vráti po vypnutí tejto funkcie alebo po ukončení Asteru.",
        shelfClearOnClose: "Vymazať pri zatvorení",
        shelfClearOnCloseCaption: "Vyprázdni policu len vtedy, keď kliknete na jej tlačidlo zatvorenia. Automatické skrytie a zbalenie položky zachovajú."
    )
}
